# 1. Library calling

In [6]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
import warnings
from tqdm import tqdm
import numpy as np
import os
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

# 2. Defining the Product Information and Location

In [10]:
SummaryFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects'
summaryFile='Scraping_List.txt'
st=pd.read_csv(SummaryFolder+'\\'+summaryFile)
print(st)
#Define Product to extract
search_text = st['Product Name'][49]
print(search_text)
Source="Amazon"
OFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Outputs'
IFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Inputs'
imagepath=fr"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\Vikram Data research\{search_text}\ProductImage"
if not os.path.exists(imagepath):
    os.makedirs(imagepath)
filename=Source+'ProductLinks_'+search_text+'.xlsx'
df1=pd.read_excel(IFolder+'\\'+filename)
df1

                                  Product Name
0                                Ignition Coil
1                      Windshield Washer Pumps
2                        coupler trailer locks
3          Adjustable Trailer Hitch Ball Mount
4                               Vacuum Cleaner
5                                   Spark Plug
6              bluetooth Enabled Trailer locks
7                          Power Steering Hose
8   Power Steering Pressure Line Hose Assembly
9                       Washer Fluid Reservoir
10          Hitch Ball Mount with Weight Scale
11                               LED Headlamps
12                             LED flashlights
13                   Fiberglass Tonneau Covers
14                    Aluminium Tonneau Covers
15                     Hardfold Tonneau Covers
16                            Spark Plug Wires
17                 washer fluid reservoir tank
18                   Non Automotive Gas Struts
19                     trunk hanging organizer
20                                    car jack
21                              Towing Mirrors
22                                    Gas Lift
23                        caliper pad spreader
24                               fuel injector
25        wireless carplay screen with dashcam
26                 Vehicle Soft-Shell Carriers
27                               Scissor Jacks
28               Electrical Hydraulic Car Jack
29                 Electrical Scissor Car Jack
30                               Trailer Locks
31                             Conical Filters
32                                  Car Covers
33                                 Tyre Covers
34                                    Car Mats
35                           Dolly Tire Racks
36                             Cargo Organizer
37                               Car Organizer
38                   Rechargeable Hand Warmers
39                         ATV UTV Cargo Racks
40                             Car Organizer-1
41          SwingAway Hitchmount Cargo Carrier
42                          Gas and Water Cans
43                                   SwingAway
44                        Steering Wheel Locks
45                     Universal Lift Supports
46                          Metallic Fuel Cans
47                          Home Air Purifiers
48                                       Locks
49                              Bluetooth TPMS
Bluetooth TPMS

,Links,Name,Sponsored?,ASINs
0,https://www.amazon.com/dp/B0CTLXV1LW,TPMS Sensor 56029398AB 433Mhz Tire Pressure Mo...,Sponsored,B0CTLXV1LW
1,https://www.amazon.com/dp/B08PD7ZQVN,"LEEPEE Tire Pressure Monitoring System, 5 Alar...",Sponsored,B08PD7ZQVN
2,https://www.amazon.com/dp/B09Y1QM2P5,leepee Motorcycle Tire Pressure Monitoring Sys...,NaN,B09Y1QM2P5
3,https://www.amazon.com/dp/B09Z2P6M48,"Bluetooth Tire Pressure Monitoring System, wit...",NaN,B09Z2P6M48
4,https://www.amazon.com/dp/B0BKVHLPSP,B-Qtech Tire Pressure Monitoring System (0~199...,NaN,B0BKVHLPSP
...,...,...,...,...
427,https://www.amazon.com/dp/B08D5Z3J5Q,MORESENSOR Signature Series 433MHz TPMS Tire P...,NaN,B08D5Z3J5Q
428,https://www.amazon.com/dp/B0CQ8J9K5J,maXpeedingrods Double Din Car Stereo Radio 2G+...,Sponsored,B0CQ8J9K5J
429,https://www.amazon.com/dp/B08PD7WNNF,Autel MaxiPRO MP900-TS Scanner : 2024 Newest T...,Sponsored,B08PD7WNNF
430,https://www.amazon.com/dp/B0CWHKT7BL,ADEERLUO Tire Pressure Monitoring System for/C...,Sponsored,B0CWHKT7BL
431,https://www.amazon.com/dp/B08XK3DJ42,OBD2 Scanner TOPDON AD500 Oil/SAS/Throttle/TPM...,Sponsored,B08XK3DJ42

In [11]:
df1.loc[1,"Name"]

'LEEPEE Tire Pressure Monitoring System, 5 Alarm Modes, with 4 External Sensors TPMS, Support iOS and Android, Real-time Displays Pressure and Temperature (0.1-6.4Bar)'

In [12]:
links=[]
for i in range(len(df1)):
    # if " " in df1.loc[i,"Name"]:
        links.append(df1['Links'][i])

links=set(links)
links=list(links)

In [13]:
length=len(links)
print(length)

432

# 3. Setting Webdriver and Website Specific Information

In [14]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
wait=WebDriverWait(driver, 5)
driver.get('https://www.amazon.com/')

In [15]:
location = driver.find_element(By.ID, 'nav-global-location-popover-link')

location.click()
sleep(3)
pin = driver.find_element(By.ID, 'GLUXZipUpdateInput')
pinnumber='94203'
pin.send_keys(pinnumber)

apply=driver.find_element(By.CSS_SELECTOR, 'span.a-button-inner[data-action="GLUXPostalUpdateAction"]')
apply.click()

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [18]:
cols =['Sl.No','Attributes','Short_Details'] #,'Review_Mentions'
df = pd.DataFrame(columns=cols)
df
count=0

In [9]:
from IPython.display import clear_output 
import numpy as np
from datetime import timedelta
import datetime 
timestamp=[]
timediff=[]
def timeremaining(balanceitem,i):
    timestamp.insert(i,datetime.datetime.now())
    if i>=1:
        diff=timestamp[i]-timestamp[i-1]
        timediff.insert(i,diff.total_seconds())		
        remainingtime=np.median(timediff)*balanceitem
        millis=int(remainingtime)		
        #print(millis)
        seconds=(millis)%60
        seconds = int(seconds)
        minutes=(millis/(60))%60
        minutes = int((minutes)) #math.floor
        hours=(millis/(60*60))%24
        hours=int(hours)
        print(f'Item looped: {i+1} \nItems Remining: {balanceitem-1} and \nTime Remaining: {hours}:{minutes}:{seconds}')
        etc=datetime.datetime.now()+timedelta(hours=hours,minutes=minutes,seconds=seconds)
        print(f'Estimated time of completion:{etc}')        
        clear_output(wait=True)

In [19]:
driver.get(links[10])

In [20]:
for i in tqdm(range(length)):
    driver.get(links[i])
    df.loc[count,'Sl.No']=int(i)
    sleep(1)
    df.loc[count,'Name']=driver.find_element(By.XPATH, "//span[@class='a-size-large product-title-word-break']").text
    df.loc[count,'Links']=links[i]
    try:
        pricetopay=float(driver.find_element(By.CLASS_NAME, "priceToPay").text.replace('''\n''','.').replace('$','').replace(',',''))
        df.loc[count,'Current Price']=pricetopay
    except:
        pass
    try:
        listprice=float(driver.find_element(By.CLASS_NAME, "a-text-price").text.replace('''\n''','.').replace('$','').replace(',',''))
        df.loc[count,'List Price']=listprice
    except:
        try:
            df.loc[count,'List Price']=pricetopay
        except:
            pass
    try:
        df.loc[count,'Rating']=float(driver.find_element(By.ID, "averageCustomerReviews").text.split("\n")[0])
    except:
        df.loc[count,'Rating']=0               
    try:
        df.loc[count,'No of Ratings']=int(driver.find_element(By.ID, "acrCustomerReviewText").text.split(' ')[0].replace(",",""))
    except:
        df.loc[count,'No of Ratings']=0
    Alist=[]
    try:
        table=driver.find_element(By.CSS_SELECTOR,'[id="productDetails_techSpec_section_1"]')
        Values=table.find_elements(By.TAG_NAME, "tr")
        for row in Values:
            # Extract data from columns (td/th elements)
            l=row.find_element(By.TAG_NAME, "th").text
            v=row.find_element(By.TAG_NAME, "td").text
            Alist.append(l+":"+v)
    except:
        pass
    try:
        table=driver.find_element(By.CSS_SELECTOR,'[id="productDetails_detailBullets_sections1"]')
        Values=table.find_elements(By.TAG_NAME, "tr")
        for row in Values:
            # Extract data from columns (td/th elements)
            l=row.find_element(By.TAG_NAME, "th").text
            v=row.find_element(By.TAG_NAME, "td").text
            Alist.append(l+":"+v)
    except:
        attrs=driver.find_element(By.CSS_SELECTOR,'[id="detailBulletsWrapper_feature_div"]').find_elements(By.CSS_SELECTOR,'[class="a-list-item"]')
        for att in attrs:
            Alist.append(att.text)
    df.at[count,'Attributes']=Alist
    try:
        df.loc[count,'Sales_LastMonth']=int(driver.find_element(By.ID, "social-proofing-faceout-title-tk_bought").text.split("+")[0].replace('K','000'))
    except:
        df.loc[count,'Sales_LastMonth']=0
    try:
        df.loc[count,'Details']=driver.find_element(By.XPATH, "(//div[@class='a-section a-spacing-medium a-spacing-top-small'])").text
    except:
        pass
    try:
        ls=driver.find_elements(By.CSS_SELECTOR,'[class="a-span3"]')
        vs=driver.find_elements(By.CSS_SELECTOR,'[class="a-span9"]')
        D_s=[]
        for l,v in zip(ls,vs):
            D_s.append(l.text+":"+v.text)
    except:
        pass
    try:
        es=driver.find_elements(By.CLASS_NAME,"a-normal")
        os= es[2].find_elements(By.CLASS_NAME,"a-text-bold")
        vs=es[2].find_elements(By.CSS_SELECTOR,'[class="a-size-base handle-overflow"]')
        for o, v  in zip( os, vs):
            D_s.append(o.text+":"+v.text)
    except:
        pass

    df.at[count,"Short_Details"]=D_s
    try:
        df.loc[count,'Product_Category']=driver.find_element(By.CSS_SELECTOR,'[class="a-unordered-list a-horizontal a-size-small"]').text.rsplit('\n')[-1]
    except:
        pass
    try:
        df.loc[count,'ReviewSummary']=driver.find_element(By.CSS_SELECTOR,'[id="product-summary"]').text
    except:
        pass
    try:
        elements=driver.find_element(By.ID, 'aspect-button-group-0').find_elements(By.TAG_NAME, 'button')
        len(elements)
        slist=[]
        for element in elements:
            s=element.get_attribute('data-csa-c-item-id')
            slist.append(s)
        #print(slist)
        df.at[count,"Sentiment"]=slist
    except:
        df.loc[count,'Sentiment']=""
    try: 
        filename=links[i].split("/")[-1]+".jpg" # Extract filename from URL (modify if needed)
        t=driver.find_element(By.CSS_SELECTOR,'[id="landingImage"]')
        s=t.get_attribute('src')
        import requests

        # Download the image using requests
        response = requests.get(s, stream=True)

        if response.status_code == 200:            
            savepath=imagepath+"\\"+filename
        # Get filename from URL or generate a unique one
            with open(savepath, 'wb') as f:
                for chunk in response.iter_content(1024):
                    f.write(chunk)
            print(f"Image downloaded: {filename}")
        else:
            print(f"Failed to download image: {s}")
    except:
        print(f"part number not available for {filename}")
    count=count+1
    balanceitem=length-i
    #print(balanceitem)
    #timeremaining(balanceitem,i)
    clear_output(wait=True)

100%|██████████| 432/432 [41:07<00:00,  5.71s/it]

In [21]:
print(df.shape)
df.head()

(432, 14)

,Sl.No,Attributes,Short_Details,Name,Links,Current Price,List Price,Rating,No of Ratings,Sales_LastMonth,Details,Product_Category,ReviewSummary,Sentiment
0,0,"[Manufacturer:tuhaowa, Brand:tuhaowa, Item Wei...","[Brand:tuhaowa, Style:Modern, Mounting Type:Fl...",TPMS Sensor Tire Pressure Sensor Compatible wi...,https://www.amazon.com/dp/B09PV8PGQ8,39.99,39.99,2.9,116.0,0.0,About this item\n🚗Fitment 1: The tire pressure...,Replacement Sensors,Customers say\nCustomers have negative opinion...,
1,1,[Package Dimensions : 7.52 x 3.46 x 1.06 inche...,"[Brand:T Sportline, Style:Modern, Output Type:...",4 New Tesla Bluetooth TPMS Tire Pressure Monit...,https://www.amazon.com/dp/B0BD9CMSR1,109.95,69.99,4.4,13.0,0.0,,Replacement Sensors,NaN,
2,2,"[Manufacturer:VAOYAO, Brand:VAOYAO, Model:C260...",[],"Tire Pressure Monitoring System, Solar Power U...",https://www.amazon.com/dp/B0CJ29LC8J,23.99,23.99,3.3,8.0,0.0,【2 Installation Positions ＆ Adjustable Angle】T...,Aftermarket Systems,NaN,
3,3,"[Manufacturer:XTOOL, Brand:XTOOL, Model:XTOOL ...","[Brand:XTOOL, Power Source:OBD II Port, Operat...","Wireless OBD2 Scanner for Android & iPhone, XT...",https://www.amazon.com/dp/B09KT9XNML,199.00,699.00,4.4,692.0,200.0,About this item\n🚀 Stay Ahead with Free Update...,Code Readers & Scan Tools,Customers say\nCustomers like the live data an...,"[Performance_POSITIVE, Value_POSITIVE, Quality..."
4,4,"[Brand:MOBILETRON, Item dimensions L x W x H:3...","[Brand:MOBILETRON, Item dimensions L x W x H:3...",MORESENSOR Signature Series 315MHz TPMS Tire P...,https://www.amazon.com/dp/B01MT9ZNYO,49.99,69.99,4.2,160.0,0.0,About this item\nRelearn Ready : Our preprogra...,Replacement Sensors,Customers say\nCustomers have expressed positi...,"[Value_POSITIVE, Quality_POSITIVE, Performance..."

# 5. Post Processing Data and Exporting

In [22]:
namesplit=search_text.split(" ")
print(namesplit)

['Bluetooth', 'TPMS']

In [23]:
df['Name_Clean']=df['Name'].str.lower().str.replace("compatible with","").str.replace('w/',"with ")
for i in range(len(df)):
    if namesplit[0] in df['Name_Clean'][i] and namesplit[1] in df['Name_Clean'][i]and namesplit[2] in df['Name_Clean'][i]and namesplit[3] in df['Name_Clean'][i]and namesplit[1] in df['Name_Clean'][4]:
        df.loc[i,'Product']=search_text
    else:
        df.loc[i,"Product"]="Other Product"
del df['Name_Clean']

In [84]:
#df = df[(df['Current Price'] > 0)]

In [24]:
df['Short_Details'][1]

['Brand:T Sportline',
 'Style:Modern',
 'Output Type:Digital',
 'Specific Uses For Product:Pressure',
 'Global Trade Identification Number:00810105900903']

In [25]:
df['Material']=df['Short_Details'].apply(lambda x: str(x).replace('[','').replace(']','').replace('\'', '').replace(' ','')).str.split('Material:',expand=True)[1].str.split(''',''',expand=True)[0]
df['ASIN']=df['Links'].str.split('dp/',expand=True)[1]
df=df.drop_duplicates(subset=['Links'])

In [26]:
#df['Part Number']=df["Attributes"].apply(lambda x: str(x).replace('[','').replace(']','').replace('\'', '').replace(' ','')).str.split('ManufacturerPartNumber:',expand=True)[1].str.split(',',expand=True)[0]
df['Brand']=df["Attributes"].apply(lambda x: str(x).replace('[','').replace(']','').replace('\'', '').replace(' ','')).str.split('Brand:',expand=True)[1].str.split(',',expand=True)[0]
df['Manufacturer']=df["Attributes"].apply(lambda x: str(x).replace('[','').replace(']','').replace('\'', '').replace(' ','')).str.split('Manufacturer:',expand=True)[1].str.split(',',expand=True)[0]
df['Source']="Amazon"
df[['Rating',"No of Ratings","Sales_LastMonth",'Manufacturer','Material', "Brand","Source"]].head() #,'Part Number'

,Rating,No of Ratings,Sales_LastMonth,Manufacturer,Material,Brand,Source
0,2.9,116.0,0.0,tuhaowa,None,tuhaowa,Amazon
1,4.4,13.0,0.0,TSportline,None,None,Amazon
2,3.3,8.0,0.0,VAOYAO,None,VAOYAO,Amazon
3,4.4,692.0,200.0,XTOOL,None,XTOOL,Amazon
4,4.2,160.0,0.0,MobiletronElectronics,ReinforcedPlasticandMetalValveStem,MOBILETRON,Amazon

In [27]:
cols=["Sl.No",
"Name",
"Product",
'Product_Category',
"Current Price",
"List Price",
"Rating",
"No of Ratings",
"Short_Details",
"Details",
"Sales_LastMonth",
"Attributes",
"Brand",

"Manufacturer",

"ReviewSummary",
"Sentiment",
"Material",
"ASIN",
"Links",
"Source"
] #"Part Number","FirstAvailableDate",
df=df[cols]

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 432 entries, 0 to 431
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Sl.No             432 non-null    object
 1   Name              432 non-null    object
 2   Product           432 non-null    object
 3   Product_Category  432 non-null    object
 4   Current Price     426 non-null    float64
 5   List Price        432 non-null    float64
 6   Rating            432 non-null    float64
 7   No of Ratings     432 non-null    float64
 8   Short_Details     432 non-null    object
 9   Details           432 non-null    object
 10  Sales_LastMonth   432 non-null    float64
 11  Attributes        432 non-null    object
 12  Brand             285 non-null    object
 13  Manufacturer      424 non-null    object
 14  ReviewSummary     178 non-null    object
 15  Sentiment         432 non-null    object
 16  Material          106 non-null    object
 17  ASIN              432 non-null    object
 18  Links             432 non-null    object
 19  Source            432 non-null    object
dtypes: float64(5), object(15)
memory usage: 70.9+ KB

In [29]:
print(df.shape)
df.head()

(432, 20)

,Sl.No,Name,Product,Product_Category,Current Price,List Price,Rating,No of Ratings,Short_Details,Details,Sales_LastMonth,Attributes,Brand,Manufacturer,ReviewSummary,Sentiment,Material,ASIN,Links,Source
0,0,TPMS Sensor Tire Pressure Sensor Compatible wi...,Other Product,Replacement Sensors,39.99,39.99,2.9,116.0,"[Brand:tuhaowa, Style:Modern, Mounting Type:Fl...",About this item\n🚗Fitment 1: The tire pressure...,0.0,"[Manufacturer:tuhaowa, Brand:tuhaowa, Item Wei...",tuhaowa,tuhaowa,Customers say\nCustomers have negative opinion...,,None,B09PV8PGQ8,https://www.amazon.com/dp/B09PV8PGQ8,Amazon
1,1,4 New Tesla Bluetooth TPMS Tire Pressure Monit...,Other Product,Replacement Sensors,109.95,69.99,4.4,13.0,"[Brand:T Sportline, Style:Modern, Output Type:...",,0.0,[Package Dimensions : 7.52 x 3.46 x 1.06 inche...,None,TSportline,NaN,,None,B0BD9CMSR1,https://www.amazon.com/dp/B0BD9CMSR1,Amazon
2,2,"Tire Pressure Monitoring System, Solar Power U...",Other Product,Aftermarket Systems,23.99,23.99,3.3,8.0,[],【2 Installation Positions ＆ Adjustable Angle】T...,0.0,"[Manufacturer:VAOYAO, Brand:VAOYAO, Model:C260...",VAOYAO,VAOYAO,NaN,,None,B0CJ29LC8J,https://www.amazon.com/dp/B0CJ29LC8J,Amazon
3,3,"Wireless OBD2 Scanner for Android & iPhone, XT...",Other Product,Code Readers & Scan Tools,199.00,699.00,4.4,692.0,"[Brand:XTOOL, Power Source:OBD II Port, Operat...",About this item\n🚀 Stay Ahead with Free Update...,200.0,"[Manufacturer:XTOOL, Brand:XTOOL, Model:XTOOL ...",XTOOL,XTOOL,Customers say\nCustomers like the live data an...,"[Performance_POSITIVE, Value_POSITIVE, Quality...",None,B09KT9XNML,https://www.amazon.com/dp/B09KT9XNML,Amazon
4,4,MORESENSOR Signature Series 315MHz TPMS Tire P...,Other Product,Replacement Sensors,49.99,69.99,4.2,160.0,"[Brand:MOBILETRON, Item dimensions L x W x H:3...",About this item\nRelearn Ready : Our preprogra...,0.0,"[Brand:MOBILETRON, Item dimensions L x W x H:3...",MOBILETRON,MobiletronElectronics,Customers say\nCustomers have expressed positi...,"[Value_POSITIVE, Quality_POSITIVE, Performance...",ReinforcedPlasticandMetalValveStem,B01MT9ZNYO,https://www.amazon.com/dp/B01MT9ZNYO,Amazon

In [30]:
dfAtt=df[['ASIN','Attributes']]
dfAtt=dfAtt.explode('Attributes')
dfAtt[['Attributes', 'Value']] = dfAtt['Attributes'].str.split(':',1, expand=True)

In [31]:
summary_df = pd.pivot_table(dfAtt, values='Value', index='Attributes',aggfunc='count').reset_index()
summary_df =summary_df.sort_values(by='Value',ascending=False)
summary_df=summary_df.rename(columns ={'Value':'No Products contains this Attribute'})
summary_df

,Attributes,No Products contains this Attribute
102,Best Sellers Rank,392
110,Customer Reviews,360
131,Item Weight,346
94,ASIN,330
111,Date First Available,322
...,...,...
65,#50 in Aftermarket Tire Pressure Monitoring Sy...,0
66,#516 in Replacement Tire Pressure Monitoring S...,0
67,#54 in Replacement Tire Pressure Monitoring Sy...,0
68,#561 in Replacement Tire Pressure Monitoring S...,0
0,,0

In [32]:
with pd.ExcelWriter(OFolder+'\\'+f'{Source}ProductDetails_'+search_text+'.xlsx') as writer:  # doctest: +SKIP
    df.to_excel(writer,index=False, sheet_name='Raw')
    summary_df.to_excel(writer,index=False, sheet_name='Attribute_Summary')
    dfAtt.to_excel(writer,index=False, sheet_name='Attribute_Values')

# 99. Archived Codes

In [1]:
#Downloading images from amazon.
from selenium import webdriver
from selenium.webdriver.common.by import By
import openpyxl
import requests
from io import BytesIO
from openpyxl import Workbook
from openpyxl.drawing.image import Image

#--------------------------------------------------------------------------------------------------------------------------
il=[]
for i in range(length):
    driver.get(links[i])
    imagelink=driver.find_element(By.ID,"landingImage").get_attribute('src')
    il.append(imagelink)
    response = requests.get(imagelink)
    img_data = BytesIO(response.content)
    ASIN=links[i].split('dp/')[1]
    img_filename = f"{ASIN}.jpg"
    with open(img_filename, "wb") as img_file:
        img_file.write(img_data.getvalue())
    # # Create a DataFrame
    # df = pd.DataFrame({'Product Image URL': [imagelink]})
    # df.loc[count,'ASIN']=ASIN
    # # Save the DataFrame to an Excel file
    # excel_filename = "product_data.xlsx"
    # df.to_excel(excel_filename, index=False,)
    # wb = Workbook()
    # ws = wb.active
    # img = Image(img_filename)
    # ws.add_image(img, f'C{count+2}')
    # wb.save(excel_filename)
    balanceitem=length-i
    timeremaining(balanceitem,i)

NameError: name 'length' is not defined