# 1. Library calling

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
import warnings
from tqdm import tqdm
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

# 2. Defining the Product Information and Location

In [2]:
SummaryFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects'
summaryFile='Scraping_List.txt'
st=pd.read_csv(SummaryFolder+'\\'+summaryFile)
print(st)
#Define Product to extract
search_text = st['Product Name'][42]
print(search_text)
Source="e-bay"
OFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Outputs'
IFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Inputs'
imagepath=fr"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\Vikram Data research"+'\\'+search_text+"\e-bay"

                                  Product Name
0                                Ignition Coil
1                      Windshield Washer Pumps
2                        coupler trailer locks
3          Adjustable Trailer Hitch Ball Mount
4                               Vacuum Cleaner
5                                   Spark Plug
6              bluetooth Enabled Trailer locks
7                          Power Steering Hose
8   Power Steering Pressure Line Hose Assembly
9                       Washer Fluid Reservoir
10          Hitch Ball Mount with Weight Scale
11                               LED Headlamps
12                             LED flashlights
13                   Fiberglass Tonneau Covers
14                    Aluminium Tonneau Covers
15                     Hardfold Tonneau Covers
16                            Spark Plug Wires
17                 washer fluid reservoir tank
18                   Non Automotive Gas Struts
19                     trunk hanging organizer
20                                    car jack
21                              Towing Mirrors
22                                    Gas Lift
23                        caliper pad spreader
24                               fuel injector
25        wireless carplay screen with dashcam
26                 Vehicle Soft-Shell Carriers
27                               Scissor Jacks
28               Electrical Hydraulic Car Jack
29                 Electrical Scissor Car Jack
30                               Trailer Locks
31                             Conical Filters
32                                  Car Covers
33                                 Tyre Covers
34                                    Car Mats
35                           Dolly Tire Racks
36                             Cargo Organizer
37                               Car Organizer
38                   Rechargeable Hand Warmers
39                         ATV UTV Cargo Racks
40                             Car Organizer-1
41          SwingAway Hitchmount Cargo Carrier
42                          Gas and Water Cans
43                                   SwingAway
44                        Steering Wheel Locks
45                     Universal Lift Supports
Gas and Water Cans

In [3]:
imagepath

'C:\\Users\\Vikram.Vadhirajan\\OneDrive - Trico\\Vikram Data research\\Gas and Water Cans\\e-bay'

# 3. Setting Webdriver and Website Specific Information

In [4]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
wait=WebDriverWait(driver, 5)
driver.get('https://www.ebay.com/')

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [6]:
cols =['Links'] #,'Review_Mentions'
df1 = pd.DataFrame(columns=cols)
count1=0

In [8]:
Details=driver.find_elements(By.CSS_SELECTOR,'[class="s-item__info clearfix"]')
for i in range(len(Details)):
    if i>=1:
        df1.loc[count1,"Name"]=Details[i].text.split("\n")[0]
        try:
            df1.loc[count1,"Current Price"]=float(Details[i].text.split("$")[1].split("\n")[0])
        except:
            df1.loc[count1,"Current Price"]=Details[i].text.split("$")[1].split("\n")[0]
        try:
            df1.loc[count1,"List Price"]=float(Details[i].text.split("Was: $")[1].split("  ")[0])
        except:
            df1.loc[count1,"List Price"]=0
        try:
            df1.loc[count1,"Sales_LastMonth"]=int(Details[i].text.split("sold")[0].split("\n")[-1])
        except:
            df1.loc[count1,"Sales_LastMonth"]=0
        df1.loc[count1,"Links"]=Details[i].find_element(By.CLASS_NAME,"s-item__link").get_attribute("href")
        df1.loc[count1,"ItemNumber"]=Details[i].text.split("Item: ")[1].split("\n")[0]
        try:
            df1.loc[count1,"Rating"]=Details[i].text.split(" out of 5")[0].split("\n")[-1]
        except:
            pass
        try:
            df1.loc[count1,"No of Ratings"]=Details[i].text.split("product rating")[0].split("\n")[-1]
        except:
            pass
        count1=count1+1

In [192]:
length=len(df1)

In [10]:
df1

,Links,Name,Current Price,List Price,Sales_LastMonth,ItemNumber,Rating,No of Ratings
0,https://www.ebay.com/itm/296371886252?itmmeta=...,5 Gallon SmartControl Dual Handle Diesel Fuel ...,20.23,0.0,0.0,296371886252,Item: 296371886252,Item: 296371886252
1,https://www.ebay.com/itm/364863456249?itmmeta=...,Scepter 5 Gallon SmartControl Dual Handle Dies...,20.81,0.0,0.0,364863456249,Item: 364863456249,Item: 364863456249
2,https://www.ebay.com/itm/375361474544?itmmeta=...,5 Gallon SmartControl Dual Handle Diesel Fuel ...,22.11,0.0,16.0,375361474544,Item: 375361474544,Item: 375361474544
3,https://www.ebay.com/itm/386879183012?itmmeta=...,Scepter 5 Gallon Gas Can SmartControl Enhance ...,20.81,0.0,53.0,386879183012,Item: 386879183012,Item: 386879183012
4,https://www.ebay.com/itm/315277306111?itmmeta=...,5 Gallon SmartControl Dual Handle Diesel Fuel ...,22.26,0.0,7.0,315277306111,Item: 315277306111,Item: 315277306111
...,...,...,...,...,...,...,...,...
235,https://www.ebay.com/itm/364886877515?itmmeta=...,1.3 Gal/5L For ATV/off road/motorbike Fuel Gas...,42.0,0.0,0.0,364886877515,Item: 364886877515,Item: 364886877515
236,https://www.ebay.com/itm/364885428371?itmmeta=...,For ATV/off road/motorbike Fuel Gas Storage Ta...,41.89,0.0,0.0,364885428371,Item: 364885428371,Item: 364885428371
237,https://www.ebay.com/itm/196381567607?itmmeta=...,1.3 Gal/5L For ATV/off road/motorbike Fuel Gas...,42.0,0.0,0.0,196381567607,Item: 196381567607,Item: 196381567607
238,https://www.ebay.com/itm/174593986611?itmmeta=...,8 Gallon 30L Fuel Pack Gas Container Fuel Can ...,299.99,0.0,0.0,174593986611,Item: 174593986611,Item: 174593986611
239,https://www.ebay.com/itm/303668326176?itmmeta=...,20L 30L Can Backup Tank Fuel Gas Gasoline Cont...,49.99 to,0.0,0.0,303668326176,Item: 303668326176,Item: 303668326176

In [194]:
cols =['Sl.No','Attributes'] #,'Review_Mentions'
df = pd.DataFrame(columns=cols)
count=0

In [143]:
driver.get(df1['Links'][15])

In [144]:
delements=driver.find_elements(By.CLASS_NAME,"ux-labels-values__labels")
velements=driver.find_elements(By.CLASS_NAME,"ux-labels-values__values")
for d, v in zip(delements,velements):
    c=d.text+v.text
    s=d.text+":" +v.text
    print(s)

Shipping::Free Other Shipping. See details
for shipping
:International shipment of items may be subject to customs processing and additional charges.
Located in: Ha Tinh, Vietnam
Delivery::Estimated between Wed, May 22 and Wed, May 29 to 94203
This item has an extended handling time and a delivery estimate greater than 11 business days.
Please allow additional time if international delivery is subject to customs processing.
Returns::Seller does not accept returns. See details
- for more information about returns
Payments::
Condition:New: A brand-new, unused, unopened, undamaged item in its original packaging (where packaging is ... Read more
about the condition
Brand:Scepter
:
:
:

In [195]:
for i in tqdm(range(length)):
    driver.get(df1['Links'][i])
    df.loc[count,'Links']=df1['Links'][i]
    sleep(1)

    delements=driver.find_elements(By.CLASS_NAME,"ux-labels-values__labels")
    velements=driver.find_elements(By.CLASS_NAME,"ux-labels-values__values")
    Alist=[]
    for d, v in zip(delements,velements):
        c=d.text+v.text
        s=d.text+":" +v.text
        if ":" in c:
            pass
        else:
            if s.startswith(':'):
                pass
            else:
                Alist.append(s)
    df['Attributes'] = df['Attributes'].astype('object')
    df.at[count,'Attributes']=Alist
    df.loc[count,"Source"]=Source
    df.loc[count,"Product"]=search_text
    count=count+1
    clear_output(wait=True)

 17%|█▋        | 40/240 [03:14<16:14,  4.87s/it]

KeyboardInterrupt:

In [23]:

filename=df1['ItemNumber'][5]+".jpg" # Extract filename from URL (modify if needed)
t=driver.find_element(By.CLASS_NAME,"image-treatment")
s=t.get_attribute('src')
print(s)
import requests

# Download the image using requests
response = requests.get(s, stream=True)

if response.status_code == 200:
    savepath=imagepath+"\\"+filename
# Get filename from URL or generate a unique one
    with open(savepath, 'wb') as f:
        for chunk in response.iter_content(1024):
            f.write(chunk)
    print(f"Image downloaded: {filename}")
else:
    print(f"Failed to download image: {s}")

None

MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant http://None?

In [197]:
print(df.shape)
df

(41, 5)

,Sl.No,Attributes,Links,Source,Product
0,NaN,"[Features:For Emergency, Color:Yellow, Item We...",https://www.ebay.com/itm/126230989799?itmmeta=...,e-bay,Steering Wheel Locks
1,NaN,"[OE/OEM Part Number:No, Material:Plastic, Capa...",https://www.ebay.com/itm/154593952241?itmmeta=...,e-bay,Steering Wheel Locks
2,NaN,"[库存SKU:1507305181, 平台SKU:WAL4-wu-1507305181, F...",https://www.ebay.com/itm/395388338868?itmmeta=...,e-bay,Steering Wheel Locks
3,NaN,"[Brand:Unbranded, MPN:FSCD571, UPC:Does not ap...",https://www.ebay.com/itm/135000483801?itmmeta=...,e-bay,Steering Wheel Locks
4,NaN,"[Model:SUR5SFG2, UPC:0855465008067, Brand:Sure...",https://www.ebay.com/itm/285382222098?itmmeta=...,e-bay,Steering Wheel Locks
5,NaN,"[Assembled Product Weight:3.31 lb, Brand:Unbra...",https://www.ebay.com/itm/364863456249?itmmeta=...,e-bay,Steering Wheel Locks
6,NaN,"[Brand:Unbranded, Manufacturer Part Number:Doe...",https://www.ebay.com/itm/234194448488?itmmeta=...,e-bay,Steering Wheel Locks
7,NaN,"[Brand:Unbranded, Assembled Product Weight:2.6...",https://www.ebay.com/itm/386879183012?itmmeta=...,e-bay,Steering Wheel Locks
8,NaN,"[Brand:Unbranded, MPN:FSCD571, UPC:Does not ap...",https://www.ebay.com/itm/226137233310?itmmeta=...,e-bay,Steering Wheel Locks
9,NaN,"[Type:Fuel Tank, Brand:ibacpstore, Capacity:3 ...",https://www.ebay.com/itm/295310231475?itmmeta=...,e-bay,Steering Wheel Locks
10,NaN,"[Brand:Unbranded, Dimensions (L x W x H):12.00...",https://www.ebay.com/itm/315277306111?itmmeta=...,e-bay,Steering Wheel Locks
11,NaN,"[Country/Region of Manufacture:China, Mounting...",https://www.ebay.com/itm/404859155429?itmmeta=...,e-bay,Steering Wheel Locks
12,NaN,"[Type:Fuel Tank, Brand:ibacpstore, Capacity:3 ...",https://www.ebay.com/itm/295310231501?itmmeta=...,e-bay,Steering Wheel Locks
13,NaN,"[Brand:LTO, Manufacturer Part Number:Does Not ...",https://www.ebay.com/itm/285099002766?itmmeta=...,e-bay,Steering Wheel Locks
14,NaN,"[Brand:Xuanyue, Type:Fuel Tank, Material:High-...",https://www.ebay.com/itm/145761229310?itmmeta=...,e-bay,Steering Wheel Locks
15,NaN,"[Brand:Unbranded, MPN:FSCD571, UPC:Does not ap...",https://www.ebay.com/itm/364807882016?itmmeta=...,e-bay,Steering Wheel Locks
16,NaN,"[Brand:VP Racing Fuels, MPN:VP-(2)3532-(1)3044]",https://www.ebay.com/itm/275993300087?itmmeta=...,e-bay,Steering Wheel Locks
17,NaN,"[Brand:WINMAX, Capacity:5 gal, Country/Region ...",https://www.ebay.com/itm/285462190258?itmmeta=...,e-bay,Steering Wheel Locks
18,NaN,"[Brand:Ibacpstore, MPN:Does Not Apply]",https://www.ebay.com/itm/295516957421?itmmeta=...,e-bay,Steering Wheel Locks
19,NaN,"[Brand:Unbranded, Assembled Product Weight:3.3...",https://www.ebay.com/itm/186429253137?itmmeta=...,e-bay,Steering Wheel Locks
20,NaN,"[Brand:Scepter, MPN:FSCD571, UPC:Does not apply]",https://www.ebay.com/itm/364811764898?epid=170...,e-bay,Steering Wheel Locks
21,NaN,"[Brand:Unbranded, Dimensions (L x W x H):12.00...",https://www.ebay.com/itm/285810122958?itmmeta=...,e-bay,Steering Wheel Locks
22,NaN,"[Brand:Ibacpstore, MPN:Does Not Apply]",https://www.ebay.com/itm/295517162534?itmmeta=...,e-bay,Steering Wheel Locks
23,NaN,[Brand:Scepter],https://www.ebay.com/itm/166021850927?itmmeta=...,e-bay,Steering Wheel Locks
24,NaN,"[Brand:RotopaX, Fit:Universal Fit, Service：:√A...",https://www.ebay.com/itm/235203041963?itmmeta=...,e-bay,Steering Wheel Locks
25,NaN,"[Brand:ibacpstore, Type:Fuel Tank, Capacity:1....",https://www.ebay.com/itm/295310225278?itmmeta=...,e-bay,Steering Wheel Locks
26,NaN,"[Brand:Ibacpstore, MPN:Does Not Apply]",https://www.ebay.com/itm/295517166503?itmmeta=...,e-bay,Steering Wheel Locks
27,NaN,"[Brand:WINMAX, Capacity:8 gal, Country/Region ...",https://www.ebay.com/itm/284238601692?itmmeta=...,e-bay,Steering Wheel Locks
28,NaN,"[Brand:Unbranded, UPC:Does not apply, MPN:FSCD...",https://www.ebay.com/itm/375361474544?itmmeta=...,e-bay,Steering Wheel Locks
29,NaN,"[Brand:lighting-likes, Material:ABS Plastic, F...",https://www.ebay.com/itm/144070658222?itmmeta=...,e-bay,Steering Wheel Locks
30,NaN,"[Brand:Unbranded, Capacity:8 gal, Features:Lon...",https://www.ebay.com/itm/144760886994?itmmeta=...,e-bay,Steering Wheel Locks
31,NaN,"[Brand:lighting-likes, Material:ABS Plastic, F...",https://www.ebay.com/itm/144592441021?itmmeta=...,e-bay,Steering Wheel Locks
32,NaN,"[Fits:Jeep, Warranty:Yes, Certifications:EPA a...",https://www.ebay.com/itm/201470087365?epid=631...,e-bay,Steering Wheel Locks
33,NaN,"[Brand:Feweni, Type:Fuel Tank, Material:High-d...",https://www.ebay.com/itm/145382759277?itmmeta=...,e-bay,Steering Wheel Locks
34,NaN,"[Manufacturer Part Number:PER52821001, Country...",https://www.ebay.com/itm/255011594560?itmmeta=...,e-bay,Steering Wheel Locks
35,NaN,"[Brand:Unbranded, Capacity:5.2 gal, Country/Re...",https://www.ebay.com/itm/285734030837?itmmeta=...,e-bay,Steering Wheel Locks
36,NaN,"[Brand:CCH, Manufacturer Part Number:Does Not ...",https://www.ebay.com/itm/114348686724?itmmeta=...,e-bay,Steering Wheel Locks
37,NaN,"[Assembled Product Weight:1.35 lb, Assembled P...",https://www.ebay.com/itm/176349422381?itmmeta=...,e-bay,Steering Wheel Locks
38,NaN,"[Capacity:20L (5 gallon), Color:Red, Manufactu...",https://www.ebay.com/itm/133857063397?itmmeta=...,e-bay,Steering Wheel Locks
39,NaN,[*Besonderheiten*:✨✨Easy installation & Compac...,https://www.ebay.com/itm/296288406479?itmmeta=...,e-bay,Steering Wheel Locks
40,NaN,NaN,https://www.ebay.com/itm/404641113565?itmmeta=...,NaN,NaN

# 5. Post Processing Data and Exporting

In [198]:
df['Brand']=df["Attributes"].apply(lambda x: str(x).replace('[','').replace(']','').replace('\'', '').replace(' ','')).str.split('Brand:',expand=True)[1].str.split(',',expand=True)[0]
df['Material']=df["Attributes"].apply(lambda x: str(x).replace('[','').replace(']','').replace('\'', '').replace(' ','')).str.split('Material:',expand=True)[1].str.split(',',expand=True)[0]
df['Part Number']=df["Attributes"].apply(lambda x: str(x).replace('[','').replace(']','').replace('\'', '').replace(' ','')).str.split("ManufacturerPartNumber:",expand=True)[1].str.split(',',expand=True)[0]
df['UPC Code']=df["Attributes"].apply(lambda x: str(x).replace('[','').replace(']','').replace('\'', '').replace(' ','')).str.split('UPC:',expand=True)[1].str.split(',',expand=True)[0]

In [199]:
print(df1.shape)
df1.info()

(240, 8)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 240 entries, 0 to 239
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Links            240 non-null    object
 1   Name             240 non-null    object
 2   Current Price    240 non-null    object
 3   List Price       240 non-null    float64
 4   Sales_LastMonth  240 non-null    float64
 5   ItemNumber       240 non-null    object
 6   Rating           240 non-null    object
 7   No of Ratings    240 non-null    object
dtypes: float64(2), object(6)
memory usage: 25.0+ KB

In [200]:
print(df.shape)
df.info()

(41, 9)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 41 entries, 0 to 40
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sl.No        0 non-null      object
 1   Attributes   40 non-null     object
 2   Links        41 non-null     object
 3   Source       40 non-null     object
 4   Product      40 non-null     object
 5   Brand        40 non-null     object
 6   Material     22 non-null     object
 7   Part Number  19 non-null     object
 8   UPC Code     31 non-null     object
dtypes: object(9)
memory usage: 4.2+ KB

In [201]:
Mergeddf=pd.merge(df1,df,on = "Links",how='left')
print(Mergeddf.shape)
Mergeddf.info()

(240, 16)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 240 entries, 0 to 239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Links            240 non-null    object
 1   Name             240 non-null    object
 2   Current Price    240 non-null    object
 3   List Price       240 non-null    float64
 4   Sales_LastMonth  240 non-null    float64
 5   ItemNumber       240 non-null    object
 6   Rating           240 non-null    object
 7   No of Ratings    240 non-null    object
 8   Sl.No            0 non-null      object
 9   Attributes       40 non-null     object
 10  Source           40 non-null     object
 11  Product          40 non-null     object
 12  Brand            40 non-null     object
 13  Material         22 non-null     object
 14  Part Number      19 non-null     object
 15  UPC Code         31 non-null     object
dtypes: float64(2), object(14)
memory usage: 31.9+ KB

In [202]:
cols=["Sl.No",
"Name",
"Product",
"Current Price",
"List Price",
"Rating",
"No of Ratings",
"Sales_LastMonth",
"Attributes",
"Brand",
"Part Number",
"UPC Code",
"Links",
"Source"
] #
Mergeddf=Mergeddf[cols]

In [203]:
Mergeddf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 240 entries, 0 to 239
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Sl.No            0 non-null      object
 1   Name             240 non-null    object
 2   Product          40 non-null     object
 3   Current Price    240 non-null    object
 4   List Price       240 non-null    float64
 5   Rating           240 non-null    object
 6   No of Ratings    240 non-null    object
 7   Sales_LastMonth  240 non-null    float64
 8   Attributes       40 non-null     object
 9   Brand            40 non-null     object
 10  Part Number      19 non-null     object
 11  UPC Code         31 non-null     object
 12  Links            240 non-null    object
 13  Source           40 non-null     object
dtypes: float64(2), object(12)
memory usage: 28.1+ KB

In [204]:
print(Mergeddf.shape)
Mergeddf.head()

(240, 14)

,Sl.No,Name,Product,Current Price,List Price,Rating,No of Ratings,Sales_LastMonth,Attributes,Brand,Part Number,UPC Code,Links,Source
0,NaN,5 Gallon SmartControl Dual Handle Diesel Fuel ...,Steering Wheel Locks,23.72,0.00,Add to cart,Add to cart,22.0,"[Features:For Emergency, Color:Yellow, Item We...",Unbranded,None,972670564802,https://www.ebay.com/itm/126230989799?itmmeta=...,e-bay
1,NaN,8 Gallon /30L Fuel Tank Pack Gas Oil Container...,Steering Wheel Locks,75.0,87.50,Add to cart,Add to cart,100.0,"[OE/OEM Part Number:No, Material:Plastic, Capa...",Unbranded,WT01Z0727,213299445463,https://www.ebay.com/itm/154593952241?itmmeta=...,e-bay
2,NaN,5 Gallon SmartControl Dual Handle Diesel Fuel ...,Steering Wheel Locks,23.1,27.18,Add to cart,Add to cart,0.0,"[库存SKU:1507305181, 平台SKU:WAL4-wu-1507305181, F...",Unbranded,None,DoesNotApply,https://www.ebay.com/itm/395388338868?itmmeta=...,e-bay
3,NaN,5 Gallon SmartControl Dual Handle Diesel Fuel ...,Steering Wheel Locks,22.41,31.57,Add to cart,Add to cart,14.0,"[Brand:Unbranded, MPN:FSCD571, UPC:Does not ap...",Unbranded,None,Doesnotapply,https://www.ebay.com/itm/135000483801?itmmeta=...,e-bay
4,NaN,SURECAN 5 GALLON GASOLINE FUEL TYPE II SAFETY ...,Steering Wheel Locks,64.99,0.00,Add to cart,Add to cart,48.0,"[Model:SUR5SFG2, UPC:0855465008067, Brand:Sure...",SureCan,None,0855465008067,https://www.ebay.com/itm/285382222098?itmmeta=...,e-bay

In [205]:
dfAtt=Mergeddf[['Links','Attributes']]
dfAtt=dfAtt.explode('Attributes')
dfAtt[['Attributes', 'Value']] = dfAtt['Attributes'].str.split(':',1, expand=True)

In [206]:
summary_df = pd.pivot_table(dfAtt, values='Value', index='Attributes',aggfunc='count').reset_index()
summary_df =summary_df.sort_values(by='Value',ascending=False)
summary_df=summary_df.rename(columns ={'Value':'No Products contains this Attribute'})
summary_df

                    Attributes  No Products contains this Attribute
5                        Brand                                   41
54                         UPC                                   32
35                         MPN                                   25
39                    Material                                   22
9                        Color                                   21
..                         ...                                  ...
24                       Fit 8                                    1
1                     Also For                                    1
38       Manufacturer warranty                                    1
43  Mounting Hardware Included                                    1
67                  🔥Features🔥                                    1

[68 rows x 2 columns]

In [207]:
with pd.ExcelWriter(OFolder+'\\'+f'{Source}ProductDetails_'+search_text+'.xlsx') as writer:  # doctest: +SKIP
    Mergeddf.to_excel(writer,index=False, sheet_name='Raw')
    summary_df.to_excel(writer,index=False, sheet_name='Attribute_Summary')

# 99. Archived Codes

In [ ]:
# for i in range(42,127):#len(links)):
#     Rows=[]
#     driver.get(links[i])
#     Rows.append(i)
#     sleep(1)
#     product = driver.find_elements(By.XPATH, "//span[@class='a-size-large product-title-word-break']")
#     if len(product)==0:
#         Rows.append("-")
#     else:
#         for n in product:
#             Rows.append(n.text)
#     price=driver.find_elements(By.XPATH, "//span[@class='a-price a-text-price a-size-medium apexPriceToPay']")
#     if len(price)==0:
#         price=driver.find_elements(By.XPATH, "//span[@class='a-price aok-align-center reinventPricePriceToPayMargin priceToPay']")
#     if len(price)==0:
#         Rows.append("-")
#     else:
#         for pr in price:
#             if "\n" in pr.text:
#                 prm=pr.text.replace('\n',".")
#                 Rows.append(prm)
#             else:    
#                 if pr.text== "":
#                     pass
#                 else: 
#                     Rows.append(pr.text)
#     try:
#         listprice=driver.find_element(By.CLASS_NAME,"basisPrice")
#         Rows.append(listprice.text.split("$")[1])
#     except:
#         for pr in price:
#             if "\n" in pr.text:
#                 prm=pr.text.replace('\n',".")
#                 Rows.append(prm)
#             else:    
#                 if pr.text== "":
#                     pass
#                 else: 
#                     Rows.append(pr.text)
#     try:
#         rating=driver.find_element(By.ID, "averageCustomerReviews")
#         if len(rating.text)==0:
#             Rows.append("-")
#         else:
#             Rows.append(rating.text)
#     except:
#         Rows.append("-")
#     PDetail=driver.find_elements(By.ID, "productDetails_techSpec_section_1")
#     if len(PDetail)==0:
#         Rows.append("-") 
#     else:
#         for det in PDetail:
#             Rows.append(det.text)
#     Sales = driver.find_elements(By.XPATH, "(//span[@class='a-size-small social-proofing-faceout-title-text'])")
#     if len(Sales)==0:
#         Rows.append("-")
#     else:
#         for s in Sales:
#             Rows.append(s.text)
#     IDetails=driver.find_elements(By.XPATH, "(//div[@class='a-section a-spacing-medium a-spacing-top-small'])")
#     if len(IDetails)==0:
#         Rows.append("-") 
#     else:
#         for Idet in IDetails:
#             Rows.append(Idet.text)
#     #driver.find_element(By.TAG_NAME,'body').send_keys(Keys.END)
#     #sleep(3)
#     try:
#         crt=driver.find_element(By.ID,'acrCustomerReviewText')
#         crt.click()
#     except:
#         print("no Review")
#     sleep(2)
#     # try:
#     #     Reveiews=driver.find_element(By.ID, "cr-lighthut-1-")
#     #     list_items = Reveiews.find_elements(By.CLASS_NAME,"cr-lighthouse-term ")
#     #     ListWords=[]
#     #     for item in list_items:
#     #         ListWords.append(item.text)
#     #     Rows.append(ListWords)         
#     # except:
#     #     Rows.append("-") 
#     Rows.append(links[i])
#     new_row=pd.DataFrame([Rows],columns=cols)
#     df=pd.concat([df,new_row])
#     print("Scanned pages:", i+1,"@",datetime.datetime.now())

In [ ]:
def tryconvert(value, default, *types):
    for t in types:
        try:
            return t(value)
        except (ValueError, TypeError):
            continue
    return default