# 1. Library calling

In [89]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
import pandas as pd
import datetime
import warnings
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
# from janitor import xlsx_table
from tqdm import tqdm

# 2. Defining the Product Information and Location

In [133]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
wait=WebDriverWait(driver, 10)
driver.get('https://ph.baldwinfilters.com/baldwin/en/baldwin-products')

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [134]:
cols1 =['Sl.No'] 
df1= pd.DataFrame(columns=cols1)
count1=0

In [128]:
driver.find_element(By.CSS_SELECTOR,'[title="Fuel Filter Elements"]').click()

In [139]:
len(driver.find_elements(By.XPATH, "//div[contains(@class, 'productListItemContentRight')]"))

15

In [123]:
driver.execute_script("window.scrollTo(0, 0);")

In [ ]:
for step in tqdm(range(5,15)):
    driver.find_elements(By.XPATH, "//div[contains(@class, 'productListItemContentRight')]")[step].click()
    sleep(3)
    try:
        # Locate the <select> element first
        dropdown = driver.find_element(By.TAG_NAME, "select")

        # Initialize Select class
        select = Select(dropdown)

        # Pick the option by visible text
        select.select_by_visible_text("All")
        sleep(2)
    except:
        pass
    Products=driver.find_elements(By.XPATH, "//a[contains(@class, 'product_list_table_aUnderline')]")
    partname=driver.find_element(By.CSS_SELECTOR,'[class="bold"]').text
    for product in tqdm(Products):
        count1+=1
        df1.at[count1-1, 'Sl.No'] = count1
        df1.at[count1-1, 'Product Type'] = partname
        df1.at[count1-1, 'Product Name'] = product.text
        df1.at[count1-1, 'Product Link'] = product.get_attribute('href')
    sleep(2)
    driver.execute_script("window.scrollTo(0, 0);")
    driver.find_element(By.CSS_SELECTOR,'[title="Fuel Filters"]').click()
    sleep(2)

100%|██████████| 8/8 [00:00<00:00, 131.13it/s]
100%|██████████| 59/59 [00:00<00:00, 143.79it/s]
100%|██████████| 16/16 [00:00<00:00, 141.68it/s]
100%|██████████| 12/12 [00:00<00:00, 144.53it/s]
100%|██████████| 214/214 [00:01<00:00, 140.80it/s]
 33%|███▎      | 5/15 [00:52<01:45, 10.56s/it]

IndexError: list index out of range

In [106]:
df1

,Sl.No,Product Type,Product Name,Product Link
0,1,Baldwin - Hydraulic Filter Elements,PT9348-MPG,https://ph.baldwinfilters.com/baldwin/en/produ...
1,2,Baldwin - Hydraulic Filter Elements,PT9351-MPG,https://ph.baldwinfilters.com/baldwin/en/produ...
2,3,Baldwin - Hydraulic Filter Elements,PT9354-MPG,https://ph.baldwinfilters.com/baldwin/en/produ...
3,4,Baldwin - Hydraulic Filter Elements,PT9357,https://ph.baldwinfilters.com/baldwin/en/produ...
4,5,Baldwin - Hydraulic Filter Elements,PT9361,https://ph.baldwinfilters.com/baldwin/en/produ...
...,...,...,...,...
1213,1214,Baldwin - Hydraulic Filter Elements,PT23054-MPG,https://ph.baldwinfilters.com/baldwin/en/produ...
1214,1215,Baldwin - Hydraulic Filter Elements,PT23554,https://ph.baldwinfilters.com/baldwin/en/produ...
1215,1216,Baldwin - Hydraulic Filter Elements,PT23621-MPG,https://ph.baldwinfilters.com/baldwin/en/produ...
1216,1217,Baldwin - Hydraulic Filter Elements,PT23636-MPG,https://ph.baldwinfilters.com/baldwin/en/produ...
1217,1218,Baldwin - Hydraulic Filter Elements,PT23558-MPG,https://ph.baldwinfilters.com/baldwin/en/produ...

In [ ]:
driver.find_element(By.CLASS_NAME, 'product_list_table_aUnderline__68p8r').text

'BF46160-SPS'

In [6]:
driver.find_element(By.CLASS_NAME, 'product_list_table_aUnderline__68p8r').get_attribute('href')

'https://ph.baldwinfilters.com/baldwin/en/product/baldwin-spin-on-fuel-filters/bf46160-sps'

In [25]:
driver.find_element(By.CSS_SELECTOR, "a.product-tile-name")

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a.product-tile-name"}
  (Session info: chrome=139.0.7258.155); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x0x7ff69b363d85+79397]
	GetHandleVerifier [0x0x7ff69b363de0+79488]
	(No symbol) [0x0x7ff69b10c0fa]
	(No symbol) [0x0x7ff69b162fd6]
	(No symbol) [0x0x7ff69b16328c]
	(No symbol) [0x0x7ff69b1b6537]
	(No symbol) [0x0x7ff69b18b1df]
	(No symbol) [0x0x7ff69b1b3344]
	(No symbol) [0x0x7ff69b18af73]
	(No symbol) [0x0x7ff69b1541b1]
	(No symbol) [0x0x7ff69b154f43]
	GetHandleVerifier [0x0x7ff69b62e1ed+3005069]
	GetHandleVerifier [0x0x7ff69b62831d+2980797]
	GetHandleVerifier [0x0x7ff69b647e0d+3110573]
	GetHandleVerifier [0x0x7ff69b37d6de+184190]
	GetHandleVerifier [0x0x7ff69b38516f+215567]
	GetHandleVerifier [0x0x7ff69b36c974+115220]
	GetHandleVerifier [0x0x7ff69b36cb29+115657]
	GetHandleVerifier [0x0x7ff69b353268+11016]
	(No symbol) [0x0x7ffd3f527374]
	RtlUserThreadStart [0x0x7ffd40cfcc91+33]

In [51]:
print(driver.page_source)

<html lang="en-US" style="--numberOfRowsInMenu: 14; --numberOfColumnsInMenu: 2;" data-uw-w-loader="" data-uw-rm-lang="false"><head><meta http-equiv="origin-trial" content="A7vZI3v+Gz7JfuRolKNM4Aff6zaGuT7X0mf3wtoZTnKv6497cVMnhy03KDqX7kBz/q/iidW7srW31oQbBt4VhgoAAACUeyJvcmlnaW4iOiJodHRwczovL3d3dy5nb29nbGUuY29tOjQ0MyIsImZlYXR1cmUiOiJEaXNhYmxlVGhpcmRQYXJ0eVN0b3JhZ2VQYXJ0aXRpb25pbmczIiwiZXhwaXJ5IjoxNzU3OTgwODAwLCJpc1N1YmRvbWFpbiI6dHJ1ZSwiaXNUaGlyZFBhcnR5Ijp0cnVlfQ=="><meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://service.force.com/embeddedservice/ https://cdn.content.aws-dev2-uswest2.aws.sfdc.cl/ https://cdn.content.aws-prod1-useast1.aws.sfdc.cl/ https://payments.salesforce.com/ https://js.stripe.com/ https://www.paypal.com/sdk/js https://checkoutshopper-live.adyen.com/ https://checkoutshopper-test.adyen.com/ https://pal-test.adyen.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://pay.google.com import: blob: https://uip.canary.lwc.dev https://www.google.com https://www.gstatic.com https://fleetpride.cardconnect.com:8443/ https://fleetpride.dirxion.com/ https://www.googletagmanager.com https://www.google-analytics.com https://*.kaptcha.com https://www.fleetpride.com https://acsbapp.com https://cdn.acsbapp.com https://*.livechatinc.com https://*.appcues.com wss://*.appcues.net https://*.facebook.net https://cdn.cookielaw.org https://*.onetrust.com https://static.cloud.coveo.com https://googleads.g.doubleclick.net https://cdn.lr-intake.com https://www2.fleetpride.com https://r.lr-intake.com https://analytics.google.com https://bat.bing.com https://tagmanager.google.com https://www.googleadservices.com https://www.googlesyndication.com https://pagead2.googlesyndication.com https://adservice.google.com https://www.youtube.com https://www.blogger.com https://www.withgoogle.com https://www.youtube-nocookie.com https://tagassistant.google.com https://www.facebook.com https://www.clarity.ms https://www.bing.com https://www.microsoft.com https://clarity.microsoft.com https://ui.ads.microsoft.com https://ads.microsoft.com https://w.clarity.ms https://s.clarity.ms https://cdn.userway.org https://api.userway.org https://cookie-cdn.1trust.app https://cdn-ukwest.onetrust.com https://cookie-cdn.cookiepro.com https://cdn-au.onetrust.com https://cdn-apac.onetrust.com https://*.clarity.ms https://*.fullstory.com https://unpkg.com https://*.launchdarkly.com https://www.datadoghq-browser-agent.com https://*.licdn.com https://*.linkedin.com https://s.go-mpulse.net https://px.ads.linkedin.com https://c.go-mpulse.net https://*.akamaihd.net https://*.akstat.io https://app-orderreturns-selfservice-qa-scus-001-frdbdtcqdteveuds.southcentralus-01.azurewebsites.net https://fleetpride-team-b45d58fd8e5606d17400232.freshchat.com https://tags.srv.stackadapt.com https://*.freshchat.com https://in.fw-cdn.com https://*.reddit.com https://*.redditstatic.com https://fleetpride.cardconnect.com:6443 https://fleetpride-uat.cardconnect.com https://*.amazonaws.com https://fw-cdn.com; object-src 'self' www.google.com; style-src 'self' 'unsafe-inline' https://service.force.com/embeddedservice/ https://fonts.googleapis.com/css2 https://fonts.googleapis.com/css https://checkoutshopper-live.adyen.com/ https://checkoutshopper-test.adyen.com/ blob: https://globalplatform.cloud.coveo.com https://cloudplatform.coveo.com https://platform.cloud.coveo.com https://*.gstatic.com https://fonts.googleapis.com https://usageanalytics.coveo.com https://fw-cdn.com https://fleetpride.cardconnect.com:8443 https://www.google.com https://*.kaptcha.com https://*.livechatinc.com https://cdn.acsbapp.com https://acsbapp.com https://*.appcues.com wss://*.appcues.net https://*.facebook.com https://*.fleetpride.com https://fleetpride.dirxion.com https://*.google-analytics.com https://www.googletagmanager.com https://www.gstatic.com https://*.onetrust.com https://cdn.cookielaw.org https://app.powerbi.com https://static.cloud.coveo.com https://cdn.lr-intake.com https://www2.fleetpride.com https://*.doubleclick.net https://stats.g.doubleclick.net https://*.g.doubleclick.net https://r.lr-intake.com https://analytics.google.com https://bat.bing.com https://tagmanager.google.com https://www.googleadservices.com https://www.googlesyndication.com https://pagead2.googlesyndication.com https://adservice.google.com https://www.youtube.com https://www.blogger.com https://www.withgoogle.com https://www.youtube-nocookie.com https://tagassistant.google.com https://www.clarity.ms https://www.facebook.net *.bing.com https://www.microsoft.com https://clarity.microsoft.com https://ui.ads.microsoft.com https://ads.microsoft.com https://api.ipify.org https://www.datadoghq-browser-agent.com https://browser-intake-us3-datadoghq.com https://session-replay-datadoghq.com https://w.clarity.ms https://s.clarity.ms https://cdn.userway.org https://api.userway.org https://*.clarity.ms https://cookie-cdn.1trust.app https://*.fullstory.com *.linkedin.com https://*.licdn.com *.userway.org datadoghq-browser-agent.com https://cloud8.8x8.com https://vcc-na4.8x8.com https://*.launchdarkly.com https://unpkg.com https://c.go-mpulse.net https://*.akstat.io https://googletagmanager.com https://*.googletagmanager.com https://*.analytics.google.com https://*.google.com https://ssl.gstatic.com https://googleads.g.doubleclick.net https://ad.doubleclick.net https://td.doubleclick.net https://ade.googlesyndication.com https://fonts.gstatic.com https://www.google-analytics.com https://*.stackadapt.com https://qvdt3feo.com https://*.reddit.com https://*.redditstatic.com https://in.fw-cdn.com https://fleetpride-team-b45d58fd8e5606d17400232.freshchat.com https://tags.srv.stackadapt.com https://*.freshchat.com https://*.amazonaws.com; img-src 'self' data: blob: https://fleetpride.my.salesforce.com https://fleetpride.file.force.com https://img.youtube.com https://i.ytimg.com https://i.vimeocdn.com https://login.salesforce.com/icons/ https://payments.salesforce.com/icons/ https://cdn.content.aws-prod1-useast1.aws.sfdc.cl/icons/ https://cdn.content.aws-dev2-uswest2.aws.sfdc.cl/icons/ https://*.adyen.com https://www.sandbox.paypal.com https://www.paypal.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.gstatic.com https://usa594.sfdc-lywfpd.salesforce.com/icons/ https://globalplatform.cloud.coveo.com https://cloudplatform.coveo.com https://platform.cloud.coveo.com https://*.gstatic.com https://fonts.googleapis.com https://usageanalytics.coveo.com https://fw-cdn.com https://fleetpride.cardconnect.com:8443 https://www.google.com https://*.kaptcha.com https://*.livechatinc.com https://cdn.acsbapp.com https://acsbapp.com https://*.appcues.com wss://*.appcues.net https://*.facebook.com https://*.fleetpride.com https://fleetpride.dirxion.com https://*.google-analytics.com https://www.googletagmanager.com https://*.onetrust.com https://cdn.cookielaw.org https://app.powerbi.com https://static.cloud.coveo.com https://cdn.lr-intake.com https://www2.fleetpride.com https://*.doubleclick.net https://stats.g.doubleclick.net https://*.g.doubleclick.net https://r.lr-intake.com https://analytics.google.com https://bat.bing.com https://tagmanager.google.com https://www.googleadservices.com https://www.googlesyndication.com https://pagead2.googlesyndication.com https://adservice.google.com https://www.youtube.com https://www.blogger.com https://www.withgoogle.com https://www.youtube-nocookie.com https://tagassistant.google.com https://www.clarity.ms https://www.facebook.net *.bing.com https://www.microsoft.com https://clarity.microsoft.com https://ui.ads.microsoft.com https://ads.microsoft.com https://api.ipify.org https://www.datadoghq-browser-agent.com https://browser-intake-us3-datadoghq.com https://session-replay-datadoghq.com https://w.clarity.ms https://s.clarity.ms https://cdn.userway.org https://api.userway.org https://*.clarity.ms https://cookie-cdn.1trust.app https://*.fullstory.com *.linkedin.com https://*.licdn.com *.userway.org datadoghq-browser-agent.com https://cloud8.8x8.com https://vcc-na4.8x8.com https://*.launchdarkly.com https://unpkg.com https://c.go-mpulse.net https://*.akstat.io https://googletagmanager.com https://*.googletagmanager.com https://*.analytics.google.com https://*.google.com https://ssl.gstatic.com https://googleads.g.doubleclick.net https://ad.doubleclick.net https://td.doubleclick.net https://ade.googlesyndication.com https://fonts.gstatic.com https://www.google-analytics.com https://*.stackadapt.com https://qvdt3feo.com https://*.reddit.com https://*.redditstatic.com https://in.fw-cdn.com https://fleetpride-team-b45d58fd8e5606d17400232.freshchat.com https://tags.srv.stackadapt.com https://*.freshchat.com https://*.amazonaws.com; media-src 'self' blob: https://globalplatform.cloud.coveo.com https://cloudplatform.coveo.com https://platform.cloud.coveo.com https://*.gstatic.com https://fonts.googleapis.com https://usageanalytics.coveo.com https://fw-cdn.com https://fleetpride.cardconnect.com:8443 https://www.google.com https://*.kaptcha.com https://*.livechatinc.com https://cdn.acsbapp.com https://acsbapp.com https://*.appcues.com wss://*.appcues.net https://*.facebook.com https://*.fleetpride.com https://fleetpride.dirxion.com https://*.google-analytics.com https://www.googletagmanager.com https://www.gstatic.com https://*.onetrust.com https://cdn.cookielaw.org https://app.powerbi.com https://static.cloud.coveo.com https://cdn.lr-intake.com https://www2.fleetpride.com https://*.doubleclick.net https://stats.g.doubleclick.net https://*.g.doubleclick.net https://r.lr-intake.com https://analytics.google.com https://bat.bing.com https://tagmanager.google.com https://www.googleadservices.com https://www.googlesyndication.com https://pagead2.googlesyndication.com https://adservice.google.com https://www.youtube.com https://www.blogger.com https://www.withgoogle.com https://www.youtube-nocookie.com https://tagassistant.google.com https://www.clarity.ms https://www.facebook.net *.bing.com https://www.microsoft.com https://clarity.microsoft.com https://ui.ads.microsoft.com https://ads.microsoft.com https://api.ipify.org https://www.datadoghq-browser-agent.com https://browser-intake-us3-datadoghq.com https://session-replay-datadoghq.com https://w.clarity.ms https://s.clarity.ms https://cdn.userway.org https://api.userway.org https://*.clarity.ms https://cookie-cdn.1trust.app https://*.fullstory.com *.linkedin.com https://*.licdn.com *.userway.org datadoghq-browser-agent.com https://cloud8.8x8.com https://vcc-na4.8x8.com https://*.launchdarkly.com https://unpkg.com https://c.go-mpulse.net https://*.akstat.io https://googletagmanager.com https://*.googletagmanager.com https://*.analytics.google.com https://*.google.com https://ssl.gstatic.com https://googleads.g.doubleclick.net https://ad.doubleclick.net https://td.doubleclick.net https://ade.googlesyndication.com https://fonts.gstatic.com https://www.google-analytics.com https://*.stackadapt.com https://qvdt3feo.com https://*.reddit.com https://*.redditstatic.com https://in.fw-cdn.com https://fleetpride-team-b45d58fd8e5606d17400232.freshchat.com https://tags.srv.stackadapt.com https://*.freshchat.com https://*.amazonaws.com;  frame-src 'self' https://service.force.com/embeddedservice/ https://usa594.sfdc-lywfpd.salesforce.com https://sfdc-link-preview-staging.sfdc.sh https://sfdc-link-preview.hk.salesforce.com https://cdn.embedly.com https://www.youtube.com https://player.vimeo.com https://play.vidyard.com https://player.cloudinary.com https://fast.wistia.net https://players.brightcove.net https://s1.adis.ws https://scormanywhere.secure.force.com https://appiniummastertrial.secure.force.com https://js.stripe.com/ https://www.paypal.com https://www.sandbox.paypal.com https://checkoutshopper-live.adyen.com/ https://checkoutshopper-test.adyen.com/ https://pal-test.adyen.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://pay.google.com https://*.a.forceusercontent.com/lightningmaps/ https://*.a.forceusercontent.com https://location.force.com https://fleetpride.file.force.com https://globalplatform.cloud.coveo.com https://cloudplatform.coveo.com https://platform.cloud.coveo.com https://*.gstatic.com https://fonts.googleapis.com https://usageanalytics.coveo.com https://fw-cdn.com https://*.coveo.com https://fleetpride.cardconnect.com:8443 https://www.google.com https://*.kaptcha.com https://*.livechatinc.com https://cdn.acsbapp.com https://acsbapp.com https://*.appcues.com wss://*.appcues.net https://*.facebook.com https://*.fleetpride.com https://fleetpride.dirxion.com https://*.google-analytics.com https://www.googletagmanager.com https://www.gstatic.com https://*.onetrust.com https://cdn.cookielaw.org https://app.powerbi.com https://static.cloud.coveo.com https://cdn.lr-intake.com https://www2.fleetpride.com https://*.doubleclick.net https://stats.g.doubleclick.net https://*.g.doubleclick.net https://r.lr-intake.com https://analytics.google.com https://bat.bing.com https://tagmanager.google.com https://www.googleadservices.com https://www.googlesyndication.com https://pagead2.googlesyndication.com https://adservice.google.com https://www.blogger.com https://www.withgoogle.com https://www.youtube-nocookie.com https://tagassistant.google.com https://www.clarity.ms https://www.facebook.net *.bing.com https://www.microsoft.com https://clarity.microsoft.com https://ui.ads.microsoft.com https://ads.microsoft.com https://api.ipify.org https://www.datadoghq-browser-agent.com https://browser-intake-us3-datadoghq.com https://session-replay-datadoghq.com https://w.clarity.ms https://s.clarity.ms https://cdn.userway.org https://api.userway.org https://*.clarity.ms https://cookie-cdn.1trust.app https://*.fullstory.com *.linkedin.com https://*.licdn.com *.userway.org datadoghq-browser-agent.com https://cloud8.8x8.com https://vcc-na4.8x8.com https://*.launchdarkly.com https://unpkg.com https://c.go-mpulse.net https://*.akstat.io https://googletagmanager.com https://*.googletagmanager.com https://*.analytics.google.com https://*.google.com https://ssl.gstatic.com https://googleads.g.doubleclick.net https://ad.doubleclick.net https://td.doubleclick.net https://ade.googlesyndication.com https://fonts.gstatic.com https://www.google-analytics.com https://*.stackadapt.com https://qvdt3feo.com https://*.reddit.com https://*.redditstatic.com https://in.fw-cdn.com https://fleetpride-team-b45d58fd8e5606d17400232.freshchat.com https://tags.srv.stackadapt.com https://*.freshchat.com https://*.amazonaws.com; font-src 'self' data: https://fonts.gstatic.com/ https://globalplatform.cloud.coveo.com https://cloudplatform.coveo.com https://platform.cloud.coveo.com https://*.gstatic.com https://fonts.googleapis.com https://usageanalytics.coveo.com https://fw-cdn.com https://fleetpride.cardconnect.com:8443 https://www.google.com https://*.kaptcha.com https://*.livechatinc.com https://cdn.acsbapp.com https://acsbapp.com https://*.appcues.com wss://*.appcues.net https://*.facebook.com https://*.fleetpride.com https://fleetpride.dirxion.com https://*.google-analytics.com https://www.googletagmanager.com https://www.gstatic.com https://*.onetrust.com https://cdn.cookielaw.org https://app.powerbi.com https://static.cloud.coveo.com https://cdn.lr-intake.com https://www2.fleetpride.com https://*.doubleclick.net https://stats.g.doubleclick.net https://*.g.doubleclick.net https://r.lr-intake.com https://analytics.google.com https://bat.bing.com https://tagmanager.google.com https://www.googleadservices.com https://www.googlesyndication.com https://pagead2.googlesyndication.com https://adservice.google.com https://www.youtube.com https://www.blogger.com https://www.withgoogle.com https://www.youtube-nocookie.com https://tagassistant.google.com https://www.clarity.ms https://www.facebook.net *.bing.com https://www.microsoft.com https://clarity.microsoft.com https://ui.ads.microsoft.com https://ads.microsoft.com https://api.ipify.org https://www.datadoghq-browser-agent.com https://browser-intake-us3-datadoghq.com https://session-replay-datadoghq.com https://w.clarity.ms https://s.clarity.ms https://cdn.userway.org https://api.userway.org https://*.clarity.ms https://cookie-cdn.1trust.app https://*.fullstory.com https://*.coveo.com *.linkedin.com https://*.licdn.com *.userway.org datadoghq-browser-agent.com https://cloud8.8x8.com https://vcc-na4.8x8.com https://*.launchdarkly.com https://unpkg.com https://c.go-mpulse.net https://*.akstat.io https://googletagmanager.com https://*.googletagmanager.com https://*.analytics.google.com https://*.google.com https://ssl.gstatic.com https://googleads.g.doubleclick.net https://ad.doubleclick.net https://td.doubleclick.net https://ade.googlesyndication.com https://fonts.gstatic.com https://www.google-analytics.com https://*.stackadapt.com https://qvdt3feo.com https://*.reddit.com https://*.redditstatic.com https://in.fw-cdn.com https://fleetpride-team-b45d58fd8e5606d17400232.freshchat.com https://tags.srv.stackadapt.com https://*.freshchat.com https://*.amazonaws.com; connect-src 'self' https://www.paypal.com https://www.sandbox.paypal.com https://fleetpride.my.salesforce-scrt.com https://fonts.googleapis.com/css2 https://payments.salesforce.com/ https://cdn.content.aws-dev2-uswest2.aws.sfdc.cl/ https://checkoutshopper-live.adyen.com/ https://checkoutshopper-test.adyen.com/ https://js.stripe.com/ https://www.google.com/recaptcha/ https://o11y.sfproxy-core2.sfdc-lywfpd.svc.sfdcfc.net/ui-telemetry https://globalplatform.cloud.coveo.com https://cloudplatform.coveo.com https://platform.cloud.coveo.com https://*.gstatic.com https://fonts.googleapis.com https://usageanalytics.coveo.com https://fw-cdn.com https://*.coveo.com https://fleetpride.cardconnect.com:8443 https://www.google.com https://*.kaptcha.com https://*.livechatinc.com https://cdn.acsbapp.com https://acsbapp.com https://*.appcues.com wss://*.appcues.net https://*.facebook.com https://*.fleetpride.com https://fleetpride.dirxion.com https://*.google-analytics.com https://www.googletagmanager.com https://www.gstatic.com https://*.onetrust.com https://cdn.cookielaw.org https://app.powerbi.com https://static.cloud.coveo.com https://cdn.lr-intake.com https://www2.fleetpride.com https://*.doubleclick.net https://stats.g.doubleclick.net https://*.g.doubleclick.net https://r.lr-intake.com https://analytics.google.com https://bat.bing.com https://tagmanager.google.com https://www.googleadservices.com https://www.googlesyndication.com https://pagead2.googlesyndication.com https://adservice.google.com https://www.youtube.com https://www.blogger.com https://www.withgoogle.com https://www.youtube-nocookie.com https://tagassistant.google.com https://www.clarity.ms https://www.facebook.net *.bing.com https://www.microsoft.com https://clarity.microsoft.com https://ui.ads.microsoft.com https://ads.microsoft.com https://api.ipify.org https://www.datadoghq-browser-agent.com https://browser-intake-us3-datadoghq.com https://session-replay-datadoghq.com https://w.clarity.ms https://s.clarity.ms https://cdn.userway.org https://api.userway.org https://*.clarity.ms https://cookie-cdn.1trust.app https://*.fullstory.com *.linkedin.com https://*.licdn.com *.userway.org datadoghq-browser-agent.com https://cloud8.8x8.com https://vcc-na4.8x8.com https://*.launchdarkly.com https://unpkg.com https://c.go-mpulse.net https://*.akstat.io https://googletagmanager.com https://*.googletagmanager.com https://*.analytics.google.com https://*.google.com https://ssl.gstatic.com https://googleads.g.doubleclick.net https://ad.doubleclick.net https://td.doubleclick.net https://ade.googlesyndication.com https://fonts.gstatic.com https://www.google-analytics.com https://*.stackadapt.com https://qvdt3feo.com https://*.reddit.com https://*.redditstatic.com https://in.fw-cdn.com https://fleetpride-team-b45d58fd8e5606d174

In [ ]:
iframe = driver.find_element(By.TAG_NAME, "iframe")

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"iframe"}
  (Session info: chrome=139.0.7258.155); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x0x7ff69b363d85+79397]
	GetHandleVerifier [0x0x7ff69b363de0+79488]
	(No symbol) [0x0x7ff69b10c0fa]
	(No symbol) [0x0x7ff69b162fd6]
	(No symbol) [0x0x7ff69b16328c]
	(No symbol) [0x0x7ff69b1b6537]
	(No symbol) [0x0x7ff69b18b1df]
	(No symbol) [0x0x7ff69b1b3344]
	(No symbol) [0x0x7ff69b18af73]
	(No symbol) [0x0x7ff69b1541b1]
	(No symbol) [0x0x7ff69b154f43]
	GetHandleVerifier [0x0x7ff69b62e1ed+3005069]
	GetHandleVerifier [0x0x7ff69b62831d+2980797]
	GetHandleVerifier [0x0x7ff69b647e0d+3110573]
	GetHandleVerifier [0x0x7ff69b37d6de+184190]
	GetHandleVerifier [0x0x7ff69b38516f+215567]
	GetHandleVerifier [0x0x7ff69b36c974+115220]
	GetHandleVerifier [0x0x7ff69b36cb29+115657]
	GetHandleVerifier [0x0x7ff69b353268+11016]
	(No symbol) [0x0x7ffd3f527374]
	RtlUserThreadStart [0x0x7ffd40cfcc91+33]

In [17]:
driver.switch_to.window()

TypeError: SwitchTo.window() missing 1 required positional argument: 'window_name'

In [50]:
driver.find_element(By.CSS_SELECTOR,'#main > webruntime-app:nth-child(8) > lwr-router-container > webruntime-inner-app > dxp_data_provider-user-data-provider > dxp_data_provider-data-proxy > c-b2b-fp-commerce-layout > main > webruntime-router-container > dxp_data_provider-user-data-provider > dxp_data_provider-data-proxy > commerce_data_provider-search-data-provider > dxp_data_provider-data-proxy > community_layout-slds-flexible-layout > div > community_layout-section:nth-child(2) > div.lwc-6j9an5vbrcd.columns-content > community_layout-column > div > c-b2b-fp-coveo-search-page > div.search__container.slds-p-around_medium > c-b2b-fp-search-interface > c-quantic-modal-a11y-handler > slot > slot > div > div.slds-col.slds-size_1-of-1.slds-large-size_3-of-4.slds-order_1.slds-large-order_2 > c-b2b-fp-result-list > div.slds-grid.slds-wrap.slds-grid_vertical-stretch.slds-gutters_direct.gridView > c-b2b-fp-grid-result-list:nth-child(1) > div:nth-child(1) > c-b2b-fp-result > c-b2b-fp-product-result-template > div.lgc-bg.slds-p-vertical_medium.slds-border_bottom.plp.gridView > div.slds-grid.plp-card.plp.slds-grid_vertical-stretch > div.slds-col.slds-grid.title-wrapper.slds-gutters > div.slds-order_2.title-wrapper > slot:nth-child(1) > div > c-b2b-fp-product-info > div > div.product-name > c-b2b-fp-custom-result-link > a > span')

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#main > webruntime-app:nth-child(8) > lwr-router-container > webruntime-inner-app > dxp_data_provider-user-data-provider > dxp_data_provider-data-proxy > c-b2b-fp-commerce-layout > main > webruntime-router-container > dxp_data_provider-user-data-provider > dxp_data_provider-data-proxy > commerce_data_provider-search-data-provider > dxp_data_provider-data-proxy > community_layout-slds-flexible-layout > div > community_layout-section:nth-child(2) > div.lwc-6j9an5vbrcd.columns-content > community_layout-column > div > c-b2b-fp-coveo-search-page > div.search__container.slds-p-around_medium > c-b2b-fp-search-interface > c-quantic-modal-a11y-handler > slot > slot > div > div.slds-col.slds-size_1-of-1.slds-large-size_3-of-4.slds-order_1.slds-large-order_2 > c-b2b-fp-result-list > div.slds-grid.slds-wrap.slds-grid_vertical-stretch.slds-gutters_direct.gridView > c-b2b-fp-grid-result-list:nth-child(1) > div:nth-child(1) > c-b2b-fp-result > c-b2b-fp-product-result-template > div.lgc-bg.slds-p-vertical_medium.slds-border_bottom.plp.gridView > div.slds-grid.plp-card.plp.slds-grid_vertical-stretch > div.slds-col.slds-grid.title-wrapper.slds-gutters > div.slds-order_2.title-wrapper > slot:nth-child(1) > div > c-b2b-fp-product-info > div > div.product-name > c-b2b-fp-custom-result-link > a > span"}
  (Session info: chrome=139.0.7258.155); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x0x7ff706033d85+79397]
	GetHandleVerifier [0x0x7ff706033de0+79488]
	(No symbol) [0x0x7ff705ddc0fa]
	(No symbol) [0x0x7ff705e32fd6]
	(No symbol) [0x0x7ff705e3328c]
	(No symbol) [0x0x7ff705e86537]
	(No symbol) [0x0x7ff705e5b1df]
	(No symbol) [0x0x7ff705e83344]
	(No symbol) [0x0x7ff705e5af73]
	(No symbol) [0x0x7ff705e241b1]
	(No symbol) [0x0x7ff705e24f43]
	GetHandleVerifier [0x0x7ff7062fe1ed+3005069]
	GetHandleVerifier [0x0x7ff7062f831d+2980797]
	GetHandleVerifier [0x0x7ff706317e0d+3110573]
	GetHandleVerifier [0x0x7ff70604d6de+184190]
	GetHandleVerifier [0x0x7ff70605516f+215567]
	GetHandleVerifier [0x0x7ff70603c974+115220]
	GetHandleVerifier [0x0x7ff70603cb29+115657]
	GetHandleVerifier [0x0x7ff706023268+11016]
	(No symbol) [0x0x7ffd3f527374]
	RtlUserThreadStart [0x0x7ffd40cfcc91+33]

In [37]:
driver.find_element(By.CSS_SELECTOR,'[part="formatted-rich-text"]')

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[part="formatted-rich-text"]"}
  (Session info: chrome=139.0.7258.155); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x0x7ff706033d85+79397]
	GetHandleVerifier [0x0x7ff706033de0+79488]
	(No symbol) [0x0x7ff705ddc0fa]
	(No symbol) [0x0x7ff705e32fd6]
	(No symbol) [0x0x7ff705e3328c]
	(No symbol) [0x0x7ff705e86537]
	(No symbol) [0x0x7ff705e5b1df]
	(No symbol) [0x0x7ff705e83344]
	(No symbol) [0x0x7ff705e5af73]
	(No symbol) [0x0x7ff705e241b1]
	(No symbol) [0x0x7ff705e24f43]
	GetHandleVerifier [0x0x7ff7062fe1ed+3005069]
	GetHandleVerifier [0x0x7ff7062f831d+2980797]
	GetHandleVerifier [0x0x7ff706317e0d+3110573]
	GetHandleVerifier [0x0x7ff70604d6de+184190]
	GetHandleVerifier [0x0x7ff70605516f+215567]
	GetHandleVerifier [0x0x7ff70603c974+115220]
	GetHandleVerifier [0x0x7ff70603cb29+115657]
	GetHandleVerifier [0x0x7ff706023268+11016]
	(No symbol) [0x0x7ffd3f527374]
	RtlUserThreadStart [0x0x7ffd40cfcc91+33]

In [27]:
product_element = driver.find_element(By.CSS_SELECTOR, "span.highlighted-title")
product_href = product_element.find_element(By.XPATH, "./ancestor::a").get_attribute("href")
print("Product HREF:", product_href)

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"span.highlighted-title"}
  (Session info: chrome=139.0.7258.155); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x0x7ff706033d85+79397]
	GetHandleVerifier [0x0x7ff706033de0+79488]
	(No symbol) [0x0x7ff705ddc0fa]
	(No symbol) [0x0x7ff705e32fd6]
	(No symbol) [0x0x7ff705e3328c]
	(No symbol) [0x0x7ff705e86537]
	(No symbol) [0x0x7ff705e5b1df]
	(No symbol) [0x0x7ff705e83344]
	(No symbol) [0x0x7ff705e5af73]
	(No symbol) [0x0x7ff705e241b1]
	(No symbol) [0x0x7ff705e24f43]
	GetHandleVerifier [0x0x7ff7062fe1ed+3005069]
	GetHandleVerifier [0x0x7ff7062f831d+2980797]
	GetHandleVerifier [0x0x7ff706317e0d+3110573]
	GetHandleVerifier [0x0x7ff70604d6de+184190]
	GetHandleVerifier [0x0x7ff70605516f+215567]
	GetHandleVerifier [0x0x7ff70603c974+115220]
	GetHandleVerifier [0x0x7ff70603cb29+115657]
	GetHandleVerifier [0x0x7ff706023268+11016]
	(No symbol) [0x0x7ffd3f527374]
	RtlUserThreadStart [0x0x7ffd40cfcc91+33]

In [27]:
for j in range (11):
    hrefs=driver.find_elements(By.CLASS_NAME,"searchItems-info")
    for i in range(len(hrefs)):
        print(count1)
        df1.loc[count1,'Sl.No']=count1
        df1.loc[count1,'PartNumber']=hrefs[i].text.split("\n")[0]
        df1.loc[count1,"PartName"]=hrefs[i].text.split("\n")[1]
        df1.loc[count1,'Link']=hrefs[i].find_element(By.TAG_NAME, "a").get_attribute('href')
        try:
            df1.loc[count1,'Application Summary']=hrefs[i].text.split("\n")[2].split(": ")[1]
        except:
            df1.loc[count1,'Application Summary']="NA"
        # try: 
        #     filename=hrefs[i].text.split("\n")[0]+".jpg" # Extract filename from URL (modify if needed)
        #     if i<10:
        #         t=driver.find_elements(By.CLASS_NAME,"searchItems-img")[i].find_element(By.CSS_SELECTOR,f'[id="rptDetails_ctl0{i}_imgProductMain"]')
        #     else:
        #         t=driver.find_elements(By.CLASS_NAME,"searchItems-img")[i].find_element(By.CSS_SELECTOR,f'[id="rptDetails_ctl{i}_imgProductMain"]')
        #     s=t.get_attribute('src')
        #     import requests
        #     # Download the image using requests
        #     response = requests.get(s, stream=True)

        #     if response.status_code == 200:
        #         savepath=r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\96_Competitor Data\Dorman Parts\MasterCylinder"+"\\"+filename
        #     # Get filename from URL or generate a unique one
        #         with open(savepath, 'wb') as f:
        #             for chunk in response.iter_content(1024):
        #                 f.write(chunk)
        #         print(f"Image downloaded: {filename}")
        #     else:
        #         print(f"Failed to download image: {s}")
        # except:
        #     print(f"part number not available for {filename}")  
        count1=count1+1
    driver.find_element(By.ID,"pagingBottom_nextButton").click()
    sleep(10)
    clear_output(True)

7204
7205
7206
7207
7208
7209
7210
7211
7212
7213
7214
7215
7216
7217
7218
7219
7220
7221
7222
7223
7224
7225
7226
7227
7228
7229
7230
7231
7232
7233
7234
7235
7236
7237
7238
7239
7240
7241
7242
7243
7244
7245
7246
7247
7248
7249
7250
7251
7252
7253
7254
7255
7256
7257
7258
7259
7260
7261
7262
7263
7264
7265
7266
7267
7268
7269
7270
7271
7272
7273
7274
7275
7276
7277
7278
7279
7280
7281
7282
7283
7284
7285
7286
7287
7288
7289
7290
7291
7292
7293
7294
7295
7296
7297
7298
7299
7300
7301
7302
7303

In [28]:
print(len(df1))
df1
df = df1.drop_duplicates(subset=['PartNumber', 'PartName', 'Link', 'Application Summary']).reset_index(drop=True)
df

7304

,Sl.No,PartNumber,PartName,Link,Application Summary
0,0,C92388,Parking Brake Cable,https://www.dormanproducts.com/p-44668-c92388....,"Dodge D100 Pickup 1969-68, Dodge W100 Pickup 1..."
1,1,C95505,Parking Brake Cable,https://www.dormanproducts.com/p-14160-c95505....,Ford 2004-99
2,2,C93682,Parking Brake Cable,https://www.dormanproducts.com/p-23176-c93682....,"Chevrolet 1999-85, GMC 1999-85"
3,3,C660366,Parking Brake Cable,https://www.dormanproducts.com/p-23127-c660366...,"Ford F-450 Super Duty 2004-00, Ford F-550 Supe..."
4,4,C95915,Parking Brake Cable,https://www.dormanproducts.com/p-44564-c95915....,Ford F-250 1999-98
...,...,...,...,...,...
1696,6427,C660406,Parking Brake Cable,https://www.dormanproducts.com/p-8928-c660406....,Toyota MR2 1989-87
1697,6428,C660830,Parking Brake Cable,https://www.dormanproducts.com/p-102997-c66083...,Lexus GX470 2009-03
1698,6839,C94719,Parking Brake Cable,https://www.dormanproducts.com/p-11142-c94719....,"Buick 1996-94, Cadillac 1996-94, Chevrolet 199..."
1699,6885,C661111,Parking Brake Cable,https://www.dormanproducts.com/p-79531-c661111...,"Ford Escape 2008, Mercury Mariner 2008"
1700,6886,C93627,Parking Brake Cable,https://www.dormanproducts.com/p-16885-c93627....,Dodge Dakota 1996-87

In [29]:
cols2 =['Sl.No']
df2= pd.DataFrame(columns=cols2)
count2=0
cols3 =['Sl.No','OENumbers']
df3= pd.DataFrame(columns=cols3)
count3=0

In [30]:
driver.get(df['Link'][1])

In [77]:
frame_0 = driver.find_element(By.ID,'ifDetailApp')
driver.switch_to.frame(frame_0)

In [78]:
driver.find_element(By.ID,"pagingBottom_nextButton").click()

In [44]:
for i in tqdm(range(1629,len(df))):
    print(f"Begins with the item# {i}, {df['PartNumber'][i]}")
    driver.get(df['Link'][i])
    sleep(1)
    lk=df['Link'][i]
    pname=driver.find_element(By.ID,'lblProductDesc').text
    pn=driver.find_element(By.ID,'lblProductName').text
    OEs=driver.find_elements(By.CSS_SELECTOR,'[scope="row"]')
    Olist=[]
    for oe in OEs:
        Olist.append(oe.text)
#----------------------------------------------------------------------------------------------------------------------------
    ps=driver.find_elements(By.CSS_SELECTOR,'[style="width:100%;"]')
    for p in ps:
        lines=len(p.text.split('\n'))
        for l in range(lines):
            Attr=p.text.split('\n')[l].split(": ")[0]
            Value=p.text.split('\n')[l].split(": ")[1]
            df3.loc[count3,'Sl.No']=count3
            df3.loc[count3,'Sl.No']=count3
            df3.loc[count3,'PartNumber']=pn
            df3.loc[count3,'PartName']=pname
            df3.at[count3,'OENumbers']=Olist
            df3.loc[count3,Attr]=Value
            df3.loc[count3,'ProductDescription']=driver.find_element(By.CSS_SELECTOR,'[id="productDesc"]').text
            df3.loc[count3,'Link']=lk
        count3=count3+1
#----------------------------------------------------------------------------------------------------------------------------
    frame_0 = driver.find_element(By.ID,'ifDetailApp')
    driver.switch_to.frame(frame_0)
    for i in range(100):
        try:        
            cs=driver.find_elements(By.CLASS_NAME,'detail-app-row')
            for c in cs:
                    df2.loc[count2,'Sl.No']=count2
                    df2.loc[count2,'PartNumber']=pn
                    df2.loc[count2,'PartName']=pname
                    df2.loc[count2,'Year']=int(c.find_element(By.CSS_SELECTOR,f'[style="width:5%;"]').text)
                    df2.loc[count2,'Make']=c.find_element(By.CSS_SELECTOR,f'[style="width:13%;"]').text
                    df2.loc[count2,'Model']=c.find_element(By.CSS_SELECTOR,f'[style="width:17%;"]').text
                    df2.loc[count2,'Positions']=c.find_elements(By.XPATH,"//td[@style='width:17%;']")[1].text
                    df2.loc[count2,'Configuration']=c.find_element(By.CSS_SELECTOR,f'[style="width:21%;"]').text
                    df2.loc[count2,'ApplicationNotes']=c.find_element(By.CSS_SELECTOR,f'[style="width:27%;"]').text            
                    count2=count2+1   
            driver.find_element(By.ID,"pagingBottom_nextButton").click()
            sleep(2)
        except:
            break
    clear_output(wait=True)

100%|██████████| 72/72 [04:52<00:00,  4.06s/it]

In [45]:
df3

,Sl.No,OENumbers,PartNumber,PartName,Conduit Included,ProductDescription,Link,Conduit Length,Housing Color,Mounting Hardware Included,...,Jacket Diameter,Jacket Included,Material,Mounting Bracket Included,Strand Quantity,Wire Gauge Measurement,Jacket Material,Overall Length,End 1 Connector Threaded,End 2 Connector Threaded
0,0,[2511363],C92388,Parking Brake Cable,Yes,Product Description\nThis parking brake cable ...,https://www.dormanproducts.com/p-44668-c92388....,27.4 in,Black,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"[F6UZ-2853-AA, XC2Z-2853-DB]",C95505,Parking Brake Cable,Yes,Product Description\nThis parking brake cable ...,https://www.dormanproducts.com/p-14160-c95505....,72.51 in,Black,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"[15549116, 15624632]",C93682,Parking Brake Cable,Yes,Product Description\nThis parking brake cable ...,https://www.dormanproducts.com/p-23176-c93682....,63.46 in,Black,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,[F81Z-2A793-JA],C660366,Parking Brake Cable,No,Product Description\nThis parking brake cable ...,https://www.dormanproducts.com/p-23127-c660366...,NaN,Natural,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,[],C95915,Parking Brake Cable,Yes,Product Description\nThis parking brake cable ...,https://www.dormanproducts.com/p-44564-c95915....,88.86 in,Black,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1699,1699,[46430-17030],C660406,Parking Brake Cable,Yes,Product Description\nThis parking brake cable ...,https://www.dormanproducts.com/p-8928-c660406....,24.44 in,Black,No,...,NaN,No,Steel,Yes,19,11 ga.,NaN,NaN,NaN,NaN
1700,1700,[46430-60010],C660830,Parking Brake Cable,Yes,Product Description\nThis parking brake cable ...,https://www.dormanproducts.com/p-102997-c66083...,70.55 in,Black,No,...,1 mm,Yes,Steel,Yes,49,9 ga.,NaN,NaN,NaN,NaN
1701,1701,"[10223642, 18022642]",C94719,Parking Brake Cable,Yes,Product Description\nThis parking brake cable ...,https://www.dormanproducts.com/p-11142-c94719....,78.75 in,Black,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1702,1702,[8L8Z 2A635-A],C661111,Parking Brake Cable,Yes,Product Description\nThis parking brake cable ...,https://www.dormanproducts.com/p-79531-c661111...,35.43 in,Black,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1703,1703,[4294383],C93627,Parking Brake Cable,Yes,Product Description\nThis parking brake cable ...,https://www.dormanproducts.com/p-16885-c93627....,19.5 in,Black,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
df2

,Sl.No,PartNumber,PartName,Year,Make,Model,Positions,ApplicationNotes,Configuration
0,0,C92388,Parking Brake Cable,1970.0,Dodge,W100 Pickup,Rear Left; Rear Right,Axle Mounted Parking Brake,
1,1,C92388,Parking Brake Cable,1969.0,Dodge,D100 Pickup,Rear Left; Rear Right,,
2,2,C92388,Parking Brake Cable,1969.0,Dodge,W100 Pickup,Rear Left; Rear Right,Axle Mounted Parking Brake,
3,3,C92388,Parking Brake Cable,1968.0,Dodge,D100 Pickup,Rear Left; Rear Right,,
4,4,C95505,Parking Brake Cable,2004.0,Ford,F-450 Super Duty,Front,Transmission Mounted Parking Brake,
...,...,...,...,...,...,...,...,...,...
26280,26280,C93627,Parking Brake Cable,1991.0,Dodge,Dakota,Rear Left; Rear Right,10 In. Rear Brakes,
26281,26281,C93627,Parking Brake Cable,1990.0,Dodge,Dakota,Rear Left; Rear Right,10 In. Rear Brakes,
26282,26282,C93627,Parking Brake Cable,1989.0,Dodge,Dakota,Rear Left; Rear Right,10 In. Rear Brakes,
26283,26283,C93627,Parking Brake Cable,1988.0,Dodge,Dakota,Rear Left; Rear Right,10 In. Rear Brakes,
26284,26284,C93627,Parking Brake Cable,1987.0,Dodge,Dakota,Rear Left; Rear Right,10 In. Rear Brakes,

In [47]:
df2=df2[["Sl.No","PartNumber","PartName","Year","Make","Model","Positions","ApplicationNotes","Configuration"]]
df2

,Sl.No,PartNumber,PartName,Year,Make,Model,Positions,ApplicationNotes,Configuration
0,0,C92388,Parking Brake Cable,1970.0,Dodge,W100 Pickup,Rear Left; Rear Right,Axle Mounted Parking Brake,
1,1,C92388,Parking Brake Cable,1969.0,Dodge,D100 Pickup,Rear Left; Rear Right,,
2,2,C92388,Parking Brake Cable,1969.0,Dodge,W100 Pickup,Rear Left; Rear Right,Axle Mounted Parking Brake,
3,3,C92388,Parking Brake Cable,1968.0,Dodge,D100 Pickup,Rear Left; Rear Right,,
4,4,C95505,Parking Brake Cable,2004.0,Ford,F-450 Super Duty,Front,Transmission Mounted Parking Brake,
...,...,...,...,...,...,...,...,...,...
26280,26280,C93627,Parking Brake Cable,1991.0,Dodge,Dakota,Rear Left; Rear Right,10 In. Rear Brakes,
26281,26281,C93627,Parking Brake Cable,1990.0,Dodge,Dakota,Rear Left; Rear Right,10 In. Rear Brakes,
26282,26282,C93627,Parking Brake Cable,1989.0,Dodge,Dakota,Rear Left; Rear Right,10 In. Rear Brakes,
26283,26283,C93627,Parking Brake Cable,1988.0,Dodge,Dakota,Rear Left; Rear Right,10 In. Rear Brakes,
26284,26284,C93627,Parking Brake Cable,1987.0,Dodge,Dakota,Rear Left; Rear Right,10 In. Rear Brakes,

In [48]:
OFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\96_Competitor Data\Dorman Parts'
product="ParkingBrakeCable"

In [49]:
len(df)

1701

In [51]:
with pd.ExcelWriter(OFolder+'\\'+f'Dorman{product}_detail'+'.xlsx') as writer:  
    df.to_excel(writer,index=False, sheet_name='List')
    df2.to_excel(writer,index=False, sheet_name='Coverage')
    df3.to_excel(writer,index=False, sheet_name='Attributes')