In [1]:
#pip install selenium
#pip install webdriver_manager
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib.parse import unquote
from selenium.webdriver.support.ui import Select
import pandas as pd
import datetime 

import warnings

# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

In [2]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.get('https://parts.ford.com/shop/en/us/engine/spark-plugs#facet:&productBeginIndex:0&orderBy:&pageView:&minPrice:&maxPrice:&pageSize:&')

In [3]:
driver.find_elements(By.CLASS_NAME,"pNameWidth")[1].text

'Spark Plug'

In [4]:
driver.find_elements(By.CLASS_NAME,"pNumber")[1].text.split(":")[1]

' SP476 (AS4C)'

In [5]:
driver.find_elements(By.CSS_SELECTOR,'[class="partMSRP hidden-xs"]')[1].text.split("$")[1]

'2.85'

In [10]:
driver.find_elements(By.XPATH,'//div[@class="partImageContainer"]/a')[1].get_attribute('href')

'https://parts.ford.com/shop/en/us/engine/spark-plugs/spark-plug-p-sp476?pdp=y'

In [59]:
Cols=["Links","Name"]
df = pd.DataFrame(columns=Cols)
count=0

In [68]:
names=driver.find_elements(By.CLASS_NAME,"pNameWidth")
Part_Numbers=driver.find_elements(By.CLASS_NAME,"pNumber")
MSRPS=driver.find_elements(By.CSS_SELECTOR,'[class="partMSRP hidden-xs"]')
Links=driver.find_elements(By.XPATH,'//div[@class="partImageContainer"]/a')

for name,pn,msrp,link in zip(names,Part_Numbers,MSRPS,Links):
    df.loc[count,"Name"]=name.text
    df.loc[count,"PartNumber"]=pn.text.split(":")[1]
    df.loc[count,"MSRP"]=float(msrp.text.split("$")[1])
    df.loc[count,"Links"]=link.get_attribute('href')
    count=count+1

len(df)

94

In [69]:
df.drop_duplicates()

,Links,Name,PartNumber,MSRP
0,https://parts.ford.com/shop/en/us/engine/spark...,Spark Plug,SP420X (BSF42CX),6.56
1,https://parts.ford.com/shop/en/us/engine/spark...,Spark Plug,SP476 (AS4C),2.85
2,https://parts.ford.com/shop/en/us/engine/spark...,Spark Plug,SP461 (AGSF43C),6.05
3,https://parts.ford.com/shop/en/us/engine/spark...,Spark Plug (GT),SP583 (CYFS092YPT3),21.27
4,https://parts.ford.com/shop/en/us/engine/spark...,Spark Plug,SP447X (AGSF32CX),6.22
...,...,...,...,...
89,https://parts.ford.com/shop/en/us/engine/spark...,AIR CONDITIONING (A/C). Refrigerant Liquid Hos...,YF3678 (BC4Z19837A),90.73
90,https://parts.ford.com/shop/en/us/engine/spark...,Spark Plug,SP409AX (AWSF44CAX),4.63
91,https://parts.ford.com/shop/en/us/engine/spark...,Spark Plug,SP473AX (AL7CAX),6.45
92,https://parts.ford.com/shop/en/us/engine/spark...,Spark Plug,SP588 (HYFS12YPT),23.64
93,https://parts.ford.com/shop/en/us/engine/spark...,Direct Ignition Coil Boot. Ignition Wire Prote...,P2GZ12A402A,14.44

In [70]:
df

,Links,Name,PartNumber,MSRP
0,https://parts.ford.com/shop/en/us/engine/spark...,Spark Plug,SP420X (BSF42CX),6.56
1,https://parts.ford.com/shop/en/us/engine/spark...,Spark Plug,SP476 (AS4C),2.85
2,https://parts.ford.com/shop/en/us/engine/spark...,Spark Plug,SP461 (AGSF43C),6.05
3,https://parts.ford.com/shop/en/us/engine/spark...,Spark Plug (GT),SP583 (CYFS092YPT3),21.27
4,https://parts.ford.com/shop/en/us/engine/spark...,Spark Plug,SP447X (AGSF32CX),6.22
...,...,...,...,...
89,https://parts.ford.com/shop/en/us/engine/spark...,AIR CONDITIONING (A/C). Refrigerant Liquid Hos...,YF3678 (BC4Z19837A),90.73
90,https://parts.ford.com/shop/en/us/engine/spark...,Spark Plug,SP409AX (AWSF44CAX),4.63
91,https://parts.ford.com/shop/en/us/engine/spark...,Spark Plug,SP473AX (AL7CAX),6.45
92,https://parts.ford.com/shop/en/us/engine/spark...,Spark Plug,SP588 (HYFS12YPT),23.64
93,https://parts.ford.com/shop/en/us/engine/spark...,Direct Ignition Coil Boot. Ignition Wire Prote...,P2GZ12A402A,14.44

In [73]:
OFolder=r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\95_OE_Products\Outputs"
Source='Ford'
search_text="SparkPlug"

In [74]:
df.to_excel(OFolder+'\\'+f'{Source}ProductLinks_'+search_text+'.xlsx')#