In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib.parse import unquote
from selenium.webdriver.support.ui import Select
import pandas as pd
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import datetime 
import warnings
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
from IPython.display import clear_output

In [2]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.maximize_window()
wait=WebDriverWait(driver, 10)
driver.get("https://www.gmpartsgiant.com/")

In [4]:
cols=["Sl.No"]
df= pd.DataFrame(columns=cols)
count=0

In [5]:
List=["19351570",
"19351572",
"19351591",
"12192462",
"12192470",
"19301298",
"19301299",
"19170842",
"19171855",
"19180531",
"12192471",
"12192375",
"19170849",
"19351593",
"19171849"
]
print(len(List))

15

In [6]:
from tqdm import tqdm
for i in tqdm(range(len(List))): #len(List)):
    print(f"running {i}th element | {List[i]}")
    search_text=f"{List[i]}"
    searchbox=wait.until(EC.element_to_be_clickable((By.CLASS_NAME,"ab-input-control")))
    sleep(1)
    searchbox.click()
    searchbox.send_keys(search_text)
    searchbox.submit()
    sleep(1)
    element=wait.until(EC.presence_of_element_located((By.XPATH, ".//div[@class='pn-tab-title'][h2/text()='Vehicle Fitment']")))
    driver.execute_script("arguments[0].scrollIntoView();", element)
    element.click()
    try:
        WebDriverWait(driver, 3).until(EC.presence_of_element_located((By.CLASS_NAME,"fit-vehicle-list-view-text"))).click()
    except:
        pass
    tablecontent=driver.find_elements(By.CLASS_NAME,"fit-vehicle-list-text")

    for i in range(len(tablecontent)):
        if i%3==0:
            df.loc[count,"YMM"]= tablecontent[i].text
        if i%3==1:
            df.loc[count,"EnineList"]= tablecontent[i].text
        if i%3==2:
            df.loc[count,"Vehicle Options"]= tablecontent[i].text
            df.loc[count,"PartNumber"]=search_text
            count=count+1

  0%|          | 0/15 [00:00<?, ?it/s]

running 0th element | 19351570

  7%|▋         | 1/15 [00:04<01:00,  4.35s/it]

running 1th element | 19351572

 13%|█▎        | 2/15 [00:10<01:09,  5.36s/it]

running 2th element | 19351591

 20%|██        | 3/15 [00:16<01:07,  5.66s/it]

running 3th element | 12192462

 27%|██▋       | 4/15 [00:19<00:49,  4.55s/it]

running 4th element | 12192470

 33%|███▎      | 5/15 [00:24<00:49,  4.97s/it]

running 5th element | 19301298

 40%|████      | 6/15 [00:30<00:47,  5.31s/it]

running 6th element | 19301299

 47%|████▋     | 7/15 [00:36<00:43,  5.49s/it]

running 7th element | 19170842

 53%|█████▎    | 8/15 [00:42<00:38,  5.55s/it]

running 8th element | 19171855

 60%|██████    | 9/15 [00:48<00:33,  5.62s/it]

running 9th element | 19180531

 67%|██████▋   | 10/15 [00:54<00:29,  5.84s/it]

running 10th element | 12192471

 73%|███████▎  | 11/15 [01:00<00:22,  5.74s/it]

running 11th element | 12192375

 80%|████████  | 12/15 [01:05<00:17,  5.72s/it]

running 12th element | 19170849

 87%|████████▋ | 13/15 [01:08<00:09,  4.83s/it]

running 13th element | 19351593

 93%|█████████▎| 14/15 [01:11<00:04,  4.35s/it]

running 14th element | 19171849

100%|██████████| 15/15 [01:17<00:00,  5.17s/it]

In [14]:
df

,Sl.No,YMM,EnineList,Vehicle Options,PartNumber
0,NaN,2009 Buick Allure,8 Cyl 5.3L,"CX (US)/ALLURE CX (CAN), CX 4 DOOR, CXL 4 DOOR...",19351570
1,NaN,2009 Buick LaCrosse,8 Cyl 5.3L,"CX (US)/ALLURE CX (CAN), CX 4 DOOR, CXL 4 DOOR...",19351570
2,NaN,2009-2014 Cadillac Escalade,"8 Cyl 6.0L, 8 Cyl 6.0L Flex, 8 Cyl 6.2L Flex","1/2 TON, EXT 1/2 TON, YUKON XL/DENALI XL/ESCAL...",19351570
3,NaN,2009-2013 Chevrolet Avalanche,"8 Cyl 5.3L, 8 Cyl 5.3L Flex, 8 Cyl 6.0L",1/2 TON,19351570
4,NaN,2010-2015 Chevrolet Camaro,"8 Cyl 6.2L, 8 Cyl 7.0L","SS 2 DOOR CONVERTIBLE, SS 2 DOOR COUPE",19351570
...,...,...,...,...,...
124,NaN,2008 Hummer H3,8 Cyl 5.3L,SUV,19351593
125,NaN,2005-2006 Pontiac GTO,8 Cyl 6.0L,GTO,19351593
126,NaN,2005-2008 Pontiac Grand Prix,8 Cyl 5.3L,"4 DOOR, GT 4 DOOR, GT2 4 DOOR, GTP 4 DOOR, GXP...",19351593
127,NaN,1997-2000 Buick Regal,6 Cyl 3.8L,"CUSTOM, GS, LIMITED, LS, REGAL",19171849
128,NaN,1997-2000 Pontiac Grand Prix,6 Cyl 3.8L,"2 DOOR, 4 DOOR, GT 2 DOOR, GT 4 DOOR, GTP 2 DO...",19171849

In [17]:
for i in range(len(df)):
    if "," in df["YMM"][i]:
        n=df["YMM"][i].count(",")
        df.at[i,"Model_Years"]=df['YMM'][i].split(" ")[0:(1+n)]
        df.loc[i,"Make"]=df["YMM"][i].split(" ")[(1+n)]
        df.loc[i,"Model"]=" ".join(df["YMM"][i].split(" ")[(2+n):])        
        print(n)
    else:
        df.at[i,"Model_Years"]=df['YMM'][i].split(" ")[0:(1)]
        df.loc[i,"Make"]=df["YMM"][i].split(" ")[1]
        df.loc[i,"Model"]=" ".join(df["YMM"][i].split(" ")[2:])

df=df.explode("Model_Years")

df = df.reset_index(drop=True)
for i in range(len(df)):
    if "-" in df['Model_Years'][i]:
        #print(i)
        year=df['Model_Years'].str.split('-')[i]
        startyear=year[0]
        endyear=year[1]
        df.loc[i,'Start_Year']=startyear
        df.loc[i,'End_Year']=endyear
    if "-" not in df['Model_Years'][i]:
        #print (i)
        df.loc[i,'Start_Year']=df['Model_Years'][i]
        df.loc[i,'End_Year']=df['Model_Years'][i]


df['Start_Year']=df['Start_Year'].str.replace(",","").replace(" ","").astype(int)
df['End_Year']=df['End_Year'].str.replace(",","").replace(" ","").astype(int)

1

In [18]:
df

,Sl.No,YMM,EnineList,Vehicle Options,PartNumber,Model_Years,Make,Model,Start_Year,End_Year
0,NaN,2009 Buick Allure,8 Cyl 5.3L,"CX (US)/ALLURE CX (CAN), CX 4 DOOR, CXL 4 DOOR...",19351570,2009,Buick,Allure,2009,2009
1,NaN,2009 Buick LaCrosse,8 Cyl 5.3L,"CX (US)/ALLURE CX (CAN), CX 4 DOOR, CXL 4 DOOR...",19351570,2009,Buick,LaCrosse,2009,2009
2,NaN,2009-2014 Cadillac Escalade,"8 Cyl 6.0L, 8 Cyl 6.0L Flex, 8 Cyl 6.2L Flex","1/2 TON, EXT 1/2 TON, YUKON XL/DENALI XL/ESCAL...",19351570,2009-2014,Cadillac,Escalade,2009,2014
3,NaN,2009-2013 Chevrolet Avalanche,"8 Cyl 5.3L, 8 Cyl 5.3L Flex, 8 Cyl 6.0L",1/2 TON,19351570,2009-2013,Chevrolet,Avalanche,2009,2013
4,NaN,2010-2015 Chevrolet Camaro,"8 Cyl 6.2L, 8 Cyl 7.0L","SS 2 DOOR CONVERTIBLE, SS 2 DOOR COUPE",19351570,2010-2015,Chevrolet,Camaro,2010,2015
...,...,...,...,...,...,...,...,...,...,...
125,NaN,2008 Hummer H3,8 Cyl 5.3L,SUV,19351593,2008,Hummer,H3,2008,2008
126,NaN,2005-2006 Pontiac GTO,8 Cyl 6.0L,GTO,19351593,2005-2006,Pontiac,GTO,2005,2006
127,NaN,2005-2008 Pontiac Grand Prix,8 Cyl 5.3L,"4 DOOR, GT 4 DOOR, GT2 4 DOOR, GTP 4 DOOR, GXP...",19351593,2005-2008,Pontiac,Grand Prix,2005,2008
128,NaN,1997-2000 Buick Regal,6 Cyl 3.8L,"CUSTOM, GS, LIMITED, LS, REGAL",19171849,1997-2000,Buick,Regal,1997,2000
129,NaN,1997-2000 Pontiac Grand Prix,6 Cyl 3.8L,"2 DOOR, 4 DOOR, GT 2 DOOR, GT 4 DOOR, GTP 2 DO...",19171849,1997-2000,Pontiac,Grand Prix,1997,2000

In [19]:
df['Years'] = df.apply(lambda row: list(range(row['Start_Year'], row['End_Year'] + 1)), axis=1)
df.drop(columns={'End_Year','Start_Year'})
df=df.explode('Years')
df=df.drop(columns={'End_Year','Start_Year'})

df["Engine"]=df["EnineList"].str.split(", ")
df=df.explode("Engine")

In [20]:
from tqdm import tqdm
for i in tqdm(range(10,len(List))): #len(List)):
    print(f"running {i}th element | {List[i]}")
    search_text=f"{List[i]}"
    searchbox=wait.until(EC.element_to_be_clickable((By.CLASS_NAME,"ab-input-control")))
    sleep(1)
    searchbox.click()
    searchbox.send_keys(search_text)
    searchbox.submit()
    try:
        wait.until(EC.presence_of_element_located((By.CLASS_NAME,"ab-select-col"))).find_element(By.XPATH,".//li[1]").click()
    except:
        pass
    sleep(1)
    result=wait.until(EC.presence_of_element_located((By.CLASS_NAME,"ns-main-title"))).text
    if "Search Results" in result:

        Names=wait.until(EC.visibility_of_all_elements_located((By.CSS_SELECTOR,'[class="ns-parts-list-desc"]')))
        PartNumbers=driver.find_elements(By.CSS_SELECTOR,'[class="ns-parts-list-parts"]')
        for name, pno in zip(Names, PartNumbers):
            App=driver.find_element(By.CLASS_NAME,"av-side-rqi").text
            try:
                Spec=driver.find_element(By.CLASS_NAME,"av-side-opi").text
            except:
                Spec=" "
            df.loc[count,"Application"]= App+" " +Spec
            df.loc[count,"Name"]=name.text
            df.loc[count, "Sl.No"]=i
            df.loc[count,"OrignialSelection"]=List[i]
            df.loc[count,"Number"]=pno.text.split("\n")[0]
            count=count+1
    else:
        print("No results")
    driver.find_element(By.CLASS_NAME,"av-side-change-btn").click()
    sleep(1)
    driver.find_element(By.CLASS_NAME,"av-prev-clear-btn").click()
    sleep(3)
    clear_output(True)

100%|██████████| 49/49 [10:00<00:00, 12.25s/it]

In [372]:
df.columns

Index(['Sl.No', 'YMM', 'EnineList', 'Vehicle Options', 'PartNumber',
       'Model_Years', 'Make', 'Model', 'Years', 'Engine'],
      dtype='object')

In [20]:
dfo=df[['Make','Model', 'Years', 'Engine', 'Vehicle Options', 'PartNumber']]

In [21]:
dfo

,Make,Model,Years,Engine,Vehicle Options,PartNumber
0,Buick,Allure,2009,8 Cyl 5.3L,"CX (US)/ALLURE CX (CAN), CX 4 DOOR, CXL 4 DOOR...",19351570
1,Buick,LaCrosse,2009,8 Cyl 5.3L,"CX (US)/ALLURE CX (CAN), CX 4 DOOR, CXL 4 DOOR...",19351570
2,Cadillac,Escalade,2009,8 Cyl 6.0L,"1/2 TON, EXT 1/2 TON, YUKON XL/DENALI XL/ESCAL...",19351570
2,Cadillac,Escalade,2009,8 Cyl 6.0L Flex,"1/2 TON, EXT 1/2 TON, YUKON XL/DENALI XL/ESCAL...",19351570
2,Cadillac,Escalade,2009,8 Cyl 6.2L Flex,"1/2 TON, EXT 1/2 TON, YUKON XL/DENALI XL/ESCAL...",19351570
...,...,...,...,...,...,...
128,Buick,Regal,2000,6 Cyl 3.8L,"CUSTOM, GS, LIMITED, LS, REGAL",19171849
129,Pontiac,Grand Prix,1997,6 Cyl 3.8L,"2 DOOR, 4 DOOR, GT 2 DOOR, GT 4 DOOR, GTP 2 DO...",19171849
129,Pontiac,Grand Prix,1998,6 Cyl 3.8L,"2 DOOR, 4 DOOR, GT 2 DOOR, GT 4 DOOR, GTP 2 DO...",19171849
129,Pontiac,Grand Prix,1999,6 Cyl 3.8L,"2 DOOR, 4 DOOR, GT 2 DOOR, GT 4 DOOR, GTP 2 DO...",19171849
129,Pontiac,Grand Prix,2000,6 Cyl 3.8L,"2 DOOR, 4 DOOR, GT 2 DOOR, GT 4 DOOR, GTP 2 DO...",19171849

In [23]:
OFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\GM Parts Giant'

with pd.ExcelWriter(OFolder+'\GMPartsGiant-CableSet_OE PartNumber_Expanded.xlsx') as writer:  
    dfo.to_excel(writer,index=False, sheet_name='Cleaned')
    df.to_excel(writer,index=False, sheet_name='Raw')