# 1. Library calling

In [1]:
#pip install selenium
#pip install webdriver_manager
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib.parse import unquote
from selenium.webdriver.support.ui import Select
import pandas as pd
import datetime 

import warnings

# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

# 2. Defining the Product Information and Location

In [2]:
SummaryFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects'
summaryFile='Scraping_List.txt'
st=pd.read_csv(SummaryFolder+'\\'+summaryFile)
print(st)
#Define Product to extract
search_text = st['Product Name'][9]
print(search_text)
Source="Go-Parts"
OFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Outputs'
IFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Inputs'

                                  Product Name
0                                Ignition Coil
1                      Windshield Washer Pumps
2                        coupler trailer locks
3          Adjustable Trailer Hitch Ball Mount
4                               Vacuum Cleaner
5                                   Spark Plug
6              bluetooth Enabled Trailer locks
7                          Power Steering Hose
8   Power Steering Pressure Line Hose Assembly
9                       Washer Fluid Reservoir
10          Hitch Ball Mount with Weight Scale
11                               LED Headlamps
12                             LED flashlights
13                   Fiberglass Tonneau Covers
14                    Aluminium Tonneau Covers
15                     Hardfold Tonneau Covers
16                            Spark Plug Wires
17                 washer fluid reservoir tank
18                   Non Automotive Gas Struts
Washer Fluid Reservoir

# 3. Setting Webdriver and Website Specific Information

In [3]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.get('https://www.go-parts.com/')
driver.maximize_window()
wait=WebDriverWait(driver, 5)

In [4]:
# Find the search bar by its ID
try:
    search_bar = driver.find_element(By.ID, 'top-search-input')
except:
    pass

# Enter the search text

search_bar.send_keys(search_text)

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [5]:
Cols=["Links","Name"]
df = pd.DataFrame(columns=Cols)
count=0

In [6]:
for i in range(50):
    try:
        wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '[class="ais-infinite-hits--showmore"]'))).click()
        sleep(1)
    except:
        break

In [7]:
count=0
nelements=driver.find_elements(By.CSS_SELECTOR,'div.product-info a.product-name')
for element in nelements:
    df.loc[count,'Name']=element.text
    df.loc[count,'Links']=element.get_attribute('href').split("?query")[0]
    count=count+1

In [8]:
df

,Links,Name
0,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ AC1288104)
1,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir - Front (Dorman 603-211)
2,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ CH1288271)
3,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ GM1288271)
4,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ HY1288112)
...,...,...
282,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ SU1288108)
283,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ VW1288135)
284,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ AU1288106)
285,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ HO1288213)
286,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ VW1288129)

# 5. Post Processing Data and Exporting

In [9]:
df=df.drop_duplicates(subset=["Links"])
df

,Links,Name
0,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ AC1288104)
1,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir - Front (Dorman 603-211)
2,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ CH1288271)
3,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ GM1288271)
4,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ HY1288112)
...,...,...
282,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ SU1288108)
283,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ VW1288135)
284,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ AU1288106)
285,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ HO1288213)
286,https://www.go-parts.com/ps-product-new.php?sk...,Washer Fluid Reservoir (LKQ VW1288129)

In [10]:
df.to_excel(IFolder+'\\'+f'{Source}ProductLinks_'+search_text+'.xlsx', index=False)

# 99. Archived Codes