# Library calling

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib.parse import unquote
from selenium.webdriver.support.ui import Select
import pandas as pd
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import datetime 
import warnings
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
from IPython.display import clear_output

# Defining the Product Information and Location

In [34]:
df1=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\10_Spark Plug Wire Set\Cableset_Data_Yuvaraj.xlsx")

In [35]:
df1

,Years,Make,Model,Engine Block,Engine Capacity,Keys
0,2010,Cadillac,CTS,V8,6.2,2010 Cadillac CTS 6.2L V8
1,2011,Cadillac,CTS,V8,6.2,2011 Cadillac CTS 6.2L V8
2,2010,Cadillac,Escalade,V8,6.2,2010 Cadillac Escalade 6.2L V8
3,2009,Chevrolet,Avalanche,V8,6.0,2009 Chevrolet Avalanche 6.0L V8
4,2011,Chevrolet,Caprice,V8,6.0,2011 Chevrolet Caprice 6.0L V8
...,...,...,...,...,...,...
546,2002,Dodge,Ram 3500 Van,V8,5.9,2002 Dodge Ram 3500 Van 5.9L V8
547,2003,Dodge,Ram 3500 Van,V8,5.9,2003 Dodge Ram 3500 Van 5.9L V8
548,1999,Dodge,Ram 3500 Van,V8,5.2,1999 Dodge Ram 3500 Van 5.2L V8
549,2002,Dodge,Ram 3500 Van,V8,5.2,2002 Dodge Ram 3500 Van 5.2L V8
550,2003,Dodge,Ram 3500 Van,V8,5.2,2003 Dodge Ram 3500 Van 5.2L V8

In [28]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 551 entries, 0 to 550
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Years            551 non-null    int64
 1   Make             551 non-null    object
 2   Model            551 non-null    object
 3   Engine Block     551 non-null    object
 4   Engine Capacity  551 non-null    float64
 5   Key              551 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 26.0+ KB

In [ ]:
# Keys=df95["Keys1"]
# print(Keys[0], len(Keys) )

#  Setting Webdriver and Website Specific Information

In [29]:
cols=["Sl.No"]
df= pd.DataFrame(columns=cols)

In [30]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.maximize_window()
wait=WebDriverWait(driver, 10)
driver.get('https://dh.identifix.com/id/login')
sleep(1)
username_field = driver.find_element(By.ID,'UserName')  
username_field.send_keys('constantina')
sleep(1)

password_field = driver.find_element(By.ID,'Password')  
password_field.send_keys('constantina01')
sleep(1)

Login = driver.find_element(By.ID,'Login')  
Login.click()
sleep(1)

home=driver.current_url
driver.get(home)

# Defining the Dataframe and Extracting the data into the Dataframe

# Extracting the Final Link

In [31]:
df1

,Years,Make,Model,Engine Block,Engine Capacity,Key
0,2010,Cadillac,CTS,V8,6.2,2010 Cadillac CTS 6.2L V8
1,2011,Cadillac,CTS,V8,6.2,2011 Cadillac CTS 6.2L V8
2,2010,Cadillac,Escalade,V8,6.2,2010 Cadillac Escalade 6.2L V8
3,2009,Chevrolet,Avalanche,V8,6.0,2009 Chevrolet Avalanche 6.0L V8
4,2011,Chevrolet,Caprice,V8,6.0,2011 Chevrolet Caprice 6.0L V8
...,...,...,...,...,...,...
546,2002,Dodge,Ram 3500 Van,V8,5.9,2002 Dodge Ram 3500 Van 5.9L V8
547,2003,Dodge,Ram 3500 Van,V8,5.9,2003 Dodge Ram 3500 Van 5.9L V8
548,1999,Dodge,Ram 3500 Van,V8,5.2,1999 Dodge Ram 3500 Van 5.2L V8
549,2002,Dodge,Ram 3500 Van,V8,5.2,2002 Dodge Ram 3500 Van 5.2L V8
550,2003,Dodge,Ram 3500 Van,V8,5.2,2003 Dodge Ram 3500 Van 5.2L V8

In [51]:
driver.get(home)

In [36]:
from tqdm import tqdm
for i in tqdm(range(len(df1))):
    driver.get(home)
    print(i," items completed- currently Running: ", df1['Keys'][i])
    #print(round(df1.loc[i,'%Coverage'],2),"% Covered", i," items completed- currently Running: ", df1.loc[i,'Keys1'] )
    sleep(4)
    typebox=wait.until(EC.presence_of_element_located((By.ID,"CreateVehicle_suggest_box")))
    #typebox.click()
    boxed=df1.loc[i,'Keys']
    df.loc[i,"Sl.No"]=i
    df.loc[i,'Keys']=df1.loc[i,'Keys']
    #df.loc[i,'VehCount']=df1.loc[i,'VehCount']
    #df.loc[i,'%Coverage']=df1.loc[i,'%Coverage']
    #print(boxed)
    sleep(4)
    typebox.send_keys(boxed)
    o2=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME,"ui-menu-item")))
    #print("number of vehicle: ", len(o2))
    df.loc[i,"Number of Variants"]=len(o2)
    if(len(o2))<=1:
        o=wait.until(EC.presence_of_element_located((By.CLASS_NAME,"ui-menu-item")))
        o.click()
    else:
        o2[0].click()
    try:
        sleep(1) 
        selected_text = wait.until(EC.presence_of_element_located((By.CLASS_NAME,"vehicle-info"))).text    
        df.loc[i,'Selected Model']=selected_text
        df.loc[i,'Baselink']=driver.current_url    
        # #driver.get(home)
        # NewV = wait.until(EC.presence_of_element_located((By.XPATH, "//div[@class='sub-menu-item right-sub-menu-item']/a[@title='New Vehicle']")))
        # NewV.click()
    except:
        driver.get(home)
    clear_output(wait=True)

100%|██████████| 551/551 [2:26:42<00:00, 15.98s/it]

In [37]:
df.info()
df.tail()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 551 entries, 0 to 550
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Sl.No               551 non-null    object
 1   Keys                551 non-null    object
 2   Number of Variants  551 non-null    float64
 3   Selected Model      551 non-null    object
 4   Baselink            551 non-null    object
dtypes: float64(1), object(4)
memory usage: 42.0+ KB

,Sl.No,Keys,Number of Variants,Selected Model,Baselink
546,546,2002 Dodge Ram 3500 Van 5.9L V8,1.0,"2002 Dodge Ram 3500 Van 5.9L, V8, Gas, VIN Z, ...",https://dh.identifix.com/VehicleHome/Index?ROI...
547,547,2003 Dodge Ram 3500 Van 5.9L V8,1.0,"2003 Dodge Ram 3500 Van 5.9L, V8, Gas, VIN Z, ...",https://dh.identifix.com/VehicleHome/Index?ROI...
548,548,1999 Dodge Ram 3500 Van 5.2L V8,3.0,"1999 Dodge Ram 3500 Van 5.2L, V8, CNG, VIN T, ...",https://dh.identifix.com/VehicleHome/Index?ROI...
549,549,2002 Dodge Ram 3500 Van 5.2L V8,2.0,"2002 Dodge Ram 3500 Van 5.2L, V8, CNG, VIN T, ...",https://dh.identifix.com/VehicleHome/Index?ROI...
550,550,2003 Dodge Ram 3500 Van 5.2L V8,2.0,"2003 Dodge Ram 3500 Van 5.2L, V8, CNG, VIN T, ...",https://dh.identifix.com/VehicleHome/Index?ROI...

# Post Processing Data

In [38]:
len(df)

551

In [39]:
Product_Code1="Cable+Set"

In [40]:
df["Generic_Product_Search_Link"]=df['Baselink'].str.replace("VehicleHome", "MotorPartsLabor").str.replace("VSM=2&LocationId=13", f"LocationId=4&WorkflowPath=5&AssetTypeId=19&Tab=TabMotorPartAndLabor&MenuItemId=19&LinkName=See%2520more...#DocAssets=19&KW={Product_Code1}&VETId=8&STMode=1&Paging=&position=0&IsCat=0&AssetCategoryId=&SMode=4")
df.head()

,Sl.No,Keys,Number of Variants,Selected Model,Baselink,Generic_Product_Search_Link
0,0,2010 Cadillac CTS 6.2L V8,1.0,"2010 Cadillac CTS V 6.2L, V8, Asp S/C, VIN P, ...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...
1,1,2011 Cadillac CTS 6.2L V8,1.0,"2011 Cadillac CTS V 6.2L, V8, Asp S/C, VIN P, ...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...
2,2,2010 Cadillac Escalade 6.2L V8,5.0,"2010 Cadillac Escalade 6.2L, V8, Flex, VIN F, ...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...
3,3,2009 Chevrolet Avalanche 6.0L V8,2.0,"2009 Chevrolet Avalanche LT 6.0L, V8, Gas, VIN...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...
4,4,2011 Chevrolet Caprice 6.0L V8,1.0,"2011 Chevrolet Caprice PPV 6.0L, V8, USA",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...

In [41]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 551 entries, 0 to 550
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sl.No                        551 non-null    object
 1   Keys                         551 non-null    object
 2   Number of Variants           551 non-null    float64
 3   Selected Model               551 non-null    object
 4   Baselink                     551 non-null    object
 5   Generic_Product_Search_Link  551 non-null    object
dtypes: float64(1), object(5)
memory usage: 46.3+ KB

In [42]:
OFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\Identifix\Identifix_Product_Links'

with pd.ExcelWriter(OFolder+'\VIO-Identifix_ProductLinks-CableSet.xlsx') as writer:  
    df.to_excel(writer,index=False, sheet_name='Links')
    # df95.to_excel(writer,index=True, sheet_name='Coverage95')
    # df2.to_excel(writer,index=True, sheet_name='CoverageFull')

In [45]:
es=driver.find_elements(By.CLASS_NAME,"pd-ll-link")


for e in es:

    print(e.get_attribute("href"))

https://www.gmpartsgiant.com/parts/gm-wire-kit-19301299.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-19301299.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-19180531.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-19180531.html
https://www.gmpartsgiant.com/parts/gm-wire-asm-splg-19351578.html
https://www.gmpartsgiant.com/parts/gm-wire-asm-splg-19351578.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-19171845.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-19171845.html
https://www.gmpartsgiant.com/parts/gm-wire-set-splg-19351573.html
https://www.gmpartsgiant.com/parts/gm-wire-set-splg-19351573.html
https://www.gmpartsgiant.com/parts/gm-wire-asm-splg-5-cyl-19351564.html
https://www.gmpartsgiant.com/parts/gm-wire-asm-splg-5-cyl-19351564.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-19154584.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-19154584.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-19154581.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-19154581.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-88892832.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-88892832.html
https://www.gmpartsgiant.com/parts/gm-wire-12192467.html
https://www.gmpartsgiant.com/parts/gm-wire-12192467.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-12043736.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-12043736.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-19154585.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-19154585.html
https://www.gmpartsgiant.com/parts/gm-wire-12192476.html
https://www.gmpartsgiant.com/parts/gm-wire-12192476.html
https://www.gmpartsgiant.com/parts/gm-wire-splg-12072154.html
https://www.gmpartsgiant.com/parts/gm-wire-splg-12072154.html
https://www.gmpartsgiant.com/parts/gm-wire-12192465.html
https://www.gmpartsgiant.com/parts/gm-wire-12192465.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-88984267.html
https://www.gmpartsgiant.com/parts/gm-wire-kit-88984267.html
https://www.gmpartsgiant.com/parts/gm-wire-asm-splg-19351592.html
https://www.gmpartsgiant.com/parts/gm-wire-asm-splg-19351592.html
https://www.gmpartsgiant.com/parts/gm-wire-asm-splg-19351911.html
https://www.gmpartsgiant.com/parts/gm-wire-asm-splg-19351911.html
https://www.gmpartsgiant.com/parts/gm-wire-12192475.html
https://www.gmpartsgiant.com/parts/gm-wire-12192475.html
https://www.gmpartsgiant.com/parts/gm-harness-12635741.html
https://www.gmpartsgiant.com/parts/gm-harness-12635741.html

In [44]:
len(es)

40

# Archived Codes

In [ ]:
for i in range(283,len(Keys)):
    typebox=driver.find_element(By.ID,"CreateVehicle_suggest_box")
    #typebox.click()
    boxed=Keys[i]
    #print(boxed)
    sleep(2)
    typebox.send_keys(boxed)
    sleep(1)
    o2=driver.find_elements(By.CLASS_NAME,"ui-menu-item")
    print("number of vehicle: ", len(o2))
    if(len(o2))<=1:
        o=driver.find_element(By.CLASS_NAME,"ui-menu-item")
        o.click()
    else:
        o2[1].click()
    sleep(3)
    selected_text = WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.CLASS_NAME,"vehicle-info"))).text
    try:        
        OEMRepair = WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.XPATH,"//li/a[text()='OEM Repair/Replace']")))
        # WebDriverWait(driver, max_wait_time).until(OEMRepair)
        sleep(1)
        OEMRepair.click()
        sleep(1)
        #IGCoil = driver.find_element(By.ID,"tb-search-box")
        IGCoil = WebDriverWait(driver, 40).until(EC.element_to_be_clickable(( By.ID,"tb-search-box")))
        element_to_click = WebDriverWait(driver, 40).until(EC.element_to_be_clickable(( By.ID,"bt-search")))
        #WebDriverWait(driver, max_wait_time).until(IGCoil)
        # Click the element
        sleep(5)
        IGCoil.send_keys("Ignition Coil(s)")
        sleep(1)
        #search = WebDriverWait(driver, 40).until(EC.presence_of_element_located((By.ID,"bt-search")))
        element_to_click.click()
        sleep(2)
        #WebDriverWait(driver, max_wait_time).until(search)       
        # expand=driver.find_element(By.CLASS_NAME,"expand-collapse-icon")
        # WebDriverWait(driver, max_wait_time).until(expand)
        # expand.click()
        # link2=driver.find_element(By.CLASS_NAME,'document-link')
        # Page2=link2.get_attribute('href')
        # actions=ActionChains(driver).send_keys(Keys.ARROW_DOWN).send_keys(Keys.ENTER)
        # actions.perform()
        NewV = WebDriverWait(driver, 40).until(EC.presence_of_element_located((By.XPATH, "//div[@class='sub-menu-item right-sub-menu-item']/a[@title='New Vehicle']")))
        df.loc[i,'Selected Model']=selected_text
        df.loc[i,'Link']=driver.current_url
        print(i+1)
        NewV.click()
    except:
        NewV = WebDriverWait(driver, 40).until(EC.presence_of_element_located((By.XPATH, "//div[@class='sub-menu-item right-sub-menu-item']/a[@title='New Vehicle']")))
        df.loc[i,'Selected Model']=selected_text
        df.loc[i,'Link']="No OEM Repair"
        NewV.click()
    # df.loc[row,"Link2"]=Page2
    #print("Number of items: ",i+1)