In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib.parse import unquote
from selenium.webdriver.support.ui import Select
import pandas as pd
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import datetime 
import numpy as np
import warnings
from tqdm import tqdm
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
from IPython.display import clear_output

In [2]:
ReplacePC="Serpentine+Belt"

In [3]:
# Product="CABLE SET" #"SERPENTINE BELT"
# ProductCode="Thermostat" #"Serpentine+Belt"

In [4]:
# df=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\Identifix\Identifix_Product_Links\VIO-Identifix_ProductLinks-Filler.xlsx")
df=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\101_Other_Support\OEPartNumber\VIO-Identifix_ProductLinks-extra12.xlsx",sheet_name='Links')
df.tail()

,Sl.No,Keys,Number of Variants,Selected Model,Baselink,Generic_Product_Search_Link,ProductCode,Product
2770,3037,2023 Toyota CamryLE 2.5L 4,20,NaN,NaN,NaN,Water+Pump,WATER PUMP
2771,3039,2023 Toyota CamrySE 2.5L 4,20,NaN,NaN,NaN,Water+Pump,WATER PUMP
2772,3041,2023 Toyota CorollaLE 2.0L 4,20,"2023 Toyota Corolla 2.0L, L4, Gas, Des M20A-FK...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Water+Pump,WATER PUMP
2773,3042,2023 Toyota RAV4LEAWD 2.5L 4,20,NaN,NaN,NaN,Water+Pump,WATER PUMP
2774,3043,2023 Toyota RAV4XLEPremium 2.5L 4,20,NaN,NaN,NaN,Water+Pump,WATER PUMP

In [5]:
df2=df.dropna(subset='Generic_Product_Search_Link')
#df2=df2[(df2["Inclusion"]=="Include") & (df2['%Coverage']=="New")]
df2=df2.reset_index()

In [6]:
del df2['index']

In [7]:
df2.shape

(2766, 8)

In [8]:
for i in range(len(df2)):
    df2.loc[i,"Product_Specific_Link"]=df2['Generic_Product_Search_Link'][i].replace(ReplacePC,df2['ProductCode'][i])
del df2["Generic_Product_Search_Link"]
del df2['Baselink']

In [9]:
#df2=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\Identifix\Ignition_Coil_Tempload.xlsx")

In [10]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2766 entries, 0 to 2765
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Sl.No                  2766 non-null   int64
 1   Keys                   2766 non-null   object
 2   Number of Variants     2766 non-null   int64
 3   Selected Model         2766 non-null   object
 4   ProductCode            2766 non-null   object
 5   Product                2766 non-null   object
 6   Product_Specific_Link  2766 non-null   object
dtypes: int64(2), object(5)
memory usage: 151.4+ KB

In [11]:
print(df2['Product_Specific_Link'][5])

https://dh.identifix.com/MotorPartsLabor/Index?ROID=377276961&VID=2068330&LocationId=4&WorkflowPath=5&AssetTypeId=19&Tab=TabMotorPartAndLabor&MenuItemId=19&LinkName=See%2520more...#DocAssets=19&KW=Fuel+Tank+Sending+Unit&VETId=8&STMode=1&Paging=&position=0&IsCat=0&AssetCategoryId=&SMode=4

In [41]:
cols=["Sl.No"]
df3= pd.DataFrame(columns=cols)
count3=0

In [50]:
path= 'C://chromedriver.exe'

driver=webdriver.Chrome()
driver.maximize_window()
wait=WebDriverWait(driver, 5)
driver.get('https://dh.identifix.com/id/login')
sleep(1)



username_field = driver.find_element(By.ID,'UserName')  
username_field.send_keys('vr140418')
sleep(1)

password_field = driver.find_element(By.ID,'Password')  
password_field.send_keys('rameshv001')
sleep(1)

Login = driver.find_element(By.ID,'Login')  
Login.click()

sleep(2)
home=driver.current_url

In [14]:
driver.get(home)

In [15]:
driver.get(df2['Product_Specific_Link'][4])

In [16]:
df2.head()

,Sl.No,Keys,Number of Variants,Selected Model,ProductCode,Product,Product_Specific_Link
0,0,1985 Ford Bronco 5.8L 8,6,"1985 Ford Bronco Custom 5.8L, V8, VIN G, 16V, ...",Fuel+Tank+Sending+Unit,FUEL GAUGE SENDING UNIT,https://dh.identifix.com/MotorPartsLabor/Index...
1,1,1985 Ford F150 4.9L 6,6,"1985 Ford F-150 4.9L, L6, Gas, VIN Y, 12V, Car...",Fuel+Tank+Sending+Unit,FUEL GAUGE SENDING UNIT,https://dh.identifix.com/MotorPartsLabor/Index...
2,2,1985 Ford F150 5.0L 8,6,"1985 Ford F-150 5.0L, V8, Gas, VIN F, 16V, Car...",Fuel+Tank+Sending+Unit,FUEL GAUGE SENDING UNIT,https://dh.identifix.com/MotorPartsLabor/Index...
3,3,1985 Ford F150 5.8L 8,6,"1985 Ford F-150 5.8L, V8, Gas, VIN G, 16V, Car...",Fuel+Tank+Sending+Unit,FUEL GAUGE SENDING UNIT,https://dh.identifix.com/MotorPartsLabor/Index...
4,7,1985 Ford F250 4.9L 6,6,"1985 Ford F-250 4.9L, L6, Gas, VIN Y, 12V, Car...",Fuel+Tank+Sending+Unit,FUEL GAUGE SENDING UNIT,https://dh.identifix.com/MotorPartsLabor/Index...

In [39]:
df2=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\Identifix\Identifix_Product_Links\PartNumberDetails\Temp_Container\VIO-Identifix_General_OEPartNumberWNotes_Filler_0_2900_old.xlsx",sheet_name="No Details")
df2.tail()

,Sl.No,Keys,Number of Variants,Selected Model,ProductCode,Combined Key,Product,Product_Specific_Link,Appln Notes,OE Part Number,Price [$]
1791,3025,2023 Dodge ChargerScatPack 6.4L 8,10,"2023 Dodge Challenger R/T Scat Pack 6.4L, V8, ...",Water+Pump,2023 Dodge ChargerScatPack 6.4L 8Water+Pump,WATER PUMP,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Information Available In Identifix,NaN
1792,3026,2023 Dodge RAM3500Laramie 6.7L 6,20,"2023 Dodge Challenger GT 3.6L, V6, Asp N, VIN ...",Water+Pump,2023 Dodge RAM3500Laramie 6.7L 6Water+Pump,WATER PUMP,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Information Available In Identifix,NaN
1793,3034,2023 Hyundai TucsonLimited 2.5L 4,20,"2023 Hyundai Santa Cruz Limited 2.5L, L4, Asp ...",Water+Pump,2023 Hyundai TucsonLimited 2.5L 4Water+Pump,WATER PUMP,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Information Available In Identifix,NaN
1794,3036,2023 Jeep GrandCherokeeSummit 3.6L 6,20,"2023 Jeep Gladiator Freedom 3.6L, V6, Gas, Asp...",Water+Pump,2023 Jeep GrandCherokeeSummit 3.6L 6Water+Pump,WATER PUMP,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Information Available In Identifix,NaN
1795,3041,2023 Toyota CorollaLE 2.0L 4,20,"2023 Toyota Corolla 2.0L, L4, Gas, Des M20A-FK...",Water+Pump,2023 Toyota CorollaLE 2.0L 4Water+Pump,WATER PUMP,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Information Available In Identifix,NaN

In [48]:
df2=df2[df2["OE Part Number"]=="No Part Number"]

In [51]:
for i in tqdm(range(len(df2))):#len(df2)
    try:
        if len(df2['Product_Specific_Link'][i])>1:
            driver.get(df2['Product_Specific_Link'][i])
            Product=df2['Product'][i]
            sleep(2)
            try:                   
                print("Running element #",i,"|",df2.loc[i,"Selected Model"])
                print("__________________________________________________________________________________________")
                sleep(2)
                for exp in range (100):
                    try:
                        WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.CLASS_NAME,'dynatree-ico-cf'))).click()
                    except:
                        break
                sleep(2)
                sbs=wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,f'[title="{Product}"]')))
                for w in range(len(sbs)):
                    sbs[w].click()
                sleep(1)
                es=WebDriverWait(driver, 15).until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,'[class="part-labor-table"]')))
                for e in es:
                    if 'Mfg.' in e.text:
                        if "$" in e.text:
                            pns=e.text.count("$")
                            #print(pns)
                            for pn in range(pns):
                                Appnote=e.text.split("$")[pn].split("\n")[-2]
                                PN=e.text.split("$")[pn].split("\n")[-1]
                                Price=float(e.text.split("$")[pn+1].split("\n")[0])
                                print(Appnote,"|",PN,"|",Price)
                                df3.loc[count3,"Sl.No"]=df2['Sl.No'][i]
                                df3.loc[count3,"Keys"]=df2['Keys'][i]
                                df3.loc[count3,"Links"]=df2['Product_Specific_Link'][i]
                                df3.loc[count3,"Appln Notes"]=Appnote
                                df3.loc[count3,"OE Part Number"]=PN
                                df3.loc[count3,"Price [$]"]=Price
                                count3=count3+1
                        else:
                            df3.loc[count3,"Sl.No"]=df2[i,'Sl.No']
                            df3.loc[count3,"Keys"]=df2['Keys'][i]
                            df3.loc[count3,"Links"]=df2['Product_Specific_Link'][i]
                            df3.loc[count3,"OE Part Number"]="['"+e.text.split('\n')[4]+"']"
                            count3=count3+1
                    else:
                        df3.loc[count3,"Sl.No"]=df2['Sl.No'][i]
                        df3.loc[count3,"Keys"]=df2['Keys'][i]
                        df3.loc[count3,"Links"]=df2['Product_Specific_Link'][i]
                        df3.loc[count3,"OE Part Number"]="No Part Number"
                        count3=count3+1
            except:
                df3.loc[count3,"Sl.No"]=df2['Sl.No'][i]
                df3.loc[count3,"Keys"]=df2['Keys'][i]
                df3.loc[count3,"Links"]=df2['Product_Specific_Link'][i]
                df3.loc[count3,"OE Part Number"]="No Information Available In Identifix"
                count3=count3+1
            print("__________________________________________________________________________________________")            
            print(i,"|",df2.loc[i,"Selected Model"],df3.loc[count3-1,"OE Part Number"])
            sleep(2)
            clear_output(wait=True)
    except:
        pass
        pass

100%|██████████| 624/624 [48:53<00:00,  4.70s/it]

In [52]:
df3

,Sl.No,Keys,Links,OE Part Number,Appln Notes,Price [$]
0,7,1985 Ford F250 4.9L 6,https://dh.identifix.com/MotorPartsLabor/Index...,No Part Number,NaN,NaN
1,7,1985 Ford F250 4.9L 6,https://dh.identifix.com/MotorPartsLabor/Index...,EOUZ9275B,Gas,129.13
2,9,1985 Ford F250 6.9L 8,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN
3,10,1985 Ford F350 4.9L 6,https://dh.identifix.com/MotorPartsLabor/Index...,No Part Number,NaN,NaN
4,10,1985 Ford F350 4.9L 6,https://dh.identifix.com/MotorPartsLabor/Index...,EOUZ9275B,Gas,129.13
...,...,...,...,...,...,...
440,1050,1996 Acura Integra 1.8L 4,https://dh.identifix.com/MotorPartsLabor/Index...,No Part Number,NaN,NaN
441,1050,1996 Acura Integra 1.8L 4,https://dh.identifix.com/MotorPartsLabor/Index...,No Part Number,NaN,NaN
442,1059,1998 Honda AccordDX 2.3L 4,https://dh.identifix.com/MotorPartsLabor/Index...,No Part Number,NaN,NaN
443,1059,1998 Honda AccordDX 2.3L 4,https://dh.identifix.com/MotorPartsLabor/Index...,19301PAA306,Fuji,46.88
444,1059,1998 Honda AccordDX 2.3L 4,https://dh.identifix.com/MotorPartsLabor/Index...,19301PAA306,Nippon,46.88

In [53]:
df3=pd.merge(df2,df3[['Keys','Appln Notes','OE Part Number','Price [$]']], on='Keys',how='outer')
df3.tail()

,Sl.No,Keys,Number of Variants,Selected Model,ProductCode,Combined Key,Product,Product_Specific_Link,Appln Notes_x,OE Part Number_x,Price [$]_x,Appln Notes_y,OE Part Number_y,Price [$]_y
857,2827,2021 Chevrolet BlazerPremier 3.6L 6,16,"2021 Chevrolet Blazer LT 3.6L, V6, Asp N, VIN ...",Thermostat,2021 Chevrolet BlazerPremier 3.6L 6Thermostat,THERMOSTAT,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,NaN,NaN,NaN
858,2828,2021 Chevrolet EquinoxLT 1.5L 4,8,"2021 Chevrolet Equinox L 1.5L, L4, USA/Canada",Thermostat,2021 Chevrolet EquinoxLT 1.5L 4Thermostat,THERMOSTAT,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,NaN,NaN,NaN
859,2874,2021 GMC AcadiaDenali 3.6L 6,8,"2021 GMC Acadia AT4 3.6L, V6, Asp N, VIN S, De...",Thermostat,2021 GMC AcadiaDenali 3.6L 6Thermostat,THERMOSTAT,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,NaN,NaN,NaN
860,2893,2021 Jeep Renegade80thAnniversaryAWD 1.3L 4,6,"2021 Jeep Renegade 80th Anniversary 1.3L, L4, ...",Thermostat,2021 Jeep Renegade80thAnniversaryAWD 1.3L 4The...,THERMOSTAT,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,NaN,NaN,NaN
861,2924,2021 Toyota SiennaLimitedAWD 2.5L 4,20,"2021 Toyota Avalon Hybrid Limited 2.5L, L4, FU...",Thermostat,2021 Toyota SiennaLimitedAWD 2.5L 4Thermostat,THERMOSTAT,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,NaN,NaN,NaN

In [56]:
df4=df3
df4

,Sl.No,Keys,Number of Variants,Selected Model,ProductCode,Combined Key,Product,Product_Specific_Link,Appln Notes_x,OE Part Number_x,Price [$]_x,Appln Notes_y,OE Part Number_y,Price [$]_y
0,7,1985 Ford F250 4.9L 6,6,"1985 Ford F-250 4.9L, L6, Gas, VIN Y, 12V, Car...",Fuel+Tank+Sending+Unit,1985 Ford F250 4.9L 6Fuel+Tank+Sending+Unit,FUEL GAUGE SENDING UNIT,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,NaN,No Part Number,NaN
1,7,1985 Ford F250 4.9L 6,6,"1985 Ford F-250 4.9L, L6, Gas, VIN Y, 12V, Car...",Fuel+Tank+Sending+Unit,1985 Ford F250 4.9L 6Fuel+Tank+Sending+Unit,FUEL GAUGE SENDING UNIT,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,Gas,EOUZ9275B,129.13
2,9,1985 Ford F250 6.9L 8,3,"1985 Ford F-250 6.9L, V8, Diesel, VIN 1, 16V, ...",Fuel+Tank+Sending+Unit,1985 Ford F250 6.9L 8Fuel+Tank+Sending+Unit,FUEL GAUGE SENDING UNIT,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,NaN,No Information Available In Identifix,NaN
3,10,1985 Ford F350 4.9L 6,6,"1985 Ford F-350 4.9L, L6, Gas, VIN Y, 12V, Car...",Fuel+Tank+Sending+Unit,1985 Ford F350 4.9L 6Fuel+Tank+Sending+Unit,FUEL GAUGE SENDING UNIT,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,NaN,No Part Number,NaN
4,10,1985 Ford F350 4.9L 6,6,"1985 Ford F-350 4.9L, L6, Gas, VIN Y, 12V, Car...",Fuel+Tank+Sending+Unit,1985 Ford F350 4.9L 6Fuel+Tank+Sending+Unit,FUEL GAUGE SENDING UNIT,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,Gas,EOUZ9275B,129.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,2827,2021 Chevrolet BlazerPremier 3.6L 6,16,"2021 Chevrolet Blazer LT 3.6L, V6, Asp N, VIN ...",Thermostat,2021 Chevrolet BlazerPremier 3.6L 6Thermostat,THERMOSTAT,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,NaN,NaN,NaN
858,2828,2021 Chevrolet EquinoxLT 1.5L 4,8,"2021 Chevrolet Equinox L 1.5L, L4, USA/Canada",Thermostat,2021 Chevrolet EquinoxLT 1.5L 4Thermostat,THERMOSTAT,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,NaN,NaN,NaN
859,2874,2021 GMC AcadiaDenali 3.6L 6,8,"2021 GMC Acadia AT4 3.6L, V6, Asp N, VIN S, De...",Thermostat,2021 GMC AcadiaDenali 3.6L 6Thermostat,THERMOSTAT,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,NaN,NaN,NaN
860,2893,2021 Jeep Renegade80thAnniversaryAWD 1.3L 4,6,"2021 Jeep Renegade 80th Anniversary 1.3L, L4, ...",Thermostat,2021 Jeep Renegade80thAnniversaryAWD 1.3L 4The...,THERMOSTAT,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,NaN,NaN,NaN
861,2924,2021 Toyota SiennaLimitedAWD 2.5L 4,20,"2021 Toyota Avalon Hybrid Limited 2.5L, L4, FU...",Thermostat,2021 Toyota SiennaLimitedAWD 2.5L 4Thermostat,THERMOSTAT,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,NaN,NaN,NaN

In [57]:
lmax=df4["Sl.No"].max()
lmin=df4["Sl.No"].min()

print( lmin,lmax)

7 2924

In [58]:
df_NOinfo=df3[df3['OE Part Number']=="No Information Available In Identifix"]
df_NOinfo

KeyError: 'OE Part Number'

In [59]:
df_NOPartNo=df3[df3['OE Part Number']=="No Part Number"]
dfNOinfo_cleaned=pd.merge(df_NOPartNo,df4[['Keys']].drop_duplicates(), on='Keys',how='outer',indicator=True)
#dfNOinfo_cleaned=dfNOinfo_cleaned[dfNOinfo_cleaned['_merge']=='left_only']
dfNOinfo_cleaned

KeyError: 'OE Part Number'

In [62]:
OFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\Identifix\Identifix_Product_Links\PartNumberDetails\Temp_Container'

with pd.ExcelWriter(OFolder+f'\VIO-Identifix_General_OEPartNumberWNotes_Filler_{lmin}_{lmax}_new.xlsx') as writer:  
    df4.to_excel(writer,index=False, sheet_name='OEPartNumber')
    #df_NOinfo.to_excel(writer,index=False, sheet_name='No Info Parts')
    #df_NOPartNo.to_excel(writer,index=False, sheet_name='No PartNumber')
    #dfNOinfo_cleaned.to_excel(writer,index=False, sheet_name='No PartNumber_cleaned')
    df3.to_excel(writer,index=False, sheet_name='Raw')

# Archived Codes

for i in tqdm(range(8700,len(df2))):
    #print(i)
    try:
        if len(df2['Product_Specific_Link'][i])>1:
            driver.get(df2['Product_Specific_Link'][i])
            sleep(2)
            plist=[]
            try:                   
                for exp in range (100):
                    try:
                        WebDriverWait(driver, 1).until(EC.presence_of_element_located((By.CLASS_NAME,'dynatree-ico-cf'))).click()
                    except:
                        break
                sbs=wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,f'[title="{Product}"]')))
                for w in range(len(sbs)):
                    sbs[w].click()
                es=WebDriverWait(driver, 15).until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,'[class="part-labor-table"]')))
                sleep(1)
                for e in es:
                    if 'Mfg.' in e.text:
                        if "$" in e.text:
                            ft=e.text.split('\n')
                            for f in ft:
                                if "$" in f:
                                    plist.append(f.split(' ')[0])
                            df2.at[i,"OE Part Number"]=list(set(plist))
                        else:
                            df2.at[i,"OE Part Number"]="['"+e.text.split('\n')[4]+"']"
                    else:
                        df2.at[i,"OE Part Number"]="No Part Number"
            except:
                df2.loc[i,"OE Part Number"]="No Information Available In Identifix"
            
            clear_output(wait=True)
            print(i,"|",df2.loc[i,"Selected Model"],"- ", df2.loc[i,"OE Part Number"])
    except:
        pass
        pass