# Library calling

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib.parse import unquote
from selenium.webdriver.support.ui import Select
import pandas as pd
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import datetime 
import warnings
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
from IPython.display import clear_output

# Defining the Product Information and Location

In [3]:
df1=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\98_Misc_Codes\VIO_Data.xlsx",sheet_name="Raw")

In [16]:
df1=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\15_Fuel_Injector\Identifix_Extraction.xlsx")

In [17]:
df1

,Keys1,Links,VehCount
0,"1985 Ford F-150 Base 5.0L, V8, GAS, VIN N, Des...",LinkAvailable,998
1,"1985 Ford F-150 XL 5.0L, V8, GAS, VIN N, Des -...",LinkAvailable,1038
2,"1985 Ford F-150 XLT Lariat 5.0L, V8, GAS, VIN ...",LinkAvailable,1036
3,"1985 Ford F-250 Base 6.9L, V8, DIESEL, VIN 1, ...",LinkAvailable,687
4,"1985 Ford F-250 XL 6.9L, V8, DIESEL, VIN 1, De...",LinkAvailable,654
...,...,...,...
8401,"2023 Ford Transit-350 HD XL 3.5L, V6, GAS, VIN...",LinktobeExtracted,37
8402,"2023 Ford Transit-350 HD XLT 3.5L, V6, GAS, VI...",LinktobeExtracted,31
8403,"2023 Ford Transit-350 PTV 3.5L, V6, GAS, VIN G...",LinktobeExtracted,76
8404,"2023 Ford Transit-350 XL 3.5L, V6, GAS, VIN G,...",LinktobeExtracted,90
8405,"2023 Ford Transit-350 XLT 3.5L, V6, GAS, VIN G...",LinktobeExtracted,80

In [20]:
df2=df1[['Keys1','VehCount','Links']]
df2=df2.groupby(['Keys1'],as_index=False)['VehCount'].sum()
df2=df2.sort_values(by='VehCount', ascending=False, inplace=False).reset_index()
del df2['index']
df2['TotalRun']=df2['VehCount'].cumsum()
df2['%Coverage']=(df2['TotalRun']/df2['VehCount'].sum())*100

In [15]:
df2

,Keys1,VehCount,TotalRun,%Coverage
0,"2018 Chevrolet Silverado 1500 LT 5.3L, V8, GAS...",154653,154653,0.425071
1,"2015 Chevrolet Silverado 1500 LT 5.3L, V8, GAS...",112580,267233,0.734502
2,"2014 Chevrolet Silverado 1500 LT 5.3L, V8, FLE...",101121,368354,1.012438
3,"2015 Jeep Grand Cherokee Limited 3.6L, V6, FLE...",100719,469073,1.289268
4,"2007 Honda Odyssey EX-L 3.5L, V6, GAS, VIN -, ...",98821,567894,1.560882
...,...,...,...,...
8401,"1984 Ford E-350 Econoline Club Wagon XL 6.9L, ...",1,36382883,99.999989
8402,1988 Ford E-250 Econoline Club Wagon Custom 4....,1,36382884,99.999992
8403,"2016 Chevrolet Silverado 3500 HD WT 6.0L, V8, ...",1,36382885,99.999995
8404,"2016 Chevrolet Express 4500 Base 6.0L, V8, CNG...",1,36382886,99.999997
8405,"2019 GMC Savana 4500 Base 6.0L, V8, CNG, VIN B...",1,36382887,100.000000

In [8]:
df95=df2[df2['%Coverage']<=95.1]

In [43]:
df95=df1[df1['Links']=='LinktobeExtracted'].reset_index()

In [44]:
df95.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4037 entries, 0 to 4036
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     4037 non-null   int64
 1   Keys1     4037 non-null   object
 2   Links     4037 non-null   object
 3   VehCount  4037 non-null   int64
dtypes: int64(2), object(2)
memory usage: 126.3+ KB

In [ ]:
# Keys=df95["Keys1"]
# print(Keys[0], len(Keys) )

#  Setting Webdriver and Website Specific Information

In [9]:
cols=["Sl.No"]
df= pd.DataFrame(columns=cols)

In [28]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.maximize_window()
wait=WebDriverWait(driver, 10)
driver.get('https://dh.identifix.com/id/login')
sleep(1)
username_field = driver.find_element(By.ID,'UserName')  
username_field.send_keys('constantina')
sleep(1)

password_field = driver.find_element(By.ID,'Password')  
password_field.send_keys('constantina01')
sleep(1)

Login = driver.find_element(By.ID,'Login')  
Login.click()
sleep(1)

home=driver.current_url
driver.get(home)

There was an error managing chrome (error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: An existing connection was forcibly closed by the remote host. (os error 10054)); using driver found in the cache

# Defining the Dataframe and Extracting the data into the Dataframe

# Extracting the Final Link

In [45]:
df95

,index,Keys1,Links,VehCount
0,4369,1983 Ford E-250 Econoline Club Wagon Custom 6....,LinktobeExtracted,7
1,4370,"1983 Ford E-250 Econoline Club Wagon XL 6.9L, ...",LinktobeExtracted,7
2,4371,"1983 Ford E-350 Econoline Club Wagon XL 6.9L, ...",LinktobeExtracted,2
3,4372,"1983 Ford E-350 Econoline Custom 6.9L, V8, DIE...",LinktobeExtracted,37
4,4373,"1983 Ford E-350 Econoline XL 6.9L, V8, DIESEL,...",LinktobeExtracted,37
...,...,...,...,...
4032,8401,"2023 Ford Transit-350 HD XL 3.5L, V6, GAS, VIN...",LinktobeExtracted,37
4033,8402,"2023 Ford Transit-350 HD XLT 3.5L, V6, GAS, VI...",LinktobeExtracted,31
4034,8403,"2023 Ford Transit-350 PTV 3.5L, V6, GAS, VIN G...",LinktobeExtracted,76
4035,8404,"2023 Ford Transit-350 XL 3.5L, V6, GAS, VIN G,...",LinktobeExtracted,90
4036,8405,"2023 Ford Transit-350 XLT 3.5L, V6, GAS, VIN G...",LinktobeExtracted,80

In [4]:
df95=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\Identifix\Identifix_Product_Links\VIO-Identifix_ProductLinks-Filler.xlsx")

In [8]:
df95["%Coverage"][26000]

'Filled'

In [9]:
df95=df95[df95['%Coverage']=="Filled"]

In [14]:
df95=df95.reset_index()

In [51]:
driver.get(home)

In [8]:
df95=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\101_Other_Support\OEPartNumber\OE part extract.xlsx",sheet_name="Output")
df95

,part_type_description,OE Part Number,Keys
0,Fuel Tank Sending Unit,NaN,1985 Ford Bronco 5.8L 8
1,Fuel Tank Sending Unit,NaN,1985 Ford F150 4.9L 6
2,Fuel Tank Sending Unit,NaN,1985 Ford F150 5.0L 8
3,Fuel Tank Sending Unit,NaN,1985 Ford F150 5.8L 8
4,Fuel Tank Sending Unit,NaN,1985 Ford F150 4.9L 6
...,...,...,...
3040,Water Pump,NaN,2023 Toyota CamrySE 2.5L 4
3041,Water Pump,NaN,2023 Toyota CorollaLE 2.0L 4
3042,Water Pump,NaN,2023 Toyota RAV4LEAWD 2.5L 4
3043,Thermostat,NaN,2023 Toyota RAV4XLEPremium 2.5L 4
3044,Water Pump,NaN,2023 Toyota RAV4XLEPremium 2.5L 4

In [32]:
from tqdm import tqdm
for i in tqdm(range(2429,len(df95))):
    driver.get(home)
    print(i," items completed- currently Running: ", df95.loc[i,'Keys'])
    #print(round(df95.loc[i,'%Coverage'],2),"% Covered", i," items completed- currently Running: ", df95.loc[i,'Keys1'] )
    sleep(4)
    typebox=wait.until(EC.presence_of_element_located((By.ID,"CreateVehicle_suggest_box")))
    #typebox.click()
    boxed=df95.loc[i,'Keys']
    df.loc[i,"Sl.No"]=i
    df.loc[i,'Keys']=df95.loc[i,'Keys']
    #df.loc[i,'VehCount']=df95.loc[i,'VehCount']
    #df.loc[i,'%Coverage']=df95.loc[i,'%Coverage']
    #print(boxed)
    sleep(4)
    typebox.send_keys(boxed)
    o2=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME,"ui-menu-item")))
    #print("number of vehicle: ", len(o2))
    df.loc[i,"Number of Variants"]=len(o2)
    if(len(o2))<=1:
        o=wait.until(EC.presence_of_element_located((By.CLASS_NAME,"ui-menu-item")))
        o.click()
    else:
        o2[0].click()
    try:
        sleep(1) 
        selected_text = wait.until(EC.presence_of_element_located((By.CLASS_NAME,"vehicle-info"))).text    
        df.loc[i,'Selected Model']=selected_text
        df.loc[i,'Baselink']=driver.current_url    
        # #driver.get(home)
        # NewV = wait.until(EC.presence_of_element_located((By.XPATH, "//div[@class='sub-menu-item right-sub-menu-item']/a[@title='New Vehicle']")))
        # NewV.click()
    except:
        driver.get(home)
    clear_output(wait=True)

100%|██████████| 616/616 [2:58:11<00:00, 17.36s/it]

In [33]:
df.info()
df.tail()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3045 entries, 0 to 3044
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Sl.No               3045 non-null   object
 1   Keys                3045 non-null   object
 2   Number of Variants  3045 non-null   float64
 3   Selected Model      3036 non-null   object
 4   Baselink            3036 non-null   object
dtypes: float64(1), object(4)
memory usage: 207.3+ KB

,Sl.No,Keys,Number of Variants,Selected Model,Baselink
3040,3040,2023 Toyota CamrySE 2.5L 4,20.0,NaN,NaN
3041,3041,2023 Toyota CorollaLE 2.0L 4,20.0,"2023 Toyota Corolla 2.0L, L4, Gas, Des M20A-FK...",https://dh.identifix.com/VehicleHome/Index?ROI...
3042,3042,2023 Toyota RAV4LEAWD 2.5L 4,20.0,NaN,NaN
3043,3043,2023 Toyota RAV4XLEPremium 2.5L 4,20.0,NaN,NaN
3044,3044,2023 Toyota RAV4XLEPremium 2.5L 4,20.0,NaN,NaN

# Post Processing Data

In [34]:
len(df)

3045

In [35]:
Product_Code1="Serpentine+Belt"

In [36]:
df["Generic_Product_Search_Link"]=df['Baselink'].str.replace("VehicleHome", "MotorPartsLabor").str.replace("VSM=2&LocationId=13", f"LocationId=4&WorkflowPath=5&AssetTypeId=19&Tab=TabMotorPartAndLabor&MenuItemId=19&LinkName=See%2520more...#DocAssets=19&KW={Product_Code1}&VETId=8&STMode=1&Paging=&position=0&IsCat=0&AssetCategoryId=&SMode=4")
df.head()

,Sl.No,Keys,Number of Variants,Selected Model,Baselink,Generic_Product_Search_Link
0,0,1985 Ford Bronco 5.8L 8,6.0,"1985 Ford Bronco Custom 5.8L, V8, VIN G, 16V, ...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...
1,1,1985 Ford F150 4.9L 6,6.0,"1985 Ford F-150 4.9L, L6, Gas, VIN Y, 12V, Car...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...
2,2,1985 Ford F150 5.0L 8,6.0,"1985 Ford F-150 5.0L, V8, Gas, VIN F, 16V, Car...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...
3,3,1985 Ford F150 5.8L 8,6.0,"1985 Ford F-150 5.8L, V8, Gas, VIN G, 16V, Car...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...
4,4,1985 Ford F150 4.9L 6,6.0,"1985 Ford F-150 4.9L, L6, Gas, VIN Y, 12V, Car...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...

In [37]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3045 entries, 0 to 3044
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sl.No                        3045 non-null   object
 1   Keys                         3045 non-null   object
 2   Number of Variants           3045 non-null   float64
 3   Selected Model               3036 non-null   object
 4   Baselink                     3036 non-null   object
 5   Generic_Product_Search_Link  3036 non-null   object
dtypes: float64(1), object(5)
memory usage: 231.1+ KB

In [40]:
OFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\Identifix\Identifix_Product_Links'

with pd.ExcelWriter(OFolder+'\VIO-Identifix_ProductLinks-extra12.xlsx') as writer:  
    df.to_excel(writer,index=False, sheet_name='Links')
    # df95.to_excel(writer,index=True, sheet_name='Coverage95')
    # df2.to_excel(writer,index=True, sheet_name='CoverageFull')

In [39]:
with pd.ExcelWriter(OFolder+'\VIO-Identifix_Coverage_Full_NewRequest.xlsx') as writer:  
    df2.to_excel(writer,index=True, sheet_name='CoverageFull')

NameError: name 'df2' is not defined

# Archived Codes

In [ ]:
for i in range(283,len(Keys)):
    typebox=driver.find_element(By.ID,"CreateVehicle_suggest_box")
    #typebox.click()
    boxed=Keys[i]
    #print(boxed)
    sleep(2)
    typebox.send_keys(boxed)
    sleep(1)
    o2=driver.find_elements(By.CLASS_NAME,"ui-menu-item")
    print("number of vehicle: ", len(o2))
    if(len(o2))<=1:
        o=driver.find_element(By.CLASS_NAME,"ui-menu-item")
        o.click()
    else:
        o2[1].click()
    sleep(3)
    selected_text = WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.CLASS_NAME,"vehicle-info"))).text
    try:        
        OEMRepair = WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.XPATH,"//li/a[text()='OEM Repair/Replace']")))
        # WebDriverWait(driver, max_wait_time).until(OEMRepair)
        sleep(1)
        OEMRepair.click()
        sleep(1)
        #IGCoil = driver.find_element(By.ID,"tb-search-box")
        IGCoil = WebDriverWait(driver, 40).until(EC.element_to_be_clickable(( By.ID,"tb-search-box")))
        element_to_click = WebDriverWait(driver, 40).until(EC.element_to_be_clickable(( By.ID,"bt-search")))
        #WebDriverWait(driver, max_wait_time).until(IGCoil)
        # Click the element
        sleep(5)
        IGCoil.send_keys("Ignition Coil(s)")
        sleep(1)
        #search = WebDriverWait(driver, 40).until(EC.presence_of_element_located((By.ID,"bt-search")))
        element_to_click.click()
        sleep(2)
        #WebDriverWait(driver, max_wait_time).until(search)       
        # expand=driver.find_element(By.CLASS_NAME,"expand-collapse-icon")
        # WebDriverWait(driver, max_wait_time).until(expand)
        # expand.click()
        # link2=driver.find_element(By.CLASS_NAME,'document-link')
        # Page2=link2.get_attribute('href')
        # actions=ActionChains(driver).send_keys(Keys.ARROW_DOWN).send_keys(Keys.ENTER)
        # actions.perform()
        NewV = WebDriverWait(driver, 40).until(EC.presence_of_element_located((By.XPATH, "//div[@class='sub-menu-item right-sub-menu-item']/a[@title='New Vehicle']")))
        df.loc[i,'Selected Model']=selected_text
        df.loc[i,'Link']=driver.current_url
        print(i+1)
        NewV.click()
    except:
        NewV = WebDriverWait(driver, 40).until(EC.presence_of_element_located((By.XPATH, "//div[@class='sub-menu-item right-sub-menu-item']/a[@title='New Vehicle']")))
        df.loc[i,'Selected Model']=selected_text
        df.loc[i,'Link']="No OEM Repair"
        NewV.click()
    # df.loc[row,"Link2"]=Page2
    #print("Number of items: ",i+1)