In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib.parse import unquote
from selenium.webdriver.support.ui import Select
import pandas as pd
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import datetime 
import numpy as np
import warnings
from tqdm import tqdm
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
from IPython.display import clear_output

In [2]:
ReplacePC="Serpentine+Belt"

In [3]:
# Product="CABLE SET" #"SERPENTINE BELT"
# ProductCode="Thermostat" #"Serpentine+Belt"

In [4]:
# df=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\Identifix\Identifix_Product_Links\VIO-Identifix_ProductLinks-Filler.xlsx")
df=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\101_Other_Support\OEPartNumber\VIO-Identifix_ProductLinks-extra12.xlsx",sheet_name='Links')
df.tail()

,Sl.No,Keys,Number of Variants,Selected Model,Baselink,Generic_Product_Search_Link,ProductCode,Product
2770,3037,2023 Toyota CamryLE 2.5L 4,20,NaN,NaN,NaN,Water+Pump,WATER PUMP
2771,3039,2023 Toyota CamrySE 2.5L 4,20,NaN,NaN,NaN,Water+Pump,WATER PUMP
2772,3041,2023 Toyota CorollaLE 2.0L 4,20,"2023 Toyota Corolla 2.0L, L4, Gas, Des M20A-FK...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Water+Pump,WATER PUMP
2773,3042,2023 Toyota RAV4LEAWD 2.5L 4,20,NaN,NaN,NaN,Water+Pump,WATER PUMP
2774,3043,2023 Toyota RAV4XLEPremium 2.5L 4,20,NaN,NaN,NaN,Water+Pump,WATER PUMP

In [5]:
df2=df.dropna(subset='Generic_Product_Search_Link')
#df2=df2[(df2["Inclusion"]=="Include") & (df2['%Coverage']=="New")]
df2=df2.reset_index()

In [6]:
del df2['index']

In [7]:
df2.shape

(2766, 8)

In [8]:
for i in range(len(df2)):
    df2.loc[i,"Product_Specific_Link"]=df2['Generic_Product_Search_Link'][i].replace(ReplacePC,df2['ProductCode'][i])
del df2["Generic_Product_Search_Link"]
del df2['Baselink']

In [9]:
#df2=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\Identifix\Ignition_Coil_Tempload.xlsx")

In [10]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2766 entries, 0 to 2765
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Sl.No                  2766 non-null   int64
 1   Keys                   2766 non-null   object
 2   Number of Variants     2766 non-null   int64
 3   Selected Model         2766 non-null   object
 4   ProductCode            2766 non-null   object
 5   Product                2766 non-null   object
 6   Product_Specific_Link  2766 non-null   object
dtypes: int64(2), object(5)
memory usage: 151.4+ KB

In [11]:
print(df2['Product_Specific_Link'][5])

https://dh.identifix.com/MotorPartsLabor/Index?ROID=377276961&VID=2068330&LocationId=4&WorkflowPath=5&AssetTypeId=19&Tab=TabMotorPartAndLabor&MenuItemId=19&LinkName=See%2520more...#DocAssets=19&KW=Fuel+Tank+Sending+Unit&VETId=8&STMode=1&Paging=&position=0&IsCat=0&AssetCategoryId=&SMode=4

In [311]:
cols=["Sl.No"]
df3= pd.DataFrame(columns=cols)
count3=0

In [289]:
path= 'C://chromedriver.exe'

driver=webdriver.Chrome()
driver.maximize_window()
wait=WebDriverWait(driver, 5)
driver.get('https://dh.identifix.com/id/login')
sleep(1)



username_field = driver.find_element(By.ID,'UserName')  
username_field.send_keys('constantina')
sleep(1)

password_field = driver.find_element(By.ID,'Password')  
password_field.send_keys('constantina01')
sleep(1)

Login = driver.find_element(By.ID,'Login')  
Login.click()

sleep(2)
home=driver.current_url

In [14]:
driver.get(home)

In [15]:
driver.get(df2['Product_Specific_Link'][4])

In [140]:
df2=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\101_Other_Support\OEPartNumber\Missing_Info.xlsx")
df2.tail()

,Sl.No,Keys,Number of Variants,Selected Model,ProductCode,Combined_Key,Product,Product_Specific_Link
2026,2027,2022 Toyota SiennaXLE 2.5L 4,20,"2022 Toyota Avalon Hybrid Limited 2.5L, L4, FU...",Water+Pump,2022 Toyota SiennaXLE 2.5L 4Water Pump,WATER PUMP,https://dh.identifix.com/MotorPartsLabor/Index...
2027,2028,2023 Dodge RAM3500Laramie 6.7L 6,20,"2023 Dodge Challenger GT 3.6L, V6, Asp N, VIN ...",Water+Pump,2023 Dodge RAM3500Laramie 6.7L 6Water Pump,WATER PUMP,https://dh.identifix.com/MotorPartsLabor/Index...
2028,2029,2023 Hyundai TucsonLimited 2.5L 4,20,"2023 Hyundai Santa Cruz Limited 2.5L, L4, Asp ...",Water+Pump,2023 Hyundai TucsonLimited 2.5L 4Water Pump,WATER PUMP,https://dh.identifix.com/MotorPartsLabor/Index...
2029,2030,2023 Jeep GrandCherokeeSummit 3.6L 6,20,"2023 Jeep Gladiator Freedom 3.6L, V6, Gas, Asp...",Water+Pump,2023 Jeep GrandCherokeeSummit 3.6L 6Water Pump,WATER PUMP,https://dh.identifix.com/MotorPartsLabor/Index...
2030,2031,2023 Toyota CorollaLE 2.0L 4,20,"2023 Toyota Corolla 2.0L, L4, Gas, Des M20A-FK...",Water+Pump,2023 Toyota CorollaLE 2.0L 4Water Pump,WATER PUMP,https://dh.identifix.com/MotorPartsLabor/Index...

In [141]:
df2

,Sl.No,Keys,Number of Variants,Selected Model,ProductCode,Combined_Key,Product,Product_Specific_Link
0,1,1995 MercedesBenz E300D 3.0L 6,1,"1995 Mercedes-Benz E300 3.0L, L6, USA/Canada",Fuel+Pump,1995 MercedesBenz E300D 3.0L 6Fuel Pump,FUEL PUMP,https://dh.identifix.com/MotorPartsLabor/Index...
1,2,2017 AlfaRomeo Giulia 2.0L 4,2,"2017 Alfa Romeo Giulia 2.0L, L4, VIN N, Des EC...",Fuel+Pump,2017 AlfaRomeo Giulia 2.0L 4Fuel Pump,FUEL PUMP,https://dh.identifix.com/MotorPartsLabor/Index...
2,3,2018 AlfaRomeo Stelvio 2.0L 4,2,"2018 Alfa Romeo Stelvio 2.0L, L4, VIN N, Des E...",Fuel+Pump,2018 AlfaRomeo Stelvio 2.0L 4Fuel Pump,FUEL PUMP,https://dh.identifix.com/MotorPartsLabor/Index...
3,4,2019 Chevrolet Silverado1500LT 2.7L 4,3,"2019 Chevrolet Silverado 1500 LT 2.7L, L4, Gas...",Fuel+Pump,2019 Chevrolet Silverado1500LT 2.7L 4Fuel Pump,FUEL PUMP,https://dh.identifix.com/MotorPartsLabor/Index...
4,5,2023 Ford Explorer 2.3L 4,5,"2023 Ford Explorer 2.3L, L4, Gas, Asp T, VIN H...",Fuel+Pump,2023 Ford Explorer 2.3L 4Fuel Pump,FUEL PUMP,https://dh.identifix.com/MotorPartsLabor/Index...
...,...,...,...,...,...,...,...,...
2026,2027,2022 Toyota SiennaXLE 2.5L 4,20,"2022 Toyota Avalon Hybrid Limited 2.5L, L4, FU...",Water+Pump,2022 Toyota SiennaXLE 2.5L 4Water Pump,WATER PUMP,https://dh.identifix.com/MotorPartsLabor/Index...
2027,2028,2023 Dodge RAM3500Laramie 6.7L 6,20,"2023 Dodge Challenger GT 3.6L, V6, Asp N, VIN ...",Water+Pump,2023 Dodge RAM3500Laramie 6.7L 6Water Pump,WATER PUMP,https://dh.identifix.com/MotorPartsLabor/Index...
2028,2029,2023 Hyundai TucsonLimited 2.5L 4,20,"2023 Hyundai Santa Cruz Limited 2.5L, L4, Asp ...",Water+Pump,2023 Hyundai TucsonLimited 2.5L 4Water Pump,WATER PUMP,https://dh.identifix.com/MotorPartsLabor/Index...
2029,2030,2023 Jeep GrandCherokeeSummit 3.6L 6,20,"2023 Jeep Gladiator Freedom 3.6L, V6, Gas, Asp...",Water+Pump,2023 Jeep GrandCherokeeSummit 3.6L 6Water Pump,WATER PUMP,https://dh.identifix.com/MotorPartsLabor/Index...
2030,2031,2023 Toyota CorollaLE 2.0L 4,20,"2023 Toyota Corolla 2.0L, L4, Gas, Des M20A-FK...",Water+Pump,2023 Toyota CorollaLE 2.0L 4Water Pump,WATER PUMP,https://dh.identifix.com/MotorPartsLabor/Index...

In [160]:
driver.get(df2['Product_Specific_Link'][11])

In [296]:
Product="WATER PUMP"

In [309]:
sbs=wait.until(EC.presence_of_all_elements_located((By.XPATH, f"//a[@class= 'dynatree-title document-link' and @title='{Product}']")))
print(len(sbs))
for w in range(len(sbs)):
    if w>=0:
        sbs[w].click()

1

In [290]:
for exp in range (100):
    try:
        WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.CLASS_NAME,'dynatree-ico-cf'))).click()
    except:
        break

In [313]:
for i in tqdm(range(1540,len(df2))):#len(df2)
    try:
        if len(df2['Product_Specific_Link'][i])>1:
            driver.get(df2['Product_Specific_Link'][i])
            Product=df2['Product'][i]
            sleep(2)
            try:                   
                print("Running element #",i,"|",df2.loc[i,"Selected Model"])
                print("__________________________________________________________________________________________")
                sleep(1)
                for exp in range (100):
                    try:
                        WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.CLASS_NAME,'dynatree-ico-cf'))).click()
                    except:
                        break
                sleep(1)
                sbs=wait.until(EC.presence_of_all_elements_located((By.XPATH, f"//a[@class= 'dynatree-title document-link' and @title='{Product}']")))
                print(len(sbs))
                for w in range(len(sbs)):
                    if w>=0:
                        sbs[w].click()
                    else:
                        pass
                sleep(3)
                es=WebDriverWait(driver, 15).until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,'[class="part-labor-table"]')))
                for j in range(len(es)):
                    if 'Mfg.' in es[j].text:
                        if "$" in es[j].text:
                            pns=es[j].text.count("$")
                            #print(pns)
                            for pn in range(pns):
                                Appnote=es[j].text.split("$")[pn].split("\n")[-2]
                                PN=es[j].text.split("$")[pn].split("\n")[-1]
                                Price=float(es[j].text.split("$")[pn+1].replace(",","").split("\n")[0])
                                print(Appnote,"|",PN,"|",Price)
                                # df3.loc[count3,"Sl.No"]=df2['Sl.No'][i]
                                df3.loc[count3,"Combined_Key"]=df2['Combined_Key'][i]
                                df3.loc[count3,"Links"]=df2['Product_Specific_Link'][i]
                                df3.loc[count3,"Appln Notes"]=Appnote
                                df3.loc[count3,"OE Part Number"]=PN
                                df3.loc[count3,"Price [$]"]=Price
                                count3=count3+1
                        else:
                            df3.loc[count3,"Sl.No"]=df2['Sl.No'][i]
                            df3.loc[count3,"Combined_Key"]=df2['Combined_Key'][i]
                            df3.loc[count3,"Links"]=df2['Product_Specific_Link'][i]
                            PN=es[j].text.split('\n')[4]
                            Appnote=es[j].text.split('\n')[3]
                            df3.loc[count3,"Appln Notes"]=Appnote
                            df3.loc[count3,"OE Part Number"]=PN
                            count3=count3+1
                    else:
                        df3.loc[count3,"Sl.No"]=df2['Sl.No'][i]
                        df3.loc[count3,"Combined_Key"]=df2['Combined_Key'][i]
                        df3.loc[count3,"Links"]=df2['Product_Specific_Link'][i]
                        df3.loc[count3,"OE Part Number"]="No Part Number"
                        count3=count3+1
            except:
                df3.loc[count3,"Sl.No"]=df2['Sl.No'][i]
                df3.loc[count3,"Combined_Key"]=df2['Combined_Key'][i]
                df3.loc[count3,"Links"]=df2['Product_Specific_Link'][i]
                df3.loc[count3,"OE Part Number"]="No Information Available In Identifix"
                count3=count3+1
            print("__________________________________________________________________________________________")            
            print(i,"|",df3.loc[count3-1,"OE Part Number"],df2.loc[i,"Selected Model"])
            clear_output(wait=True)
            sleep(1)
    except:
        pass
        pass

100%|██████████| 491/491 [1:41:26<00:00, 12.40s/it]

In [314]:
df3

,Sl.No,Combined_Key,Links,OE Part Number,Appln Notes,Price [$]
0,1541,2023 Hyundai VenueSE 1.6L 4Thermostat,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN
1,1542,2008 BMW M3 4.0L 8Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,No Part Number,NaN,NaN
2,NaN,2008 BMW M3 4.0L 8Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,11517586925,w/o Turbo,643.00
3,NaN,2008 BMW M3 4.0L 8Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,11517838201,M Series,552.31
4,1543,2010 BMW M3 4.0L 8Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,No Part Number,NaN,NaN
...,...,...,...,...,...,...
1352,2027,2022 Toyota SiennaXLE 2.5L 4Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN
1353,2028,2023 Dodge RAM3500Laramie 6.7L 6Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN
1354,2029,2023 Hyundai TucsonLimited 2.5L 4Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN
1355,2030,2023 Jeep GrandCherokeeSummit 3.6L 6Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN
1356,2031,2023 Toyota CorollaLE 2.0L 4Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN

In [315]:
lmax=df3["Sl.No"].max()
lmin=df3["Sl.No"].min()

print( lmin,lmax)

1541 2031

In [316]:
df_NOinfo=df3[df3['OE Part Number']=="No Information Available In Identifix"]
df_NOinfo

,Sl.No,Combined_Key,Links,OE Part Number,Appln Notes,Price [$]
0,1541,2023 Hyundai VenueSE 1.6L 4Thermostat,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN
100,1580,2017 Genesis G90Ultimate 5.0L 8Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN
108,1584,2018 BMW 530e 2.0L 4Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN
178,1609,2015 Kia K900V8Luxury 5.0L 8Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN
219,1624,2020 Hyundai SonataSE 2.5L 4Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN
...,...,...,...,...,...,...
1352,2027,2022 Toyota SiennaXLE 2.5L 4Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN
1353,2028,2023 Dodge RAM3500Laramie 6.7L 6Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN
1354,2029,2023 Hyundai TucsonLimited 2.5L 4Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN
1355,2030,2023 Jeep GrandCherokeeSummit 3.6L 6Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN
1356,2031,2023 Toyota CorollaLE 2.0L 4Water Pump,https://dh.identifix.com/MotorPartsLabor/Index...,No Information Available In Identifix,NaN,NaN

In [282]:
df_NOPartNo=df3[df3['OE Part Number']=="No Part Number"]
dfNOinfo_cleaned=pd.merge(df_NOPartNo,df4[['Keys']].drop_duplicates(), on='Keys',how='outer',indicator=True)
#dfNOinfo_cleaned=dfNOinfo_cleaned[dfNOinfo_cleaned['_merge']=='left_only']
dfNOinfo_cleaned

NameError: name 'df4' is not defined

In [317]:
OFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\Identifix\Identifix_Product_Links\PartNumberDetails\Temp_Container'

with pd.ExcelWriter(OFolder+f'\VIO-Identifix_General_OEPartNumberWNotes_Filler_{lmin}_{lmax}_new.xlsx') as writer:  
    #df4.to_excel(writer,index=False, sheet_name='OEPartNumber')
    #df_NOinfo.to_excel(writer,index=False, sheet_name='No Info Parts')
    #df_NOPartNo.to_excel(writer,index=False, sheet_name='No PartNumber')
    #dfNOinfo_cleaned.to_excel(writer,index=False, sheet_name='No PartNumber_cleaned')
    df3.to_excel(writer,index=False, sheet_name='Raw')

# Archived Codes

for i in tqdm(range(8700,len(df2))):
    #print(i)
    try:
        if len(df2['Product_Specific_Link'][i])>1:
            driver.get(df2['Product_Specific_Link'][i])
            sleep(2)
            plist=[]
            try:                   
                for exp in range (100):
                    try:
                        WebDriverWait(driver, 1).until(EC.presence_of_element_located((By.CLASS_NAME,'dynatree-ico-cf'))).click()
                    except:
                        break
                sbs=wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,f'[title="{Product}"]')))
                for w in range(len(sbs)):
                    sbs[w].click()
                es=WebDriverWait(driver, 15).until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,'[class="part-labor-table"]')))
                sleep(1)
                for e in es:
                    if 'Mfg.' in e.text:
                        if "$" in e.text:
                            ft=e.text.split('\n')
                            for f in ft:
                                if "$" in f:
                                    plist.append(f.split(' ')[0])
                            df2.at[i,"OE Part Number"]=list(set(plist))
                        else:
                            df2.at[i,"OE Part Number"]="['"+e.text.split('\n')[4]+"']"
                    else:
                        df2.at[i,"OE Part Number"]="No Part Number"
            except:
                df2.loc[i,"OE Part Number"]="No Information Available In Identifix"
            
            clear_output(wait=True)
            print(i,"|",df2.loc[i,"Selected Model"],"- ", df2.loc[i,"OE Part Number"])
    except:
        pass
        pass