In [19]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib.parse import unquote
from selenium.webdriver.support.ui import Select
import pandas as pd
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import datetime 
import numpy as np
import warnings
from tqdm import tqdm
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
from IPython.display import clear_output

In [20]:
ReplacePC="Serpentine+Belt"

In [21]:
Product="CABLE SET" #"SERPENTINE BELT"
ProductCode="Cable+Set" #"Serpentine+Belt"

In [22]:
df=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\Identifix\Identifix_Product_Links\VIO-Identifix_ProductLinks-Filler.xlsx")
df.tail()

,Sl.No,Keys,Year,Make,Model,Sub Model,B Type,#Cyl,Litre,Fuel,YMMSMVXLF,VehCount,%Coverage,Number of Variants,Selected Model,Baselink,Generic_Product_Search_Link,Inclusion
26427,26427,"1998 Chevrolet P30 Base 7.4L, V8, GAS, VIN J, ...",1998,Chevrolet,P30,Base,V,8,7.4,GAS,1998ChevroletP30BaseV87.4GAS,25,Extra-2,1,"1998 Chevrolet P30 7.4L, V8, Gas, Asp N, VIN J...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Exclude
26428,26428,"1996 GMC Savana 1500 SLE 4.3L, V6, GAS, VIN W,...",1996,GMC,Savana 1500,SLE,V,6,4.3,GAS,1996GMCSavana 1500SLEV64.3GAS,17,Extra-2,1,"1996 GMC Savana 1500 Sle 4.3L, V6, VIN W, Des ...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Exclude
26429,26429,"1998 GMC C2500 Suburban Base 5.7L, V8, GAS, VI...",1998,GMC,C2500 Suburban,Base,V,8,5.7,GAS,1998GMCC2500 SuburbanBaseV85.7GAS,17,Extra-2,3,"1998 GMC C2500 Suburban 5.7L, V8, Gas, Asp N, ...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Exclude
26430,26430,"2005 GMC Savana 2500 SLE 4.3L, V6, GAS, VIN X,...",2005,GMC,Savana 2500,SLE,V,6,4.3,GAS,2005GMCSavana 2500SLEV64.3GAS,28,Extra-2,1,"2005 GMC Savana 2500 Sle 4.3L, V6, Gas, VIN X,...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Exclude
26431,26431,"2000 Isuzu Hombre XS 4.3L, V6, GAS, VIN W, Des...",2000,Isuzu,Hombre,XS,V,6,4.3,GAS,2000IsuzuHombreXSV64.3GAS,24,Extra-2,1,"2000 Isuzu Hombre XS 4.3L, V6, Gas, VIN W, Des...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Exclude

In [23]:
df2=df.dropna(subset='Generic_Product_Search_Link')
#df2=df2[(df2["Inclusion"]=="Include")]
#df2=df2[(df2["Inclusion"]=="Include") & (df2['%Coverage']=="Extra-2")]
df2=df2.reset_index()

In [24]:
del df2['index']

In [25]:
df2.shape

(25453, 18)

In [26]:
df2

,Sl.No,Keys,Year,Make,Model,Sub Model,B Type,#Cyl,Litre,Fuel,YMMSMVXLF,VehCount,%Coverage,Number of Variants,Selected Model,Baselink,Generic_Product_Search_Link,Inclusion
0,0,"2018 Chevrolet Silverado 1500 LT 5.3L, V8, GAS...",2018,Chevrolet,Silverado 1500,LT,V,8,5.3,GAS,2018ChevroletSilverado 1500LTV85.3GAS,319649,0.101695,1,"2018 Chevrolet Silverado 1500 LT 5.3L, V8, Gas...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Exclude
1,1,"2012 Honda Civic LX 1.8L, L4, GAS, VIN -, Des ...",2012,Honda,Civic,LX,L,4,1.8,GAS,2012HondaCivicLXL41.8GAS,310821,0.200582,1,"2012 Honda Civic LX 1.8L, L4, Gas, Des R18Z1, ...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Exclude
2,2,"2015 Chevrolet Silverado 1500 LT 5.3L, V8, GAS...",2015,Chevrolet,Silverado 1500,LT,V,8,5.3,GAS,2015ChevroletSilverado 1500LTV85.3GAS,292757,0.293722,1,"2015 Chevrolet Silverado 1500 LT 5.3L, V8, Gas...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Exclude
3,3,"2014 Chevrolet Silverado 1500 LT 5.3L, V8, FLE...",2014,Chevrolet,Silverado 1500,LT,V,8,5.3,FLEX,2014ChevroletSilverado 1500LTV85.3FLEX,266009,0.378352,1,"2014 Chevrolet Silverado 1500 LT 5.3L, V8, Fle...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Exclude
4,4,"2017 Chevrolet Silverado 1500 LT 5.3L, V8, GAS...",2017,Chevrolet,Silverado 1500,LT,V,8,5.3,GAS,2017ChevroletSilverado 1500LTV85.3GAS,258814,0.460693,1,"2017 Chevrolet Silverado 1500 LT 5.3L, V8, Gas...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Exclude
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25448,26427,"1998 Chevrolet P30 Base 7.4L, V8, GAS, VIN J, ...",1998,Chevrolet,P30,Base,V,8,7.4,GAS,1998ChevroletP30BaseV87.4GAS,25,Extra-2,1,"1998 Chevrolet P30 7.4L, V8, Gas, Asp N, VIN J...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Exclude
25449,26428,"1996 GMC Savana 1500 SLE 4.3L, V6, GAS, VIN W,...",1996,GMC,Savana 1500,SLE,V,6,4.3,GAS,1996GMCSavana 1500SLEV64.3GAS,17,Extra-2,1,"1996 GMC Savana 1500 Sle 4.3L, V6, VIN W, Des ...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Exclude
25450,26429,"1998 GMC C2500 Suburban Base 5.7L, V8, GAS, VI...",1998,GMC,C2500 Suburban,Base,V,8,5.7,GAS,1998GMCC2500 SuburbanBaseV85.7GAS,17,Extra-2,3,"1998 GMC C2500 Suburban 5.7L, V8, Gas, Asp N, ...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Exclude
25451,26430,"2005 GMC Savana 2500 SLE 4.3L, V6, GAS, VIN X,...",2005,GMC,Savana 2500,SLE,V,6,4.3,GAS,2005GMCSavana 2500SLEV64.3GAS,28,Extra-2,1,"2005 GMC Savana 2500 Sle 4.3L, V6, Gas, VIN X,...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Exclude
25452,26431,"2000 Isuzu Hombre XS 4.3L, V6, GAS, VIN W, Des...",2000,Isuzu,Hombre,XS,V,6,4.3,GAS,2000IsuzuHombreXSV64.3GAS,24,Extra-2,1,"2000 Isuzu Hombre XS 4.3L, V6, Gas, VIN W, Des...",https://dh.identifix.com/VehicleHome/Index?ROI...,https://dh.identifix.com/MotorPartsLabor/Index...,Exclude

In [27]:
for i in range(len(df2)):
    df2.loc[i,"Product_Specific_Link"]=df2['Generic_Product_Search_Link'][i].replace(ReplacePC,ProductCode)
del df2["Generic_Product_Search_Link"]
del df2['Baselink']

In [10]:
#df2=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\Identifix\Ignition_Coil_Tempload.xlsx")

In [28]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25453 entries, 0 to 25452
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Sl.No                  25453 non-null  int64
 1   Keys                   25453 non-null  object
 2   Year                   25453 non-null  int64
 3   Make                   25453 non-null  object
 4   Model                  25453 non-null  object
 5   Sub Model              25453 non-null  object
 6   B Type                 25453 non-null  object
 7   #Cyl                   25453 non-null  object
 8   Litre                  25453 non-null  float64
 9   Fuel                   25453 non-null  object
 10  YMMSMVXLF              25453 non-null  object
 11  VehCount               25453 non-null  int64
 12  %Coverage              25453 non-null  object
 13  Number of Variants     25453 non-null  int64
 14  Selected Model         25453 non-null  object
 15  Inclusion              25453 non-null  object
 16  Product_Specific_Link  25453 non-null  object
dtypes: float64(1), int64(4), object(12)
memory usage: 3.3+ MB

In [29]:
df2

,Sl.No,Keys,Year,Make,Model,Sub Model,B Type,#Cyl,Litre,Fuel,YMMSMVXLF,VehCount,%Coverage,Number of Variants,Selected Model,Inclusion,Product_Specific_Link
0,0,"2018 Chevrolet Silverado 1500 LT 5.3L, V8, GAS...",2018,Chevrolet,Silverado 1500,LT,V,8,5.3,GAS,2018ChevroletSilverado 1500LTV85.3GAS,319649,0.101695,1,"2018 Chevrolet Silverado 1500 LT 5.3L, V8, Gas...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...
1,1,"2012 Honda Civic LX 1.8L, L4, GAS, VIN -, Des ...",2012,Honda,Civic,LX,L,4,1.8,GAS,2012HondaCivicLXL41.8GAS,310821,0.200582,1,"2012 Honda Civic LX 1.8L, L4, Gas, Des R18Z1, ...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...
2,2,"2015 Chevrolet Silverado 1500 LT 5.3L, V8, GAS...",2015,Chevrolet,Silverado 1500,LT,V,8,5.3,GAS,2015ChevroletSilverado 1500LTV85.3GAS,292757,0.293722,1,"2015 Chevrolet Silverado 1500 LT 5.3L, V8, Gas...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...
3,3,"2014 Chevrolet Silverado 1500 LT 5.3L, V8, FLE...",2014,Chevrolet,Silverado 1500,LT,V,8,5.3,FLEX,2014ChevroletSilverado 1500LTV85.3FLEX,266009,0.378352,1,"2014 Chevrolet Silverado 1500 LT 5.3L, V8, Fle...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...
4,4,"2017 Chevrolet Silverado 1500 LT 5.3L, V8, GAS...",2017,Chevrolet,Silverado 1500,LT,V,8,5.3,GAS,2017ChevroletSilverado 1500LTV85.3GAS,258814,0.460693,1,"2017 Chevrolet Silverado 1500 LT 5.3L, V8, Gas...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25448,26427,"1998 Chevrolet P30 Base 7.4L, V8, GAS, VIN J, ...",1998,Chevrolet,P30,Base,V,8,7.4,GAS,1998ChevroletP30BaseV87.4GAS,25,Extra-2,1,"1998 Chevrolet P30 7.4L, V8, Gas, Asp N, VIN J...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...
25449,26428,"1996 GMC Savana 1500 SLE 4.3L, V6, GAS, VIN W,...",1996,GMC,Savana 1500,SLE,V,6,4.3,GAS,1996GMCSavana 1500SLEV64.3GAS,17,Extra-2,1,"1996 GMC Savana 1500 Sle 4.3L, V6, VIN W, Des ...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...
25450,26429,"1998 GMC C2500 Suburban Base 5.7L, V8, GAS, VI...",1998,GMC,C2500 Suburban,Base,V,8,5.7,GAS,1998GMCC2500 SuburbanBaseV85.7GAS,17,Extra-2,3,"1998 GMC C2500 Suburban 5.7L, V8, Gas, Asp N, ...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...
25451,26430,"2005 GMC Savana 2500 SLE 4.3L, V6, GAS, VIN X,...",2005,GMC,Savana 2500,SLE,V,6,4.3,GAS,2005GMCSavana 2500SLEV64.3GAS,28,Extra-2,1,"2005 GMC Savana 2500 Sle 4.3L, V6, Gas, VIN X,...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...
25452,26431,"2000 Isuzu Hombre XS 4.3L, V6, GAS, VIN W, Des...",2000,Isuzu,Hombre,XS,V,6,4.3,GAS,2000IsuzuHombreXSV64.3GAS,24,Extra-2,1,"2000 Isuzu Hombre XS 4.3L, V6, Gas, VIN W, Des...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...

In [30]:
print(df2['Product_Specific_Link'][5])

https://dh.identifix.com/MotorPartsLabor/Index?ROID=371965162&VID=2401576&LocationId=4&WorkflowPath=5&AssetTypeId=19&Tab=TabMotorPartAndLabor&MenuItemId=19&LinkName=See%2520more...#DocAssets=19&KW=Cable+Set&VETId=8&STMode=1&Paging=&position=0&IsCat=0&AssetCategoryId=&SMode=4

In [31]:
cols=["Sl.No"]
df3= pd.DataFrame(columns=cols)
count3=0

In [69]:
path= 'C://chromedriver.exe'

driver=webdriver.Chrome()
driver.maximize_window()
wait=WebDriverWait(driver, 5)
driver.get('https://dh.identifix.com/id/login')
sleep(1)



username_field = driver.find_element(By.ID,'UserName')  
username_field.send_keys('constantina')
sleep(1)

password_field = driver.find_element(By.ID,'Password')  
password_field.send_keys('constantina01')
sleep(1)

Login = driver.find_element(By.ID,'Login')  
Login.click()

sleep(2)
home=driver.current_url

In [ ]:
driver.get(home)

In [15]:
driver.get(df2['Product_Specific_Link'][5])

In [70]:
for i in tqdm(range(24367,len(df2))):
    try:
        if len(df2['Product_Specific_Link'][i])>1:
            driver.get(df2['Product_Specific_Link'][i])
            sleep(2)
            try:                   
                print("Running element #",i,"|",df2.loc[i,"Selected Model"])
                print("__________________________________________________________________________________________")
                sleep(2)
                for exp in range (100):
                    try:
                        WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.CLASS_NAME,'dynatree-ico-cf'))).click()
                    except:
                        break
                sleep(2)
                sbs=wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,f'[title="{Product}"]')))
                for w in range(len(sbs)):
                    sbs[w].click()
                sleep(1)
                es=WebDriverWait(driver, 15).until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,'[class="part-labor-table"]')))
                for e in es:
                    if 'Mfg.' in e.text:
                        if "$" in e.text:
                            pns=e.text.count("$")
                            #print(pns)
                            for pn in range(pns):
                                Appnote=e.text.split("$")[pn].split("\n")[-2]
                                PN=e.text.split("$")[pn].split("\n")[-1]
                                Price=float(e.text.split("$")[pn+1].split("\n")[0])
                                print(Appnote,"|",PN,"|",Price)
                                df3.loc[count3,"Sl.No"]=df2['Sl.No'][i]
                                df3.loc[count3,"Keys"]=df2['Keys'][i]
                                df3.loc[count3,"Links"]=df2['Product_Specific_Link'][i]
                                df3.loc[count3,"Appln Notes"]=Appnote
                                df3.loc[count3,"OE Part Number"]=PN
                                df3.loc[count3,"Price [$]"]=Price
                                count3=count3+1
                        else:
                            df3.loc[count3,"Sl.No"]=df2['Sl.No'][i]
                            df3.loc[count3,"Keys"]=df2['Keys'][i]
                            df3.loc[count3,"Links"]=df2['Product_Specific_Link'][i]
                            df3.loc[count3,"OE Part Number"]="['"+e.text.split('\n')[4]+"']"
                            count3=count3+1
                    else:
                        df3.loc[count3,"Sl.No"]=df2['Sl.No'][i]
                        df3.loc[count3,"Keys"]=df2['Keys'][i]
                        df3.loc[count3,"Links"]=df2['Product_Specific_Link'][i]
                        df3.loc[count3,"OE Part Number"]="No Part Number"
                        count3=count3+1
            except:
                df3.loc[count3,"Sl.No"]=df2['Sl.No'][i]
                df3.loc[count3,"Keys"]=df2['Keys'][i]
                df3.loc[count3,"Links"]=df2['Product_Specific_Link'][i]
                df3.loc[count3,"OE Part Number"]="No Information Available In Identifix"
                count3=count3+1
            print("__________________________________________________________________________________________")            
            print(i,"|",df2.loc[i,"Selected Model"],df3.loc[count3-1,"OE Part Number"])
            sleep(2)
            clear_output(wait=True)
    except:
        pass
        pass

100%|██████████| 1086/1086 [4:42:31<00:00, 15.61s/it]

In [71]:
df3=pd.merge(df2,df3[['Keys','Appln Notes','OE Part Number','Price [$]']], on='Keys',how='outer')
df3.tail()

,Sl.No,Keys,Year,Make,Model,Sub Model,B Type,#Cyl,Litre,Fuel,YMMSMVXLF,VehCount,%Coverage,Number of Variants,Selected Model,Inclusion,Product_Specific_Link,Appln Notes,OE Part Number,Price [$]
37019,26430,"2005 GMC Savana 2500 SLE 4.3L, V6, GAS, VIN X,...",2005,GMC,Savana 2500,SLE,V,6,4.3,GAS,2005GMCSavana 2500SLEV64.3GAS,28,Extra-2,1,"2005 GMC Savana 2500 Sle 4.3L, V6, Gas, VIN X,...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,#6,12173581,27.74
37020,26430,"2005 GMC Savana 2500 SLE 4.3L, V6, GAS, VIN X,...",2005,GMC,Savana 2500,SLE,V,6,4.3,GAS,2005GMCSavana 2500SLEV64.3GAS,28,Extra-2,1,"2005 GMC Savana 2500 Sle 4.3L, V6, Gas, VIN X,...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,NaN,NaN
37021,26431,"2000 Isuzu Hombre XS 4.3L, V6, GAS, VIN W, Des...",2000,Isuzu,Hombre,XS,V,6,4.3,GAS,2000IsuzuHombreXSV64.3GAS,24,Extra-2,1,"2000 Isuzu Hombre XS 4.3L, V6, Gas, VIN W, Des...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN
37022,26431,"2000 Isuzu Hombre XS 4.3L, V6, GAS, VIN W, Des...",2000,Isuzu,Hombre,XS,V,6,4.3,GAS,2000IsuzuHombreXSV64.3GAS,24,Extra-2,1,"2000 Isuzu Hombre XS 4.3L, V6, Gas, VIN W, Des...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,4.3L,8889842650,185.02
37023,26431,"2000 Isuzu Hombre XS 4.3L, V6, GAS, VIN W, Des...",2000,Isuzu,Hombre,XS,V,6,4.3,GAS,2000IsuzuHombreXSV64.3GAS,24,Extra-2,1,"2000 Isuzu Hombre XS 4.3L, V6, Gas, VIN W, Des...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,NaN,NaN

In [72]:
df4=df3.dropna(subset="Appln Notes")
df4

,Sl.No,Keys,Year,Make,Model,Sub Model,B Type,#Cyl,Litre,Fuel,YMMSMVXLF,VehCount,%Coverage,Number of Variants,Selected Model,Inclusion,Product_Specific_Link,Appln Notes,OE Part Number,Price [$]
13777,14010,"2002 Ford Taurus SES 3.0L, V6, GAS, VIN S, Des...",2002,Ford,Taurus,SES,V,6,3.0,GAS,2002FordTaurusSESV63.0GAS,4801,85.257335,1,"2002 Ford Taurus SES 3.0L, V6, Gas, VIN S, 24V...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,DOHC,1U2Z12259HA,88.36
13778,14010,"2002 Ford Taurus SES 3.0L, V6, GAS, VIN S, Des...",2002,Ford,Taurus,SES,V,6,3.0,GAS,2002FordTaurusSESV63.0GAS,4801,85.257335,1,"2002 Ford Taurus SES 3.0L, V6, Gas, VIN S, 24V...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,OHV,4F1Z12259AA,78.91
13806,14031,"2006 Chevrolet Tahoe Base 5.3L, V8, FLEX, VIN ...",2006,Chevrolet,Tahoe,Base,V,8,5.3,FLEX,2006ChevroletTahoeBaseV85.3FLEX,4787,85.289361,4,"2006 Chevrolet Tahoe 5.3L, V8, Flex, VIN Z, De...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,Coil Stamped 12558693,19351572,147.50
13807,14031,"2006 Chevrolet Tahoe Base 5.3L, V8, FLEX, VIN ...",2006,Chevrolet,Tahoe,Base,V,8,5.3,FLEX,2006ChevroletTahoeBaseV85.3FLEX,4787,85.289361,4,"2006 Chevrolet Tahoe 5.3L, V8, Flex, VIN Z, De...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,Coil Stamped 19005218,19351571,132.68
13808,14031,"2006 Chevrolet Tahoe Base 5.3L, V8, FLEX, VIN ...",2006,Chevrolet,Tahoe,Base,V,8,5.3,FLEX,2006ChevroletTahoeBaseV85.3FLEX,4787,85.289361,4,"2006 Chevrolet Tahoe 5.3L, V8, Flex, VIN Z, De...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,Coil Stamped 19005218,19417606,132.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37016,26430,"2005 GMC Savana 2500 SLE 4.3L, V6, GAS, VIN X,...",2005,GMC,Savana 2500,SLE,V,6,4.3,GAS,2005GMCSavana 2500SLEV64.3GAS,28,Extra-2,1,"2005 GMC Savana 2500 Sle 4.3L, V6, Gas, VIN X,...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,#3,19351563,36.83
37017,26430,"2005 GMC Savana 2500 SLE 4.3L, V6, GAS, VIN X,...",2005,GMC,Savana 2500,SLE,V,6,4.3,GAS,2005GMCSavana 2500SLEV64.3GAS,28,Extra-2,1,"2005 GMC Savana 2500 Sle 4.3L, V6, Gas, VIN X,...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,#4,19351562,36.83
37018,26430,"2005 GMC Savana 2500 SLE 4.3L, V6, GAS, VIN X,...",2005,GMC,Savana 2500,SLE,V,6,4.3,GAS,2005GMCSavana 2500SLEV64.3GAS,28,Extra-2,1,"2005 GMC Savana 2500 Sle 4.3L, V6, Gas, VIN X,...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,#5,19351564,40.73
37019,26430,"2005 GMC Savana 2500 SLE 4.3L, V6, GAS, VIN X,...",2005,GMC,Savana 2500,SLE,V,6,4.3,GAS,2005GMCSavana 2500SLEV64.3GAS,28,Extra-2,1,"2005 GMC Savana 2500 Sle 4.3L, V6, Gas, VIN X,...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,#6,12173581,27.74
37022,26431,"2000 Isuzu Hombre XS 4.3L, V6, GAS, VIN W, Des...",2000,Isuzu,Hombre,XS,V,6,4.3,GAS,2000IsuzuHombreXSV64.3GAS,24,Extra-2,1,"2000 Isuzu Hombre XS 4.3L, V6, Gas, VIN W, Des...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,4.3L,8889842650,185.02

In [73]:
lmax=df4["Sl.No"].max()
lmin=df4["Sl.No"].min()

print( lmin,lmax)

14010 26431

In [74]:
df_NOinfo=df3[df3['OE Part Number']=="No Information Available In Identifix"]
df_NOinfo

,Sl.No,Keys,Year,Make,Model,Sub Model,B Type,#Cyl,Litre,Fuel,YMMSMVXLF,VehCount,%Coverage,Number of Variants,Selected Model,Inclusion,Product_Specific_Link,Appln Notes,OE Part Number,Price [$]
13762,13998,"2015 Volkswagen Jetta TDI S 2.0L, L4, DIESEL, ...",2015,Volkswagen,Jetta,TDI S,L,4,2.0,DIESEL,2015VolkswagenJettaTDI SL42.0DIESEL,4810,85.238986,1,"2015 Volkswagen Jetta TDI S 2.0L, L4, Diesel, ...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Information Available In Identifix,NaN
13763,13999,"2011 BMW 128i Base 3.0L, L6, GAS, VIN -, Des N...",2011,BMW,128i,Base,L,6,3.0,GAS,2011BMW128iBaseL63.0GAS,4809,85.240516,1,"2011 BMW 128I 3.0L, L6, Des N52B30A, USA/Canada",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Information Available In Identifix,NaN
13764,14000,"1997 Jeep Grand Cherokee Laredo 5.2L, V8, GAS,...",1997,Jeep,Grand Cherokee,Laredo,V,8,5.2,GAS,1997JeepGrand CherokeeLaredoV85.2GAS,4809,85.242046,1,"1997 Jeep Grand Cherokee Laredo 5.2L, V8, VIN ...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Information Available In Identifix,NaN
13765,14001,"2022 Mazda MX-5 Miata Grand Touring 2.0L, L4, ...",2022,Mazda,MX-5 Miata,Grand Touring,L,4,2.0,GAS,2022MazdaMX-5 MiataGrand TouringL42.0GAS,4809,85.243576,2,"2022 Mazda MX-5 Miata Grand Touring 2.0L, L4, USA",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Information Available In Identifix,NaN
13766,14002,"2014 Audi S4 Premium Plus 3.0L, V6, GAS, VIN -...",2014,Audi,S4,Premium Plus,V,6,3.0,GAS,2014AudiS4Premium PlusV63.0GAS,4808,85.245106,1,"2014 Audi S4 Premium Plus 3.0L, V6, Des CTUB, USA",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Information Available In Identifix,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36992,26423,"1999 Chevrolet P30 Base 7.4L, V8, GAS, VIN J, ...",1999,Chevrolet,P30,Base,V,8,7.4,GAS,1999ChevroletP30BaseV87.4GAS,31,Extra-2,1,"1999 Chevrolet P30 7.4L, V8, Gas, Asp N, VIN J...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Information Available In Identifix,NaN
37002,26425,"1996 GMC Savana 2500 Base 4.3L, V6, GAS, VIN W...",1996,GMC,Savana 2500,Base,V,6,4.3,GAS,1996GMCSavana 2500BaseV64.3GAS,34,Extra-2,1,"1996 GMC Savana 2500 4.3L, V6, Gas, Asp N, VIN...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Information Available In Identifix,NaN
37004,26426,"1996 GMC Savana 2500 Base 5.0L, V8, GAS, VIN M...",1996,GMC,Savana 2500,Base,V,8,5.0,GAS,1996GMCSavana 2500BaseV85.0GAS,34,Extra-2,2,"1996 GMC Savana 2500 5.0L, V8, Gas, Asp N, VIN...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Information Available In Identifix,NaN
37006,26427,"1998 Chevrolet P30 Base 7.4L, V8, GAS, VIN J, ...",1998,Chevrolet,P30,Base,V,8,7.4,GAS,1998ChevroletP30BaseV87.4GAS,25,Extra-2,1,"1998 Chevrolet P30 7.4L, V8, Gas, Asp N, VIN J...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Information Available In Identifix,NaN
37008,26428,"1996 GMC Savana 1500 SLE 4.3L, V6, GAS, VIN W,...",1996,GMC,Savana 1500,SLE,V,6,4.3,GAS,1996GMCSavana 1500SLEV64.3GAS,17,Extra-2,1,"1996 GMC Savana 1500 Sle 4.3L, V6, VIN W, Des ...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Information Available In Identifix,NaN

In [75]:
df_NOPartNo=df3[df3['OE Part Number']=="No Part Number"]
dfNOinfo_cleaned=pd.merge(df_NOPartNo,df4[['Keys']].drop_duplicates(), on='Keys',how='outer',indicator=True)
#dfNOinfo_cleaned=dfNOinfo_cleaned[dfNOinfo_cleaned['_merge']=='left_only']
dfNOinfo_cleaned

,Sl.No,Keys,Year,Make,Model,Sub Model,B Type,#Cyl,Litre,Fuel,...,VehCount,%Coverage,Number of Variants,Selected Model,Inclusion,Product_Specific_Link,Appln Notes,OE Part Number,Price [$],_merge
0,14005.0,"2019 Chevrolet Express 4500 Base 6.0L, V8, FLE...",2019.0,Chevrolet,Express 4500,Base,V,8,6.0,FLEX,...,4806.0,85.249694,1.0,"2019 Chevrolet Express 4500 6.0L, V8, Flex, VI...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,left_only
1,14007.0,"1998 Dodge Dakota Sport 5.2L, V8, GAS, VIN Y, ...",1998.0,Dodge,Dakota,Sport,V,8,5.2,GAS,...,4804.0,85.252751,1.0,"1998 Dodge Dakota Sport 5.2L, V8, VIN Y, 16V, ...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,left_only
2,14007.0,"1998 Dodge Dakota Sport 5.2L, V8, GAS, VIN Y, ...",1998.0,Dodge,Dakota,Sport,V,8,5.2,GAS,...,4804.0,85.252751,1.0,"1998 Dodge Dakota Sport 5.2L, V8, VIN Y, 16V, ...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,left_only
3,14008.0,"2016 GMC Savana 3500 Base 4.8L, V8, FLEX, VIN ...",2016.0,GMC,Savana 3500,Base,V,8,4.8,FLEX,...,4804.0,85.254279,3.0,"2016 GMC Savana 3500 4.8L, V8, Flex, Asp N, VI...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,left_only
4,14008.0,"2016 GMC Savana 3500 Base 4.8L, V8, FLEX, VIN ...",2016.0,GMC,Savana 3500,Base,V,8,4.8,FLEX,...,4804.0,85.254279,3.0,"2016 GMC Savana 3500 4.8L, V8, Flex, Asp N, VI...",Exclude,https://dh.identifix.com/MotorPartsLabor/Index...,NaN,No Part Number,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4065,NaN,"1998 Pontiac Grand Am SE 3.1L, V6, GAS, VIN M,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
4066,NaN,"1998 Chevrolet Express 1500 LS 5.0L, V8, GAS, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
4067,NaN,"1998 Chevrolet Express 1500 LS 4.3L, V6, GAS, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
4068,NaN,"1998 GMC Savana 1500 Base 5.0L, V8, GAS, VIN M...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
4069,NaN,"1999 GMC Savana 1500 Base 5.0L, V8, GAS, VIN M...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only

In [76]:
OFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\Identifix\Identifix_Product_Links\PartNumberDetails\Temp_Container'

with pd.ExcelWriter(OFolder+f'\VIO-Identifix_{Product}_OEPartNumberWNotes_Filler_{lmin}_{lmax}.xlsx') as writer:  
    df4.to_excel(writer,index=False, sheet_name='OEPartNumber')
    df_NOinfo.to_excel(writer,index=False, sheet_name='No Info Parts')
    #df_NOPartNo.to_excel(writer,index=False, sheet_name='No PartNumber')
    dfNOinfo_cleaned.to_excel(writer,index=False, sheet_name='No PartNumber_cleaned')
    df3.to_excel(writer,index=False, sheet_name='Raw')

# Archived Codes

for i in tqdm(range(8700,len(df2))):
    #print(i)
    try:
        if len(df2['Product_Specific_Link'][i])>1:
            driver.get(df2['Product_Specific_Link'][i])
            sleep(2)
            plist=[]
            try:                   
                for exp in range (100):
                    try:
                        WebDriverWait(driver, 1).until(EC.presence_of_element_located((By.CLASS_NAME,'dynatree-ico-cf'))).click()
                    except:
                        break
                sbs=wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,f'[title="{Product}"]')))
                for w in range(len(sbs)):
                    sbs[w].click()
                es=WebDriverWait(driver, 15).until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,'[class="part-labor-table"]')))
                sleep(1)
                for e in es:
                    if 'Mfg.' in e.text:
                        if "$" in e.text:
                            ft=e.text.split('\n')
                            for f in ft:
                                if "$" in f:
                                    plist.append(f.split(' ')[0])
                            df2.at[i,"OE Part Number"]=list(set(plist))
                        else:
                            df2.at[i,"OE Part Number"]="['"+e.text.split('\n')[4]+"']"
                    else:
                        df2.at[i,"OE Part Number"]="No Part Number"
            except:
                df2.loc[i,"OE Part Number"]="No Information Available In Identifix"
            
            clear_output(wait=True)
            print(i,"|",df2.loc[i,"Selected Model"],"- ", df2.loc[i,"OE Part Number"])
    except:
        pass
        pass