# 1. Library calling

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
import warnings
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

In [2]:
links=["https://www.amazon.com/dp/B08CDJMQT1",
"https://www.amazon.com/dp/B08L479JGJ",
"https://www.amazon.com/dp/B08K8P5RVH",
"https://www.amazon.com/dp/B07XC3D1BP",
"https://www.amazon.com/dp/B08L71GBX7",
"https://www.amazon.com/dp/B07XVQ3KL5",
"https://www.amazon.com/dp/B071JR7DXV",
"https://www.amazon.com/dp/B07XVRX7HW",
"https://www.amazon.com/dp/B09GJZVKKJ",
"https://www.amazon.com/dp/B07V31TZT5",
"https://www.amazon.com/dp/B0BTMXZJF3",
"https://www.amazon.com/dp/B00M80BXNS",
"https://www.amazon.com/dp/B0CL37ZXV5",
"https://www.amazon.com/dp/B0C4QBJWGL",
"https://www.amazon.com/dp/B0CJMHWGJ3",
"https://www.amazon.com/dp/B0B5G2XJ5B",
"https://www.amazon.com/dp/B07XVR31XH",
"https://www.amazon.com/dp/B0CHVM7MLP",
"https://www.amazon.com/dp/B07XLV7BB2",
"https://www.amazon.com/dp/B08V47XFFR",
"https://www.amazon.com/dp/B0CQTDG6ML",
"https://www.amazon.com/dp/B0CQTJ61N2",
"https://www.amazon.com/dp/B08L44X6NZ",
"https://www.amazon.com/dp/B08CR7YF7Y",
"https://www.amazon.com/dp/B07GNLG19C",
"https://www.amazon.com/dp/B07Y28ZYSN",
"https://www.amazon.com/dp/B0CHYJWFWB",
"https://www.amazon.com/dp/B08V4GNKH9",
"https://www.amazon.com/dp/B08R75FT8J",
"https://www.amazon.com/dp/B0BPJ1F2JY",
"https://www.amazon.com/dp/B08P74W4HG",
"https://www.amazon.com/dp/B08CBFL8LN",
"https://www.amazon.com/dp/B0BXVP78NG",
"https://www.amazon.com/dp/B0CJPMY539",
"https://www.amazon.com/dp/B0C4H6T4RD",
"https://www.amazon.com/dp/B08L462B87",
"https://www.amazon.com/dp/B07XVQXLBK",
"https://www.amazon.com/dp/B0B5NB1G7Y",
"https://www.amazon.com/dp/B07V35Z6HF",
"https://www.amazon.com/dp/B07XVPYJZ4",
"https://www.amazon.com/dp/B0CRSWJV79",
"https://www.amazon.com/dp/B0C5HMCRT4",
"https://www.amazon.com/dp/B0CHRS3T1T",
"https://www.amazon.com/dp/B0B8M4RK6R",
"https://www.amazon.com/dp/B0CHVHNT58",
"https://www.amazon.com/dp/B09WLH4C9M",
"https://www.amazon.com/dp/B0B5G3SZ2V",
"https://www.amazon.com/dp/B0B5G2MNVL",
"https://www.amazon.com/dp/B0C4G2V4MF",
"https://www.amazon.com/dp/B0CM6CVVWS",
"https://www.amazon.com/dp/B09W9J31Q6",
"https://www.amazon.com/dp/B07JBQXYCW",
"https://www.amazon.com/dp/B0BQW6D6MM",
"https://www.amazon.com/dp/B0BZHFZZTC",
"https://www.amazon.com/dp/B071JR545L",
"https://www.amazon.com/dp/B00AN93NG6",
"https://www.amazon.com/dp/B07XVNMXQQ",
"https://www.amazon.com/dp/B08LNC24ZK",
"https://www.amazon.com/dp/B09V1T8WNW",
"https://www.amazon.com/dp/B08L8T2T21",
"https://www.amazon.com/dp/B07V33B8KB",
"https://www.amazon.com/dp/B0BRD672MY",
"https://www.amazon.com/dp/B0BXFXZVF4",
"https://www.amazon.com/dp/B0CHVMX3VJ",
"https://www.amazon.com/dp/B087R5QYN9",
"https://www.amazon.com/dp/B0CRTT931Y",
"https://www.amazon.com/dp/B0CNSZYKY7",
"https://www.amazon.com/dp/B0CHYK4XTV",
"https://www.amazon.com/dp/B0CHYJKGP1",
"https://www.amazon.com/dp/B0CRR5QYDW",
"https://www.amazon.com/dp/B0C4H6WY81",
"https://www.amazon.com/dp/B08LN941WW",
"https://www.amazon.com/dp/B0CM6DB9FL",
"https://www.amazon.com/dp/B071WNHZGZ",
"https://www.amazon.com/dp/B08V4KWD9Q",
"https://www.amazon.com/dp/B0CRTVFZXC",
"https://www.amazon.com/dp/B071WP5VNF",
"https://www.amazon.com/dp/B0B7KMYR99",
"https://www.amazon.com/dp/B0BNBJFHD8",
"https://www.amazon.com/dp/B0CBZ71ZVS",
"https://www.amazon.com/dp/B08SVW6Z4C",
"https://www.amazon.com/dp/B093K7ZM2F",
"https://www.amazon.com/dp/B07Y8V4NM9",
"https://www.amazon.com/dp/B071WNQNHY",
"https://www.amazon.com/dp/B072145V7R",
"https://www.amazon.com/dp/B0CG1M386H",
"https://www.amazon.com/dp/B07BSCQYB2",
"https://www.amazon.com/dp/B08CKPST2J",
"https://www.amazon.com/dp/B0BRD5XDVD",
"https://www.amazon.com/dp/B0CHWGGK2W",
"https://www.amazon.com/dp/B0C1P6FWD3",
"https://www.amazon.com/dp/B07V32JBS9",
"https://www.amazon.com/dp/B08K2YXXY5",
"https://www.amazon.com/dp/B08R76BVXV",
"https://www.amazon.com/dp/B0CHVXW58R",
"https://www.amazon.com/dp/B0BXVRY1NY",
"https://www.amazon.com/dp/B0CNSZG5WW",
"https://www.amazon.com/dp/B09WH47N3T",
"https://www.amazon.com/dp/B07TY41TZ3",
"https://www.amazon.com/dp/B08DL7TJ2N",
"https://www.amazon.com/dp/B09CV5P968",
"https://www.amazon.com/dp/B0BZHJQ76C",
"https://www.amazon.com/dp/B0BRD5RKKN",
"https://www.amazon.com/dp/B098N3QWYD",
"https://www.amazon.com/dp/B08LMR8H8T",
"https://www.amazon.com/dp/B0CHVKWCFN",
"https://www.amazon.com/dp/B0BRD7Y6SY",
"https://www.amazon.com/dp/B071JR33MB",
"https://www.amazon.com/dp/B07V31HQYZ",
"https://www.amazon.com/dp/B08K39BJ6X",
"https://www.amazon.com/dp/B0BNMKS29M",
"https://www.amazon.com/dp/B0BNPX4GFT",
"https://www.amazon.com/dp/B0B5G35Z8W",
"https://www.amazon.com/dp/B0B5NBXP1H",
"https://www.amazon.com/dp/B08CK8416N",
"https://www.amazon.com/dp/B0BRD51SRY",
"https://www.amazon.com/dp/B07Y28V3B3",
"https://www.amazon.com/dp/B019NUGMKE",
"https://www.amazon.com/dp/B0B5NYH1HR",
"https://www.amazon.com/dp/B07WG3L9SZ",
"https://www.amazon.com/dp/B0CHVLRZV9",
"https://www.amazon.com/dp/B0CL2Z239C",
"https://www.amazon.com/dp/B0CQTFW4R5",
"https://www.amazon.com/dp/B0CJPKPJ9T",
"https://www.amazon.com/dp/B09TW4JCNH",
"https://www.amazon.com/dp/B0B5MNB6C2",
"https://www.amazon.com/dp/B0BXFGCKLZ",
"https://www.amazon.com/dp/B08K2VGP5K",
"https://www.amazon.com/dp/B08K2NCM14",
"https://www.amazon.com/dp/B0BS2MBSHM",
"https://www.amazon.com/dp/B07XLV791S",
"https://www.amazon.com/dp/B0BHVYCMFQ",
"https://www.amazon.com/dp/B08594NBKB",
"https://www.amazon.com/dp/B09YWPGX22",
"https://www.amazon.com/dp/B08ZHLK97Q",
"https://www.amazon.com/dp/B0B8M8RGF9",
"https://www.amazon.com/dp/B0C1P3MZRX",
"https://www.amazon.com/dp/B0BPHYCDYF",
"https://www.amazon.com/dp/B0C4DQ3V2F",
"https://www.amazon.com/dp/B093KBNZKB",
"https://www.amazon.com/dp/B0BRD3VW3T",
"https://www.amazon.com/dp/B00EUZZK60",
"https://www.amazon.com/dp/B084WY8WXK",
"https://www.amazon.com/dp/B0BNBGLSBB",
"https://www.amazon.com/dp/B08LNCPN7G",
"https://www.amazon.com/dp/B0BRD4PLHZ",
"https://www.amazon.com/dp/B0CHVTVMHN",
"https://www.amazon.com/dp/B0C97HCSL1",
"https://www.amazon.com/dp/B094FLV2T8",
"https://www.amazon.com/dp/B01LVZAFLC",
"https://www.amazon.com/dp/B008DVYCNY",
"https://www.amazon.com/dp/B09GJ8TTZQ",
"https://www.amazon.com/dp/B08CK4G3MX",
"https://www.amazon.com/dp/B081S4JMG1",
"https://www.amazon.com/dp/B07XVRMC9S",
"https://www.amazon.com/dp/B0C1P71GTY",
"https://www.amazon.com/dp/B09VQ18Y7Y",
"https://www.amazon.com/dp/B0C8HLG21M",
"https://www.amazon.com/dp/B07GNMVHJT",
"https://www.amazon.com/dp/B0B7GVDRWM",
"https://www.amazon.com/dp/B07TWT6LP4",
"https://www.amazon.com/dp/B0CB7687KQ",
"https://www.amazon.com/dp/B082FMB2WB",
"https://www.amazon.com/dp/B08CKGC3YG",
"https://www.amazon.com/dp/B07XVQPMC8",
"https://www.amazon.com/dp/B07XVQ5LGS",
"https://www.amazon.com/dp/B0B7BCHWRV",
"https://www.amazon.com/dp/B0BXFZJ373",
"https://www.amazon.com/dp/B07TWZYJZ7",
"https://www.amazon.com/dp/B0CJZ9GBXP",
"https://www.amazon.com/dp/B07STF6BB9",
"https://www.amazon.com/dp/B0CL2YY861",
"https://www.amazon.com/dp/B0CL37BYFS",
"https://www.amazon.com/dp/B0C1P3CH5V",
"https://www.amazon.com/dp/B00EUZZK5Q",
"https://www.amazon.com/dp/B07BSF5L5B",
"https://www.amazon.com/dp/B07TZM81G5",
"https://www.amazon.com/dp/B08R75QSGK",
"https://www.amazon.com/dp/B0CHYL9KCH",
"https://www.amazon.com/dp/B0CT31FVCQ",
"https://www.amazon.com/dp/B07213TGBJ",
"https://www.amazon.com/dp/B0BMG2QWM9",
"https://www.amazon.com/dp/B0B5NWDLJ8",
"https://www.amazon.com/dp/B0BZHL19JY",
"https://www.amazon.com/dp/B00AN93LYK",
"https://www.amazon.com/dp/B0BD7274CW",
"https://www.amazon.com/dp/B0BRD5P3N4",
"https://www.amazon.com/dp/B08LND82SP",
"https://www.amazon.com/dp/B0CJRWLWL3",
"https://www.amazon.com/dp/B0B5G2DRVT",
"https://www.amazon.com/dp/B0B5NYNW7J",
"https://www.amazon.com/dp/B07XVR7W29",
"https://www.amazon.com/dp/B07SSD1DGZ",
"https://www.amazon.com/dp/B08R74DW8X",
"https://www.amazon.com/dp/B08HJN125S",
"https://www.amazon.com/dp/B0B8MF3HZY",
"https://www.amazon.com/dp/B0C23WY1PH",
"https://www.amazon.com/dp/B0C5T5JRJZ",
"https://www.amazon.com/dp/B08K2FZJCC",
"https://www.amazon.com/dp/B0C8HMRS77",
"https://www.amazon.com/dp/B07V31FG25",
"https://www.amazon.com/dp/B0BRD67FY4",
"https://www.amazon.com/dp/B07V2ZGFHY",
"https://www.amazon.com/dp/B0CJNRK7L6",
"https://www.amazon.com/dp/B0C1P1YNXH",
"https://www.amazon.com/dp/B00AN93MOY",
"https://www.amazon.com/dp/B0BRCMTFHK",
"https://www.amazon.com/dp/B0C4G59W9J",
"https://www.amazon.com/dp/B0CJFYK6Q6",
"https://www.amazon.com/dp/B08CK4LF8T",
"https://www.amazon.com/dp/B0BD737K1S",
"https://www.amazon.com/dp/B071WNCTSQ",
"https://www.amazon.com/dp/B07JCLB58S",
"https://www.amazon.com/dp/B07QX9X3PQ",
"https://www.amazon.com/dp/B0BD7CW6F8",
"https://www.amazon.com/dp/B08CKDSG33",
"https://www.amazon.com/dp/B07BV1YBGN",
"https://www.amazon.com/dp/B07213NPN8",
"https://www.amazon.com/dp/B0CFXYQC9H",
"https://www.amazon.com/dp/B071JR75YY",
"https://www.amazon.com/dp/B0B8MMCK8L",
"https://www.amazon.com/dp/B09HC2N1Q6",
"https://www.amazon.com/dp/B0CHYKZ82Y",
"https://www.amazon.com/dp/B08L441B6K",
"https://www.amazon.com/dp/B09KKRFWPQ",
"https://www.amazon.com/dp/B0C5BYXT9X",
"https://www.amazon.com/dp/B0CQTHTR8F",
"https://www.amazon.com/dp/B096KZ9CBP",
"https://www.amazon.com/dp/B0B5NY3DRK",
"https://www.amazon.com/dp/B0CJNNB5GP",
"https://www.amazon.com/dp/B0CL38DS43",
"https://www.amazon.com/dp/B0BRD5PGC3",
"https://www.amazon.com/dp/B08DL8QFRT",
"https://www.amazon.com/dp/B0BDDR53TX",
"https://www.amazon.com/dp/B0B8MLJZM1",
"https://www.amazon.com/dp/B0CRTVXNR6",
"https://www.amazon.com/dp/B0CNSXRV9Z",
"https://www.amazon.com/dp/B0CLL4XFTJ",
"https://www.amazon.com/dp/B071JR2VLY",
"https://www.amazon.com/dp/B0881YFMFR",
"https://www.amazon.com/dp/B09QL991BW",
"https://www.amazon.com/dp/B0C1N2S1MH",
"https://www.amazon.com/dp/B07J5CVWGD",
"https://www.amazon.com/dp/B0BS1VL8R8",
"https://www.amazon.com/dp/B09CV7K1TM",
"https://www.amazon.com/dp/B0BD72VCZF",
"https://www.amazon.com/dp/B09256P1X7",
"https://www.amazon.com/dp/B071WNGWTL",
"https://www.amazon.com/dp/B0C4H7HS8G",
"https://www.amazon.com/dp/B0BTWGVT24",
"https://www.amazon.com/dp/B0C6836MYJ",
"https://www.amazon.com/dp/B0C9WXHZTS",
"https://www.amazon.com/dp/B0CBLSN1CW",
"https://www.amazon.com/dp/B0C6G6BFXY",
"https://www.amazon.com/dp/B0BJ4BLWT6",
"https://www.amazon.com/dp/B0CM61KCQN",
"https://www.amazon.com/dp/B0C1P3VF7Q",
"https://www.amazon.com/dp/B0B8M68L31",
"https://www.amazon.com/dp/B08DL7WYMM",
"https://www.amazon.com/dp/B0C4G397VR",
"https://www.amazon.com/dp/B0BD72YB5S",
"https://www.amazon.com/dp/B071JQWWBG",
"https://www.amazon.com/dp/B072JY132D",
"https://www.amazon.com/dp/B0CJNRBGDV",
"https://www.amazon.com/dp/B09PFJXPYC",
"https://www.amazon.com/dp/B0CL9NS5P5",
"https://www.amazon.com/dp/B09GJSZHLP",
"https://www.amazon.com/dp/B08X4R8QLV",
"https://www.amazon.com/dp/B07XVSGHD6",
"https://www.amazon.com/dp/B0C8HXGJWT",
"https://www.amazon.com/dp/B0C7M3FYKY",
"https://www.amazon.com/dp/B0C1P4D3QJ",
"https://www.amazon.com/dp/B07TLG5SP6",
"https://www.amazon.com/dp/B0B8MFCCFD",
"https://www.amazon.com/dp/B09J54FLG6",
"https://www.amazon.com/dp/B082FM9KMV",
"https://www.amazon.com/dp/B087C9VHQL",
"https://www.amazon.com/dp/B0CL2YWZTC",
"https://www.amazon.com/dp/B07Y29B6GF",
"https://www.amazon.com/dp/B07Y28K7VQ",
"https://www.amazon.com/dp/B087YRG3V5",
"https://www.amazon.com/dp/B0BFJWBTH6",
"https://www.amazon.com/dp/B082FMKXMN",
"https://www.amazon.com/dp/B071WN817B",
"https://www.amazon.com/dp/B08L42KZV4",
"https://www.amazon.com/dp/B0C771GCYM",
"https://www.amazon.com/dp/B09WLHKDCD",
"https://www.amazon.com/dp/B0C4H6F3D1",
"https://www.amazon.com/dp/B09L48ZSZV",
"https://www.amazon.com/dp/B087C8QTLQ",
"https://www.amazon.com/dp/B016YKFEIW",
"https://www.amazon.com/dp/B0BHW8Z2BM",
"https://www.amazon.com/dp/B09179VK82",
"https://www.amazon.com/dp/B0C4G5J9VH",
"https://www.amazon.com/dp/B08K36KL6F",
"https://www.amazon.com/dp/B09MKHY9TP",
"https://www.amazon.com/dp/B08DL7JKBB",
"https://www.amazon.com/dp/B0BRD41NR4",
"https://www.amazon.com/dp/B0CRQPJT13",
"https://www.amazon.com/dp/B08V4B41CR",
"https://www.amazon.com/dp/B07STXVYMQ",
"https://www.amazon.com/dp/B0CL384QPL",
"https://www.amazon.com/dp/B0C4G1VSLK",
"https://www.amazon.com/dp/B0881ZDFFS",
"https://www.amazon.com/dp/B0CJ5X4257",
"https://www.amazon.com/dp/B0BF8HY577",
"https://www.amazon.com/dp/B0CHYK4SFK",
"https://www.amazon.com/dp/B0C67X31PT",
"https://www.amazon.com/dp/B00X70WR1K",
"https://www.amazon.com/dp/B01DNSZE6K",
"https://www.amazon.com/dp/B0BFJMMBYG",
"https://www.amazon.com/dp/B0BRBWBLMV",
"https://www.amazon.com/dp/B0CJNQR6GN",
"https://www.amazon.com/dp/B0BXFZ69X2",
"https://www.amazon.com/dp/B01M12DSL5",
"https://www.amazon.com/dp/B07L5ZX2YS",
"https://www.amazon.com/dp/B0CKW32TDK",
"https://www.amazon.com/dp/B019ECASTC",
"https://www.amazon.com/dp/B07VGWMY4Z",
"https://www.amazon.com/dp/B0C4D65J9F",
"https://www.amazon.com/dp/B0CH3511V6",
"https://www.amazon.com/dp/B08DL8THV1",
"https://www.amazon.com/dp/B08R775WM2",
"https://www.amazon.com/dp/B0CL2YL726",
"https://www.amazon.com/dp/B08L4328HB",
"https://www.amazon.com/dp/B08PP8GSND",
"https://www.amazon.com/dp/B0CHRN5C36",
"https://www.amazon.com/dp/B0B69GWZLV",
"https://www.amazon.com/dp/B0B2D8MCD4",
"https://www.amazon.com/dp/B01DNSXO4Y",
"https://www.amazon.com/dp/B06XDY6CXS",
"https://www.amazon.com/dp/B084WTKCFZ",
"https://www.amazon.com/dp/B01LY5BMR4",
"https://www.amazon.com/dp/B07QX91WFG",
"https://www.amazon.com/dp/B08X4RS6PM",
"https://www.amazon.com/dp/B0CHYHYW1K",
"https://www.amazon.com/dp/B071G57HKX",
"https://www.amazon.com/dp/B00AN93LY0",
"https://www.amazon.com/dp/B071WP7L9G",
"https://www.amazon.com/dp/B0BNBGK4MB",
"https://www.amazon.com/dp/B0C6G5YGCY",
"https://www.amazon.com/dp/B07XVRSWGZ",
"https://www.amazon.com/dp/B0BXFYRG54",
"https://www.amazon.com/dp/B098N4QV4Y",
"https://www.amazon.com/dp/B00X70WBZM",
"https://www.amazon.com/dp/B0BPJ3K8CH",
"https://www.amazon.com/dp/B0B5G39QWS",
"https://www.amazon.com/dp/B01BU7BS8O",
"https://www.amazon.com/dp/B09PFKH77F",
"https://www.amazon.com/dp/B0881Y15YP",
"https://www.amazon.com/dp/B0CL36FZN8",
"https://www.amazon.com/dp/B08L8T468M",
"https://www.amazon.com/dp/B09WLGRT32",
"https://www.amazon.com/dp/B071JR75VF",
"https://www.amazon.com/dp/B0925R4V5R",
"https://www.amazon.com/dp/B0CH35G2MJ",
"https://www.amazon.com/dp/B07J5SY3V1",
"https://www.amazon.com/dp/B082FM17GP",
"https://www.amazon.com/dp/B0BWSM6KYS",
"https://www.amazon.com/dp/B0CHRRM6FN",
"https://www.amazon.com/dp/B0CKWL8FKC",
"https://www.amazon.com/dp/B0B8M6GN3Q",
"https://www.amazon.com/dp/B0B8M4GLW4",
"https://www.amazon.com/dp/B0CNYLBNK5",
"https://www.amazon.com/dp/B087Z3BJTF",
"https://www.amazon.com/dp/B0B5WJZ4QG",
"https://www.amazon.com/dp/B071G58X7H",
"https://www.amazon.com/dp/B0CJNN5QBN",
"https://www.amazon.com/dp/B071WP4CHS",
"https://www.amazon.com/dp/B071WP4YWN",
"https://www.amazon.com/dp/B09L4N8J5R",
"https://www.amazon.com/dp/B0C6G6L96G",
"https://www.amazon.com/dp/B01DNSYHUY",
"https://www.amazon.com/dp/B01LY5BNRM",
"https://www.amazon.com/dp/B09WLFWNPN",
"https://www.amazon.com/dp/B09MD9SBHT",
"https://www.amazon.com/dp/B0CLY4CYND",
"https://www.amazon.com/dp/B07WX576Q3",
"https://www.amazon.com/dp/B0C9WWN54S",
"https://www.amazon.com/dp/B09PFK5DZ3",
"https://www.amazon.com/dp/B0C3B6SQQ5",
"https://www.amazon.com/dp/B08L71ZZBX",
"https://www.amazon.com/dp/B0CJNNTWVW",
"https://www.amazon.com/dp/B072145V6Q",
"https://www.amazon.com/dp/B08CKMN6M3",
"https://www.amazon.com/dp/B07P6G3GSN",
"https://www.amazon.com/dp/B088QBLXP1",
"https://www.amazon.com/dp/B00AN93M76",
"https://www.amazon.com/dp/B0CB74NVTK",
"https://www.amazon.com/dp/B0C3W8RJ26",
"https://www.amazon.com/dp/B09MD9S79C",
"https://www.amazon.com/dp/B07DCJH18W",
"https://www.amazon.com/dp/B0CB73WZTR",
"https://www.amazon.com/dp/B09WLHPQDC",
"https://www.amazon.com/dp/B0C67XCXRF",
"https://www.amazon.com/dp/B09178ZH9S",
"https://www.amazon.com/dp/B0BD6SVNW2",
"https://www.amazon.com/dp/B00X70W576",
"https://www.amazon.com/dp/B071JR1YHN",
"https://www.amazon.com/dp/B01LWIPTAJ",
"https://www.amazon.com/dp/B01DNSYCF4",
"https://www.amazon.com/dp/B07213KXY8",
"https://www.amazon.com/dp/B01DNSX7EQ",
"https://www.amazon.com/dp/B0077A835K",
"https://www.amazon.com/dp/B07V16K7X6",
"https://www.amazon.com/dp/B0C4H87HCD",
"https://www.amazon.com/dp/B071WNNP32",
"https://www.amazon.com/dp/B09PFJM37V",
"https://www.amazon.com/dp/B07XVR2J2H",
"https://www.amazon.com/dp/B0CQLY3XJS",
"https://www.amazon.com/dp/B0CL38F4BY",
"https://www.amazon.com/dp/B0BWQ84412",
"https://www.amazon.com/dp/B084Y8KK99",
"https://www.amazon.com/dp/B0BJ3CWQHW",
"https://www.amazon.com/dp/B00X70WTYU",
"https://www.amazon.com/dp/B06XHZFBHR",
"https://www.amazon.com/dp/B0C4G3PYMZ",
"https://www.amazon.com/dp/B0CFY9S5DP",
"https://www.amazon.com/dp/B088QCCHM9",
"https://www.amazon.com/dp/B0B8MRRBN5",
"https://www.amazon.com/dp/B0B8M8VNLT",
"https://www.amazon.com/dp/B01DNSZAA0",
"https://www.amazon.com/dp/B08DL8Z19X",
"https://www.amazon.com/dp/B087YV3QJM",
"https://www.amazon.com/dp/B08DKZD1F6",
"https://www.amazon.com/dp/B07QWB16BB",
"https://www.amazon.com/dp/B071WNHZH1",
"https://www.amazon.com/dp/B0CFYB3KF6",
"https://www.amazon.com/dp/B0BXFZ74XH",
"https://www.amazon.com/dp/B09V1VQYSN",
"https://www.amazon.com/dp/B09TG5X6PP",
"https://www.amazon.com/dp/B0BPJ3Y8Q6",
"https://www.amazon.com/dp/B09256LCW1",
"https://www.amazon.com/dp/B09V1VG3NV",
"https://www.amazon.com/dp/B0CJRXXCJV",
"https://www.amazon.com/dp/B071JR6Y3X",
"https://www.amazon.com/dp/B0CRR9277X",
"https://www.amazon.com/dp/B09DWQGW1J",
"https://www.amazon.com/dp/B0C4G1R745",
"https://www.amazon.com/dp/B07DCJNPYB",
"https://www.amazon.com/dp/B071JQFDRF",
"https://www.amazon.com/dp/B08L43CN7F",
"https://www.amazon.com/dp/B071WP6MRV",
"https://www.amazon.com/dp/B0CB6X4YGT",
"https://www.amazon.com/dp/B0BPJMLSN4",
"https://www.amazon.com/dp/B0C1P1DXPN",
"https://www.amazon.com/dp/B09258WWKG",
"https://www.amazon.com/dp/B08CKD45W6",
"https://www.amazon.com/dp/B0BXFX8FR3",
"https://www.amazon.com/dp/B0B8MF8XCB",
"https://www.amazon.com/dp/B072JYF7XG",
"https://www.amazon.com/dp/B09DWQ27V6",
"https://www.amazon.com/dp/B087YZCGLT",
"https://www.amazon.com/dp/B0C1P2K4XV",
"https://www.amazon.com/dp/B087LLVHLM",
"https://www.amazon.com/dp/B0B8MC8TPD",
"https://www.amazon.com/dp/B08487S94B",
"https://www.amazon.com/dp/B0BXFYZ8J8",
"https://www.amazon.com/dp/B0BPJMG54T",
"https://www.amazon.com/dp/B09MD8TCQ3",
"https://www.amazon.com/dp/B01DNSVOFK",
"https://www.amazon.com/dp/B071WP2PF2",
"https://www.amazon.com/dp/B0881Y6DVR",
"https://www.amazon.com/dp/B07XVS5BW4",
"https://www.amazon.com/dp/B0CMTP4FXT",
"https://www.amazon.com/dp/B08X4RHKSK",
"https://www.amazon.com/dp/B0C1P2YM9V",
"https://www.amazon.com/dp/B08ZH4R1F7",
"https://www.amazon.com/dp/B09KKXJBBW",
"https://www.amazon.com/dp/B08V54T262",
"https://www.amazon.com/dp/B0BXFWWWVL",
"https://www.amazon.com/dp/B0B5NYFBQD",
"https://www.amazon.com/dp/B07QZD7D8M",
"https://www.amazon.com/dp/B095CKH29H",
"https://www.amazon.com/dp/B0BZHH64P6",
"https://www.amazon.com/dp/B00AN93OHY",
"https://www.amazon.com/dp/B09H17JZZW",
"https://www.amazon.com/dp/B087YW6P3S",
"https://www.amazon.com/dp/B0BM431F7M",
"https://www.amazon.com/dp/B082FK3HVH",
"https://www.amazon.com/dp/B09257P1CX",
"https://www.amazon.com/dp/B0881Y12NB",
"https://www.amazon.com/dp/B00X70WT90",
"https://www.amazon.com/dp/B0BZV375V2",
"https://www.amazon.com/dp/B08DLDVV69",
"https://www.amazon.com/dp/B08P7657ZM",
"https://www.amazon.com/dp/B019E4EZJO",
"https://www.amazon.com/dp/B0BS1WZQBN",
"https://www.amazon.com/dp/B0CMTKK493",
"https://www.amazon.com/dp/B09QJJHXR6",
"https://www.amazon.com/dp/B0CNXK8917",
"https://www.amazon.com/dp/B07XF5FNSS",
"https://www.amazon.com/dp/B0BFJL7YFH",
"https://www.amazon.com/dp/B08V3TCKY6",
"https://www.amazon.com/dp/B01M03LYMM",
"https://www.amazon.com/dp/B07J5NRLJN",
"https://www.amazon.com/dp/B0CFXWBR7H",
"https://www.amazon.com/dp/B0BX9882T4",
"https://www.amazon.com/dp/B087YYHLN9",
"https://www.amazon.com/dp/B081P7KLQ6",
"https://www.amazon.com/dp/B082FMB2MT",
"https://www.amazon.com/dp/B0C67X11JW",
"https://www.amazon.com/dp/B087CB23M2",
"https://www.amazon.com/dp/B0BM44CT4W",
"https://www.amazon.com/dp/B0BG4TX9VJ",
"https://www.amazon.com/dp/B08L44SLQQ",
"https://www.amazon.com/dp/B06XJF9X8B",
"https://www.amazon.com/dp/B085HX5B6F",
"https://www.amazon.com/dp/B09DWRX12T",
"https://www.amazon.com/dp/B09WLFN5ZQ",
"https://www.amazon.com/dp/B08L437X4G",
"https://www.amazon.com/dp/B08DL9XMV1",
"https://www.amazon.com/dp/B07J3NY24P",
"https://www.amazon.com/dp/B07QY8Y465",
"https://www.amazon.com/dp/B0CM6D9YJ1",
"https://www.amazon.com/dp/B0BLVKJNB1",
"https://www.amazon.com/dp/B09WLHP7MP",
"https://www.amazon.com/dp/B07XVRT57R",
"https://www.amazon.com/dp/B087Z3BV1G",
"https://www.amazon.com/dp/B0CL36VYDD",
"https://www.amazon.com/dp/B0CD2XKT8Y",
"https://www.amazon.com/dp/B071G58DCB",
"https://www.amazon.com/dp/B0BTMXJZ56",
"https://www.amazon.com/dp/B07213Z3NP",
"https://www.amazon.com/dp/B01DNSVLYY",
"https://www.amazon.com/dp/B0BJ3B8SQN",
"https://www.amazon.com/dp/B0B5NW5SS5",
"https://www.amazon.com/dp/B087LYSTZQ",
"https://www.amazon.com/dp/B01ETG2AD0",
"https://www.amazon.com/dp/B09QT7SQ99",
"https://www.amazon.com/dp/B0BF3VB97W",
"https://www.amazon.com/dp/B072JXTPTB",
"https://www.amazon.com/dp/B082FMG6QK",
"https://www.amazon.com/dp/B0C5HB2C98",
"https://www.amazon.com/dp/B08TGQTKG6",
"https://www.amazon.com/dp/B0B1VW91D5",
"https://www.amazon.com/dp/B09WLJ74T6",
"https://www.amazon.com/dp/B07XVS6NR1",
"https://www.amazon.com/dp/B0CFXYHCQX",
"https://www.amazon.com/dp/B086QK9WSV",
"https://www.amazon.com/dp/B07213MXMB",
"https://www.amazon.com/dp/B09WLJ8ZNH",
"https://www.amazon.com/dp/B0BL8RPHMX",
"https://www.amazon.com/dp/B08LNC9KHM",
"https://www.amazon.com/dp/B0BX5QQW6F",
"https://www.amazon.com/dp/B0CN91B34Y",
"https://www.amazon.com/dp/B09GJJ9TMM",
"https://www.amazon.com/dp/B07TST4PSM",
"https://www.amazon.com/dp/B0C4G188R6",
"https://www.amazon.com/dp/B01DNSWZGM",
"https://www.amazon.com/dp/B071G58GP1",
"https://www.amazon.com/dp/B09V1SNGPQ",
"https://www.amazon.com/dp/B0925VBH1Z",
"https://www.amazon.com/dp/B0077A7THS",
"https://www.amazon.com/dp/B07QY97252",
"https://www.amazon.com/dp/B01DNSZ2KI",
"https://www.amazon.com/dp/B087Z2WQ1D",
"https://www.amazon.com/dp/B0BM5LYHJQ",
"https://www.amazon.com/dp/B0834P37WW",
"https://www.amazon.com/dp/B07QY8FMPT",
"https://www.amazon.com/dp/B0B8LR2WXP",
"https://www.amazon.com/dp/B01DNSWK1C",
"https://www.amazon.com/dp/B08DL9QXSD",
"https://www.amazon.com/dp/B0BJ83P6N6",
"https://www.amazon.com/dp/B004BE3FL2",
"https://www.amazon.com/dp/B0C6G717Z7",
"https://www.amazon.com/dp/B08ZHPV3DW",
"https://www.amazon.com/dp/B071WN939D",
"https://www.amazon.com/dp/B09WLHZRP2",
"https://www.amazon.com/dp/B0CH1BGH4H",
"https://www.amazon.com/dp/B09PFJL4XT",
"https://www.amazon.com/dp/B0BXFWPPVV",
"https://www.amazon.com/dp/B0CNT278CQ",
"https://www.amazon.com/dp/B07QYCHG4P",
"https://www.amazon.com/dp/B071WNYXX2",
"https://www.amazon.com/dp/B0932HV1K9",
"https://www.amazon.com/dp/B06XJPLZGR",
"https://www.amazon.com/dp/B0BX27KS55",
"https://www.amazon.com/dp/B07QV9VPKL",
"https://www.amazon.com/dp/B0CNSZ3Y9V",
"https://www.amazon.com/dp/B0834N5PTX",
"https://www.amazon.com/dp/B071G57Y8G",
"https://www.amazon.com/dp/B07LBH761C",
"https://www.amazon.com/dp/B0B8MCK59T",
"https://www.amazon.com/dp/B06XJHDZ7Z",
"https://www.amazon.com/dp/B0B2D63G5Y",
"https://www.amazon.com/dp/B071JR6M21",
"https://www.amazon.com/dp/B08J4648C3",
"https://www.amazon.com/dp/B0C4H934FP",
"https://www.amazon.com/dp/B07Y5MN19V",
"https://www.amazon.com/dp/B0BD72D47F",
"https://www.amazon.com/dp/B081P57B9L",
"https://www.amazon.com/dp/B082FKP62V",
"https://www.amazon.com/dp/B071JQWHPD",
"https://www.amazon.com/dp/B07QY9TR88",
"https://www.amazon.com/dp/B082FN3JKM",
"https://www.amazon.com/dp/B0B6CS21WN",
"https://www.amazon.com/dp/B0BPJ3LKKK",
"https://www.amazon.com/dp/B082FLZFW1",
"https://www.amazon.com/dp/B08R7484MB",
"https://www.amazon.com/dp/B08CMMN16B",
"https://www.amazon.com/dp/B0C4H6HRYN",
"https://www.amazon.com/dp/B0BTWD5VCM",
"https://www.amazon.com/dp/B08X1PDRXD",
"https://www.amazon.com/dp/B09V1QS8PR",
"https://www.amazon.com/dp/B071WNCVW1",
"https://www.amazon.com/dp/B0C8HSVY6D",
"https://www.amazon.com/dp/B019E4EZKI",
"https://www.amazon.com/dp/B0BTWG6SST",
"https://www.amazon.com/dp/B0CKV5WBFV",
"https://www.amazon.com/dp/B0B1JHYJXF",
"https://www.amazon.com/dp/B0CL2YQPH8",
"https://www.amazon.com/dp/B07DCNKBYC",
"https://www.amazon.com/dp/B09257HTQJ",
"https://www.amazon.com/dp/B07QZCJ422",
"https://www.amazon.com/dp/B08DL8QJ3M",
"https://www.amazon.com/dp/B09VPZPJXN",
"https://www.amazon.com/dp/B09TG5X6PN",
"https://www.amazon.com/dp/B082S8MBFC",
"https://www.amazon.com/dp/B0BC2DH9RQ",
"https://www.amazon.com/dp/B09QT63R63",
"https://www.amazon.com/dp/B01DNSY9RA",
"https://www.amazon.com/dp/B07JCL7BGJ",
"https://www.amazon.com/dp/B0BXFXRW1P",
"https://www.amazon.com/dp/B0C4G2H93V",
"https://www.amazon.com/dp/B071WP5ZSG",
"https://www.amazon.com/dp/B0CDC2KYZC",
"https://www.amazon.com/dp/B0B2DC9RC3",
"https://www.amazon.com/dp/B08LNBCK5D",
"https://www.amazon.com/dp/B071G52LDJ",
"https://www.amazon.com/dp/B0077A7I3S",
"https://www.amazon.com/dp/B0CGG5KRNP",
"https://www.amazon.com/dp/B0CM6DDW7D",
"https://www.amazon.com/dp/B08DL989HS",
"https://www.amazon.com/dp/B087L1VL11",
"https://www.amazon.com/dp/B0BPJJYVFY",
"https://www.amazon.com/dp/B087L8PNKV",
"https://www.amazon.com/dp/B08ZHSFNPS",
"https://www.amazon.com/dp/B09WLJGFSX",
"https://www.amazon.com/dp/B08X4RXBYN",
"https://www.amazon.com/dp/B0CGG13MP5",
"https://www.amazon.com/dp/B0BTWH2KPJ",
"https://www.amazon.com/dp/B09VQ14XTR",
"https://www.amazon.com/dp/B09PFJKT7G",
"https://www.amazon.com/dp/B0834NQ7JL",
"https://www.amazon.com/dp/B071WNMQGH",
"https://www.amazon.com/dp/B00X70WAJE",
"https://www.amazon.com/dp/B0BPJ4MQ6C",
"https://www.amazon.com/dp/B0B2TSWRDR",
"https://www.amazon.com/dp/B09WLJFRZJ",
"https://www.amazon.com/dp/B00M80BRXY",
"https://www.amazon.com/dp/B09J58GL6X",
"https://www.amazon.com/dp/B08ZH4JG7B",
"https://www.amazon.com/dp/B09256KJD3",
"https://www.amazon.com/dp/B0B41DGDJT",
"https://www.amazon.com/dp/B08K2PFJPX",
"https://www.amazon.com/dp/B071JQCBRL",
"https://www.amazon.com/dp/B0BTMWHWYT",
"https://www.amazon.com/dp/B07214BZ66",
"https://www.amazon.com/dp/B0B8M6DTZC",
"https://www.amazon.com/dp/B09QL92KLP",
"https://www.amazon.com/dp/B0CKW1PXFZ",
"https://www.amazon.com/dp/B07J3PX6M9",
"https://www.amazon.com/dp/B07C91DV9P",
"https://www.amazon.com/dp/B07YLL92MF",
"https://www.amazon.com/dp/B0B9SS5WJ2",
"https://www.amazon.com/dp/B01DNSVFD6",
"https://www.amazon.com/dp/B0BX2174ZT",
"https://www.amazon.com/dp/B0BHW1YBVZ",
"https://www.amazon.com/dp/B0BD7XRSBZ",
"https://www.amazon.com/dp/B0C6G5MCSV",
"https://www.amazon.com/dp/B09QLBJKFL",
"https://www.amazon.com/dp/B087LSCGZ8",
"https://www.amazon.com/dp/B09253MFPZ",
"https://www.amazon.com/dp/B0BX9782JY",
"https://www.amazon.com/dp/B00I11U2ZI",
"https://www.amazon.com/dp/B0C4G2GFPF",
"https://www.amazon.com/dp/B0BCJDRT65",
"https://www.amazon.com/dp/B071WNXY9K",
"https://www.amazon.com/dp/B09MD9WGXN",
"https://www.amazon.com/dp/B087YTKHMK",
"https://www.amazon.com/dp/B0C4G1D6NY",
"https://www.amazon.com/dp/B09PFK4XW8",
"https://www.amazon.com/dp/B08DL7WNXN",
"https://www.amazon.com/dp/B0BHVYP8S7",
"https://www.amazon.com/dp/B0BCHWG61P",
"https://www.amazon.com/dp/B0077A7LVW",
"https://www.amazon.com/dp/B082FJTHZY",
"https://www.amazon.com/dp/B0B5JSL19R",
"https://www.amazon.com/dp/B088Q91BN8",
"https://www.amazon.com/dp/B0BTWGBKTD",
"https://www.amazon.com/dp/B082FMX41K",
"https://www.amazon.com/dp/B0CGGFD7F5",
"https://www.amazon.com/dp/B087L29BNF",
"https://www.amazon.com/dp/B0BHW3FWLP",
"https://www.amazon.com/dp/B0BXFYG79G",
"https://www.amazon.com/dp/B09HW774GK",
"https://www.amazon.com/dp/B0BD6YD4M6",
"https://www.amazon.com/dp/B087C8M1Z4",
"https://www.amazon.com/dp/B088QBLXNV",
"https://www.amazon.com/dp/B087LVRD3J",
"https://www.amazon.com/dp/B0BJJF69VH",
"https://www.amazon.com/dp/B0B8MC9HVG",
"https://www.amazon.com/dp/B0CGGBBFFF",
"https://www.amazon.com/dp/B0C4G36HHZ",
"https://www.amazon.com/dp/B0C5C4ZNGT",
"https://www.amazon.com/dp/B09WLKG942",
"https://www.amazon.com/dp/B0CGFZCYXW",
"https://www.amazon.com/dp/B09DWPCM5M",
"https://www.amazon.com/dp/B0CR21TV3K",
"https://www.amazon.com/dp/B09YWZXQXK",
"https://www.amazon.com/dp/B08X4SGDQ7",
"https://www.amazon.com/dp/B0CNT18MFF",
"https://www.amazon.com/dp/B00X70WD6O",
"https://www.amazon.com/dp/B0BPJFM5K2",
"https://www.amazon.com/dp/B0CD2YLNTZ",
"https://www.amazon.com/dp/B08CKD67BQ",
"https://www.amazon.com/dp/B0BX1XQ7FS",
"https://www.amazon.com/dp/B0CGFXR39L",
"https://www.amazon.com/dp/B0BD6ZCXCL",
"https://www.amazon.com/dp/B0C4H7PBXJ",
"https://www.amazon.com/dp/B0CR21LD8X",
"https://www.amazon.com/dp/B087LSLNCY",
"https://www.amazon.com/dp/B0B4174GNB",
"https://www.amazon.com/dp/B0CGGF36Z4",
"https://www.amazon.com/dp/B0C4H643KP",
"https://www.amazon.com/dp/B0B3T3QC7T",
"https://www.amazon.com/dp/B0CT2Y9YNG",
"https://www.amazon.com/dp/B09GFSX2BL",
"https://www.amazon.com/dp/B0CSP6JDBG",
"https://www.amazon.com/dp/B0BV6J67CD",
"https://www.amazon.com/dp/B0CGG72JC4",
"https://www.amazon.com/dp/B0BBR2N7CJ",
"https://www.amazon.com/dp/B0CNV17ZYP",
"https://www.amazon.com/dp/B0CGFPY5ZW",
"https://www.amazon.com/dp/B08ZS9SR7Z",
"https://www.amazon.com/dp/B09VQ3193T",
"https://www.amazon.com/dp/B08X4RK9YG",
"https://www.amazon.com/dp/B0BTMXFXJV",
"https://www.amazon.com/dp/B0C4H6DZ4L",
"https://www.amazon.com/dp/B01MXI8ASS",
"https://www.amazon.com/dp/B0BXFZR1QL",
"https://www.amazon.com/dp/B00L32L7HO",
"https://www.amazon.com/dp/B08ZH4QL5L",
"https://www.amazon.com/dp/B082FK87MJ",
"https://www.amazon.com/dp/B087Z2QG5V",
"https://www.amazon.com/dp/B0BZ762BNJ",
"https://www.amazon.com/dp/B092579CBV",
"https://www.amazon.com/dp/B0834P7TGC",
"https://www.amazon.com/dp/B0CGGBL5JL",
"https://www.amazon.com/dp/B0CGFXD1GN",
"https://www.amazon.com/dp/B0CGFPR4SB",
"https://www.amazon.com/dp/B082FMNVV2",
"https://www.amazon.com/dp/B08CK8P3SH",
"https://www.amazon.com/dp/B09WGVSVWR",
"https://www.amazon.com/dp/B0CL36Z3YD",
"https://www.amazon.com/dp/B08V4Y3641",
"https://www.amazon.com/dp/B0CGFS1YYY",
"https://www.amazon.com/dp/B08487BRL1",
"https://www.amazon.com/dp/B0077A7PAO",
"https://www.amazon.com/dp/B09KG3Q4RH",
"https://www.amazon.com/dp/B08VGKNW24",
"https://www.amazon.com/dp/B0BRBVHTDV",
"https://www.amazon.com/dp/B07D6Z8D5Q",
"https://www.amazon.com/dp/B0BTWFCZZG",
"https://www.amazon.com/dp/B0CGFZZBRH",
"https://www.amazon.com/dp/B09KG64ZLZ",
"https://www.amazon.com/dp/B003LFMCIE",
"https://www.amazon.com/dp/B0CGG38VWN",
"https://www.amazon.com/dp/B0BXFZT7S8",
"https://www.amazon.com/dp/B09WGVRX2J",
"https://www.amazon.com/dp/B07G5XMT49",
"https://www.amazon.com/dp/B0B5JXRB5M",
"https://www.amazon.com/dp/B0917BDKL8",
"https://www.amazon.com/dp/B0CRLBMPB3",
"https://www.amazon.com/dp/B0CQP5WC7J",
"https://www.amazon.com/dp/B0BD71H994",
"https://www.amazon.com/dp/B00X70WOCC",
"https://www.amazon.com/dp/B0C67X91WP",
"https://www.amazon.com/dp/B087C9W8P2",
"https://www.amazon.com/dp/B08CKD1ZXW",
"https://www.amazon.com/dp/B08ZKVWKYP",
"https://www.amazon.com/dp/B0BXFW1M9D",
"https://www.amazon.com/dp/B0CGQRM7CJ",
"https://www.amazon.com/dp/B08ZH2JB4C",
"https://www.amazon.com/dp/B0CGG3FYLZ",
"https://www.amazon.com/dp/B0CGG3PYYQ",
"https://www.amazon.com/dp/B01N6NLHBM",
"https://www.amazon.com/dp/B085GKQMKP",
"https://www.amazon.com/dp/B0B95ZM95H",
"https://www.amazon.com/dp/B0CRL7WRYJ",
"https://www.amazon.com/dp/B08HJNM2RJ",
"https://www.amazon.com/dp/B07361K8RT",
"https://www.amazon.com/dp/B09WLHMYJZ",
"https://www.amazon.com/dp/B096DJYQ2B",
"https://www.amazon.com/dp/B0CGFZ5V4G",
"https://www.amazon.com/dp/B0B62BNQDY",
"https://www.amazon.com/dp/B0C4H8V7D8",
"https://www.amazon.com/dp/B08L45X7Y4",
"https://www.amazon.com/dp/B07YLM5VMV",
"https://www.amazon.com/dp/B08JSGQQR5",
"https://www.amazon.com/dp/B07Y5PQJDP",
"https://www.amazon.com/dp/B08ZHB45S3",
"https://www.amazon.com/dp/B09WHJ4J9F",
"https://www.amazon.com/dp/B0C685YKTS",
"https://www.amazon.com/dp/B0CGG2L3FD",
"https://www.amazon.com/dp/B08X4SR8J2",
"https://www.amazon.com/dp/B0C2CCL9CB",
"https://www.amazon.com/dp/B082FMVBXG",
"https://www.amazon.com/dp/B09257XR2P",
"https://www.amazon.com/dp/B0834NGPPK",
"https://www.amazon.com/dp/B08K2GKPDY",
"https://www.amazon.com/dp/B08ZH85S8G",
"https://www.amazon.com/dp/B0CD2Y2LD9",
"https://www.amazon.com/dp/B0CGG565NM",
"https://www.amazon.com/dp/B0C4H9KLN9",
"https://www.amazon.com/dp/B0B4ZJ6G39",
"https://www.amazon.com/dp/B0BD72SLTC",
"https://www.amazon.com/dp/B08W54LGMV",
"https://www.amazon.com/dp/B09WH8324J",
"https://www.amazon.com/dp/B08V4GN54Z",
"https://www.amazon.com/dp/B0B5K7ZR4R",
"https://www.amazon.com/dp/B0CLXSZDPY",
"https://www.amazon.com/dp/B09FSDNZXW",
"https://www.amazon.com/dp/B092579PXH",
"https://www.amazon.com/dp/B09PFK2HT3",
"https://www.amazon.com/dp/B0CKWT4VGG",
"https://www.amazon.com/dp/B087C9HTQH",
"https://www.amazon.com/dp/B0CJ5XDP15",
"https://www.amazon.com/dp/B0BS4GYJVF",
"https://www.amazon.com/dp/B0BXFZNBQT",
"https://www.amazon.com/dp/B0B8M79C64",
"https://www.amazon.com/dp/B0CLBBDK72",
"https://www.amazon.com/dp/B0B4QV1PPR",
"https://www.amazon.com/dp/B08PCW2SXM",
"https://www.amazon.com/dp/B09FM63Y3Z",
"https://www.amazon.com/dp/B00M49196Y",
"https://www.amazon.com/dp/B0CGG63THM",
"https://www.amazon.com/dp/B0BRP3RPH2",
"https://www.amazon.com/dp/B0BFQB6MQJ",
"https://www.amazon.com/dp/B0BJ6PCJ6T",
"https://www.amazon.com/dp/B0BRT44CXJ",
"https://www.amazon.com/dp/B087LTYYJ7",
"https://www.amazon.com/dp/B0C4G36Y16",
"https://www.amazon.com/dp/B09DWP436Z",
"https://www.amazon.com/dp/B0CGG413C5",
"https://www.amazon.com/dp/B0C4FTCVS4",
"https://www.amazon.com/dp/B0CGGBJN7C",
"https://www.amazon.com/dp/B0C4KCDP31",
"https://www.amazon.com/dp/B08ZS1DV6T",
"https://www.amazon.com/dp/B0917L3LD6",
"https://www.amazon.com/dp/B0C67WQQQF",
"https://www.amazon.com/dp/B072JXV38C",
"https://www.amazon.com/dp/B07474P2C3",
"https://www.amazon.com/dp/B0BS529Z15",
"https://www.amazon.com/dp/B07YLL9T5X",
"https://www.amazon.com/dp/B0BZZ4X48J",
"https://www.amazon.com/dp/B0BBZQ5QJY",
"https://www.amazon.com/dp/B087KYM4QV",
"https://www.amazon.com/dp/B082FMHX4P",
"https://www.amazon.com/dp/B0CGG63T76",
"https://www.amazon.com/dp/B087LZY34T",
"https://www.amazon.com/dp/B0C4H7KDL6",
"https://www.amazon.com/dp/B08ZHQZTYJ",
"https://www.amazon.com/dp/B09MDBCH3S",
"https://www.amazon.com/dp/B07V49G6QX",
"https://www.amazon.com/dp/B0CGG7YJD6",
"https://www.amazon.com/dp/B07R1CWZWY",
"https://www.amazon.com/dp/B09L4N6176",
"https://www.amazon.com/dp/B09V1W1HJY",
"https://www.amazon.com/dp/B0917LS7Y8",
"https://www.amazon.com/dp/B0B4W554KH",
"https://www.amazon.com/dp/B0C4H956CH",
"https://www.amazon.com/dp/B087LSY7GB",
"https://www.amazon.com/dp/B0CH2TCXPR",
"https://www.amazon.com/dp/B0CGFWNTMT",
"https://www.amazon.com/dp/B09KKTXDHW",
"https://www.amazon.com/dp/B0CGG611SB",
"https://www.amazon.com/dp/B0CMTBBF9C",
"https://www.amazon.com/dp/B0BTMXS9YL",
"https://www.amazon.com/dp/B08CK3MPY5",
"https://www.amazon.com/dp/B0BD6ZZ65J",
"https://www.amazon.com/dp/B09WLHZ6L2",
"https://www.amazon.com/dp/B0CGRSZBDS",
"https://www.amazon.com/dp/B07YLLFSWC",
"https://www.amazon.com/dp/B0CGFWDBGW",
"https://www.amazon.com/dp/B0CGFW8F93",
"https://www.amazon.com/dp/B07YLLGXDJ",
"https://www.amazon.com/dp/B00BG8OFW4",
"https://www.amazon.com/dp/B07213M4RD",
"https://www.amazon.com/dp/B09HC6VYD1",
"https://www.amazon.com/dp/B0CGG2JJGQ",
"https://www.amazon.com/dp/B0CGFTFWTB",
"https://www.amazon.com/dp/B0CGG2Y3S8",
"https://www.amazon.com/dp/B09GJH13MD",
"https://www.amazon.com/dp/B087YZ4R4N",
"https://www.amazon.com/dp/B0CRL9NNZX",
"https://www.amazon.com/dp/B0C4H79Y8L",
"https://www.amazon.com/dp/B09MD9TFF7",
"https://www.amazon.com/dp/B09VQ45R3F",
"https://www.amazon.com/dp/B0CJVDCYDS",
"https://www.amazon.com/dp/B087KXXQV9",
"https://www.amazon.com/dp/B081P72N95",
"https://www.amazon.com/dp/B0B62B6TDB",
"https://www.amazon.com/dp/B0B8M943CW",
"https://www.amazon.com/dp/B0CNYZHQS7",
"https://www.amazon.com/dp/B0834NPX2Z",
"https://www.amazon.com/dp/B0C4G2XN9T",
"https://www.amazon.com/dp/B0BX9775W4",
"https://www.amazon.com/dp/B0C6G62QG7",
"https://www.amazon.com/dp/B0CBSWK847",
"https://www.amazon.com/dp/B08BX6QFLW",
"https://www.amazon.com/dp/B0834P2H7S",
"https://www.amazon.com/dp/B0BFJJB8CC",
"https://www.amazon.com/dp/B0CGG4ZRD1",
"https://www.amazon.com/dp/B0CHPM6C24",
"https://www.amazon.com/dp/B0C4G2WN57",
"https://www.amazon.com/dp/B0B76ND2XJ",
"https://www.amazon.com/dp/B0C4G2XSY4",
"https://www.amazon.com/dp/B087Z6B93V",
"https://www.amazon.com/dp/B0BTWDG862",
"https://www.amazon.com/dp/B0B8XBZ7VT",
"https://www.amazon.com/dp/B07YLLMCYL",
"https://www.amazon.com/dp/B087L4XJXM",
"https://www.amazon.com/dp/B0CGGBZ219",
"https://www.amazon.com/dp/B0CGG6KP5P",
"https://www.amazon.com/dp/B0BTWGX2BR",
"https://www.amazon.com/dp/B0BX98XD6P",
"https://www.amazon.com/dp/B0C4H6T8S9",
"https://www.amazon.com/dp/B087YN5WR4",
"https://www.amazon.com/dp/B0BHXX73WY",
"https://www.amazon.com/dp/B0CGG8ZMYL",
"https://www.amazon.com/dp/B0BZZ2JSMD",
"https://www.amazon.com/dp/B09QV7YPZ4",
"https://www.amazon.com/dp/B08DL9VKLD",
"https://www.amazon.com/dp/B0CP263K3L",
"https://www.amazon.com/dp/B0BNPXBNL8",
"https://www.amazon.com/dp/B0C4H85CHH",
"https://www.amazon.com/dp/B07QX935RV",
"https://www.amazon.com/dp/B08ZHFB2KV",
"https://www.amazon.com/dp/B08ZGZC6JF",
"https://www.amazon.com/dp/B0CNPSFW1Z",
"https://www.amazon.com/dp/B0C682M1PY",
"https://www.amazon.com/dp/B087LB2DKD",
"https://www.amazon.com/dp/B0B5K325TJ",
"https://www.amazon.com/dp/B0BCHVXGWV",
"https://www.amazon.com/dp/B0C771RPX4",
"https://www.amazon.com/dp/B088QCCHM4",
"https://www.amazon.com/dp/B00I11TRUO",
"https://www.amazon.com/dp/B0834NFM8G",
"https://www.amazon.com/dp/B09VQ28K64",
"https://www.amazon.com/dp/B0BNPSVBZS",
"https://www.amazon.com/dp/B0077A7HNY",
"https://www.amazon.com/dp/B07MBF261Z",
"https://www.amazon.com/dp/B071G585GQ",
"https://www.amazon.com/dp/B07213G8HQ",
"https://www.amazon.com/dp/B0C54TTRMQ",
"https://www.amazon.com/dp/B0BN7XTY3Z",
"https://www.amazon.com/dp/B0BCGNWZ18",
"https://www.amazon.com/dp/B07W58L66R",
"https://www.amazon.com/dp/B0BGXB3SMV",
"https://www.amazon.com/dp/B0CGG5RX5X",
"https://www.amazon.com/dp/B0BM44BN5G",
"https://www.amazon.com/dp/B00YVJ2Z4K",
"https://www.amazon.com/dp/B019E4FE12",
"https://www.amazon.com/dp/B09C9LNL8P",
"https://www.amazon.com/dp/B0B66D4F7C",
"https://www.amazon.com/dp/B08X4RL2RL",
"https://www.amazon.com/dp/B07NSKYPJX",
"https://www.amazon.com/dp/B081567DSM",
"https://www.amazon.com/dp/B0077A7QYO",
"https://www.amazon.com/dp/B0CD2SF9M8",
"https://www.amazon.com/dp/B0BD71PYJ7",
"https://www.amazon.com/dp/B0BKJK41WD",
"https://www.amazon.com/dp/B0B4W3C8BT",
"https://www.amazon.com/dp/B0CP24VZ4W",
"https://www.amazon.com/dp/B09D94RLQV",
"https://www.amazon.com/dp/B0CGG5JMTK",
"https://www.amazon.com/dp/B087Z12G2P",
"https://www.amazon.com/dp/B07XVRH9CX",
"https://www.amazon.com/dp/B0B69R7Y6Z",
"https://www.amazon.com/dp/B0881Y4W5V",
"https://www.amazon.com/dp/B0CLC2QH5F",
"https://www.amazon.com/dp/B0CH19ZQN6",
"https://www.amazon.com/dp/B0BTNSBZKN",
"https://www.amazon.com/dp/B07NSKM24B",
"https://www.amazon.com/dp/B0BXFZ2F4L",
"https://www.amazon.com/dp/B08NLQYVS6",
"https://www.amazon.com/dp/B081P82NTM",
"https://www.amazon.com/dp/B09KKTKB3J",
"https://www.amazon.com/dp/B0C4H6Y3BZ",
"https://www.amazon.com/dp/B09DWQLWP2",
"https://www.amazon.com/dp/B0834NNSTG",
"https://www.amazon.com/dp/B087Z1QFNX",
"https://www.amazon.com/dp/B07YLKDV6X",
"https://www.amazon.com/dp/B07HHJJBZ3",
"https://www.amazon.com/dp/B0BD6Z2T5L",
"https://www.amazon.com/dp/B0CD2W8KKK",
"https://www.amazon.com/dp/B0881ZMZQW",
"https://www.amazon.com/dp/B08CK8VYSQ",
"https://www.amazon.com/dp/B09FRWVMT7",
"https://www.amazon.com/dp/B0CG93WHRT",
"https://www.amazon.com/dp/B0BFGWG6J6",
"https://www.amazon.com/dp/B087YSK33L",
"https://www.amazon.com/dp/B0BM43HPK7",
"https://www.amazon.com/dp/B07N1GLZZP",
"https://www.amazon.com/dp/B013USOP5O",
"https://www.amazon.com/dp/B09N3YZW8L",
"https://www.amazon.com/dp/B08T5WVHHS",
"https://www.amazon.com/dp/B0CNV2RWZZ",
"https://www.amazon.com/dp/B0009G2F6W",
"https://www.amazon.com/dp/B09FRYXGSF",
"https://www.amazon.com/dp/B0CQLXTWVJ",
"https://www.amazon.com/dp/B0BD7V4WXX",
"https://www.amazon.com/dp/B0CHLW9GT6",
"https://www.amazon.com/dp/B09N3XYPMX",
"https://www.amazon.com/dp/B09NPWSS8T",
"https://www.amazon.com/dp/B08DCW4G5C",
"https://www.amazon.com/dp/B097PNNZH9",
"https://www.amazon.com/dp/B07KTJWNHF",
"https://www.amazon.com/dp/B09N3Z952G",
"https://www.amazon.com/dp/B0CLCGV878",
"https://www.amazon.com/dp/B0CNV5QHN7",
"https://www.amazon.com/dp/B09N412Z31",
"https://www.amazon.com/dp/B07J3PYZF4",
"https://www.amazon.com/dp/B07JJ95RR5",
"https://www.amazon.com/dp/B0CNV61ZHQ",
"https://www.amazon.com/dp/B07J3RVB6J",
"https://www.amazon.com/dp/B077BXSC6H",
"https://www.amazon.com/dp/B0CNV2TQ7B",
"https://www.amazon.com/dp/B07J9LGZS7",
"https://www.amazon.com/dp/B0B4WBX234",
"https://www.amazon.com/dp/B09N3XJW21",
"https://www.amazon.com/dp/B0CRRB3ZZH",
"https://www.amazon.com/dp/B0C4G38S5Y",
"https://www.amazon.com/dp/B0B4QZ3TFF",
"https://www.amazon.com/dp/B0CMTM3M24",
"https://www.amazon.com/dp/B07JVMLF7K",
"https://www.amazon.com/dp/B07J3SXP24",
"https://www.amazon.com/dp/B07JVP3PFL",
"https://www.amazon.com/dp/B0C4G44H67",
"https://www.amazon.com/dp/B0B4RHNG45",
"https://www.amazon.com/dp/B07JCG369Q",
"https://www.amazon.com/dp/B09WLK7GCH",
"https://www.amazon.com/dp/B0CNSZH6H5",
"https://www.amazon.com/dp/B07JC3JYNL",
"https://www.amazon.com/dp/B07JR2DD3H",
"https://www.amazon.com/dp/B07JQXSJRG",
"https://www.amazon.com/dp/B0C4G2LWMD",
"https://www.amazon.com/dp/B07J9LHHPV",
"https://www.amazon.com/dp/B0CNV2ZM1D",
"https://www.amazon.com/dp/B0BXVDPX9D",
"https://www.amazon.com/dp/B08CK6QW86",
"https://www.amazon.com/dp/B0CM6BZXQM",
"https://www.amazon.com/dp/B09DWQ1HF7",
"https://www.amazon.com/dp/B08Y8F44Y2",
"https://www.amazon.com/dp/B0BXFXBDW5",
"https://www.amazon.com/dp/B0CJTRFD2C",
"https://www.amazon.com/dp/B0CM6DG15D",
"https://www.amazon.com/dp/B0CNSZGHNB",
"https://www.amazon.com/dp/B0CT583GPL",
"https://www.amazon.com/dp/B07WJ8WX3K",
"https://www.amazon.com/dp/B0CNTZVQQL",
"https://www.amazon.com/dp/B0CMCS3HNM",
"https://www.amazon.com/dp/B0CNV6RBK3",
"https://www.amazon.com/dp/B0B5N9M7WL",
"https://www.amazon.com/dp/B0B5NYS2LB",
"https://www.amazon.com/dp/B0CMHXDWD3",
"https://www.amazon.com/dp/B0CMSTT89V",
"https://www.amazon.com/dp/B0CLCCVWF3",
"https://www.amazon.com/dp/B077BVH25G",
"https://www.amazon.com/dp/B0CNRJZZTG",
"https://www.amazon.com/dp/B077C12QFG",
"https://www.amazon.com/dp/B0BX97QYV5",
"https://www.amazon.com/dp/B0CN18DB2V",
"https://www.amazon.com/dp/B0CMTVL7FG",
"https://www.amazon.com/dp/B0CQNXCPC2",
"https://www.amazon.com/dp/B0CP2437S8",
"https://www.amazon.com/dp/B0CLC28BJK",
"https://www.amazon.com/dp/B077BYZR6F",
"https://www.amazon.com/dp/B0CQLX7G18",
"https://www.amazon.com/dp/B014WWGQ9U",
"https://www.amazon.com/dp/B077BXPKF2",
"https://www.amazon.com/dp/B08NWMT8YQ",
"https://www.amazon.com/dp/B0CLC3FX59",
"https://www.amazon.com/dp/B0CQP93DGM",
"https://www.amazon.com/dp/B0CQLX3LJD",
"https://www.amazon.com/dp/B077BYWZVY",
"https://www.amazon.com/dp/B0BZHL62Z9",
"https://www.amazon.com/dp/B08NWNGYGG",
"https://www.amazon.com/dp/B09178RB3G",
"https://www.amazon.com/dp/B0CQP8D8LL",
"https://www.amazon.com/dp/B0CQLWBPZ7",
"https://www.amazon.com/dp/B077BX75ST",
"https://www.amazon.com/dp/B0CMPWM4NF",
"https://www.amazon.com/dp/B09DWQXG3K",
"https://www.amazon.com/dp/B0CQNY2GFS",
"https://www.amazon.com/dp/B07J3PZD2R",
"https://www.amazon.com/dp/B077BYZ91W",
"https://www.amazon.com/dp/B077BXMLV7",
"https://www.amazon.com/dp/B077C2H14R",
"https://www.amazon.com/dp/B0777Q4TVR",
"https://www.amazon.com/dp/B077BVH2FT",
"https://www.amazon.com/dp/B077BYY2B2",
"https://www.amazon.com/dp/B077BWL7M3",
"https://www.amazon.com/dp/B0777LWLFW",
"https://www.amazon.com/dp/B0777Q71SZ",
"https://www.amazon.com/dp/B077BVH2FZ",
"https://www.amazon.com/dp/B077BYY2BK",
"https://www.amazon.com/dp/B07FJ9BYYT",
"https://www.amazon.com/dp/B0C9WXYT44",
"https://www.amazon.com/dp/B0CP1X35CR",
"https://www.amazon.com/dp/B07F7QH7MN",
"https://www.amazon.com/dp/B077BVH2G1",
"https://www.amazon.com/dp/B0BPTFXH3S",
"https://www.amazon.com/dp/B09YVB87L8",
"https://www.amazon.com/dp/B09YYKPT3H",
"https://www.amazon.com/dp/B077BZFRMV",
"https://www.amazon.com/dp/B09YV8F5WJ",
"https://www.amazon.com/dp/B077BZGF87",
"https://www.amazon.com/dp/B0B158QD1J",
"https://www.amazon.com/dp/B077BXNMK5",
"https://www.amazon.com/dp/B09YYDCZGH",
"https://www.amazon.com/dp/B01M5BNX8Y",
"https://www.amazon.com/dp/B0CH2X3QLR",
"https://www.amazon.com/dp/B00279RELK",
"https://www.amazon.com/dp/B07ZQR9TPB",
"https://www.amazon.com/dp/B07NVSPD3T",
"https://www.amazon.com/dp/B07ZQPKS2P",
"https://www.amazon.com/dp/B07RG83C5S",
"https://www.amazon.com/dp/B08JHGXN7D",
"https://www.amazon.com/dp/B0BPTG1G8X",
"https://www.amazon.com/dp/B00HESVC8U",
"https://www.amazon.com/dp/B0BRN5TC68",
"https://www.amazon.com/dp/B0BX6CLG2C",
"https://www.amazon.com/dp/B082FNTCJT",
"https://www.amazon.com/dp/B082FMVD3P",
"https://www.amazon.com/dp/B07BS74TPF",
"https://www.amazon.com/dp/B0849XSSH3",
"https://www.amazon.com/dp/B071WP5VP9",
"https://www.amazon.com/dp/B07V39MYDG",
"https://www.amazon.com/dp/B07V56QYZ8",
"https://www.amazon.com/dp/B08L447MY5",
"https://www.amazon.com/dp/B07GNK7HSM",
"https://www.amazon.com/dp/B08L455C1J",
"https://www.amazon.com/dp/B09V1TR191",
"https://www.amazon.com/dp/B01KZV319U",
"https://www.amazon.com/dp/B01M8INHN4",
"https://www.amazon.com/dp/B016VADTCS",
"https://www.amazon.com/dp/B01KZV3398"
]

# 3. Setting Webdriver and Website Specific Information

In [3]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.get('https://www.amazon.com/')
wait=WebDriverWait(driver, 5)

In [5]:
location = driver.find_element(By.ID, 'nav-global-location-popover-link')

location.click()
sleep(1)
pin = driver.find_element(By.ID, 'GLUXZipUpdateInput')
pinnumber='94203'
pin.send_keys(pinnumber)

apply=driver.find_element(By.CSS_SELECTOR, 'span.a-button-inner[data-action="GLUXPostalUpdateAction"]')
apply.click()

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [9]:
cols =['Sl.No'] #,'Review_Mentions'
df = pd.DataFrame(columns=cols)
df
count=0

In [10]:
timestamp=[]
timediff=[]
from IPython.display import clear_output 
import numpy as np
from datetime import timedelta
def timeremaining(balanceitem,i):
    timestamp.insert(i,datetime.datetime.now())
    if i>=1:
        diff=timestamp[i]-timestamp[i-1]
        timediff.insert(i,diff.total_seconds())		
        remainingtime=np.median(timediff)*balanceitem
        millis=int(remainingtime)		
        #print(millis)
        seconds=(millis)%60
        seconds = int(seconds)
        minutes=(millis/(60))%60
        minutes = int((minutes)) #math.floor
        hours=(millis/(60*60))%24
        hours=int(hours)
        print(f'Item Scraped: {i+1} \nItems Remining: {balanceitem-1} and \nTime Remaining: {hours}:{minutes}:{seconds}')
        etc=datetime.datetime.now()+timedelta(hours=hours,minutes=minutes,seconds=seconds)
        print(f'Estimated time of completion:{etc}')        
        clear_output(wait=True)

In [13]:
for i in range(552,len(links)):
    driver.get(links[i])
    df.loc[count,'Sl.No']=i+1
    df.loc[count,'Links']=links[i]
    try:
        df.loc[count,'ReviewSummary']=driver.find_element(By.CSS_SELECTOR,'[id="product-summary"]').text
    except:
        df.loc[count,'ReviewSummary']=""
    try:
        elements=driver.find_elements(By.CLASS_NAME,'_cr-product-insights_style_aspect-button__1BFiu' )
        len(elements)
        slist=[]
        for element in elements:
            s=df.loc[count,'Sentiment']=element.get_attribute('data-csa-c-item-id')
            slist.append(s)
        #print(slist)
        df.at[count,"Sentiment"]=slist
    except:
        df.loc[count,'Sentiment']=""
    count=count+1
    balanceitem=len(links)-i
    timeremaining(balanceitem,i)
    clear_output(wait=True)

Item Scraped: 1150
Items Remining: 0 and
Time Remaining: 0:0:5
Estimated time of completion:2024-01-30 00:47:38.937903

In [14]:
df

,Sl.No,Links,ReviewSummary,Sentiment
0,1,https://www.amazon.com/dp/B08CDJMQT1,"Customers say\nCustomers like the quality, fit...","[Quality_POSITIVE, Ease of installation_POSITI..."
1,2,https://www.amazon.com/dp/B08L479JGJ,"Customers say\nCustomers like the security, ap...","[Ease of installation_POSITIVE, Appearance_POS..."
2,3,https://www.amazon.com/dp/B08K8P5RVH,"Customers say\nCustomers like the quality, app...","[Ease of installation_POSITIVE, Quality_POSITI..."
3,4,https://www.amazon.com/dp/B07XC3D1BP,"Customers say\nCustomers like the performance,...","[Quality_POSITIVE, Ease of installation_POSITI..."
4,5,https://www.amazon.com/dp/B08L71GBX7,"Customers say\nCustomers like the performance,...","[Ease of installation_POSITIVE, Appearance_POS..."
...,...,...,...,...
1146,1146,https://www.amazon.com/dp/B09V1TR191,"Customers say\nCustomers like the appearance, ...","[Ease of installation_POSITIVE, Quality_POSITI..."
1147,1147,https://www.amazon.com/dp/B01KZV319U,Customers say\nCustomers like the performance ...,"[Ease of installation_POSITIVE, Performance_PO..."
1148,1148,https://www.amazon.com/dp/B01M8INHN4,,[]
1149,1149,https://www.amazon.com/dp/B016VADTCS,"Customers say\nCustomers like the condition, e...","[Ease of installation_POSITIVE, Quality_POSITI..."
1150,1150,https://www.amazon.com/dp/B01KZV3398,"Customers say\nCustomers like the quality, per...","[Appearance_POSITIVE, Performance_POSITIVE, Qu..."

In [54]:
df.to_excel('Reviews1.xlsx', index=False)

In [28]:
for i in range(len(links)):
    driver.get(links[i])
    df.loc[count,'Sl.No']=i
    df.loc[count,'Links']=links[i]
    try:
        df.loc[count,'FirstAvailableDate']=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME,"prodDetAttrValue")))[-1].text
    except:
        df.loc[count,'FirstAvailableDate']=""
    count=count+1
    balanceitem=len(links)-i
    timeremaining(balanceitem,i)
    clear_output(wait=True)

Item Scraped: 1150
Items Remining: 0 and
Time Remaining: 0:0:3

In [29]:
df

     Sl.No                                 Links  FirstAvailableDate
0        0  https://www.amazon.com/dp/B08CDJMQT1        July 6, 2020
1        1  https://www.amazon.com/dp/B08L479JGJ    October 12, 2020
2        2  https://www.amazon.com/dp/B08K8P5RVH  September 10, 2020
3        3  https://www.amazon.com/dp/B07XC3D1BP   September 5, 2019
4        4  https://www.amazon.com/dp/B08L71GBX7    October 14, 2020
...    ...                                   ...                 ...
1157  1145  https://www.amazon.com/dp/B09V1TR191       March 7, 2022
1158  1146  https://www.amazon.com/dp/B01KZV319U     August 25, 2016
1159  1147  https://www.amazon.com/dp/B01M8INHN4  September 24, 2013
1160  1148  https://www.amazon.com/dp/B016VADTCS   September 2, 2015
1161  1149  https://www.amazon.com/dp/B01KZV3398     August 25, 2016

[1162 rows x 3 columns]

In [31]:
df.to_excel('First_available.xlsx', index=False)

In [18]:
df

  Sl.No                                 Links  FirstAvailableDate
0     0  https://www.amazon.com/dp/B08CDJMQT1        July 6, 2020
1     1  https://www.amazon.com/dp/B08L479JGJ    October 12, 2020
2     2  https://www.amazon.com/dp/B08K8P5RVH  September 10, 2020
3     3  https://www.amazon.com/dp/B07XC3D1BP   September 5, 2019
4     4  https://www.amazon.com/dp/B08L71GBX7    October 14, 2020
5     5  https://www.amazon.com/dp/B07XVQ3KL5        June 6, 2019

In [10]:
for i in range(len(links)):
    driver.get(links[i])
    df.loc[count,'Sl.No']=i
    sleep(1)
    product = driver.find_elements(By.XPATH, "//span[@class='a-size-large product-title-word-break']")
    if len(product)==0:
        df.loc[count,'Name']="-"
    else:
        for n in product:
            df.loc[count,'Name']=n.text
    price=driver.find_elements(By.XPATH, "//span[@class='a-price a-text-price a-size-medium apexPriceToPay']")
    if len(price)==0:
        price=driver.find_elements(By.XPATH, "//span[@class='a-price aok-align-center reinventPricePriceToPayMargin priceToPay']")
    if len(price)==0:
        df.loc[count,'Current Price']="0"
    else:
        for pr in price:
            if "\n" in pr.text:
                prm=pr.text.replace('\n',".")
                df.loc[count,'Current Price']=prm
            else:    
                if pr.text== "":
                    pass
                else: 
                    df.loc[count,'Current Price']=pr.text
    try:
        listprice=driver.find_element(By.CLASS_NAME,"basisPrice")
        df.loc[count,'List Price']=listprice.text.split("$")[1]
    except:
        for pr in price:
            if "\n" in pr.text:
                prm=pr.text.replace('\n',".")
                df.loc[count,'List Price']=prm
            else:    
                if pr.text== "":
                    pass
                else: 
                    df.loc[count,'List Price']=pr.text
    try:
        rating=driver.find_element(By.ID, "averageCustomerReviews")
        if len(rating.text)==0:
            df.loc[count,'Ratings']="0"
        else:
            df.loc[count,'Ratings']=rating.text
    except:
        df.loc[count,'Ratings']="0"
    PDetail=driver.find_elements(By.ID, "productDetails_techSpec_section_1")
    if len(PDetail)==0:
        df.loc[count,'Attributes']="-"
    else:
        for det in PDetail:
            df.loc[count,'Attributes']=det.text
    Sales = driver.find_elements(By.XPATH, "(//span[@class='a-size-small social-proofing-faceout-title-text'])")
    if len(Sales)==0:
        df.loc[count,'Sales_LastMonth']="0"
    else:
        for s in Sales:
            df.loc[count,'Sales_LastMonth']=s.text.split('+')[0].replace('K','000')
    IDetails=driver.find_elements(By.XPATH, "(//div[@class='a-section a-spacing-medium a-spacing-top-small'])")
    if len(IDetails)==0:
        df.loc[count,'Details']="-" 
    else:
        for Idet in IDetails:
            df.loc[count,'Details']=Idet.text
    try:
        df.loc[count,"Details_s"]=driver.find_element(By.CSS_SELECTOR,'[class="a-normal a-spacing-micro"]').text
    except:
        df.loc[count,"Details_s"]=""
    #driver.find_element(By.TAG_NAME,'body').send_keys(Keys.END)
    #sleep(3)
    # try:
    #     crt=driver.find_element(By.ID,'acrCustomerReviewText')
    #     crt.click()
    # except:
    #     print("no Review")
    # sleep(2)
    # try:
    #     Reveiews=driver.find_element(By.ID, "cr-lighthut-1-")
    #     list_items = Reveiews.find_elements(By.CLASS_NAME,"cr-lighthouse-term ")
    #     ListWords=[]
    #     for item in list_items:
    #         ListWords.append(item.text)
    #     df.loc[count,'Review_Mentions']=ListWords)         
    # except:
    #     df.loc[count,'Review_Mentions']="-") 
    df.loc[count,'Links']=links[i]
    count=count+1

    balanceitem=len(links)-i
    timeremaining(balanceitem,i)
    clear_output(wait=True)

Item Scraped: 20
Items Remining: 0 and
Time Remaining: 0:0:5

In [11]:
df

,Sl.No,Name,Current Price,List Price,Ratings,Attributes,Sales_LastMonth,Details,Details_s,Links
0,0,BAK BAKFlip FiberMax Hard Folding Truck Bed To...,"$1,011.99","1,142.99",3.4\n25 ratings,Manufacturer BAK Industries\nBrand BAK\nModel ...,0,About this item\nFits 2008 - 2016 Ford F-250/3...,Brand BAK\nStyle Folding\nExterior Finish Pain...,https://www.amazon.com/dp/B071WNQXRN
1,1,BAK BAKFlip MX4 Hard Folding Truck Bed Tonneau...,"$1,117.64","$1,117.64",4.5\n359 ratings,Manufacturer BAK Industries\nBrand BAK\nModel ...,0,"About this item\nFits 2009-2018, 2019-21 Class...","Brand BAK\nStyle 2009-2018, 2019-21 Classic\nE...",https://www.amazon.com/dp/B07213M4RD
2,2,BAK BAKFlip FiberMax Hard Folding Truck Bed To...,"$1,047.99","1,142.99",4.4\n206 ratings,Manufacturer BAK\nBrand BAK\nModel 1126130\nIt...,0,About this item\nFits 2019 - 2022 Chevy/GMC Si...,"Brand BAK\nStyle Folding\nMaterial Fiberglass,...",https://www.amazon.com/dp/B07GNJNHC4
3,3,BAK BAKFlip FiberMax Hard Folding Truck Bed To...,"$1,097.27","$1,097.27",4.4\n206 ratings,Manufacturer BAK\nBrand BAK\nModel 1126131\nIt...,0,About this item\nFits 2019 - 2022 Chevy/GMC Si...,Brand BAK\nStyle Folding\nExterior Finish Pain...,https://www.amazon.com/dp/B07GNN6PM1
4,4,Lyon cover 6.6'ft Tri-Fold Truck Bed FRP Hard ...,$489.00,$489.00,4.3\n294 ratings,Manufacturer Lyon cover\nBrand Lyon cover\nIte...,0,About this item\n【Fitment】:2014-2021 Silverado...,Brand Lyon cover\nStyle Folding\nExterior Fini...,https://www.amazon.com/dp/B07TY41TZ3
5,5,Gator EFX Hard Tri-Fold Truck Bed Tonneau Cove...,$699.00,$699.00,4.3\n424 ratings,Manufacturer AX5H7\nBrand Gator Covers\nModel ...,0,"About this item\nFits 2014 - 2018, 2019 Ltd/Lg...",Brand Gator Covers\nStyle Folding\nExterior Fi...,https://www.amazon.com/dp/B07XLV777G
6,6,Lyon cover 5.8ft/69.3inch Hard Tri-Fold Truck ...,$479.00,$479.00,4.3\n294 ratings,Manufacturer LYCH030A\nBrand Lyon cover\nItem ...,0,About this item\nFitment :2007-2018 Silverado/...,Brand Lyon cover\nStyle Folding\nExterior Fini...,https://www.amazon.com/dp/B08G4KVKYP
7,7,BAK BAKFlip MX4 Hard Folding Truck Bed Tonneau...,"$1,055.99","1,252.99",4.4\n553 ratings,Manufacturer BAK Industries\nBrand BAK\nModel ...,0,About this item\nFits 2021 - 2022 Ford F-150 6...,Brand BAK\nStyle 2021 - 2022\nExterior Finish ...,https://www.amazon.com/dp/B08L447MY5
8,8,BAK BAKFlip F1 Hard Folding Truck Bed Tonneau ...,"$1,101.24","1,174.99",4.8\n43 ratings,Manufacturer BAK Industries\nBrand BAK\nModel ...,0,About this item\nFits 2021 - 2022 Ford F-150 6...,Brand BAK\nStyle Folding\nExterior Finish Pain...,https://www.amazon.com/dp/B08L459879
9,9,Tyger Auto T5 Alloy Hardtop Truck Bed Tonneau ...,$599.00,$599.00,4.7\n11 ratings,Manufacturer Tyger Auto\nBrand Tyger Auto\nMod...,0,About this item\nFITMENT - Compatible with 201...,Brand Tyger Auto\nStyle Folding\nExterior Fini...,https://www.amazon.com/dp/B08V4B41CR
10,10,BAK BAKFlip MX4 Hard Folding Truck Bed Tonneau...,"$1,101.37","$1,101.37","4.6\n1,469 ratings",Manufacturer BAK Industries\nBrand BAK\nModel ...,0,About this item\nFits 2019 - 2023 Chevy/GMC Si...,Brand BAK\nStyle Folding\nExterior Finish Mach...,https://www.amazon.com/dp/B08V5DDW1X
11,11,Undercover Triad Hard Folding Truck Bed Tonnea...,$922.99,$922.99,0,Manufacturer UnderCover\nBrand RealTruck\nMode...,0,About this item\nFits 2008 - 2016 Ford F-250/3...,Brand RealTruck\nStyle 2008 - 2016\nExterior F...,https://www.amazon.com/dp/B08ZHFB2KV
12,12,ONINE AWH Hard Tri-Fold Truck Bed Tonneau Cove...,$709.99,$709.99,3.8\n116 ratings,Manufacturer ONINE\nBrand ONINE\nModel Z09\nIt...,0,About this item\nCompatibility: engineered for...,Brand ONINE\nStyle Hard Trifold\nExterior Fini...,https://www.amazon.com/dp/B09GJ8TTZQ
13,13,JUST-V Hard Tri-Fold Truck Bed Tonneau Cover R...,$489.98,$489.98,4.1\n29 ratings,Manufacturer Just-V\nBrand Just-V\nItem Weight...,0,About this item\n【Fitment】:Compatible with 201...,Brand Just-V\nStyle Folding\nExterior Finish A...,https://www.amazon.com/dp/B0BXW133N8
14,14,XTWEEX Hard Tri-fold Truck Bed Tonneau Cover F...,$529.31,$529.31,4.5\n14 ratings,Manufacturer XTWEEX\nBrand XTWEEX\nModel XT-NH...,0,About this item\nFitment:Compatible For 2002-2...,Brand XTWEEX\nStyle Folding\nExterior Finish M...,https://www.amazon.com/dp/B0C4G59W9J
15,15,Hard Folding Truck Bed Tonneau Cover Compatiab...,$459.99,499.99,4.8\n8 ratings,Manufacturer WHALEMOTOR\nBrand WHALEMOTOR\nMod...,0,About this item\nVehicle Fitment: (FIT split t...,Brand WHALEMOTOR\nStyle Hinged\nExterior Finis...,https://www.amazon.com/dp/B0CHYHYW1K
16,16,Hard Folding Truck Bed Tonneau Cover Compatiab...,$449.99,489.99,4.8\n8 ratings,Manufacturer WHALEMOTOR\nBrand WHALEMOTOR\nMod...,0,About this item\nVehicle Fitment: (FIT split t...,Brand WHALEMOTOR\nStyle Hinged\nExterior Finis...,https://www.amazon.com/dp/B0CHYK4SFK
17,17,TITANICMOTOR Hard Tri Fold Aluminum Truck Bed ...,$459.99,$459.99,0,Manufacturer TITANICMOTOR\nBrand TITANICMOTOR\...,0,About this item\nExact Fit: Compatible for 200...,Brand TITANICMOTOR\nStyle Hinged\nExterior Fin...,https://www.amazon.com/dp/B0CM6D9YJ1
18,18,TITANICMOTOR Hard Quad Fold Aluminum Truck Bed...,$448.99,$448.99,4.5\n2 ratings,Manufacturer TITANICMOTOR\nBrand TITANICMOTOR\...,0,About this item\nExact Fit: Compatible for 201...,Brand TITANICMOTOR\nStyle Hinged\nExterior Fin...,https://www.amazon.com/dp/B0CM6DB9FL
19,19,AUTOSTARSHIP Fiberglass Tri Hard Truck Bed Ton...,$469.99,$469.99,5.0\n1 rating,Manufacturer AUTOSTARSHIP\nBrand AUTOSTARSHIP\...,0,About this item\nApplication: Compatible for 2...,Brand AUTOSTARSHIP\nStyle Fiberglass Tri Hard\...,https://www.amazon.com/dp/B0CMTKK493

# 5. Post Processing Data and Exporting

In [12]:
df["Rating"]=df["Ratings"].str.split('''\n''',expand=True)[0].astype(float)

In [13]:
df["No of Ratings"]=df["Ratings"].str.split('''\n''',expand=True)[1].str.split(' ',expand=True)[0].str.replace(",","").astype(float)

In [14]:
df['List Price']=df['List Price'].str.replace("$","").str.replace(",","").astype(float)

In [15]:
df["Current Price"]=df['Current Price'].str.replace("$","").str.replace(",","").astype(float)

In [16]:
df['Material']=df['Details_s'].str.split('Material ',expand=True)[1].str.split('''\n''',expand=True)[0]

In [17]:
df["Brand"]=df["Attributes"].str.split('''Brand''',expand=True)[1].str.split('''\n''',expand=True)[0]
df["Manufacturer"]=df["Attributes"].str.split('''Manufacturer''',expand=True)[1].str.split('''\n''',expand=True)[0]
df['Sales_LastMonth']=df['Sales_LastMonth'].astype(int)
df['Source']="Amazon"
del df['Ratings']
df['Sl.No']=df['Sl.No'].astype(int)
df[['Rating',"No of Ratings","Sales_LastMonth",'Manufacturer','Material', "Brand","Source"]]

,Rating,No of Ratings,Sales_LastMonth,Manufacturer,Material,Brand,Source
0,3.4,25.0,0,BAK Industries,Plastic,BAK,Amazon
1,4.5,359.0,0,BAK Industries,Aluminum,BAK,Amazon
2,4.4,206.0,0,BAK,"Fiberglass, Plastic",BAK,Amazon
3,4.4,206.0,0,BAK,Plastic,BAK,Amazon
4,4.3,294.0,0,Lyon cover,Polypropylene,Lyon cover,Amazon
5,4.3,424.0,0,AX5H7,Aluminum,Gator Covers,Amazon
6,4.3,294.0,0,LYCH030A,Polypropylene,Lyon cover,Amazon
7,4.4,553.0,0,BAK Industries,Aluminum,BAK,Amazon
8,4.8,43.0,0,BAK Industries,"Fiberglass, Plastic",BAK,Amazon
9,4.7,11.0,0,Tyger Auto,"Aluminum, Stainless Steel, Alloy Steel",Tyger Auto,Amazon
10,4.6,1469.0,0,BAK Industries,Aluminum,BAK,Amazon
11,0.0,NaN,0,UnderCover,Aluminum,RealTruck,Amazon
12,3.8,116.0,0,ONINE,Aluminum,ONINE,Amazon
13,4.1,29.0,0,Just-V,Fiberglass,Just-V,Amazon
14,4.5,14.0,0,XTWEEX,"Polypropylene, Fiberglass Reinforced Polymer",XTWEEX,Amazon
15,4.8,8.0,0,WHALEMOTOR,"Fiberglass, Aluminum",WHALEMOTOR,Amazon
16,4.8,8.0,0,WHALEMOTOR,"Fiberglass, Aluminum",WHALEMOTOR,Amazon
17,0.0,NaN,0,TITANICMOTOR,"Aluminum, Metal",TITANICMOTOR,Amazon
18,4.5,2.0,0,TITANICMOTOR,"Aluminum, Metal",TITANICMOTOR,Amazon
19,5.0,1.0,0,AUTOSTARSHIP,"Fiberglass, Aluminum, Polypropylene",AUTOSTARSHIP,Amazon

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Sl.No            20 non-null     int32
 1   Name             20 non-null     object
 2   Current Price    20 non-null     float64
 3   List Price       20 non-null     float64
 4   Attributes       20 non-null     object
 5   Sales_LastMonth  20 non-null     int32
 6   Details          20 non-null     object
 7   Details_s        20 non-null     object
 8   Links            20 non-null     object
 9   Rating           20 non-null     float64
 10  No of Ratings    18 non-null     float64
 11  Material         20 non-null     object
 12  Brand            20 non-null     object
 13  Manufacturer     20 non-null     object
 14  Source           20 non-null     object
dtypes: float64(4), int32(2), object(9)
memory usage: 2.9+ KB

In [19]:
cols=["Sl.No","Name","Current Price","List Price","Rating","No of Ratings","Details_s","Details","Sales_LastMonth","Attributes","Brand","Manufacturer",'Material',"Links","Source"]
df=df[cols]

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Sl.No            20 non-null     int32
 1   Name             20 non-null     object
 2   Current Price    20 non-null     float64
 3   List Price       20 non-null     float64
 4   Rating           20 non-null     float64
 5   No of Ratings    18 non-null     float64
 6   Details_s        20 non-null     object
 7   Details          20 non-null     object
 8   Sales_LastMonth  20 non-null     int32
 9   Attributes       20 non-null     object
 10  Brand            20 non-null     object
 11  Manufacturer     20 non-null     object
 12  Material         20 non-null     object
 13  Links            20 non-null     object
 14  Source           20 non-null     object
dtypes: float64(4), int32(2), object(9)
memory usage: 2.9+ KB

In [21]:
df

,Sl.No,Name,Current Price,List Price,Rating,No of Ratings,Details_s,Details,Sales_LastMonth,Attributes,Brand,Manufacturer,Material,Links,Source
0,0,BAK BAKFlip FiberMax Hard Folding Truck Bed To...,1011.99,1142.99,3.4,25.0,Brand BAK\nStyle Folding\nExterior Finish Pain...,About this item\nFits 2008 - 2016 Ford F-250/3...,0,Manufacturer BAK Industries\nBrand BAK\nModel ...,BAK,BAK Industries,Plastic,https://www.amazon.com/dp/B071WNQXRN,Amazon
1,1,BAK BAKFlip MX4 Hard Folding Truck Bed Tonneau...,1117.64,1117.64,4.5,359.0,"Brand BAK\nStyle 2009-2018, 2019-21 Classic\nE...","About this item\nFits 2009-2018, 2019-21 Class...",0,Manufacturer BAK Industries\nBrand BAK\nModel ...,BAK,BAK Industries,Aluminum,https://www.amazon.com/dp/B07213M4RD,Amazon
2,2,BAK BAKFlip FiberMax Hard Folding Truck Bed To...,1047.99,1142.99,4.4,206.0,"Brand BAK\nStyle Folding\nMaterial Fiberglass,...",About this item\nFits 2019 - 2022 Chevy/GMC Si...,0,Manufacturer BAK\nBrand BAK\nModel 1126130\nIt...,BAK,BAK,"Fiberglass, Plastic",https://www.amazon.com/dp/B07GNJNHC4,Amazon
3,3,BAK BAKFlip FiberMax Hard Folding Truck Bed To...,1097.27,1097.27,4.4,206.0,Brand BAK\nStyle Folding\nExterior Finish Pain...,About this item\nFits 2019 - 2022 Chevy/GMC Si...,0,Manufacturer BAK\nBrand BAK\nModel 1126131\nIt...,BAK,BAK,Plastic,https://www.amazon.com/dp/B07GNN6PM1,Amazon
4,4,Lyon cover 6.6'ft Tri-Fold Truck Bed FRP Hard ...,489.00,489.00,4.3,294.0,Brand Lyon cover\nStyle Folding\nExterior Fini...,About this item\n【Fitment】:2014-2021 Silverado...,0,Manufacturer Lyon cover\nBrand Lyon cover\nIte...,Lyon cover,Lyon cover,Polypropylene,https://www.amazon.com/dp/B07TY41TZ3,Amazon
5,5,Gator EFX Hard Tri-Fold Truck Bed Tonneau Cove...,699.00,699.00,4.3,424.0,Brand Gator Covers\nStyle Folding\nExterior Fi...,"About this item\nFits 2014 - 2018, 2019 Ltd/Lg...",0,Manufacturer AX5H7\nBrand Gator Covers\nModel ...,Gator Covers,AX5H7,Aluminum,https://www.amazon.com/dp/B07XLV777G,Amazon
6,6,Lyon cover 5.8ft/69.3inch Hard Tri-Fold Truck ...,479.00,479.00,4.3,294.0,Brand Lyon cover\nStyle Folding\nExterior Fini...,About this item\nFitment :2007-2018 Silverado/...,0,Manufacturer LYCH030A\nBrand Lyon cover\nItem ...,Lyon cover,LYCH030A,Polypropylene,https://www.amazon.com/dp/B08G4KVKYP,Amazon
7,7,BAK BAKFlip MX4 Hard Folding Truck Bed Tonneau...,1055.99,1252.99,4.4,553.0,Brand BAK\nStyle 2021 - 2022\nExterior Finish ...,About this item\nFits 2021 - 2022 Ford F-150 6...,0,Manufacturer BAK Industries\nBrand BAK\nModel ...,BAK,BAK Industries,Aluminum,https://www.amazon.com/dp/B08L447MY5,Amazon
8,8,BAK BAKFlip F1 Hard Folding Truck Bed Tonneau ...,1101.24,1174.99,4.8,43.0,Brand BAK\nStyle Folding\nExterior Finish Pain...,About this item\nFits 2021 - 2022 Ford F-150 6...,0,Manufacturer BAK Industries\nBrand BAK\nModel ...,BAK,BAK Industries,"Fiberglass, Plastic",https://www.amazon.com/dp/B08L459879,Amazon
9,9,Tyger Auto T5 Alloy Hardtop Truck Bed Tonneau ...,599.00,599.00,4.7,11.0,Brand Tyger Auto\nStyle Folding\nExterior Fini...,About this item\nFITMENT - Compatible with 201...,0,Manufacturer Tyger Auto\nBrand Tyger Auto\nMod...,Tyger Auto,Tyger Auto,"Aluminum, Stainless Steel, Alloy Steel",https://www.amazon.com/dp/B08V4B41CR,Amazon
10,10,BAK BAKFlip MX4 Hard Folding Truck Bed Tonneau...,1101.37,1101.37,4.6,1469.0,Brand BAK\nStyle Folding\nExterior Finish Mach...,About this item\nFits 2019 - 2023 Chevy/GMC Si...,0,Manufacturer BAK Industries\nBrand BAK\nModel ...,BAK,BAK Industries,Aluminum,https://www.amazon.com/dp/B08V5DDW1X,Amazon
11,11,Undercover Triad Hard Folding Truck Bed Tonnea...,922.99,922.99,0.0,NaN,Brand RealTruck\nStyle 2008 - 2016\nExterior F...,About this item\nFits 2008 - 2016 Ford F-250/3...,0,Manufacturer UnderCover\nBrand RealTruck\nMode...,RealTruck,UnderCover,Aluminum,https://www.amazon.com/dp/B08ZHFB2KV,Amazon
12,12,ONINE AWH Hard Tri-Fold Truck Bed Tonneau Cove...,709.99,709.99,3.8,116.0,Brand ONINE\nStyle Hard Trifold\nExterior Fini...,About this item\nCompatibility: engineered for...,0,Manufacturer ONINE\nBrand ONINE\nModel Z09\nIt...,ONINE,ONINE,Aluminum,https://www.amazon.com/dp/B09GJ8TTZQ,Amazon
13,13,JUST-V Hard Tri-Fold Truck Bed Tonneau Cover R...,489.98,489.98,4.1,29.0,Brand Just-V\nStyle Folding\nExterior Finish A...,About this item\n【Fitment】:Compatible with 201...,0,Manufacturer Just-V\nBrand Just-V\nItem Weight...,Just-V,Just-V,Fiberglass,https://www.amazon.com/dp/B0BXW133N8,Amazon
14,14,XTWEEX Hard Tri-fold Truck Bed Tonneau Cover F...,529.31,529.31,4.5,14.0,Brand XTWEEX\nStyle Folding\nExterior Finish M...,About this item\nFitment:Compatible For 2002-2...,0,Manufacturer XTWEEX\nBrand XTWEEX\nModel XT-NH...,XTWEEX,XTWEEX,"Polypropylene, Fiberglass Reinforced Polymer",https://www.amazon.com/dp/B0C4G59W9J,Amazon
15,15,Hard Folding Truck Bed Tonneau Cover Compatiab...,459.99,499.99,4.8,8.0,Brand WHALEMOTOR\nStyle Hinged\nExterior Finis...,About this item\nVehicle Fitment: (FIT split t...,0,Manufacturer WHALEMOTOR\nBrand WHALEMOTOR\nMod...,WHALEMOTOR,WHALEMOTOR,"Fiberglass, Aluminum",https://www.amazon.com/dp/B0CHYHYW1K,Amazon
16,16,Hard Folding Truck Bed Tonneau Cover Compatiab...,449.99,489.99,4.8,8.0,Brand WHALEMOTOR\nStyle Hinged\nExterior Finis...,About this item\nVehicle Fitment: (FIT split t...,0,Manufacturer WHALEMOTOR\nBrand WHALEMOTOR\nMod...,WHALEMOTOR,WHALEMOTOR,"Fiberglass, Aluminum",https://www.amazon.com/dp/B0CHYK4SFK,Amazon
17,17,TITANICMOTOR Hard Tri Fold Aluminum Truck Bed ...,459.99,459.99,0.0,NaN,Brand TITANICMOTOR\nStyle Hinged\nExterior Fin...,About this item\nExact Fit: Compatible for 200...,0,Manufacturer TITANICMOTOR\nBrand TITANICMOTOR\...,TITANICMOTOR,TITANICMOTOR,"Aluminum, Metal",https://www.amazon.com/dp/B0CM6D9YJ1,Amazon
18,18,TITANICMOTOR Hard Quad Fold Aluminum Truck Bed...,448.99,448.99,4.5,2.0,Brand TITANICMOTOR\nStyle Hinged\nExterior Fin...,About this item\nExact Fit: Compatible for 201...,0,Manufacturer TITANICMOTOR\nBrand TITANICMOTOR\...,TITANICMOTOR,TITANICMOTOR,"Aluminum, Metal",https://www.amazon.com/dp/B0CM6DB9FL,Amazon
19,19,AUTOSTARSHIP Fiberglass Tri Hard Truck Bed Ton...,469.99,469.99,5.0,1.0,Brand AUTOSTARSHIP\nStyle Fiberglass Tri Hard\...,About this item\nApplication: Compatible for 2...,0,Manufacturer AUTOSTARSHIP\nBrand AUTOSTARSHIP\...,AUTOSTARSHIP,AUTOSTARSHIP,"Fiberglass, Aluminum, Polypropylene",https://www.amazon.com/dp/B0CMTKK493,Amazon

In [22]:
df.to_excel('SKU_Details.xlsx', index=False)