In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib.parse import unquote
from selenium.webdriver.support.ui import Select
import pandas as pd
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import datetime 
import warnings
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
from IPython.display import clear_output

In [2]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.maximize_window()
wait=WebDriverWait(driver, 10)
driver.get("https://www.moparpartsgiant.com/")

In [3]:
cols=["Sl.No"]
df= pd.DataFrame(columns=cols)
count=0

In [4]:
List=["4728037AC",
"4728038AC",
"56028258AA",
"56028280AA",
"SPW08038AA",
"4728037AE",
"4728038AF",
"5017058AA",
"56028277AB",
"56041851AA",
"56026848",
"56026845",
"5093692AA",
"5093693AA",
"4796500AC",
"5101780AA",
"53006568",
"5093695AA",
"56028386AB"
]
print(len(List))

19

In [5]:
from tqdm import tqdm
for i in tqdm(range(len(List))): #len(List)):
    print(f"running {i}th element | {List[i]}")
    search_text=f"{List[i]}"
    searchbox=wait.until(EC.element_to_be_clickable((By.CLASS_NAME,"ab-input-control")))
    sleep(1)
    searchbox.click()
    searchbox.send_keys(search_text)
    searchbox.submit()
    sleep(1)
    element=wait.until(EC.presence_of_element_located((By.XPATH, ".//div[@class='pn-tab-title'][h2/text()='Vehicle Fitment']")))
    driver.execute_script("arguments[0].scrollIntoView();", element)
    element.click()
    try:
        wait.until(EC.presence_of_element_located((By.CLASS_NAME,"fit-vehicle-list-view-text"))).click()
    except:
        pass
    tablecontent=driver.find_elements(By.CLASS_NAME,"fit-vehicle-list-text")

    for i in range(len(tablecontent)):
        if i%3==0:
            df.loc[count,"YMM"]= tablecontent[i].text.replace(",","")
        if i%3==1:
            df.loc[count,"EnineList"]= tablecontent[i].text
        if i%3==2:
            df.loc[count,"Vehicle Options"]= tablecontent[i].text
            df.loc[count,"PartNumber"]=search_text
            count=count+1

  0%|          | 0/19 [00:00<?, ?it/s]

running 0th element | 4728037AC

  5%|▌         | 1/19 [00:13<03:59, 13.29s/it]

running 1th element | 4728038AC

 11%|█         | 2/19 [00:26<03:44, 13.21s/it]

running 2th element | 56028258AA

 16%|█▌        | 3/19 [00:39<03:30, 13.16s/it]

running 3th element | 56028280AA

 21%|██        | 4/19 [00:52<03:16, 13.10s/it]

running 4th element | SPW08038AA

 26%|██▋       | 5/19 [00:55<02:11,  9.37s/it]

running 5th element | 4728037AE

 32%|███▏      | 6/19 [01:08<02:18, 10.68s/it]

running 6th element | 4728038AF

 37%|███▋      | 7/19 [01:11<01:36,  8.04s/it]

running 7th element | 5017058AA

 42%|████▏     | 8/19 [01:24<01:45,  9.62s/it]

running 8th element | 56028277AB

 47%|████▋     | 9/19 [01:37<01:47, 10.75s/it]

running 9th element | 56041851AA

 53%|█████▎    | 10/19 [01:50<01:42, 11.41s/it]

running 10th element | 56026848

 58%|█████▊    | 11/19 [02:03<01:35, 11.94s/it]

running 11th element | 56026845

 63%|██████▎   | 12/19 [02:16<01:25, 12.21s/it]

running 12th element | 5093692AA

 68%|██████▊   | 13/19 [02:29<01:15, 12.50s/it]

running 13th element | 5093693AA

 74%|███████▎  | 14/19 [02:42<01:02, 12.60s/it]

running 14th element | 4796500AC

 79%|███████▉  | 15/19 [02:55<00:51, 12.83s/it]

running 15th element | 5101780AA

 84%|████████▍ | 16/19 [03:08<00:38, 12.84s/it]

running 16th element | 53006568

 89%|████████▉ | 17/19 [03:21<00:25, 12.83s/it]

running 17th element | 5093695AA

 95%|█████████▍| 18/19 [03:34<00:12, 12.83s/it]

running 18th element | 56028386AB

100%|██████████| 19/19 [03:47<00:00, 11.97s/it]

In [6]:
df

,Sl.No,YMM,EnineList,Vehicle Options,PartNumber
0,NaN,1999-2000 Dodge Dakota,6 Cyl 3.9L,"Club Cab 2WD, Club Cab 4WD, Quad Cab 2WD, Quad...",4728037AC
1,NaN,1999-2000 Dodge Durango,6 Cyl 3.9L,"Base 2WD, Base 4WD",4728037AC
2,NaN,1999-2001 Dodge Ram 1500,6 Cyl 3.9L,"Regular Cab 2WD, Regular Cab 4WD",4728037AC
3,NaN,1999-2001 Dodge Ram 2500,,"Regular Cab 2WD, Regular Cab 4WD, Regular Cab ...",4728037AC
4,NaN,1999-2001 Dodge Ram 3500,,"Regular Cab 2WD, Regular Cab 4WD, Regular Cab ...",4728037AC
...,...,...,...,...,...
92,NaN,2001 Dodge Ram 3500,8 Cyl 5.9L,"Quad Cab 2WD, Quad Cab 4WD",5093695AA
93,NaN,2004 Dodge Durango,8 Cyl 5.7L,"Limited 2WD, Limited 4WD, SLT 2WD, SLT 4WD, ST...",56028386AB
94,NaN,2003-2005 Dodge Ram 1500,8 Cyl 5.7L,"SLT Quad Cab 2WD, SLT Quad Cab 4WD, SLT Regula...",56028386AB
95,NaN,2003-2004 Dodge Ram 2500,8 Cyl 5.7L,"SLT Quad Cab 2WD, SLT Quad Cab 4WD, SLT Regula...",56028386AB
96,NaN,2003-2004 Dodge Ram 3500,8 Cyl 5.7L,"SLT Quad Cab 2WD, SLT Quad Cab 4WD, SLT Regula...",56028386AB

In [7]:
" ".join(df["YMM"][11].split(" ")[(2):])

'Ram 2500'

In [8]:
for i in range(len(df)):
    if "," in df["YMM"][i]:
        n=df["YMM"][i].count(",")
        df.at[i,"Model_Years"]=df['YMM'][i].split(" ")[0:(1+n)]
        df.loc[i,"Make"]=df["YMM"][i].split(" ")[(1+n)]
        df.loc[i,"Model"]=" ".join(df["YMM"][i].split(" ")[(2+n):])
        
        print(n)
    else:
        df.at[i,"Model_Years"]=df['YMM'][i].split(" ")[0:(1)]
        df.loc[i,"Make"]=df["YMM"][i].split(" ")[1]
        df.loc[i,"Model"]=" ".join(df["YMM"][i].split(" ")[2:])

df=df.explode("Model_Years")

df = df.reset_index(drop=True)
for i in range(len(df)):
    if "-" in df['Model_Years'][i]:
        #print(i)
        year=df['Model_Years'].str.split('-')[i]
        startyear=year[0]
        endyear=year[1]
        df.loc[i,'Start_Year']=startyear
        df.loc[i,'End_Year']=endyear
    if "-" not in df['Model_Years'][i]:
        #print (i)
        df.loc[i,'Start_Year']=df['Model_Years'][i]
        df.loc[i,'End_Year']=df['Model_Years'][i]


df['Start_Year']=df['Start_Year'].str.replace(",","").replace(" ","").astype(int)
df['End_Year']=df['End_Year'].str.replace(",","").replace(" ","").astype(int)

In [9]:
df

,Sl.No,YMM,EnineList,Vehicle Options,PartNumber,Model_Years,Make,Model,Start_Year,End_Year
0,NaN,1999-2000 Dodge Dakota,6 Cyl 3.9L,"Club Cab 2WD, Club Cab 4WD, Quad Cab 2WD, Quad...",4728037AC,1999-2000,Dodge,Dakota,1999,2000
1,NaN,1999-2000 Dodge Durango,6 Cyl 3.9L,"Base 2WD, Base 4WD",4728037AC,1999-2000,Dodge,Durango,1999,2000
2,NaN,1999-2001 Dodge Ram 1500,6 Cyl 3.9L,"Regular Cab 2WD, Regular Cab 4WD",4728037AC,1999-2001,Dodge,Ram 1500,1999,2001
3,NaN,1999-2001 Dodge Ram 2500,,"Regular Cab 2WD, Regular Cab 4WD, Regular Cab ...",4728037AC,1999-2001,Dodge,Ram 2500,1999,2001
4,NaN,1999-2001 Dodge Ram 3500,,"Regular Cab 2WD, Regular Cab 4WD, Regular Cab ...",4728037AC,1999-2001,Dodge,Ram 3500,1999,2001
...,...,...,...,...,...,...,...,...,...,...
92,NaN,2001 Dodge Ram 3500,8 Cyl 5.9L,"Quad Cab 2WD, Quad Cab 4WD",5093695AA,2001,Dodge,Ram 3500,2001,2001
93,NaN,2004 Dodge Durango,8 Cyl 5.7L,"Limited 2WD, Limited 4WD, SLT 2WD, SLT 4WD, ST...",56028386AB,2004,Dodge,Durango,2004,2004
94,NaN,2003-2005 Dodge Ram 1500,8 Cyl 5.7L,"SLT Quad Cab 2WD, SLT Quad Cab 4WD, SLT Regula...",56028386AB,2003-2005,Dodge,Ram 1500,2003,2005
95,NaN,2003-2004 Dodge Ram 2500,8 Cyl 5.7L,"SLT Quad Cab 2WD, SLT Quad Cab 4WD, SLT Regula...",56028386AB,2003-2004,Dodge,Ram 2500,2003,2004
96,NaN,2003-2004 Dodge Ram 3500,8 Cyl 5.7L,"SLT Quad Cab 2WD, SLT Quad Cab 4WD, SLT Regula...",56028386AB,2003-2004,Dodge,Ram 3500,2003,2004

In [10]:
df['Years'] = df.apply(lambda row: list(range(row['Start_Year'], row['End_Year'] + 1)), axis=1)
df.drop(columns={'End_Year','Start_Year'})
df=df.explode('Years')
df=df.drop(columns={'End_Year','Start_Year'})

df["Engine"]=df["EnineList"].str.split(", ")
df=df.explode("Engine")

In [11]:
df.columns

Index(['Sl.No', 'YMM', 'EnineList', 'Vehicle Options', 'PartNumber',
       'Model_Years', 'Make', 'Model', 'Years', 'Engine'],
      dtype='object')

In [12]:
dfo=df[['Make','Model', 'Years', 'Engine', 'Vehicle Options', 'PartNumber']]

In [13]:
dfo

,Make,Model,Years,Engine,Vehicle Options,PartNumber
0,Dodge,Dakota,1999,6 Cyl 3.9L,"Club Cab 2WD, Club Cab 4WD, Quad Cab 2WD, Quad...",4728037AC
0,Dodge,Dakota,2000,6 Cyl 3.9L,"Club Cab 2WD, Club Cab 4WD, Quad Cab 2WD, Quad...",4728037AC
1,Dodge,Durango,1999,6 Cyl 3.9L,"Base 2WD, Base 4WD",4728037AC
1,Dodge,Durango,2000,6 Cyl 3.9L,"Base 2WD, Base 4WD",4728037AC
2,Dodge,Ram 1500,1999,6 Cyl 3.9L,"Regular Cab 2WD, Regular Cab 4WD",4728037AC
...,...,...,...,...,...,...
94,Dodge,Ram 1500,2005,8 Cyl 5.7L,"SLT Quad Cab 2WD, SLT Quad Cab 4WD, SLT Regula...",56028386AB
95,Dodge,Ram 2500,2003,8 Cyl 5.7L,"SLT Quad Cab 2WD, SLT Quad Cab 4WD, SLT Regula...",56028386AB
95,Dodge,Ram 2500,2004,8 Cyl 5.7L,"SLT Quad Cab 2WD, SLT Quad Cab 4WD, SLT Regula...",56028386AB
96,Dodge,Ram 3500,2003,8 Cyl 5.7L,"SLT Quad Cab 2WD, SLT Quad Cab 4WD, SLT Regula...",56028386AB
96,Dodge,Ram 3500,2004,8 Cyl 5.7L,"SLT Quad Cab 2WD, SLT Quad Cab 4WD, SLT Regula...",56028386AB

In [14]:
OFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\Mopar Parts Giant'

with pd.ExcelWriter(OFolder+'\MorparPartsGiant-CableSet_OE PartNumber_Expanded.xlsx') as writer:  
    dfo.to_excel(writer,index=False, sheet_name='Cleaned')
    df.to_excel(writer,index=False, sheet_name='Raw')