# 1. Library calling

In [65]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
import warnings
from tqdm import tqdm
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
import os

# 2. Defining the Product Information and Location

# 3. Setting Webdriver and Website Specific Information

In [4]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
wait=WebDriverWait(driver, 5)
driver.get('https://motorad.com/products/?categories=thermostat&subcategories=standard-naked-thermostat%2Cultrastat%2Cstandard-fail-safe%2Chd-thermostat%2Ceconomy-thermostat%2Cpower-sport-thermostat%2Cthermostat-w-housing%2Cwater-pump-thermostat-assembly%2Chd-thermostat-w-housing%2Cthermostat-kit-ultrastat%2Cthermostat-assembly-fail-safe%2Cthermostat-assembly%2Cfail-safe-thermostat-w-housing')

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [96]:
cols =['Sl.No','PartNumber','PartName',"Link"] #,'Review_Mentions'
df = pd.DataFrame(columns=cols)
df
count=0

In [93]:
driver.find_element(By.XPATH, f"//button[span[text()='{9}']]").click()

In [97]:
for i in range(133):
    try:
        driver.find_element(By.XPATH, f"//button[span[text()='{i+3}']]").click()
    except:
        pass
    PartNumbers=driver.find_elements(By.CSS_SELECTOR,'[x-text="`SKU: #${part.part_number}`"]')
    Names=driver.find_elements(By.CSS_SELECTOR,'[x-text="part.long_desc"]')
    Links=driver.find_elements(By.XPATH, "//a[contains(@class, 'transition-all')]")
    sleep(2)
    for pn, name, link in zip(PartNumbers,Names,Links):
        df.loc[count,"Sl.No"]=count
        df.loc[count,'PageNumber']=i+3
        df.loc[count,"PartNumber"]=pn.text
        df.loc[count,"PartName"]=name.text
        df.loc[count,"Link"]=link.get_attribute('href')
        count=count+1

StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
	GetHandleVerifier [0x00007FF71EFBC6A5+28789]
	(No symbol) [0x00007FF71EF25B20]
	(No symbol) [0x00007FF71EDB8F9A]
	(No symbol) [0x00007FF71EDC09A9]
	(No symbol) [0x00007FF71EDC376C]
	(No symbol) [0x00007FF71EDC383F]
	(No symbol) [0x00007FF71EE08F86]
	(No symbol) [0x00007FF71EE3732A]
	(No symbol) [0x00007FF71EE01BC6]
	(No symbol) [0x00007FF71EE37540]
	(No symbol) [0x00007FF71EE5F7E3]
	(No symbol) [0x00007FF71EE37103]
	(No symbol) [0x00007FF71EDFFFC0]
	(No symbol) [0x00007FF71EE01273]
	GetHandleVerifier [0x00007FF71F301AED+3458237]
	GetHandleVerifier [0x00007FF71F31829C+3550316]
	GetHandleVerifier [0x00007FF71F30DB9D+3507565]
	GetHandleVerifier [0x00007FF71F082C6A+841274]
	(No symbol) [0x00007FF71EF309EF]
	(No symbol) [0x00007FF71EF2CB34]
	(No symbol) [0x00007FF71EF2CCD6]
	(No symbol) [0x00007FF71EF1C119]
	(No symbol) [0x00007FFC0C567374]
	RtlUserThreadStart [0x00007FFC0D09CC91+33]

In [105]:
PartNumbers=driver.find_elements(By.CSS_SELECTOR,'[x-text="`SKU: #${part.part_number}`"]')
Names=driver.find_elements(By.CSS_SELECTOR,'[x-text="part.long_desc"]')
Links=driver.find_elements(By.XPATH, "//a[contains(@class, 'transition-all')]")
sleep(2)
for pn, name, link in zip(PartNumbers,Names,Links):
    df.loc[count,"Sl.No"]=count
    df.loc[count,'PageNumber']=i+3
    df.loc[count,"PartNumber"]=pn.text
    df.loc[count,"PartName"]=name.text
    df.loc[count,"Link"]=link.get_attribute('href')
    count=count+1

In [107]:
df.columns

Index(['Sl.No', 'PartNumber', 'PartName', 'Link', 'PageNumber'], dtype='object')

In [109]:
df_cleaned=df[['PartNumber', 'PartName', 'Link']].drop_duplicates().reset_index(drop=True)
df_cleaned

,PartNumber,PartName,Link
0,SKU: #821070,HD Thermostat-170 Degrees,https://motorad.com/part/821070
1,SKU: #821080,HD Thermostat-180 Degrees,https://motorad.com/part/821080
2,SKU: #880060,Thermostat-160 Degrees w/ Seals,https://motorad.com/part/880060
3,SKU: #880070,Thermostat-170 Degrees w/ Seals,https://motorad.com/part/880070
4,SKU: #880080,Thermostat-180 Degrees w/ Seals,https://motorad.com/part/880080
...,...,...,...
1188,SKU: #246-192,Thermostat-192 Degrees,https://motorad.com/part/246-192
1189,SKU: #247-160,Thermostat-160 Degrees,https://motorad.com/part/247-160
1190,SKU: #247-174,Thermostat-174 Degrees,https://motorad.com/part/247-174
1191,SKU: #247-180,Thermostat-180 Degrees,https://motorad.com/part/247-180
1192,SKU: #247-192,Thermostat-192 Degrees,https://motorad.com/part/247-192

In [68]:
df=pd.read_csv('Thermostat.csv')

In [69]:
df

,PartNumber,PartName,Link
0,SKU: #821070,HD Thermostat-170 Degrees,https://motorad.com/part/821070
1,SKU: #821080,HD Thermostat-180 Degrees,https://motorad.com/part/821080
2,SKU: #880060,Thermostat-160 Degrees w/ Seals,https://motorad.com/part/880060
3,SKU: #880070,Thermostat-170 Degrees w/ Seals,https://motorad.com/part/880070
4,SKU: #880080,Thermostat-180 Degrees w/ Seals,https://motorad.com/part/880080
...,...,...,...
1188,SKU: #246-192,Thermostat-192 Degrees,https://motorad.com/part/246-192
1189,SKU: #247-160,Thermostat-160 Degrees,https://motorad.com/part/247-160
1190,SKU: #247-174,Thermostat-174 Degrees,https://motorad.com/part/247-174
1191,SKU: #247-180,Thermostat-180 Degrees,https://motorad.com/part/247-180
1192,SKU: #247-192,Thermostat-192 Degrees,https://motorad.com/part/247-192

In [70]:
df['Link'][1]

'https://motorad.com/part/821080'

In [84]:
cols =['PartNumber'] #,'Review_Mentions'
dfIC = pd.DataFrame(columns=cols)
countIC=0
df_a = pd.DataFrame(columns=cols)
counta=0

In [85]:
for i in tqdm(range(len(df))):
    driver.get(df['Link'][i])
    print("Partnumber:",df['PartNumber'][i],"the value of i is",i)
    sleep(2)
    driver.find_elements(By.CLASS_NAME,"border-transparent")[1].click() # Application
    sleep(2)
    ICList=driver.find_element(By.CLASS_NAME,'gap-4').text.split("\n")
    for ic in range(len(ICList)):
        Cust=ICList[ic].rsplit(' ', 1)[0]
        ICNum=ICList[ic].rsplit(' ', 1)[1]
        dfIC.loc[countIC,'PartNumber']=df['PartNumber'][i] 
        dfIC.loc[countIC,"Customer"]=Cust
        dfIC.loc[countIC,"InterchangeNumber"]=ICNum
        countIC=countIC+1
    driver.find_elements(By.CLASS_NAME,"border-transparent")[1].click() # Application
    sleep(2)
    Years=driver.find_elements(By.CSS_SELECTOR,'[x-text="application.year"]')
    Makes=driver.find_elements(By.CSS_SELECTOR,'[x-text="application.make"]')
    Models=driver.find_elements(By.CSS_SELECTOR,'[x-text="application.model"]')
    Engines=driver.find_elements(By.CSS_SELECTOR,'''[x-text="application.displacement_liters + 'L'"]''')
    for year, make, model, engine in zip(Years,Makes, Models, Engines):
        df_a.loc[counta,'PartNumber']=df['PartNumber'][i]   
        df_a.loc[counta,'Year']=year.text
        df_a.loc[counta,'Make']=make.text
        df_a.loc[counta,'Model']=model.text
        df_a.loc[counta,'Engine']=engine.text
        counta=counta+1
    clear_output(wait=True)

100%|██████████| 1193/1193 [3:22:07<00:00, 10.17s/it]

In [86]:
dfIC

          PartNumber        Customer InterchangeNumber
0       SKU: #821070         Advance             14007
1       SKU: #821070            AETM             14007
2       SKU: #821070        Autozone              4007
3       SKU: #821070          Cartek            821070
4       SKU: #821070  Detroit Diesel           5104238
...              ...             ...               ...
16564  SKU: #247-192            NAPA           192-742
16565  SKU: #247-192         OReilly              3589
16566  SKU: #247-192        Pep Boys           247-192
16567  SKU: #247-192           Stant             13509
16568  SKU: #247-192      Volkswagen         069121113

[16569 rows x 3 columns]

In [87]:
df_a

          PartNumber  Year           Make        Model Engine
0       SKU: #821070  1979  International         2275   7.0L
1       SKU: #821070  1979  International         2574   9.3L
2       SKU: #821070  1979  International         2575   7.0L
3       SKU: #821070  1979  International         2575   9.3L
4       SKU: #821070  1979  International         2275   9.3L
...              ...   ...            ...          ...    ...
60412  SKU: #247-192  2008     Volkswagen  Crafter Van   2.5L
60413  SKU: #247-192  2009     Volkswagen  Crafter Van   2.5L
60414  SKU: #247-192  2010     Volkswagen  Crafter Van   2.5L
60415  SKU: #247-192  2011     Volkswagen  Crafter Van   2.5L
60416  SKU: #247-192  2012     Volkswagen  Crafter Van   2.5L

[60417 rows x 5 columns]

In [88]:
OFolder=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\MotoRad"
Source="MotoRad"
search_text="Thermostat"

In [89]:
with pd.ExcelWriter(OFolder+'\\'+f'{Source}ProductDetails_'+search_text+'.xlsx') as writer:  # doctest: +SKIP
    df.to_excel(writer,index=False, sheet_name='Raw')
    df_a.to_excel(writer,index=False, sheet_name='Application_Detail')
    dfIC.to_excel(writer,index=False, sheet_name='Interchange_Detail')