# 1. Library calling

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
import warnings
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
from selenium.webdriver.support.ui import Select
from janitor import xlsx_table
from tqdm import tqdm

# 2. Defining the Product Information and Location

In [33]:
Output_Folder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\96_Competitor Data\NGK Parts\Outputs'
Product_Name="Oxygen_Sensor"

## Part Number Extraction

In [34]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
wait=WebDriverWait(driver, 10)
driver.get('https://www.ngk.com/ntk-oxygen-sensors-ngk?pagesize=40')

In [42]:
cols2 =['Sl.No'] #,'Review_Mentions'
df_out= pd.DataFrame(columns=cols2)
count=0

In [8]:
driver.find_elements(By.CSS_SELECTOR,'[class="product-title"]')[1].text

'NTK 21001 OE Identical Oxygen Sensor'

In [15]:
driver.find_elements(By.CSS_SELECTOR,'[class="sku"]')[1].text.split("#")[1]

'21001'

In [19]:
driver.find_elements(By.CSS_SELECTOR,'[class="product-list-price"]')[2].text

'$24.54 USD'

In [20]:
driver.find_elements(By.XPATH,'//h2[@class="product-title"]/a')[2].get_attribute('href')

'https://www.ngk.com/ntk-21002-oe-identical-oxygen-sensor'

In [43]:
for i in tqdm(range (50)):
    print(f'''Number of pages passed: {i},
          Number of Items Scraped{len(df_out)}''')
    Names=driver.find_elements(By.CSS_SELECTOR,'[class="product-title"]')
    PartNumbers=driver.find_elements(By.CSS_SELECTOR,'[class="sku"]')
    ListedPrices=driver.find_elements(By.CSS_SELECTOR,'[class="product-list-price"]')
    Links=driver.find_elements(By.XPATH,'//h2[@class="product-title"]/a')

    for Name, PN, LP,Link in zip(Names,PartNumbers,ListedPrices,Links):
        df_out.loc[count,'PartName']=Name.text
        df_out.loc[count,'PartNumber']=PN.text.split("#")[1]
        df_out.loc[count,'ListedPrice']=LP.text
        df_out.loc[count,'Links']=Link.get_attribute('href')
        count=count+1

    driver.find_element(By.CSS_SELECTOR,'[class="next-page"]').click()
    clear_output(wait=True)

 88%|████████▊ | 44/50 [14:51<02:10, 21.75s/it]

44 1760

 88%|████████▊ | 44/50 [14:52<02:01, 20.28s/it]

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[class="next-page"]"}
  (Session info: chrome=129.0.6668.90); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF60582B095+29557]
	(No symbol) [0x00007FF60579FA50]
	(No symbol) [0x00007FF60565B56A]
	(No symbol) [0x00007FF6056AF695]
	(No symbol) [0x00007FF6056AF8EC]
	(No symbol) [0x00007FF6056FB777]
	(No symbol) [0x00007FF6056D71CF]
	(No symbol) [0x00007FF6056F851C]
	(No symbol) [0x00007FF6056D6F33]
	(No symbol) [0x00007FF6056A116F]
	(No symbol) [0x00007FF6056A22D1]
	GetHandleVerifier [0x00007FF605B5C96D+3378253]
	GetHandleVerifier [0x00007FF605BA8497+3688311]
	GetHandleVerifier [0x00007FF605B9D1CB+3642539]
	GetHandleVerifier [0x00007FF6058EA6B6+813462]
	(No symbol) [0x00007FF6057AAB5F]
	(No symbol) [0x00007FF6057A6B74]
	(No symbol) [0x00007FF6057A6D10]
	(No symbol) [0x00007FF605795C1F]
	BaseThreadInitThunk [0x00007FFA88387344+20]
	RtlUserThreadStart [0x00007FFA88DA26B1+33]

In [45]:
df_out.head(5)

,Sl.No,PartName,PartNumber,ListedPrice,Links
0,NaN,NTK 21000 Universal Oxygen Sensor,21000,Not Available,https://www.ngk.com/ntk-21000-universal-oxygen...
1,NaN,NTK 21001 OE Identical Oxygen Sensor,21001,Not Available,https://www.ngk.com/ntk-21001-oe-identical-oxy...
2,NaN,NTK 21002 OE Identical Oxygen Sensor,21002,$24.54 USD,https://www.ngk.com/ntk-21002-oe-identical-oxy...
3,NaN,NTK 21003 OE Identical Oxygen Sensor,21003,Not Available,https://www.ngk.com/ntk-21003-oe-identical-oxy...
4,NaN,NTK 21004 OE Identical Oxygen Sensor,21004,$31.62 USD,https://www.ngk.com/ntk-21004-oe-identical-oxy...

## Part Number Extraction

In [13]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
wait=WebDriverWait(driver, 10)
driver.get('https://www.ngk.com/ntk-oxygen-sensors-ngk?pagesize=40')

In [4]:
df_in=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\96_Competitor Data\NGK Parts\Outputs\NGK_Export_Oxygen_Sensor.xlsx")

In [5]:
df_in.head()

,Sl.No,PartName,PartNumber,ListedPrice,Links
0,0,NTK 21000 Universal Oxygen Sensor,21000,Not Available,https://www.ngk.com/ntk-21000-universal-oxygen...
1,1,NTK 21001 OE Identical Oxygen Sensor,21001,Not Available,https://www.ngk.com/ntk-21001-oe-identical-oxy...
2,2,NTK 21002 OE Identical Oxygen Sensor,21002,$24.54 USD,https://www.ngk.com/ntk-21002-oe-identical-oxy...
3,3,NTK 21003 OE Identical Oxygen Sensor,21003,Not Available,https://www.ngk.com/ntk-21003-oe-identical-oxy...
4,4,NTK 21004 OE Identical Oxygen Sensor,21004,$31.62 USD,https://www.ngk.com/ntk-21004-oe-identical-oxy...

In [6]:
cols2 =['Spec'] #,'Review_Mentions'
df_out= pd.DataFrame(columns=cols2)
count=0

In [147]:
driver.find_element(By.CSS_SELECTOR,'[aria-controls="productFitment"]').click()

In [11]:
print(range(10))

range(0, 10)

In [9]:
for i in tqdm(range(33,len(df_in))):
    print(i)
    sleep(1)
    driver.get(df_in['Links'][i])
    driver.find_element(By.CSS_SELECTOR,'[aria-controls="productSpecifications"]').click()
    spec=driver.find_element(By.CSS_SELECTOR, '[id="productSpecifications"]').text

    driver.find_element(By.CSS_SELECTOR,'[aria-controls="productFitment"]').click()

    for k in range(1000):
        try:
            driver.find_elements(By.CSS_SELECTOR,'[class="product-fitment__title"]')[k].click()
            sleep(0.5)
        except:
            pass

    vfits=driver.find_elements(By.CLASS_NAME,'verify-fitment')
    for vfit in vfits:
        vfit.get_attribute('data-vehicle').split('"FullVehicleName":"')[1].split('''",''')[0]
        df_out.loc[count,'PartNumber']=df_in['PartNumber'][i]
        df_out.loc[count,'VehicleFitment']=vfit.get_attribute('data-vehicle').split('"FullVehicleName":"')[1].split('''",''')[0]
        df_out.loc[count, 'Spec']=spec
        count=count+1
    clear_output(wait=True)

  0%|          | 5/1758 [01:56<12:12:50, 25.08s/it]

38

  0%|          | 5/1758 [01:58<11:30:34, 23.64s/it]

AttributeError: 'NoneType' object has no attribute 'click'

In [12]:
df_out

            Spec PartNumber                VehicleFitment
0     Dimensions      21002    1999 Chevrolet Malibu Base
1     Dimensions      21002      1999 Chevrolet Malibu LS
2     Dimensions      21002      1999 Pontiac Grand Am GT
3     Dimensions      21002      1999 Pontiac Grand Am SE
4     Dimensions      21002     1998 Buick Skylark Custom
...          ...        ...                           ...
5359  Dimensions      21049            2002 GMC Envoy SLE
5360  Dimensions      21049            2002 GMC Envoy SLT
5361  Dimensions      21049         2002 GMC Envoy XL SLE
5362  Dimensions      21049         2002 GMC Envoy XL SLT
5363  Dimensions      21049  2002 Oldsmobile Bravada Base

[5364 rows x 3 columns]

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [46]:
with pd.ExcelWriter(Output_Folder+'\\'+f'NGK_Export_{Product_Name}'+'.xlsx') as writer:  # doctest: +SKIP
    df_out.to_excel(writer,index=True, sheet_name='Raw')

# 99. Archived Codes

In [515]:
cols2 =['Sl.No'] #,'Review_Mentions'
df3= pd.DataFrame(columns=cols2)
count=0

In [ ]:
#New Content
for i in tqdm(range(1966,len(df1))):
    selectedyear=df1.loc[i,'Years']
    selectedmake=df1.loc[i,'Make']
    selectedmodel=df1.loc[i,'Model']
    selectedengine1=df1.loc[i,'engcomb1']
    selectedengine2=df1.loc[i,'engcomb2']
    print(i,"|",selectedyear," ",selectedmake," ",selectedmodel," ",selectedengine1,selectedengine2)
    print(len(df2))
    year=wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,'[aria-labelledby="year-select"]')))
    year.click()
    y1=df1.loc[i,'Years']+1
    sleep(1)
    wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,f'[data-value="{y1}"]'))).click()
    year=wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,'[aria-labelledby="year-select"]')))    
    year.click()
    sy=wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,f'[data-value="{selectedyear}"]')))    
    sy.click()
    sleep(1)    
    #-----------------------------------------------------------------------------------------------------------------------------------------
    make=wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,'[aria-labelledby="make-select"]')))    
    make.click()
    sm=wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,f'[data-value="{selectedmake}"]')))    
    sm.click()
    sleep(1)
    #-----------------------------------------------------------------------------------------------------------------------------------------
    model=wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,'[aria-labelledby="model-select"]')))    
    model.click()
    smo=wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,f'[data-value="{selectedmodel}"]')))    
    smo.click()
    sleep(1)
    #-----------------------------------------------------------------------------------------------------------------------------------------
    engine=wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,'[aria-labelledby="engine-select"]')))    
    engine.click()
    ptype=wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,'[aria-labelledby="product-type-select"]')))
    try:
        try:
            se=wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,f'[data-value="{selectedengine2}"]')))            
            se.click()
        except:
            se=wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,f'[data-value="{selectedengine1}"]')))            
            se.click()
        
        #-----------------------------------------------------------------------------------------------------------------------------------------
        ptype.click()        
        # clear=wait.until(EC.presence_of_element_located((By.XPATH,f"//li[text()='All Products']")
        # clear.click()
        #ptype.clear()
        try:
            ProductType='NGK Ignition Coils, Wire Sets & COP Boots'
            sp=wait.until(EC.presence_of_element_located((By.XPATH,f"//li[text()='{ProductType}']")))
            sp.click()
            #-----------------------------------------------------------------------------------------------------------------------------------------
            sleep(3)
            lbs=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME,'css-8e4lkk')))
            vls=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME,'css-5kqnit')))
            boxn=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME,'css-aoeo82')))
            for b in (boxn):
                lbs=b.find_elements(By.CLASS_NAME,'css-8e4lkk')
                vls=b.find_elements(By.CLASS_NAME,'css-5kqnit')
                for lb,vl in zip(lbs,vls):
                    df2.loc[count,'Sl.No']=i
                    df2.loc[count,'Years']=df1.loc[i,'Years']
                    df2.loc[count,'Make']=df1.loc[i,'Make']
                    df2.loc[count,'Model']=df1.loc[i,'Model']
                    df2.loc[count,'EngineBaseLiter']=df1.loc[i,'EngineBaseLiter']
                    df2.loc[count,'EngineBaseCylinder']=df1.loc[i,'EngineBaseCylinder']
                    df2.loc[count,'EngineBaseBlockType']=df1.loc[i,'EngineBaseBlockType']
                    df2.loc[count,lb.text]=vl.text
                count=count+1
        except:
            pass
        ptype.click()
        clear=wait.until(EC.presence_of_element_located((By.XPATH,f"//li[text()='All Products']")))
        clear.click()
    except:
        dummy = wait.until(EC.presence_of_element_located((By.CLASS_NAME, 'css-1km1ehz')))
        dummy.click()
        df2.loc[count,'Sl.No']=i
        df2.loc[count,'Years']=df1.loc[i,'Years']
        df2.loc[count,'Make']=df1.loc[i,'Make']
        df2.loc[count,'Model']=df1.loc[i,'Model']
        df2.loc[count,'EngineBaseLiter']=df1.loc[i,'EngineBaseLiter']
        df2.loc[count,'EngineBaseCylinder']=df1.loc[i,'EngineBaseCylinder']
        df2.loc[count,'EngineBaseBlockType']=df1.loc[i,'EngineBaseBlockType']
        df2.loc[count,'Part #']="No combination available in NGK"
        df2.loc[count,'Fitment Notes']='Unsuccessful extraction'
        count=count+1        
    clear_output(wait=True)