In [1]:
#pip install selenium
#pip install webdriver_manager
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib.parse import unquote
from selenium.webdriver.support.ui import Select
import pandas as pd
import datetime 
from selenium.webdriver.common.keys import Keys
import warnings
# Ignore all warnings (not recommended in general)

In [2]:
home="https://oempartsonline.com/"
search_text="Parking Brake Cable"

In [3]:
warnings.filterwarnings("ignore")
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.get(home)
wait=WebDriverWait(driver, 10)
### Please update capatche.

In [4]:
List=driver.find_elements(By.CLASS_NAME, "font-semibold")

In [5]:
cols=['Sl.No.']
df = pd.DataFrame(columns=cols)
df
count=0

In [6]:
driver.get(home)
sleep(2)
List=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME, "font-semibold")))
sleep(1)
Makes=[]
for l in List[:-3]:
    print(l.text)
    Makes.append(l.text)

ACURA
AUDI
BMW
FORD
GM
HONDA
HYUNDAI
INFINITI
JAGUAR
KIA
LAND ROVER
LEXUS
MAZDA
MITSUBISHI
MOPAR
NISSAN
PORSCHE
SUBARU
TOYOTA
VOLKSWAGEN
VOLVO

In [7]:
len(Makes)

21

In [23]:
driver.find_elements(By.CSS_SELECTOR,'[class="catalog-product marketplace-product row "]')[10].text

IndexError: list index out of range

In [11]:
s=driver.find_elements(By.CSS_SELECTOR,'[class="product-details"]')[1].text

IndexError: list index out of range

In [36]:
print(s)

Ignition Coil
MSRP $110.88 $79.04
Contemporary Cars (Acura)
Part Number: 30520-R70-S01
Acura
Other Names: Coil, Coil Plug Hole
Replaces: 30520-R70-A01
Description: TL. TSX. 3.5l. RL.
Fits: Acura: RL, TL, TSX
ADD TO CART .CLS-1 { FILL: NONE; STROKE: #FFF; STROKE-MITERLIMIT: 10; STROKE-WIDTH: 7.34PX; } ICONS

In [42]:
s.split("Fits: ")[1].split("\n")[0]

'Acura: RL, TL, TSX'

In [9]:
for make in range(9,21):
    driver.get(home)
    sleep(2)
    List=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME, "font-semibold")))
    m=List[make].text
    print(m)
    List[make].click()
    sleep(2)
    search=wait.until(EC.presence_of_element_located((By.ID,"main_search_10")))
    search.click()
    search.send_keys(search_text)
    search.send_keys(Keys.ENTER)
    sleep(2)
    Varnum=1
    for i in range(16):
        sleep(10)
        Alles=wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,'[class="catalog-product marketplace-product row "]')))
        Names=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME,"product-title")))
        # PartNumbers=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME,"catalog-product-id")))
        # Links=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME,"product-title")))
        # Replaces=wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,'[class="catalog-product-more-in-category catalog-info-row"]')))
        # Fits=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME,"fitment-makes ")))
        sleep(5)
        # for All, Name, partnumber, replaces, fit in zip (Alles, Names, PartNumbers, Replaces, Fits):
        for All, Name in zip (Alles, Names):
            df.loc[count,'Make']=m
            df.loc[count,'#Variants']=Varnum
            df.loc[count,"Sl.No."]=count
            df.loc[count,"PartName"]=All.text.split("\n")[0]
            try:
                df.loc[count,"PartNumber"]=All.text.split("Part Number: ")[1].split("\n")[0]
            except:
                df.loc[count,"PartNumber"]=All.text.split("PART NUMBER: ")[1].split("\n")[0]
            df.loc[count,"Link"]=Name.find_element(By.CSS_SELECTOR,"a").get_attribute('href').split("?")[0]
            try:
                df.loc[count,"Replaces"]=All.text.split("Replaces: ")[1].split("\n")[0]
            except:
                df.loc[count,"Replaces"]=""
            try:
                df.loc[count,"Fitment"]=All.text.split("Fits: ")[1].split("\n")[0]
            except:
                df.loc[count,"Fitment"]=""
            try:
                df.loc[count,"Position"]=All.text.split("Positions: ")[1].split("\n")[0]
            except:
                df.loc[count,"Position"]=""
            
            count=count+1
            Varnum=Varnum+1
        driver.find_element(By.CSS_SELECTOR,f'[data-page="{i+2}"]').click()
        sleep(2)
    driver.get(home)

KIA
LAND ROVER
LEXUS
MAZDA
MITSUBISHI
MOPAR
NISSAN
PORSCHE
SUBARU
TOYOTA
VOLKSWAGEN
VOLVO

In [10]:
len(df)

6048

In [11]:
df

,Sl.No.,Make,#Variants,PartName,PartNumber,Link,Replaces,Fitment,Position
0,0,ACURA,1.0,Parking Brake Cable,47510-S3M-A02,https://acura.oempartsonline.com/oem-parts/acu...,47510-S3M-A01,Acura: CL,"Rear Right Right, Rear Right Rear"
1,1,ACURA,2.0,Parking Brake Cable,47560-S3M-A02,https://acura.oempartsonline.com/oem-parts/acu...,47560-S3M-A01,Acura: CL,"Left, Rear Left Rear"
2,2,ACURA,3.0,Parking Brake Cable,47220-SZ3-A01ZC,https://acura.oempartsonline.com/oem-parts/acu...,,Acura: RL,Front
3,3,ACURA,4.0,Parking Brake Cable,47510-SEP-A03,https://acura.oempartsonline.com/oem-parts/acu...,,Acura: TL,Rear Right Right
4,4,ACURA,5.0,Parking Brake Cable,47521-SP0-013,https://acura.oempartsonline.com/oem-parts/acu...,47521-SP0-003,Acura: Legend,"Left Rear, Left"
...,...,...,...,...,...,...,...,...,...
6043,6043,VOLVO,284.0,Ground Cable,32362263,https://volvo.oempartsonline.com/oem-parts/vol...,32240315,"Volvo: C40 Recharge, XC40 Recharge","Front, Rear"
6044,6044,VOLVO,285.0,Ground Cable,32362810,https://volvo.oempartsonline.com/oem-parts/vol...,,Volvo: C40 Recharge,Rear
6045,6045,VOLVO,286.0,Battery Cable,32210571,https://volvo.oempartsonline.com/oem-parts/vol...,,Volvo: S90,
6046,6046,VOLVO,287.0,Battery Cable,32217511,https://volvo.oempartsonline.com/oem-parts/vol...,,"Volvo: C40 Recharge, XC40 Recharge",Right Front
6047,6047,VOLVO,288.0,Positive Cable,32320687,https://volvo.oempartsonline.com/oem-parts/vol...,,Volvo: XC40,

In [12]:
df=df.drop_duplicates(subset=df.columns.difference(['Sl.No']))

In [13]:
df

,Sl.No.,Make,#Variants,PartName,PartNumber,Link,Replaces,Fitment,Position
0,0,ACURA,1.0,Parking Brake Cable,47510-S3M-A02,https://acura.oempartsonline.com/oem-parts/acu...,47510-S3M-A01,Acura: CL,"Rear Right Right, Rear Right Rear"
1,1,ACURA,2.0,Parking Brake Cable,47560-S3M-A02,https://acura.oempartsonline.com/oem-parts/acu...,47560-S3M-A01,Acura: CL,"Left, Rear Left Rear"
2,2,ACURA,3.0,Parking Brake Cable,47220-SZ3-A01ZC,https://acura.oempartsonline.com/oem-parts/acu...,,Acura: RL,Front
3,3,ACURA,4.0,Parking Brake Cable,47510-SEP-A03,https://acura.oempartsonline.com/oem-parts/acu...,,Acura: TL,Rear Right Right
4,4,ACURA,5.0,Parking Brake Cable,47521-SP0-013,https://acura.oempartsonline.com/oem-parts/acu...,47521-SP0-003,Acura: Legend,"Left Rear, Left"
...,...,...,...,...,...,...,...,...,...
6043,6043,VOLVO,284.0,Ground Cable,32362263,https://volvo.oempartsonline.com/oem-parts/vol...,32240315,"Volvo: C40 Recharge, XC40 Recharge","Front, Rear"
6044,6044,VOLVO,285.0,Ground Cable,32362810,https://volvo.oempartsonline.com/oem-parts/vol...,,Volvo: C40 Recharge,Rear
6045,6045,VOLVO,286.0,Battery Cable,32210571,https://volvo.oempartsonline.com/oem-parts/vol...,,Volvo: S90,
6046,6046,VOLVO,287.0,Battery Cable,32217511,https://volvo.oempartsonline.com/oem-parts/vol...,,"Volvo: C40 Recharge, XC40 Recharge",Right Front
6047,6047,VOLVO,288.0,Positive Cable,32320687,https://volvo.oempartsonline.com/oem-parts/vol...,,Volvo: XC40,

In [14]:
df.to_excel(rf'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\OE-Parts\Output\OEM_Parts_{search_text}.xlsx', index=True,sheet_name="Raw")