In [1]:
#pip install selenium
#pip install webdriver_manager
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib.parse import unquote
from selenium.webdriver.support.ui import Select
import pandas as pd
import datetime 
from tqdm import tqdm
import warnings
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

In [2]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
wait=WebDriverWait(driver, 5)
driver.get('https://oempartsonline.com/')

### Please update capatche.

In [17]:
df_in=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\OE-Parts\Output\OEM_Parts_Parking Brake Cable.xlsx",sheet_name='Raw')

In [18]:
df_in

,Unnamed: 0,Sl.No.,Make,#Variants,PartName,PartNumber,Link,Replaces,Fitment,Position,Check
0,0,0,ACURA,1,Parking Brake Cable,47510-S3M-A02,https://acura.oempartsonline.com/oem-parts/acu...,47510-S3M-A01,Acura: CL,"Rear Right Right, Rear Right Rear",1
1,1,1,ACURA,2,Parking Brake Cable,47560-S3M-A02,https://acura.oempartsonline.com/oem-parts/acu...,47560-S3M-A01,Acura: CL,"Left, Rear Left Rear",1
2,2,2,ACURA,3,Parking Brake Cable,47220-SZ3-A01ZC,https://acura.oempartsonline.com/oem-parts/acu...,NaN,Acura: RL,Front,1
3,3,3,ACURA,4,Parking Brake Cable,47510-SEP-A03,https://acura.oempartsonline.com/oem-parts/acu...,NaN,Acura: TL,Rear Right Right,1
4,4,4,ACURA,5,Parking Brake Cable,47521-SP0-013,https://acura.oempartsonline.com/oem-parts/acu...,47521-SP0-003,Acura: Legend,"Left Rear, Left",1
...,...,...,...,...,...,...,...,...,...,...,...
6043,6043,6043,VOLVO,284,Ground Cable,32362263,https://volvo.oempartsonline.com/oem-parts/vol...,32240315,"Volvo: C40 Recharge, XC40 Recharge","Front, Rear",0
6044,6044,6044,VOLVO,285,Ground Cable,32362810,https://volvo.oempartsonline.com/oem-parts/vol...,NaN,Volvo: C40 Recharge,Rear,0
6045,6045,6045,VOLVO,286,Battery Cable,32210571,https://volvo.oempartsonline.com/oem-parts/vol...,NaN,Volvo: S90,NaN,0
6046,6046,6046,VOLVO,287,Battery Cable,32217511,https://volvo.oempartsonline.com/oem-parts/vol...,NaN,"Volvo: C40 Recharge, XC40 Recharge",Right Front,0
6047,6047,6047,VOLVO,288,Positive Cable,32320687,https://volvo.oempartsonline.com/oem-parts/vol...,NaN,Volvo: XC40,NaN,0

In [19]:
df_in.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6048 entries, 0 to 6047
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  6048 non-null   int64
 1   Sl.No.      6048 non-null   int64
 2   Make        6048 non-null   object
 3   #Variants   6048 non-null   int64
 4   PartName    6048 non-null   object
 5   PartNumber  6048 non-null   object
 6   Link        6048 non-null   object
 7   Replaces    1552 non-null   object
 8   Fitment     6048 non-null   object
 9   Position    3506 non-null   object
 10  Check       6048 non-null   int64
dtypes: int64(4), object(7)
memory usage: 519.9+ KB

In [7]:
# df_in=df_in[df_in['Check']==1].reset_index()

In [106]:
# df_in=df_in.dropna(subset=["Link"]).reset_index()

In [20]:
df_in

,Unnamed: 0,Sl.No.,Make,#Variants,PartName,PartNumber,Link,Replaces,Fitment,Position,Check
0,0,0,ACURA,1,Parking Brake Cable,47510-S3M-A02,https://acura.oempartsonline.com/oem-parts/acu...,47510-S3M-A01,Acura: CL,"Rear Right Right, Rear Right Rear",1
1,1,1,ACURA,2,Parking Brake Cable,47560-S3M-A02,https://acura.oempartsonline.com/oem-parts/acu...,47560-S3M-A01,Acura: CL,"Left, Rear Left Rear",1
2,2,2,ACURA,3,Parking Brake Cable,47220-SZ3-A01ZC,https://acura.oempartsonline.com/oem-parts/acu...,NaN,Acura: RL,Front,1
3,3,3,ACURA,4,Parking Brake Cable,47510-SEP-A03,https://acura.oempartsonline.com/oem-parts/acu...,NaN,Acura: TL,Rear Right Right,1
4,4,4,ACURA,5,Parking Brake Cable,47521-SP0-013,https://acura.oempartsonline.com/oem-parts/acu...,47521-SP0-003,Acura: Legend,"Left Rear, Left",1
...,...,...,...,...,...,...,...,...,...,...,...
6043,6043,6043,VOLVO,284,Ground Cable,32362263,https://volvo.oempartsonline.com/oem-parts/vol...,32240315,"Volvo: C40 Recharge, XC40 Recharge","Front, Rear",0
6044,6044,6044,VOLVO,285,Ground Cable,32362810,https://volvo.oempartsonline.com/oem-parts/vol...,NaN,Volvo: C40 Recharge,Rear,0
6045,6045,6045,VOLVO,286,Battery Cable,32210571,https://volvo.oempartsonline.com/oem-parts/vol...,NaN,Volvo: S90,NaN,0
6046,6046,6046,VOLVO,287,Battery Cable,32217511,https://volvo.oempartsonline.com/oem-parts/vol...,NaN,"Volvo: C40 Recharge, XC40 Recharge",Right Front,0
6047,6047,6047,VOLVO,288,Positive Cable,32320687,https://volvo.oempartsonline.com/oem-parts/vol...,NaN,Volvo: XC40,NaN,0

In [21]:
Cols=["Sl.No"]
df = pd.DataFrame(columns=Cols)
count=0

In [54]:
# wait.until(EC.presence_of_element_located((By.CLASS_NAME,'product-title')))

# driver.find_element(By.CLASS_NAME,"fitment-expander").click()

# driver.find_elements(By.CLASS_NAME,"accordion-title")[1].click()

In [76]:
sts=driver.find_elements(By.CLASS_NAME,"product-subtitle")

In [14]:
driver.find_element(By.CSS_SELECTOR,'[class="positions"]').text.split('Positions: ')[1]

'Rear'

In [16]:
driver.find_element(By.CSS_SELECTOR,'[class="also_known_as"]').text.split('Other Names: ')[1]

'Cable, Parking Brake'

In [37]:
driver.find_element(By.CLASS_NAME,"product-superseded-list").text.split(": ")[1]

'BPE8-18-10XB, BPE8-18-10XC'

In [30]:
for i in tqdm(range(3977,len(df_in))):
    print(i)
    driver.get(df_in["Link"][i])
    wait.until(EC.presence_of_element_located((By.CLASS_NAME,'product-title')))
    sleep(1)
    try:
        driver.find_element(By.CSS_SELECTOR,'[aria-controls="tab-vehicle-fitment"]').click()
    except:
        try:
            driver.find_elements(By.CLASS_NAME,"accordion-title")[1].click()
        except:
            df.loc[count,"Sl.No"]=count+1
            df.loc[count,"PartNumber"]=df_in["PartNumber"][i]
            df.loc[count,"Link"]=df_in["Link"][i]
            df.loc[count,"Vehicle_Fitment"]="No"
            count=count+1
    
    sleep(1)

    try:
        driver.find_element(By.CLASS_NAME,"fitment-expander").click()
        sleep(1)
    except:
        pass

    VehCount=1

    years=driver.find_elements(By.CLASS_NAME,"fitment-year")
    makes=driver.find_elements(By.CLASS_NAME,"fitment-make")
    models=driver.find_elements(By.CLASS_NAME,"fitment-model")
    trims=driver.find_elements(By.CLASS_NAME,"fitment-trim")
    engines=driver.find_elements(By.CLASS_NAME,"fitment-engine")
    try:
        status=driver.find_element(By.CLASS_NAME,"message-title ").text
    except:
        status=""

    for year, make, model, trim, engine in zip( years[1:], makes[1:], models[1:], trims[1:], engines[1:]):
        df.loc[count,"Sl.No"]=count+1
        df.loc[count,"Status"]=status
        df.loc[count,"VehicleCounts"]=VehCount
        df.loc[count,"PartNumber"]=df_in["PartNumber"][i]
        df.loc[count,"Year"]=year.text
        df.loc[count,"Make"]=make.text
        df.loc[count,"Model"]=model.text
        df.loc[count,"Body & Trim"]=trim.text
        df.loc[count,"Engine & Transmission"]=engine.text
        df.loc[count,"Vehicle_Fitment"]="Yes"
        df.loc[count,"Link"]=df_in["Link"][i]
        try:
            rep=driver.find_element(By.CLASS_NAME,"product-superseded-list").text.split(": ")[1]
            df.loc[count,"Replacement"]=rep
        except:
            df.loc[count,"Replacement"]=""
        try:
            sts=driver.find_elements(By.CLASS_NAME,"product-subtitle")
            df.loc[count,"Range"]=sts[len(sts)-1].text
        except:
            pass
        try:
            df.loc[count,"Position"]=driver.find_element(By.CSS_SELECTOR,'[class="positions"]').text.split('Positions: ')[1]
        except:
            pass
        try:
            df.loc[count,"OtherNames"]=driver.find_element(By.CSS_SELECTOR,'[class="also_known_as"]').text.split('Other Names: ')[1]
        except:
            pass
        count=count+1
        VehCount=VehCount+1
    clear_output(wait=True)

100%|██████████| 2071/2071 [3:22:41<00:00,  5.87s/it]

In [31]:
df

,Sl.No,Status,VehicleCounts,PartNumber,Year,Make,Model,Body & Trim,Engine & Transmission,Vehicle_Fitment,Link,Replacement,Range,Position,OtherNames
0,1,,1.0,47510-S3M-A02,2003,Acura,CL,"Base, Type-S",3.2L V6 - Gas,Yes,https://acura.oempartsonline.com/oem-parts/acu...,47510-S3M-A01,2001-2003 Acura CL - 47510s3ma02,"Rear Right Right, Rear Right Rear","Rear Cable, Wire R Park Brake"
1,2,,2.0,47510-S3M-A02,2002,Acura,CL,"Base, Type-S",3.2L V6 - Gas,Yes,https://acura.oempartsonline.com/oem-parts/acu...,47510-S3M-A01,2001-2003 Acura CL - 47510s3ma02,"Rear Right Right, Rear Right Rear","Rear Cable, Wire R Park Brake"
2,3,,3.0,47510-S3M-A02,2001,Acura,CL,"Premium, Type-S",3.2L V6 - Gas,Yes,https://acura.oempartsonline.com/oem-parts/acu...,47510-S3M-A01,2001-2003 Acura CL - 47510s3ma02,"Rear Right Right, Rear Right Rear","Rear Cable, Wire R Park Brake"
3,4,,1.0,47560-S3M-A02,2003,Acura,CL,"Base, Type-S",3.2L V6 - Gas,Yes,https://acura.oempartsonline.com/oem-parts/acu...,47560-S3M-A01,2001-2003 Acura CL - 47560s3ma02,"Left, Rear Left Rear","Rear Cable, Wire L Park Brake"
4,5,,2.0,47560-S3M-A02,2002,Acura,CL,"Base, Type-S",3.2L V6 - Gas,Yes,https://acura.oempartsonline.com/oem-parts/acu...,47560-S3M-A01,2001-2003 Acura CL - 47560s3ma02,"Left, Rear Left Rear","Rear Cable, Wire L Park Brake"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69143,69144,,4.0,32217511,2023,Volvo,XC40 Recharge,"Core, Plus, Ultimate",Electric,Yes,https://volvo.oempartsonline.com/oem-parts/vol...,,2021-2024 Volvo - 32217511,Right Front,NaN
69144,69145,,5.0,32217511,2022,Volvo,C40 Recharge,Ultimate,"BATTERY EV (EV/BEV), Electric",Yes,https://volvo.oempartsonline.com/oem-parts/vol...,,2021-2024 Volvo - 32217511,Right Front,NaN
69145,69146,,6.0,32217511,2022,Volvo,XC40 Recharge,"Core, Plus, Ultimate","BATTERY EV (EV/BEV), Electric",Yes,https://volvo.oempartsonline.com/oem-parts/vol...,,2021-2024 Volvo - 32217511,Right Front,NaN
69146,69147,,7.0,32217511,2021,Volvo,XC40 Recharge,Base,"BATTERY EV (EV/BEV), Electric",Yes,https://volvo.oempartsonline.com/oem-parts/vol...,,2021-2024 Volvo - 32217511,Right Front,NaN
69147,69148,,1.0,32320687,2023,Volvo,XC40,"B4 Plus, B4 Ultimate, B5 Core, B5 Plus, B5 Ult...",2.0L L4 - Electric/Gas,Yes,https://volvo.oempartsonline.com/oem-parts/vol...,,2023 Volvo XC40 - 32320687,NaN,Battery Cable

In [32]:
df.to_excel(r"C :\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\27_Oxygen_Sensor\Output\MMY_PBC_All.xlsx",index=False, sheet_name='Raw')