# 1. Library calling

In [69]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
from datetime import datetime
from bs4 import BeautifulSoup
import pandas as pd
import datetime
import warnings
from IPython.display import clear_output
import numpy as np
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
import datetime
from tqdm import tqdm

# 2. Defining the Product Information and Location

In [70]:
Folder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\Vikram Data research\Holes_Engine Water Pump'
#Brand_Name='SCHRADER TPMS SOLUTIONS'
#Type_Name='TPMS Sensor'

# 3. Setting Webdriver and Website Specific Information

In [71]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.get('https://web.tecalliance.net/opticat/qa/login')
driver.maximize_window()
wait=WebDriverWait(driver, 10)
button =wait.until(EC.presence_of_element_located((By.ID,"ppms_cm_save-choices")))
button.click()

In [72]:
username_field = driver.find_element(By.ID,'userName')  
username_field.send_keys('vikram.vadhirajan@firstbrandsgroup.com')
password_field = driver.find_element(By.ID,'password')  
password_field.send_keys('FBG@Jun-2024')
button = driver.find_element(By.XPATH, "(//div[@class='col-sm-12'])")
button.click()

In [60]:
dfi=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\Downloads\Sprk Plug Qty Per Cylinder.xlsx")

In [6]:
dfi

,SL No,MakeName,ModelName,YearID,EngineBaseBlockType,EngineBaseCylinder,EngineBaseLiter,Spark Plug Qty Per Cylinder,Spec,Unnamed: 9,EngineDetail
0,1,Acura,ILX,2013,L,4,2.4,NaN,L4 2.4L,,L4 2.4L
1,2,Acura,ILX,2014,L,4,2.4,NaN,L4 2.4L,,L4 2.4L
2,3,Acura,ILX,2015,L,4,2.4,NaN,L4 2.4L,,L4 2.4L
3,4,Acura,ILX,2016,L,4,2.4,NaN,L4 2.4L,,L4 2.4L
4,5,Acura,ILX,2017,L,4,2.4,NaN,L4 2.4L,,L4 2.4L
...,...,...,...,...,...,...,...,...,...,...,...
4779,4780,Volkswagen,Tiguan,2015,L,4,2.0,NaN,L4 2.0L,,L4 2.0L
4780,4781,Volkswagen,Tiguan,2016,L,4,2.0,NaN,L4 2.0L,,L4 2.0L
4781,4782,Volkswagen,Tiguan,2017,L,4,2.0,NaN,L4 2.0L,,L4 2.0L
4782,4783,Volkswagen,Tiguan Limited,2018,L,4,2.0,NaN,L4 2.0L,,L4 2.0L
4783,4784,Volkswagen,Tiguan Limited,2017,L,4,2.0,NaN,L4 2.0L,,L4 2.0L

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [37]:
cols=['Part No.']
df = pd.DataFrame(columns=cols)
df
count=0

linkprefix="https://web.tecalliance.net/opticat/qa/parts/"
linksuffix="/ap-detail"

In [25]:
Qtys=driver.find_elements(By.CSS_SELECTOR,'[col-id="application"]')

for qty in Qtys[1:]:
    print((qty.text))

L4 2.4L 2356cc
L4 2.4L 2356cc
L4 2.4L 2356cc


L4 2.4L 2356cc
L4 2.4L 2356cc
L4 2.4L 2356cc
L4 2.4L 2356cc
L4 2.4L 2356cc
L4 2.4L 2356cc
L4 2.4L 2356cc
L4 2.4L 2356cc
L4 2.4L 2356cc
L4 2.4L 2356cc
L4 2.4L 2356cc
L4 2.4L 2356cc

In [74]:
for i in tqdm(range (4541,len(dfi))): #len(dfi)):
    driver.find_element(By.CSS_SELECTOR,'[id="menu-home"]').click()
    print(i)
    wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,'[class="ta-icon-cancel"]'))).click()    
    Type=driver.find_element(By.CSS_SELECTOR,'[placeholder="Type"]')
    Type.click()
    Type.send_keys("Car/Truck/Van")
    sleep(.5)
    driver.find_element(By.CSS_SELECTOR,'[role="option"]').click()
    Year=driver.find_element(By.CSS_SELECTOR,'[placeholder="Model year "]')
    Year.click()
    Year.send_keys(str(dfi.YearID[i]))
    sleep(.5)
    driver.find_element(By.CSS_SELECTOR,'[role="option"]').click()
    Manufacture=driver.find_element(By.CSS_SELECTOR,'[placeholder="Manufacturer "]')
    Manufacture.click()
    Manufacture.send_keys(dfi.MakeName[i])
    sleep(.5)
    driver.find_element(By.CSS_SELECTOR,'[role="option"]').click()
    Model=driver.find_element(By.CSS_SELECTOR,'[placeholder="Models "]')
    Model.click()
    try:
        Model.send_keys(dfi.ModelName[i])
        sleep(.5)
        driver.find_element(By.CSS_SELECTOR,'[role="option"]').click()
    except:
        continue
    try:
        wait.until(EC.presence_of_element_located((By.XPATH,f"//label[contains(text(), '{dfi.EngineDetail[i]}')]"))).click()
    except:
        pass
    # try:
    #     wait.until(EC.presence_of_element_located((By.XPATH,f"//label[contains(text(), '{dfi.FuelTypeName[i]}')]"))).click()
    # except:
    #     pass
    # try:
    #     driver.find_element(By.XPATH,f"//label[contains(text(), '{dfi.AspirationName[i]}')]").click()
    # except:
    #     pass
    try:
        brands=driver.find_elements(By.CLASS_NAME,'p-placeholder')[0]
        brands.click()
    except: 
        pass
    try:
        driver.find_element(By.CSS_SELECTOR,'[role="textbox"]').send_keys("Spark Plug")
        sleep(.5)
        driver.find_element(By.CSS_SELECTOR,'[role="checkbox"]').click()
        brands.click()
        sleep(3)
        if i==0:
            driver.find_element(By.CSS_SELECTOR,'[class="p-multiselect-label"]').click()
            select_2=driver.find_element(By.XPATH,"(//p-multiselectitem[@class='p-element ng-star-inserted'])[1]")
            select_2.click()
            select_3=driver.find_element(By.XPATH,"(//p-multiselectitem[@class='p-element ng-star-inserted'])[10]")
            select_3.click()
            sleep(2)
            driver.find_element(By.CSS_SELECTOR,'[class="p-multiselect-label"]').click()
        statuses=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME, "article-status-cell")))
        Contents=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME, "generic-article"))) 
        PNS=wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, '[class="text-truncate text-primary"]')))
        CNS=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME, "font-weight-bold")))
        searchtext=driver.find_element(By.CLASS_NAME, "ng-star-inserted") 
        Productcodes=wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,'div[role="row"]')))
        Qtys=driver.find_elements(By.CSS_SELECTOR,'[col-id="qty"]')
        Applns=driver.find_elements(By.CSS_SELECTOR,'[col-id="application"]')
        for status, content, pn,cn, productcode,qty,appln in zip(statuses,Contents,PNS,CNS,Productcodes[1:],Qtys[1:],Applns[1:]):
            df.loc[count,"SelectedVehicle"]=driver.find_element(By.CSS_SELECTOR,'[class="p-menuitem-text ng-star-inserted"]').text            
            df.loc[count,"Year"]=dfi.YearID[i]
            df.loc[count,"Make"]=dfi.MakeName[i]
            df.loc[count,"Model"]=dfi.ModelName[i]
            df.loc[count,"Engine_details"]=dfi.EngineDetail[i]       
            #df.loc[count,"SearchText"]=List[i]
            df.loc[count,"Competitor"]=cn.text
            df.loc[count,"Qty"]=int(qty.text)
            df.loc[count,"Application"]=(appln.text)
            df.loc[count,"Part No."]=pn.text
            #df.loc[count,"Status"]=status.text
            df.loc[count,"Name"]=content.text
            pc=productcode.get_attribute("row-id").replace("]-[","/").replace("[","").replace("]","")
            link=linkprefix+pc+linksuffix
            df.loc[count,"Link"]=driver.current_url
            df.loc[count,"ProductLink"]=link
            count=count+1    
    except:
        pass
    clear_output(wait=True)

100%|██████████| 243/243 [45:34<00:00, 11.25s/it]

In [79]:
print(df.shape)
df.tail()

(106104, 12)

,Part No.,SelectedVehicle,Year,Make,Model,Engine_details,Competitor,Qty,Application,Name,Link,ProductLink
106099,92400,2017 Volkswagen Tiguan Limited,2017.0,Tiguan Limited,Tiguan Limited,L4 2.0L,NGK,4.0,L4 2.0L 1984cc,Spark Plug,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/B...
106100,BKR7EIX,2017 Volkswagen Tiguan Limited,2017.0,Tiguan Limited,Tiguan Limited,L4 2.0L,NGK,4.0,L4 2.0L 1984cc,Spark Plug,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/B...
106101,FR7BHX-S,2017 Volkswagen Tiguan Limited,2017.0,Tiguan Limited,Tiguan Limited,L4 2.0L,NGK,4.0,L4 2.0L 1984cc,Spark Plug,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/B...
106102,PFR7S8EG,2017 Volkswagen Tiguan Limited,2017.0,Tiguan Limited,Tiguan Limited,L4 2.0L,NGK,4.0,L4 2.0L 1984cc,Spark Plug,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/B...
106103,V99-75-0047,2017 Volkswagen Tiguan Limited,2017.0,Tiguan Limited,Tiguan Limited,L4 2.0L,VEMO,4.0,L4 2.0L 1984cc,Spark Plug,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/C...

# 5. Post Processing Data and Exporting

In [82]:
# df_sorted=df[["CARTER PNo-FromHoles",'SelectedVehicle', 'Year', 'Make', 'Model','Engine_details', 'Fuel', 'Aspiration','Part No.', 'Competitor','Name', 'Link','ProductLink']]

In [119]:
df['Engine_details'][1].split(" ")[0][1:]

'4'

In [129]:
for i in range(len(df)):
    df.loc[i,"Make"]=df['SelectedVehicle'][i].split(" ")[1]
    df.loc[i,"Key"]=str(df['Year'][i]).split(".")[0]+df['Make'][i]+df['Model'][i]+df['Engine_details'][i]
    df.loc[i,'#SP/ Cyl']=round(df['Qty'][i]/int(df['Engine_details'][i].split(" ")[0][1:]),0)

In [143]:
dfcleaned=df[df["Name"]=="Spark Plug"]

In [147]:
dfcleaned

,Part No.,SelectedVehicle,Year,Make,Model,Engine_details,Competitor,Qty,Application,Name,Link,ProductLink,Product Link [copy],Key,#SP/ Cyl
2,9619,2013 Acura ILX,2013.0,Acura,ILX,L4 2.4L,Bosch,4.0,L4 2.4L 2354cc,Spark Plug,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/B...,https://web.tecalliance.net/opticat/qa/parts/B...,2013AcuraILXL4 2.4L,1.0
3,9407,2013 Acura ILX,2013.0,Acura,ILX,L4 2.4L,Champion Spark Plug,4.0,L4 2.4L 2354cc,Spark Plug,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/B...,https://web.tecalliance.net/opticat/qa/parts/B...,2013AcuraILXL4 2.4L,1.0
4,3426,2013 Acura ILX,2013.0,Acura,ILX,L4 2.4L,DENSO Auto Parts,8.0,,Spark Plug,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/B...,https://web.tecalliance.net/opticat/qa/parts/B...,2013AcuraILXL4 2.4L,2.0
5,3461,2013 Acura ILX,2013.0,Acura,ILX,L4 2.4L,DENSO Auto Parts,4.0,,Spark Plug,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/B...,https://web.tecalliance.net/opticat/qa/parts/B...,2013AcuraILXL4 2.4L,1.0
6,3483,2013 Acura ILX,2013.0,Acura,ILX,L4 2.4L,DENSO Auto Parts,4.0,,Spark Plug,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/B...,https://web.tecalliance.net/opticat/qa/parts/B...,2013AcuraILXL4 2.4L,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106099,92400,2017 Volkswagen Tiguan Limited,2017.0,Volkswagen,Tiguan Limited,L4 2.0L,NGK,4.0,L4 2.0L 1984cc,Spark Plug,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/B...,https://web.tecalliance.net/opticat/qa/parts/B...,2017VolkswagenTiguan LimitedL4 2.0L,1.0
106100,BKR7EIX,2017 Volkswagen Tiguan Limited,2017.0,Volkswagen,Tiguan Limited,L4 2.0L,NGK,4.0,L4 2.0L 1984cc,Spark Plug,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/B...,https://web.tecalliance.net/opticat/qa/parts/B...,2017VolkswagenTiguan LimitedL4 2.0L,1.0
106101,FR7BHX-S,2017 Volkswagen Tiguan Limited,2017.0,Volkswagen,Tiguan Limited,L4 2.0L,NGK,4.0,L4 2.0L 1984cc,Spark Plug,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/B...,https://web.tecalliance.net/opticat/qa/parts/B...,2017VolkswagenTiguan LimitedL4 2.0L,1.0
106102,PFR7S8EG,2017 Volkswagen Tiguan Limited,2017.0,Volkswagen,Tiguan Limited,L4 2.0L,NGK,4.0,L4 2.0L 1984cc,Spark Plug,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/B...,https://web.tecalliance.net/opticat/qa/parts/B...,2017VolkswagenTiguan LimitedL4 2.0L,1.0
106103,V99-75-0047,2017 Volkswagen Tiguan Limited,2017.0,Volkswagen,Tiguan Limited,L4 2.0L,VEMO,4.0,L4 2.0L 1984cc,Spark Plug,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/C...,https://web.tecalliance.net/opticat/qa/parts/C...,2017VolkswagenTiguan LimitedL4 2.0L,1.0

In [148]:
df['#SP/ Cyl']

0         1.0
1         1.0
2         1.0
3         1.0
4         2.0
         ...
106099    1.0
106100    1.0
106101    1.0
106102    1.0
106103    1.0
Name: #SP/ Cyl, Length: 106104, dtype: float64

In [149]:
df_grouped=dfcleaned.groupby(['Key'])['#SP/ Cyl'].agg(pd.Series.mode)

In [150]:
df_grouped

Key
1986BuickCenturyV6 3.8L     1.0
1986BuickLeSabreV6 3.8L     1.0
1987BuickCenturyL4 2.5L     1.0
1987BuickCenturyV6 2.8L     1.0
1987BuickCenturyV6 3.8L     1.0
                           ...
2023Ram1500V8 5.7L          2.0
2023Ram2500V8 6.4L          2.0
2023Ram3500V8 6.4L          2.0
2023Toyota4RunnerV6 4.0L    1.0
2023ToyotaTacomaL4 2.7L     1.0
Name: #SP/ Cyl, Length: 4593, dtype: object

In [156]:
df1=df[["Key","ProductLink","Link"]]

In [157]:
with pd.ExcelWriter(Folder+'\\'+'Opticat_Export_SparkPlug_MMYCombinationFinal.xlsx') as writer:  # doctest: +SKIP
    df.to_excel(writer,index=False, sheet_name='Raw')
    df1.to_excel(writer,index=False, sheet_name='filter')
    dfcleaned.to_excel(writer,index=False, sheet_name='Cleaned')
    df_grouped.to_excel(writer,index=True, sheet_name='Grouped')
    #df_sorted.to_excel(writer,index=False, sheet_name='Sorted')
    #df_unpivoted.to_excel(writer,index=False, sheet_name='Attributes')

# 99. Archived Codes

In [ ]:
# To extract the Supplier part number from the list


from tqdm import tqdm
for a in tqdm(range(51,len(List))):
    print(a)    
    search_content=driver.find_element(By.ID,"part-search-input")
    search_content.click()
    search_content.send_keys(List[a])
    driver.find_element(By.CSS_SELECTOR,'[ta-name="search-button"]').click()
    sleep(2)
    PN =driver.find_elements(By.XPATH, "(//div[@class='text-truncate text-primary'])")
    Suppliers =driver.find_elements(By.CSS_SELECTOR, 'p > span.font-weight-bold')       
    for p, s in zip(PN,Suppliers):
        text_content = p.find_element(By.CSS_SELECTOR,'.text-truncate a').text
        print(List[a],":",s.text.strip(),"-",text_content)
    sleep(1)
    driver.find_element(By.CSS_SELECTOR,'[id="menu-home"]').click()
    driver.find_element(By.CSS_SELECTOR,'[id="part-search-input"]').clear()

In [ ]:
        # Param =browser.find_elements(By.XPATH, "(//span[@class='article-criteria'])")
        # #counter=0
        # for index, element2 in enumerate(Param):
        #     # Access specific attributes or text content of the element
        #     criteria_name = element2.find_element(By.CSS_SELECTOR,'.font-weight-bold:first-child').text
        #     value=element2.find_element(By.CSS_SELECTOR,'span:not(.font-weight-bold)').text
        #     # print(criteria_name,'     :      ',value)
        #     if str(df.loc[counter,criteria_name])!='nan':
        #         counter=counter+1
        #         df.loc[counter,criteria_name]=value
        #     else:
        #         df.loc[counter,criteria_name]=value

In [ ]:
#Reference only

from selenium import webdriver
from bs4 import BeautifulSoup

# Wait for the page to load (you might need to adjust the wait time)
browser.implicitly_wait(10)

# Get the page source and create a BeautifulSoup object
page_source = browser.page_source
soup = BeautifulSoup(page_source, 'html.parser')

# Find all elements with the specified class
elements = soup.find_all('div', class_='ag-row')

# Enumerate the elements based on row index and article-criteria
for index, element in enumerate(elements, start=1):
    # Extract row index
    row_index = element['row-index']


    # Extract article-criteria
    article_criterias = element.select('.article-criteria')
    article_criteria_texts = [criteria.get_text(strip=True) for criteria in article_criterias]

    # Print the results (you can modify this based on your needs)

    for criteria_text in article_criteria_texts:
        CN=criteria_text.split(":")[0]
        CV=criteria_text.split(":")[1]        
        

    print("\n")

In [ ]:
Param_Name=[]

for i in range(Totalpage):
    Param =browser.find_elements(By.XPATH, "(//span[@class='article-criteria'])")
    for index, element in enumerate(Param):
        # Access specific attributes or text content of the element
        criteria_name = WebDriverWait(element, 5).until(EC.presence_of_element_located((By.CSS_SELECTOR,".font-weight-bold:first-child"))).text
        Param_Name.append(criteria_name)
    Currentpage=int(browser.find_element(By.XPATH, '//span[@ref="lbCurrent" and @class="ag-paging-number"]').text) 
    print("Page#",Currentpage,"Completed",datetime.datetime.now())
    if Currentpage < Totalpage:
        NextPage=browser.find_element(By.CLASS_NAME, 'ag-icon-next')
        NextPage.click()
        sleep(3)
        i=i+1

if Totalpage>1:
    First_Page=browser.find_element(By.XPATH,'//div[@ref="btFirst"]')
    First_Page.click()

In [ ]:
Param_Name=set(Param_Name)
cols=Param_Name
cols
df = pd.DataFrame(columns=cols)
print(len(cols))
df