In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
from datetime import datetime
import pandas as pd

# Clean

In [2]:
path= 'C://chromedriver.exe'
browser=webdriver.Chrome()
browser.get('https://web.tecalliance.net/opticat/qa/login')
browser.maximize_window()
sleep(5)

In [3]:
button = browser.find_element(By.ID,'ppms_cm_save-choices')
button.click()

In [4]:
username_field = browser.find_element(By.ID,'userName')  
username_field.send_keys('yuvaraj.g@firstbrandsgroup.com')
password_field = browser.find_element(By.ID,'password')  
password_field.send_keys('Opticat@29')
button = browser.find_element(By.XPATH, "(//div[@class='col-sm-12'])")
button.click()
sleep(2)

In [29]:
ItemCode="0986221072"


# Bosch ignition coil 0986221072
# Bosch Ignition coil 0986221120

# 30013012-75000 is an engine oil that severs to several customer and model and years

In [30]:
search_content=browser.find_element(By.ID,"part-search-input")
search_content.click()
search_content.send_keys(ItemCode)
Search_Button=browser.find_element(By.CLASS_NAME, "btn-search").click()
sleep(2)

In [31]:
click_Firstelement=browser.find_element(By.CSS_SELECTOR,'div[role="row"][aria-rowindex="2"]')
click_Firstelement.click()

In [32]:
Product_Locator= (By.CSS_SELECTOR, '.title.text-uppercase span')
Product_Name_element = WebDriverWait(browser, 10).until(EC.presence_of_element_located(Product_Locator))
sleep(5)
# Get the text content of the element
Product_Name = Product_Name_element.text
print(Product_Name)

BOSCH 0986221072 IGNITION COIL

In [33]:
Vehicle_Selection_ICON=browser.find_element(By.CSS_SELECTOR,'li.ng-star-inserted a[role="tab"] i.ta-icon-car-front')
Vehicle_Selection_ICON.click()

In [34]:
# Wait for the button to be clickable
button_locator = (By.CLASS_NAME, 'p-autocomplete-dropdown')
button = WebDriverWait(browser, 10).until(EC.element_to_be_clickable(button_locator))

# Click the button
button.click()
 

panel_locator = (By.CLASS_NAME, 'p-autocomplete-panel')
panel = WebDriverWait(browser, 10).until(EC.presence_of_element_located(panel_locator))

# Find all the items in the list
items_locator = (By.CSS_SELECTOR, '.p-autocomplete-items .ng-star-inserted')
items = panel.find_elements(*items_locator)

# Extract text from each item
item_texts = [item.text for item in items]
item_texts=set(item_texts)
item_texts=list(item_texts)
item_texts.sort()
# Print or use the item texts as needed
print(item_texts)

['Audi', 'Bentley', 'Porsche', 'Volkswagen']

In [35]:
cols=['PartNumber','Product_Name','Make','Models','Model_Years','Start_Year','End_Year']
df = pd.DataFrame(columns=cols)
df

Empty DataFrame
Columns: [PartNumber, Product_Name, Make, Models, Model_Years, Start_Year, End_Year]
Index: []

In [36]:
count=0
for j in range(len(item_texts)):
    inputkeys=item_texts[j]
    #print(inputkeys)
    input_element = browser.find_element(By.CLASS_NAME,'p-autocomplete-input')
    input_element.click()
    # Clear any existing text in the input field (optional, if needed)
    input_element.clear()
    # Type the target value into the input field
    input_element.send_keys(inputkeys)
    input_element.send_keys(Keys.ENTER)
    #print('entered')
    table_element = browser.find_element(By.XPATH, "//tbody[@_ngcontent-ng-c3462382488='']")
    # Find all rows in the table
    Model = table_element.find_elements(By.TAG_NAME, "th")
    Model_Year = table_element.find_elements(By.TAG_NAME, "td")
    for i in range(1,len(Model)):
            # This has to be defined. 
            df.loc[count,'Make']=item_texts[j]
            df.loc[count,'Product_Name']=Product_Name
            df.loc[count,'PartNumber']=ItemCode
            df.loc[count,'Models']=Model[i].text
            df.loc[count,'Model_Years']= Model_Year[i].text
            count=count+1            
    sleep(1)
    print('Manufacturers-',j+1, 'Models-',count)    
    input_element.clear()

Manufacturers- 1 Models- 38
Manufacturers- 2 Models- 76
Manufacturers- 3 Models- 77
Manufacturers- 4 Models- 80

In [37]:
df

,PartNumber,Product_Name,Make,Models,Model_Years,Start_Year,End_Year
0,0986221072,BOSCH 0986221072 IGNITION COIL,Audi,A3,"2015 - 2020, 2022 - 2023",NaN,NaN
1,0986221072,BOSCH 0986221072 IGNITION COIL,Audi,A3 Quattro,"2015 - 2020, 2022 - 2023",NaN,NaN
2,0986221072,BOSCH 0986221072 IGNITION COIL,Audi,A4,2017 - 2020,NaN,NaN
3,0986221072,BOSCH 0986221072 IGNITION COIL,Audi,A4 allroad,2017 - 2023,NaN,NaN
4,0986221072,BOSCH 0986221072 IGNITION COIL,Audi,A4 Quattro,2017 - 2023,NaN,NaN
...,...,...,...,...,...,...,...
75,0986221072,BOSCH 0986221072 IGNITION COIL,Bentley,TTS Quattro,2016 - 2023,NaN,NaN
76,0986221072,BOSCH 0986221072 IGNITION COIL,Porsche,Bentayga,2019,NaN,NaN
77,0986221072,BOSCH 0986221072 IGNITION COIL,Volkswagen,Cayenne,2019 - 2021,NaN,NaN
78,0986221072,BOSCH 0986221072 IGNITION COIL,Volkswagen,Macan,2017 - 2021,NaN,NaN
79,0986221072,BOSCH 0986221072 IGNITION COIL,Volkswagen,Panamera,2017 - 2021,NaN,NaN

In [38]:
df['Model_Years']=df['Model_Years'].str.split(',')
df=df.explode('Model_Years')
df = df.drop_duplicates()
df = df.reset_index(drop=True)

In [39]:
for i in range(len(df)):
    if "-" in df['Model_Years'][i]:
        #print(i)
        year=df['Model_Years'].str.split('-')[i]
        startyear=year[0]
        endyear=year[1]
        df.loc[i,'Start_Year']=startyear
        df.loc[i,'End_Year']=endyear
    if "-" not in df['Model_Years'][i]:
        #print (i)
        df.loc[i,'Start_Year']=df['Model_Years'][i]
        df.loc[i,'End_Year']=df['Model_Years'][i]

In [40]:
df['Start_Year']=df['Start_Year'].str.replace(" ","").astype(int)
df['End_Year']=df['End_Year'].str.replace(" ","").astype(int)

In [41]:
del df['Model_Years']
df

,PartNumber,Product_Name,Make,Models,Start_Year,End_Year
0,0986221072,BOSCH 0986221072 IGNITION COIL,Audi,A3,2015,2020
1,0986221072,BOSCH 0986221072 IGNITION COIL,Audi,A3,2022,2023
2,0986221072,BOSCH 0986221072 IGNITION COIL,Audi,A3 Quattro,2015,2020
3,0986221072,BOSCH 0986221072 IGNITION COIL,Audi,A3 Quattro,2022,2023
4,0986221072,BOSCH 0986221072 IGNITION COIL,Audi,A4,2017,2020
...,...,...,...,...,...,...
87,0986221072,BOSCH 0986221072 IGNITION COIL,Bentley,TTS Quattro,2016,2023
88,0986221072,BOSCH 0986221072 IGNITION COIL,Porsche,Bentayga,2019,2019
89,0986221072,BOSCH 0986221072 IGNITION COIL,Volkswagen,Cayenne,2019,2021
90,0986221072,BOSCH 0986221072 IGNITION COIL,Volkswagen,Macan,2017,2021
91,0986221072,BOSCH 0986221072 IGNITION COIL,Volkswagen,Panamera,2017,2021

In [42]:
current_URL=browser.current_url
print(current_URL)
df.loc[0,'Source_Link']=current_URL

https://web.tecalliance.net/opticat/qa/parts/BBHK/0986221072/ap-detail#@brc/search:Search%25200986221072;query:0986221072;groups:7060/ap-detail:0986221072;brandCode:BBHK;partNumber:0986221072

In [43]:
df.to_excel('Opticat_Where_Used_List'+ ItemCode+"_"+Product_Name +'.xlsx', index=False)

In [45]:
browser.quit()

# Trials

In [ ]:
# Wait for the button to be clickable
button_locator = (By.CLASS_NAME, 'p-autocomplete-dropdown')
button = WebDriverWait(browser, 10).until(EC.element_to_be_clickable(button_locator))

# Click the button
button.click()
 

panel_locator = (By.CLASS_NAME, 'p-autocomplete-panel')
panel = WebDriverWait(browser, 10).until(EC.presence_of_element_located(panel_locator))

# Find all the items in the list
items_locator = (By.CSS_SELECTOR, '.p-autocomplete-items .ng-star-inserted')
items = panel.find_elements(*items_locator)

# Extract text from each item
item_texts = [item.text for item in items]