# 1. Library calling

In [21]:
#pip install selenium

In [22]:
#pip install webdriver_manager

In [23]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib.parse import unquote
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
import pandas as pd
import datetime 

import warnings

# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

# 2. Defining the Product Information and Location

In [24]:
SummaryFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects'
summaryFile='Scraping_List.txt'
st=pd.read_csv(SummaryFolder+'\\'+summaryFile)
print(st)
#Define Product to extract
search_text = st['Product Name'][5]
print(search_text)
Source="OReilyAuto"
OFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Outputs'
IFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Inputs'

                                  Product Name
0                                Ignition Coil
1                      Windshield Washer Pumps
2                        coupler trailer locks
3          Adjustable Trailer Hitch Ball Mount
4                               Vacuum Cleaner
5                                   Spark Plug
6              bluetooth Enabled Trailer locks
7                          Power Steering Hose
8   Power Steering Pressure Line Hose Assembly
9                       Washer Fluid Reservoir
10          Hitch Ball Mount with Weight Scale
11                               LED Headlamps
12                             LED flashlights
13                   Fiberglass Tonneau Covers
14                    Aluminium Tonneau Covers
15                     Hardfold Tonneau Covers
16                            Spark Plug Wires
17                 washer fluid reservoir tank
18                   Non Automotive Gas Struts
19                     trunk hanging organizer
20                                    car jack
21                              Towing Mirrors
22                                    Gas Lift
23                        caliper pad spreader
24                               fuel injector
25        wireless carplay screen with dashcam
26                 Vehicle Soft-Shell Carriers
27                               Scissor Jacks
28               Electrical Hydraulic Car Jack
29                 Electrical Scissor Car Jack
30                               Trailer Locks
31                             Conical Filters
32                                  Car Covers
33                                 Tyre Covers
34                                    Car Mats
35                           Dolly Tire Racks
36                             Cargo Organizer
37                               Car Organizer
38                   Rechargeable Hand Warmers
39                         ATV UTV Cargo Racks
40                             Car Organizer-1
41          SwingAway Hitchmount Cargo Carrier
42                          Gas and Water Cans
43                                   SwingAway
44                        Steering Wheel Locks
45                     Universal Lift Supports
46                          Metallic Fuel Cans
47                          Home Air Purifiers
48                                       Locks
49                              Bluetooth TPMS
50                    Universal Towing Mirrors
51                        Windshield Wiper Arm
52                            Trailer Couplers
53                          Gooseneck Couplers
54                                Trailer TPMS
55                                Best Selling
56                         Windshield Sunshade
57                            Motor Cycle Bags
58                                Brake Fluids
59                          CAR Vacuum Cleaner
Spark Plug

# 3. Setting Webdriver and Website Specific Information

In [30]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.get('https://www.oreillyauto.com/')

In [26]:
#driver.maximize_window()

In [27]:
dropdown = driver.find_element(By.ID,'header-search-input')
dropdown.send_keys(search_text)
dropdown.submit()

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [61]:
Cols=["Links","Name"]
df = pd.DataFrame(columns=Cols)
count=0
df

Empty DataFrame
Columns: [Links, Name]
Index: []

In [58]:
  
Partnames=driver.find_elements(By.CLASS_NAME, 'product__name')
links=driver.find_elements(By.CLASS_NAME,"product__link")
partnumbers=driver.find_elements(By.CLASS_NAME, 'js-ga-product-line-number')
costs=driver.find_elements(By.CLASS_NAME, 'js-ga-product-price')

for partname,partnumber,cost,link in zip(Partnames,partnumbers,costs,links):
    df.loc[count,"Links"]=link.get_attribute('href')
    df.loc[count,"Name"]=partname.text
    df.loc[count,"PartNumber"]=partnumber.text
    df.loc[count,"Cost"]=cost.text
    #df.loc[count,'Rating']=Rating
    count=count+1

13

In [62]:
for i in range(10):

  
    Partnames=driver.find_elements(By.CLASS_NAME, 'product__name')
    links=driver.find_elements(By.CLASS_NAME,"product__link")
    partnumbers=driver.find_elements(By.CLASS_NAME, 'js-ga-product-line-number')
    costs=driver.find_elements(By.CLASS_NAME, 'js-ga-product-price')

    for partname,partnumber,cost,link in zip(Partnames,partnumbers,costs,links):
        df.loc[count,"Links"]=link.get_attribute('href')
        df.loc[count,"Name"]=partname.text
        df.loc[count,"PartNumber"]=partnumber.text
        df.loc[count,"Cost"]=cost.text
        #df.loc[count,'Rating']=Rating
        count=count+1
    driver.find_element(By.TAG_NAME,'body').send_keys(Keys.END)
    sleep(1)
    driver.find_element(By.CSS_SELECTOR,'[aria-label="Next Page"]').click()

ElementClickInterceptedException: Message: element click intercepted: Element <a aria-hidden="true" aria-label="Next Page" class="btn--page-next is-disabled">...</a> is not clickable at point (1200, 2). Other element would receive the click: <li>...</li>
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF6E78D9632+30946]
	(No symbol) [0x00007FF6E788E3C9]
	(No symbol) [0x00007FF6E7786FDA]
	(No symbol) [0x00007FF6E77DFEEE]
	(No symbol) [0x00007FF6E77DD962]
	(No symbol) [0x00007FF6E77DAE7B]
	(No symbol) [0x00007FF6E77DA095]
	(No symbol) [0x00007FF6E77CC271]
	(No symbol) [0x00007FF6E77FCA6A]
	(No symbol) [0x00007FF6E77CBBB6]
	(No symbol) [0x00007FF6E77FCC80]
	(No symbol) [0x00007FF6E781B041]
	(No symbol) [0x00007FF6E77FC813]
	(No symbol) [0x00007FF6E77CA6E5]
	(No symbol) [0x00007FF6E77CB021]
	GetHandleVerifier [0x00007FF6E7A0F83D+1301229]
	GetHandleVerifier [0x00007FF6E7A1BDB7+1351783]
	GetHandleVerifier [0x00007FF6E7A12A03+1313971]
	GetHandleVerifier [0x00007FF6E790DD06+245686]
	(No symbol) [0x00007FF6E789758F]
	(No symbol) [0x00007FF6E7893804]
	(No symbol) [0x00007FF6E7893992]
	(No symbol) [0x00007FF6E788A3EF]
	BaseThreadInitThunk [0x00007FF897957344+20]
	RtlUserThreadStart [0x00007FF898A426B1+33]

In [63]:
df

,Links,Name,PartNumber,Cost
0,https://www.oreillyauto.com/detail/c/platinum/...,Motorcraft Platinum Spark Plug,SP520,$7.39
1,https://www.oreillyauto.com/detail/c/iridium/m...,Motorcraft Spark Plug,SP580,$16.99
2,https://www.oreillyauto.com/detail/c/platinum/...,Motorcraft Platinum Spark Plug,SP493,$9.29
3,https://www.oreillyauto.com/detail/c/platinum/...,Motorcraft Platinum Spark Plug,SP504,$7.99
4,https://www.oreillyauto.com/detail/c/platinum/...,Motorcraft Platinum Spark Plug,SP479,$6.69
...,...,...,...,...
101,https://www.oreillyauto.com/detail/c/motorcraf...,Motorcraft Spark Plug,SP445,$6.89
102,https://www.oreillyauto.com/detail/c/motorcraf...,Motorcraft Spark Plug,SP447,$4.69
103,https://www.oreillyauto.com/detail/c/motorcraf...,Motorcraft Spark Plug,SP420,$4.69
104,https://www.oreillyauto.com/detail/c/motorcraf...,Motorcraft Spark Plug,SP409,$4.99
105,https://www.oreillyauto.com/detail/c/motorcraf...,Motorcraft Spark Plug,SP419,$3.99

In [64]:
for i in range(len(df)):
    df.loc[i,'Links']=df["Links"][i].split("?")[0   ]

In [65]:
print(df.shape)
df

(106, 4)

,Links,Name,PartNumber,Cost
0,https://www.oreillyauto.com/detail/c/platinum/...,Motorcraft Platinum Spark Plug,SP520,$7.39
1,https://www.oreillyauto.com/detail/c/iridium/m...,Motorcraft Spark Plug,SP580,$16.99
2,https://www.oreillyauto.com/detail/c/platinum/...,Motorcraft Platinum Spark Plug,SP493,$9.29
3,https://www.oreillyauto.com/detail/c/platinum/...,Motorcraft Platinum Spark Plug,SP504,$7.99
4,https://www.oreillyauto.com/detail/c/platinum/...,Motorcraft Platinum Spark Plug,SP479,$6.69
...,...,...,...,...
101,https://www.oreillyauto.com/detail/c/motorcraf...,Motorcraft Spark Plug,SP445,$6.89
102,https://www.oreillyauto.com/detail/c/motorcraf...,Motorcraft Spark Plug,SP447,$4.69
103,https://www.oreillyauto.com/detail/c/motorcraf...,Motorcraft Spark Plug,SP420,$4.69
104,https://www.oreillyauto.com/detail/c/motorcraf...,Motorcraft Spark Plug,SP409,$4.99
105,https://www.oreillyauto.com/detail/c/motorcraf...,Motorcraft Spark Plug,SP419,$3.99

# 5. Post Processing Data and Exporting

In [66]:
df=df.drop_duplicates(subset=["Links"])
df

,Links,Name,PartNumber,Cost
0,https://www.oreillyauto.com/detail/c/platinum/...,Motorcraft Platinum Spark Plug,SP520,$7.39
1,https://www.oreillyauto.com/detail/c/iridium/m...,Motorcraft Spark Plug,SP580,$16.99
2,https://www.oreillyauto.com/detail/c/platinum/...,Motorcraft Platinum Spark Plug,SP493,$9.29
3,https://www.oreillyauto.com/detail/c/platinum/...,Motorcraft Platinum Spark Plug,SP504,$7.99
4,https://www.oreillyauto.com/detail/c/platinum/...,Motorcraft Platinum Spark Plug,SP479,$6.69
...,...,...,...,...
101,https://www.oreillyauto.com/detail/c/motorcraf...,Motorcraft Spark Plug,SP445,$6.89
102,https://www.oreillyauto.com/detail/c/motorcraf...,Motorcraft Spark Plug,SP447,$4.69
103,https://www.oreillyauto.com/detail/c/motorcraf...,Motorcraft Spark Plug,SP420,$4.69
104,https://www.oreillyauto.com/detail/c/motorcraf...,Motorcraft Spark Plug,SP409,$4.99
105,https://www.oreillyauto.com/detail/c/motorcraf...,Motorcraft Spark Plug,SP419,$3.99

In [67]:
df.to_excel(IFolder+'\\'+f'{Source}ProductLinks_'+search_text+'.xlsx', index=False)