# 1. Library calling

In [33]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
import warnings
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
from selenium.webdriver.common.action_chains import ActionChains
warnings.filterwarnings("ignore")

# 2. Defining the Product Information and Location

In [2]:
SummaryFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects'
summaryFile='Scraping_List.txt'
st=pd.read_csv(SummaryFolder+'\\'+summaryFile)
print(st)
#Define Product to extract
search_text = st['Product Name'][9]
print(search_text)
Source="OReilyAuto"
OFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Outputs'
IFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Inputs'
filename=Source+'ProductLinks_'+search_text+'.xlsx'
df1=pd.read_excel(IFolder+'\\'+filename)
df1

                                  Product Name
0                                Ignition Coil
1                      Windshield Washer Pumps
2                        coupler trailer locks
3          Adjustable Trailer Hitch Ball Mount
4                               Vacuum Cleaner
5                                   Spark Plug
6              bluetooth Enabled Trailer locks
7                          Power Steering Hose
8   Power Steering Pressure Line Hose Assembly
9                       Washer Fluid Reservoir
10          Hitch Ball Mount with Weight Scale
11                               LED Headlamps
12                             LED flashlights
13                   Fiberglass Tonneau Covers
14                    Aluminium Tonneau Covers
15                     Hardfold Tonneau Covers
16                            Spark Plug Wires
17                 washer fluid reservoir tank
18                   Non Automotive Gas Struts
Washer Fluid Reservoir

,Links,Name
0,https://www.oreillyauto.com/detail/c/dorman-oe...,Dorman OE Solutions Plastic Washer Fluid Reser...
1,https://www.oreillyauto.com/detail/c/dorman-oe...,Dorman OE Solutions Plastic Washer Fluid Reser...
2,https://www.oreillyauto.com/detail/c/dorman-oe...,Dorman OE Solutions Plastic Washer Fluid Reser...
3,https://www.oreillyauto.com/detail/c/dorman-oe...,Dorman OE Solutions Plastic Washer Fluid Reser...
4,https://www.oreillyauto.com/detail/c/dorman-oe...,Dorman OE Solutions Plastic Washer Fluid Reser...
...,...,...
121,https://www.oreillyauto.com/detail/c/dorman-hd...,Dorman HD Solutions Plastic Washer Fluid Reser...
122,https://www.oreillyauto.com/detail/c/dorman-hd...,Dorman HD Solutions Plastic Washer Fluid Reser...
123,https://www.oreillyauto.com/detail/c/dorman-hd...,Dorman HD Solutions Plastic Washer Fluid Reser...
124,https://www.oreillyauto.com/detail/c/uro-parts...,URO Parts Washer Fluid Reservoir
125,https://www.oreillyauto.com/detail/c/uro-parts...,URO Parts Washer Fluid Reservoir

In [4]:
df1.loc[1,"Name"]

'Dorman OE Solutions Plastic Washer Fluid Reservoir'

In [5]:
links=[]
for i in range(len(df1)):
    if " " in df1.loc[i,"Name"]:
        links.append(df1['Links'][i])

In [6]:
length=len(links)

# 3. Setting Webdriver and Website Specific Information

In [52]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
wait=WebDriverWait(driver, 5)
driver.get('https://www.oreillyauto.com//')

In [4]:
driver.find_element(By.CLASS_NAME,'header-icon-button-text__top').click()
pin = driver.find_element(By.ID, 'find-a-store-search')
sleep(1)
pinnumber='94002'
pin.send_keys(pinnumber)

StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=131.0.6778.86); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
	GetHandleVerifier [0x00007FF62AE66CB5+28821]
	(No symbol) [0x00007FF62ADD3840]
	(No symbol) [0x00007FF62AC7578A]
	(No symbol) [0x00007FF62AC7C2ED]
	(No symbol) [0x00007FF62AC7EFCC]
	(No symbol) [0x00007FF62AC7F09F]
	(No symbol) [0x00007FF62ACCA0AC]
	(No symbol) [0x00007FF62ACCA174]
	(No symbol) [0x00007FF62ACBFDA7]
	(No symbol) [0x00007FF62ACEF2FA]
	(No symbol) [0x00007FF62ACBC3F6]
	(No symbol) [0x00007FF62ACEF510]
	(No symbol) [0x00007FF62AD0F412]
	(No symbol) [0x00007FF62ACEF0A3]
	(No symbol) [0x00007FF62ACBA778]
	(No symbol) [0x00007FF62ACBB8E1]
	GetHandleVerifier [0x00007FF62B19FCAD+3408013]
	GetHandleVerifier [0x00007FF62B1B741F+3504127]
	GetHandleVerifier [0x00007FF62B1AB5FD+3455453]
	GetHandleVerifier [0x00007FF62AF2BDBB+835995]
	(No symbol) [0x00007FF62ADDEB5F]
	(No symbol) [0x00007FF62ADDA814]
	(No symbol) [0x00007FF62ADDA9AD]
	(No symbol) [0x00007FF62ADCA199]
	BaseThreadInitThunk [0x00007FFAE3487344+20]
	RtlUserThreadStart [0x00007FFAE4A226B1+33]

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [5]:
cols =['Sl.No','Attributes'] #,'Review_Mentions'
df = pd.DataFrame(columns=cols)
df
count=0

In [10]:
from IPython.display import clear_output 
import numpy as np
from datetime import timedelta
import datetime 
timestamp=[]
timediff=[]
def timeremaining(balanceitem,i):
    timestamp.insert(i,datetime.datetime.now())
    if i>=1:
        diff=timestamp[i]-timestamp[i-1]
        timediff.insert(i,diff.total_seconds())		
        remainingtime=np.median(timediff)*balanceitem
        millis=int(remainingtime)		
        #print(millis)
        seconds=(millis)%60
        seconds = int(seconds)
        minutes=(millis/(60))%60
        minutes = int((minutes)) #math.floor
        hours=(millis/(60*60))%24
        hours=int(hours)
        print(f'Item looped: {i+1} \nItems Remining: {balanceitem-1} and \nTime Remaining: {hours}:{minutes}:{seconds}')
        etc=datetime.datetime.now()+timedelta(hours=hours,minutes=minutes,seconds=seconds)
        print(f'Estimated time of completion:{etc}')        
        clear_output(wait=True)

In [7]:
numbers=["CP5104",
"CP6009",
"CP6653",
"CP6169",
"CP6681",
"CP6341",
"CP6222",
"CP7163",
"CP4114",
"CP7168",
"CP6158",
"CP6682",
"CP6680",
"CP6348",
"CP5077",
"CP6741",
"CP6699",
"CP5103",
"CP7160",
"CP6662"]

In [ ]:
searchbox=driver.find_element(By.ID,"header-search-input")
searchbox.click()
searchbox.send_keys(numbers[0])
searchbox.send_keys(Keys.ENTER)
sleep(4)

ElementClickInterceptedException: Message: element click intercepted: Element <h2 class="js-product-name js-ga-product-name product__name" data-line="MTC" data-item="CP5104">...</h2> is not clickable at point (747, 621). Other element would receive the click: <div>...</div>
  (Session info: chrome=131.0.6778.86)
Stacktrace:
	GetHandleVerifier [0x00007FF62AE66CB5+28821]
	(No symbol) [0x00007FF62ADD3840]
	(No symbol) [0x00007FF62AC7578A]
	(No symbol) [0x00007FF62ACD0E8E]
	(No symbol) [0x00007FF62ACCE92C]
	(No symbol) [0x00007FF62ACCBAF6]
	(No symbol) [0x00007FF62ACCAA51]
	(No symbol) [0x00007FF62ACBCBA0]
	(No symbol) [0x00007FF62ACEF2FA]
	(No symbol) [0x00007FF62ACBC3F6]
	(No symbol) [0x00007FF62ACEF510]
	(No symbol) [0x00007FF62AD0F412]
	(No symbol) [0x00007FF62ACEF0A3]
	(No symbol) [0x00007FF62ACBA778]
	(No symbol) [0x00007FF62ACBB8E1]
	GetHandleVerifier [0x00007FF62B19FCAD+3408013]
	GetHandleVerifier [0x00007FF62B1B741F+3504127]
	GetHandleVerifier [0x00007FF62B1AB5FD+3455453]
	GetHandleVerifier [0x00007FF62AF2BDBB+835995]
	(No symbol) [0x00007FF62ADDEB5F]
	(No symbol) [0x00007FF62ADDA814]
	(No symbol) [0x00007FF62ADDA9AD]
	(No symbol) [0x00007FF62ADCA199]
	BaseThreadInitThunk [0x00007FFAE3487344+20]
	RtlUserThreadStart [0x00007FFAE4A226B1+33]

In [43]:
cols_comment =[ "Part Number", "Product Name", "Title", "Comments","Star", "Review Date"] #,'Review_Mentions','Standards'
df = pd.DataFrame(columns=cols_comment)
count=0

In [ ]:
driver.find_elements(By.CLASS_NAME,"product__link")[0].click()
driver.find_elements(By.CLASS_NAME,"bv_stars_component_container")[0].click()

In [42]:
items=driver.find_elements(By.CLASS_NAME,'bv-content-review')
len(items)

101

In [44]:
for i in range(len(items)):
    df.loc[count,"Part Number"]= driver.find_element(By.CLASS_NAME,"product_part-info").text.split("# ")[1].split(" ")[0]
    df.loc[count,"Product Name"]= driver.find_element(By.CLASS_NAME,'js-ga-product-name').text
    df.loc[count,"Title"]= items[i].find_element(By.CLASS_NAME,"bv-content-title").text
    df.loc[count,"Comments"]= items[i].find_element(By.CLASS_NAME,"bv-content-summary-body-text").text
    df.loc[count,"Star"]= items[i].find_element(By.CLASS_NAME,"bv-off-screen").text.split(" out")[0]
    df.loc[count,"Review Date"]= items[i].find_element(By.CLASS_NAME,"bv-content-datetime-stamp").text
    count=count+1

In [50]:
driver.find_element(By.CSS_SELECTOR,'[class="bv-dropdown-target"]').click()

WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=131.0.6778.86)
Stacktrace:
	GetHandleVerifier [0x00007FF62AE66CB5+28821]
	(No symbol) [0x00007FF62ADD3840]
	(No symbol) [0x00007FF62AC7578A]
	(No symbol) [0x00007FF62AC6230C]
	(No symbol) [0x00007FF62AC621D0]
	(No symbol) [0x00007FF62AC78131]
	(No symbol) [0x00007FF62AD0ED12]
	(No symbol) [0x00007FF62ACEF0A3]
	(No symbol) [0x00007FF62ACBA778]
	(No symbol) [0x00007FF62ACBB8E1]
	GetHandleVerifier [0x00007FF62B19FCAD+3408013]
	GetHandleVerifier [0x00007FF62B1B741F+3504127]
	GetHandleVerifier [0x00007FF62B1AB5FD+3455453]
	GetHandleVerifier [0x00007FF62AF2BDBB+835995]
	(No symbol) [0x00007FF62ADDEB5F]
	(No symbol) [0x00007FF62ADDA814]
	(No symbol) [0x00007FF62ADDA9AD]
	(No symbol) [0x00007FF62ADCA199]
	BaseThreadInitThunk [0x00007FFAE3487344+20]
	RtlUserThreadStart [0x00007FFAE4A226B1+33]

In [45]:
df

,Part Number,Product Name,Title,Comments,Star,Review Date
0,CP5104,Murray Temperature Control Water Pump - New,Fits and works as it should,Fit perfectly on my 2006 GMC Sierra. So far ju...,5,2 days ago
1,CP5104,Murray Temperature Control Water Pump - New,"Water pump, 2005 Chevy Silverado 2500 HD LT.","The water pump was as advertised, was complete...",5,16 days ago
2,CP5104,Murray Temperature Control Water Pump - New,Refund,Some stole package from in front of the apartm...,1,2 months ago
3,CP5104,Murray Temperature Control Water Pump - New,2002 GMC sierra 1500 water pump,Pump seems to be doing its job! Quality part n...,5,2 months ago
4,CP5104,Murray Temperature Control Water Pump - New,Water Pump Replacement,02’ Chevy Tahoe 5.3L 4X4 water pump installed ...,5,3 months ago
...,...,...,...,...,...,...
96,CP5104,Murray Temperature Control Water Pump - New,Going Strong,So far pumping away and doing good so far and ...,5,6 years ago
97,CP5104,Murray Temperature Control Water Pump - New,good product,I installed this a month ago without any probl...,5,6 years ago
98,CP5104,Murray Temperature Control Water Pump - New,worked great easy to install,easy install worked great.pay me id write more...,5,6 years ago
99,CP5104,Murray Temperature Control Water Pump - New,Casting looked OEM,The water pump looked great mounted great no i...,4,6 years ago
100,CP5104,Murray Temperature Control Water Pump - New,2000 GMC Yukon XL - works with both thermostats,Just replaced the water pump on my 2000 GMC Yu...,5,6 years ago

In [41]:
element = driver.find_element(By.CLASS_NAME,"bv-content-btn-pages-load-more-text")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
element.click()

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".bv-content-btn-pages-load-more-text"}
  (Session info: chrome=131.0.6778.86); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF62AE66CB5+28821]
	(No symbol) [0x00007FF62ADD3840]
	(No symbol) [0x00007FF62AC7578A]
	(No symbol) [0x00007FF62ACC91BE]
	(No symbol) [0x00007FF62ACC94AC]
	(No symbol) [0x00007FF62AD12647]
	(No symbol) [0x00007FF62ACEF33F]
	(No symbol) [0x00007FF62AD0F412]
	(No symbol) [0x00007FF62ACEF0A3]
	(No symbol) [0x00007FF62ACBA778]
	(No symbol) [0x00007FF62ACBB8E1]
	GetHandleVerifier [0x00007FF62B19FCAD+3408013]
	GetHandleVerifier [0x00007FF62B1B741F+3504127]
	GetHandleVerifier [0x00007FF62B1AB5FD+3455453]
	GetHandleVerifier [0x00007FF62AF2BDBB+835995]
	(No symbol) [0x00007FF62ADDEB5F]
	(No symbol) [0x00007FF62ADDA814]
	(No symbol) [0x00007FF62ADDA9AD]
	(No symbol) [0x00007FF62ADCA199]
	BaseThreadInitThunk [0x00007FFAE3487344+20]
	RtlUserThreadStart [0x00007FFAE4A226B1+33]

In [11]:
for i in range(length):
    driver.get(links[i])
    df.loc[count,'Sl.No']=int(i)
    sleep(1)
    df.loc[count,'Name']=driver.find_element(By.CLASS_NAME,'js-product-name').text
    df.loc[count,'Current Price']=float(driver.find_element(By.CLASS_NAME,'js-ga-product-price').text.replace('$',"").replace(",",""))
    df.loc[count,'Part Number']=driver.find_element(By.CLASS_NAME,'js-ga-product-line-number').text
    df.loc[count,'Product']=search_text
    try:
        df.loc[count,'Rating']=float(driver.find_element(By.CSS_SELECTOR,'[itemprop="ratingValue"]').text)
    except:
        pass
    df.loc[count,'No of Ratings']=int(driver.find_element(By.CLASS_NAME,'bv_numReviews_text').text.split('(')[1].split(')')[0].replace(",",""))
    elements=driver.find_elements(By.CLASS_NAME,"col-md-6")
    Alist=[]
    for element in elements:
        Alist.append(element.text)
    #print(Alist)
    df['Attributes'] = df['Attributes'].astype('object')
    df.at[count,'Attributes']=Alist
    df.loc[count,'UPC Code']=driver.find_element(By.CLASS_NAME,'pdp-info_wrapper').text.split('UPC:  # ')[1].split('\n')[0]
    df.loc[count,'Details']=driver.find_element(By.CSS_SELECTOR,'[itemprop="description"]').text
    df.loc[count,'Source']=Source
    df.loc[count,'Links']=links[i]   
    count=count+1
    balanceitem=length-i
    timeremaining(balanceitem,i)
    clear_output(wait=True)

Item looped: 126
Items Remining: 0 and
Time Remaining: 0:0:8
Estimated time of completion:2024-02-09 12:46:57.999631

In [12]:
print(df.shape)
df.head()

(126, 12)

,Sl.No,Attributes,Name,Current Price,Part Number,Product,No of Ratings,UPC Code,Details,Source,Links,Rating
0,0,"[Warranty: Limited Lifetime Warranty, Unit of...",Dorman OE Solutions Plastic Washer Fluid Reser...,90.99,603-005,Washer Fluid Reservoir,0.0,19495347828,Detailed Description\nWindshield Washer Fluid ...,OReilyAuto,https://www.oreillyauto.com/detail/c/dorman-oe...,NaN
1,1,"[Warranty: Limited Lifetime Warranty, Unit of...",Dorman OE Solutions Plastic Washer Fluid Reser...,99.99,603-006,Washer Fluid Reservoir,0.0,19495347835,Detailed Description\nWindshield Washer Fluid ...,OReilyAuto,https://www.oreillyauto.com/detail/c/dorman-oe...,NaN
2,2,"[Warranty: Limited Lifetime Warranty, Unit of...",Dorman OE Solutions Plastic Washer Fluid Reser...,105.99,603-014,Washer Fluid Reservoir,0.0,19495347910,Detailed Description\nWindshield Washer Fluid ...,OReilyAuto,https://www.oreillyauto.com/detail/c/dorman-oe...,NaN
3,3,"[Warranty: Limited Lifetime Warranty, Unit of...",Dorman OE Solutions Plastic Washer Fluid Reser...,60.99,603-018,Washer Fluid Reservoir,11.0,19495439400,Detailed Description\nWindshield Washer Fluid ...,OReilyAuto,https://www.oreillyauto.com/detail/c/dorman-oe...,4.7
4,4,"[Warranty: Limited Lifetime Warranty, Unit of...",Dorman OE Solutions Plastic Washer Fluid Reser...,50.99,603-023,Washer Fluid Reservoir,0.0,19495439417,Detailed Description\nWindshield Washer Fluid ...,OReilyAuto,https://www.oreillyauto.com/detail/c/dorman-oe...,NaN

# 5. Post Processing Data and Exporting

In [13]:
cols=["Sl.No",
"Name",
"Product",
"Current Price",
"Rating",
"No of Ratings",
"Details",
"Attributes",
"Part Number",
"UPC Code",
"Links",
"Source"
] 
df=df[cols]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 126 entries, 0 to 125
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sl.No          126 non-null    object
 1   Name           126 non-null    object
 2   Product        126 non-null    object
 3   Current Price  126 non-null    float64
 4   Rating         24 non-null     float64
 5   No of Ratings  126 non-null    float64
 6   Details        126 non-null    object
 7   Attributes     126 non-null    object
 8   Part Number    126 non-null    object
 9   UPC Code       126 non-null    object
 10  Links          126 non-null    object
 11  Source         126 non-null    object
dtypes: float64(3), object(9)
memory usage: 16.9+ KB

In [15]:
dfAtt=df[['UPC Code','Attributes']]
dfAtt=dfAtt.explode('Attributes')
dfAtt[['Attributes', 'Value']] = dfAtt['Attributes'].str.split(':',1, expand=True)

In [16]:
summary_df = pd.pivot_table(dfAtt, values='Value', index='Attributes',aggfunc='count').reset_index()
summary_df =summary_df.sort_values(by='Value',ascending=False)
summary_df=summary_df.rename(columns ={'Value':'No Products contains this Attribute'})
summary_df

                     Attributes  No Products contains this Attribute
21                     Warranty                                  126
20              Unit of Measure                                  126
19                          UPC                                  126
14                     Material                                  124
8             Hardware Included                                  124
1                  Cap Included                                  124
0              Bracket Included                                  114
4                         Color                                  114
6   Fluid Level Sensor Included                                   14
16                  Pressurized                                   14
15     Number Of Mounting Holes                                   13
18              Sensor Included                                   10
22         Washer Pump Included                                    8
24                   Width (mm)                                    8
11                Hose Included                                    8
3                      Capacity                                    8
10                  Height (mm)                                    7
12      Hose Port Diameter (in)                                    7
13                  Length (mm)                                    5
23                   Width (in)                                    5
2                      Cap Type                                    4
9                   Height (in)                                    3
7              Grommet Included                                    3
5            Fill Neck Included                                    3
17       Reservoir Cap Included                                    1

In [17]:
with pd.ExcelWriter(OFolder+'\\'+f'{Source}ProductDetails_'+search_text+'.xlsx') as writer:  # doctest: +SKIP
    df.to_excel(writer,index=False, sheet_name='Raw')
    summary_df.to_excel(writer,index=False, sheet_name='Attribute_Summary')

# 99. Archived Codes

In [ ]:
# for i in range(42,127):#len(links)):
#     Rows=[]
#     driver.get(links[i])
#     Rows.append(i)
#     sleep(1)
#     product = driver.find_elements(By.XPATH, "//span[@class='a-size-large product-title-word-break']")
#     if len(product)==0:
#         Rows.append("-")
#     else:
#         for n in product:
#             Rows.append(n.text)
#     price=driver.find_elements(By.XPATH, "//span[@class='a-price a-text-price a-size-medium apexPriceToPay']")
#     if len(price)==0:
#         price=driver.find_elements(By.XPATH, "//span[@class='a-price aok-align-center reinventPricePriceToPayMargin priceToPay']")
#     if len(price)==0:
#         Rows.append("-")
#     else:
#         for pr in price:
#             if "\n" in pr.text:
#                 prm=pr.text.replace('\n',".")
#                 Rows.append(prm)
#             else:    
#                 if pr.text== "":
#                     pass
#                 else: 
#                     Rows.append(pr.text)
#     try:
#         listprice=driver.find_element(By.CLASS_NAME,"basisPrice")
#         Rows.append(listprice.text.split("$")[1])
#     except:
#         for pr in price:
#             if "\n" in pr.text:
#                 prm=pr.text.replace('\n',".")
#                 Rows.append(prm)
#             else:    
#                 if pr.text== "":
#                     pass
#                 else: 
#                     Rows.append(pr.text)
#     try:
#         rating=driver.find_element(By.ID, "averageCustomerReviews")
#         if len(rating.text)==0:
#             Rows.append("-")
#         else:
#             Rows.append(rating.text)
#     except:
#         Rows.append("-")
#     PDetail=driver.find_elements(By.ID, "productDetails_techSpec_section_1")
#     if len(PDetail)==0:
#         Rows.append("-") 
#     else:
#         for det in PDetail:
#             Rows.append(det.text)
#     Sales = driver.find_elements(By.XPATH, "(//span[@class='a-size-small social-proofing-faceout-title-text'])")
#     if len(Sales)==0:
#         Rows.append("-")
#     else:
#         for s in Sales:
#             Rows.append(s.text)
#     IDetails=driver.find_elements(By.XPATH, "(//div[@class='a-section a-spacing-medium a-spacing-top-small'])")
#     if len(IDetails)==0:
#         Rows.append("-") 
#     else:
#         for Idet in IDetails:
#             Rows.append(Idet.text)
#     #driver.find_element(By.TAG_NAME,'body').send_keys(Keys.END)
#     #sleep(3)
#     try:
#         crt=driver.find_element(By.ID,'acrCustomerReviewText')
#         crt.click()
#     except:
#         print("no Review")
#     sleep(2)
#     # try:
#     #     Reveiews=driver.find_element(By.ID, "cr-lighthut-1-")
#     #     list_items = Reveiews.find_elements(By.CLASS_NAME,"cr-lighthouse-term ")
#     #     ListWords=[]
#     #     for item in list_items:
#     #         ListWords.append(item.text)
#     #     Rows.append(ListWords)         
#     # except:
#     #     Rows.append("-") 
#     Rows.append(links[i])
#     new_row=pd.DataFrame([Rows],columns=cols)
#     df=pd.concat([df,new_row])
#     print("Scanned pages:", i+1,"@",datetime.datetime.now())

In [ ]:
def tryconvert(value, default, *types):
    for t in types:
        try:
            return t(value)
        except (ValueError, TypeError):
            continue
    return default