# 1. Library calling

In [891]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
import warnings
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

from janitor import xlsx_table

# 2. Defining the Product Information and Location

In [892]:
OFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\15_Fuel_Injector'
IFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\15_Fuel_Injector\Inputs'
filename="Fuel_Injector_Dataset.xlsx"
df=xlsx_table(IFolder+'\\'+filename,sheetname="Photos", table="Data_List")
df

,Part Number,Link,Spec,Coverage,Column1
0,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chrysler 200 (17-11)\nChrysler 300 (19-11)\nCh...,None
1,STD_FJ315,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Buick Rainier (04)\nCadillac Escalade (06-02)\...,None
2,STD_FJ1217,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Cadillac Escalade (21)\nCadillac Escalade ESV ...,None
3,STD_FJ1000,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Edge (10-07)\nFord Flex (12-09)\nFord Fus...,None
4,STD_FJ612,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chrysler 300 (10-05)\nChrysler Cirrus (06-05)\...,None
5,STD_FJ1116,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Edge (22-11)\nFord Explorer (19-11)\nFord...,None
6,STD_FJ474,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Dodge Dakota (10-04)\nDodge Durango (09-04)\nD...,None
7,STD_FJ504,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Cadillac Escalade (00-99)\nChevrolet C1500 (99...,None
8,STD_FJ503,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chevrolet Astro (05-96)\nChevrolet Blazer (05-...,None
9,STD_FJ475,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chrysler Aspen (07)\nDodge Dakota (07-01)\nDod...,None
10,STD_FJ713,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Bronco (96-90)\nFord Crown Victoria (97-9...,None
11,STD_FJ732,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...","Chrysler 300 (18), (16-05)\nChrysler Aspen (09...",None
12,STD_TJ7,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Buick Commercial Chassis (93-92)\nBuick Roadma...,None
13,STD_FJ712,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Aerostar (97-86)\nFord Bronco (92-87)\nFo...,None
14,STD_FJ1029,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chrysler Town & Country (10-08)\nChrysler Voya...,None
15,STD_FJ682,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Dodge B1500 (98-96)\nDodge B2500 (98-96)\nDodg...,None
16,STD_FJ817,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Expedition (06-05)\nFord F-150 (07-05)\nF...,None
17,STD_FJ454,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Dodge Durango (00)\nDodge Ram 1500 (01-00)\nDo...,None
18,STD_FJ998,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Escape (12-09)\nFord Fusion (12-10)\nMazd...,None
19,STD_FJ1061,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Cadillac Escalade (13-10)\nChevrolet Avalanche...,None
20,STD_FJ485,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Acura ILX (15-13)\nAcura MDX (06-03)\nAcura TL...,None
21,STD_FJ977,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chevrolet Avalanche (09-07)\nChevrolet Avalanc...,None
22,STD_FJ463,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Ranger (08-01)\nMazda B3000 (07-01),None
23,STD_FJ1089,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chevrolet Express 2500 (20-10)\nChevrolet Expr...,None
24,STD_FJ1267,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Jeep Cherokee (17-14),None
25,STD_FJ887,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Buick Rainier (07-05)\nCadillac Escalade (09-0...,None
26,STD_FJ867,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford E-150 (08-04)\nFord E-150 Club Wagon (05-...,None
27,STD_FJ818,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Explorer (10-06)\nFord Explorer Sport Tra...,None
28,STD_FJ994,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Buick Enclave (11-09)\nBuick LaCrosse (11-10)\...,None
29,STD_FJ68,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...","Ford Bronco (91-90), (86-85)\nFord E-150 Econo...",None
30,STD_FJ241,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chevrolet B7 (00-99)\nChevrolet C2500 (00-99)\...,None
31,STD_FJ869,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford F-150 (08-05),None
32,STD_FJ460,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford E-150 (03)\nFord E-150 Club Wagon (03)\nF...,None
33,STD_FJ319,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Buick Rainier (07-04)\nChevrolet Colorado (07-...,None
34,DOR_904-120,https://www.standardbrand.com/en/ecatalog?part...,None,None,None
35,BA_158-0460,https://www.standardbrand.com/en/ecatalog?part...,None,None,None
36,STD_FJ585,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Toyota 4Runner (02-99)\nToyota Tacoma (04-99)\...,None
37,BOS_0986435502,https://www.standardbrand.com/en/ecatalog?part...,None,None,None
38,STD_FJ1138,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Expedition (17-15)\nFord F-150 (16-11)\nF...,None
39,STD_FJ482,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chrysler Aspen (08-07)\nDodge Durango (09-04)\...,None
40,ACD_12710481,https://www.standardbrand.com/en/ecatalog?part...,None,None,None
41,STD_FJ100,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Buick Century (96-93)\nChevrolet Beretta (96-9...,None
42,STD_FJ928,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford E-350 Club Wagon (05-04)\nFord E-350 Supe...,None
43,STD_IFS3,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nContents:\n...",Dodge Ram 2500 (10-03)\nDodge Ram 3500 (10-03)...,None
44,STD_FJ738,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford E-350 Club Wagon (03)\nFord E-350 Econoli...,None
45,STD_FJ489,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nEngine ID C...",Chevrolet C4500 Kodiak (05-04)\nChevrolet C550...,None
46,STD_FJ960,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford F-250 Super Duty (10-08)\nFord F-350 Supe...,None
47,STD_FJ927,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Excursion (04-03)\nFord F-250 Super Duty ...,None
48,STD_FJ1226,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nEngine Vin ...",Chevrolet Silverado 2500 HD (16-11)\nChevrolet...,None
49,STD_FJ173,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",AM General Hummer (01-96)\nChevrolet Blazer (9...,None
50,STD_HPI2,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nConnector G...",Ford E-350 Club Wagon (03)\nFord E-350 Econoli...,None
51,STD_FJ258,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford E-250 Econoline Club Wagon (91-83)\nFord ...,None
52,STD_FJ933,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Dodge Ram 2500 (09-04)\nDodge Ram 3500 (08-04),None
53,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford F-250 Super Duty (13-11)\nFord F-350 Supe...,None

In [893]:
del df["Column1"]

In [894]:
df=df.dropna().reset_index()
df

,index,Part Number,Link,Spec,Coverage
0,0,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chrysler 200 (17-11)\nChrysler 300 (19-11)\nCh...
1,1,STD_FJ315,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Buick Rainier (04)\nCadillac Escalade (06-02)\...
2,2,STD_FJ1217,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Cadillac Escalade (21)\nCadillac Escalade ESV ...
3,3,STD_FJ1000,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Edge (10-07)\nFord Flex (12-09)\nFord Fus...
4,4,STD_FJ612,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chrysler 300 (10-05)\nChrysler Cirrus (06-05)\...
5,5,STD_FJ1116,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Edge (22-11)\nFord Explorer (19-11)\nFord...
6,6,STD_FJ474,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Dodge Dakota (10-04)\nDodge Durango (09-04)\nD...
7,7,STD_FJ504,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Cadillac Escalade (00-99)\nChevrolet C1500 (99...
8,8,STD_FJ503,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chevrolet Astro (05-96)\nChevrolet Blazer (05-...
9,9,STD_FJ475,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chrysler Aspen (07)\nDodge Dakota (07-01)\nDod...
10,10,STD_FJ713,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Bronco (96-90)\nFord Crown Victoria (97-9...
11,11,STD_FJ732,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...","Chrysler 300 (18), (16-05)\nChrysler Aspen (09..."
12,12,STD_TJ7,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Buick Commercial Chassis (93-92)\nBuick Roadma...
13,13,STD_FJ712,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Aerostar (97-86)\nFord Bronco (92-87)\nFo...
14,14,STD_FJ1029,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chrysler Town & Country (10-08)\nChrysler Voya...
15,15,STD_FJ682,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Dodge B1500 (98-96)\nDodge B2500 (98-96)\nDodg...
16,16,STD_FJ817,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Expedition (06-05)\nFord F-150 (07-05)\nF...
17,17,STD_FJ454,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Dodge Durango (00)\nDodge Ram 1500 (01-00)\nDo...
18,18,STD_FJ998,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Escape (12-09)\nFord Fusion (12-10)\nMazd...
19,19,STD_FJ1061,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Cadillac Escalade (13-10)\nChevrolet Avalanche...
20,20,STD_FJ485,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Acura ILX (15-13)\nAcura MDX (06-03)\nAcura TL...
21,21,STD_FJ977,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chevrolet Avalanche (09-07)\nChevrolet Avalanc...
22,22,STD_FJ463,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Ranger (08-01)\nMazda B3000 (07-01)
23,23,STD_FJ1089,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chevrolet Express 2500 (20-10)\nChevrolet Expr...
24,24,STD_FJ1267,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Jeep Cherokee (17-14)
25,25,STD_FJ887,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Buick Rainier (07-05)\nCadillac Escalade (09-0...
26,26,STD_FJ867,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford E-150 (08-04)\nFord E-150 Club Wagon (05-...
27,27,STD_FJ818,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Explorer (10-06)\nFord Explorer Sport Tra...
28,28,STD_FJ994,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Buick Enclave (11-09)\nBuick LaCrosse (11-10)\...
29,29,STD_FJ68,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...","Ford Bronco (91-90), (86-85)\nFord E-150 Econo..."
30,30,STD_FJ241,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chevrolet B7 (00-99)\nChevrolet C2500 (00-99)\...
31,31,STD_FJ869,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford F-150 (08-05)
32,32,STD_FJ460,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford E-150 (03)\nFord E-150 Club Wagon (03)\nF...
33,33,STD_FJ319,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Buick Rainier (07-04)\nChevrolet Colorado (07-...
34,36,STD_FJ585,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Toyota 4Runner (02-99)\nToyota Tacoma (04-99)\...
35,38,STD_FJ1138,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Expedition (17-15)\nFord F-150 (16-11)\nF...
36,39,STD_FJ482,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Chrysler Aspen (08-07)\nDodge Durango (09-04)\...
37,41,STD_FJ100,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Buick Century (96-93)\nChevrolet Beretta (96-9...
38,42,STD_FJ928,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford E-350 Club Wagon (05-04)\nFord E-350 Supe...
39,43,STD_IFS3,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nContents:\n...",Dodge Ram 2500 (10-03)\nDodge Ram 3500 (10-03)...
40,44,STD_FJ738,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford E-350 Club Wagon (03)\nFord E-350 Econoli...
41,45,STD_FJ489,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nEngine ID C...",Chevrolet C4500 Kodiak (05-04)\nChevrolet C550...
42,46,STD_FJ960,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford F-250 Super Duty (10-08)\nFord F-350 Supe...
43,47,STD_FJ927,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford Excursion (04-03)\nFord F-250 Super Duty ...
44,48,STD_FJ1226,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nEngine Vin ...",Chevrolet Silverado 2500 HD (16-11)\nChevrolet...
45,49,STD_FJ173,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",AM General Hummer (01-96)\nChevrolet Blazer (9...
46,50,STD_HPI2,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nConnector G...",Ford E-350 Club Wagon (03)\nFord E-350 Econoli...
47,51,STD_FJ258,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford E-250 Econoline Club Wagon (91-83)\nFord ...
48,52,STD_FJ933,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Dodge Ram 2500 (09-04)\nDodge Ram 3500 (08-04)
49,53,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...,"Warranty:\n3 years/36,000 mile\n \nNew or Rema...",Ford F-250 Super Duty (13-11)\nFord F-350 Supe...

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [895]:
cols1 =['Sl.No','Model_Years','Years'] #,'Review_Mentions'
cols2 =['Sl.No',"Attributes"] #,'Review_Mentions'
df1= pd.DataFrame(columns=cols1)
df2= pd.DataFrame(columns=cols2)

In [896]:
count=0
for i in range(len(df)):
    Alist=[]
    q=(len(df["Coverage"][i].split("\n")))
    for j in range(q):
        df1.loc[count,'Sl.No']=count
        df1.loc[count,"Make"]=(df["Coverage"][i].split("\n")[j].split(" ",1)[0])
        df1.loc[count,"Model"]=(df["Coverage"][i].split("\n")[j].split("(",1)[0].split(" ",1)[1])
        df1.at[count,"Model_Years"]=(df["Coverage"][i].split("\n")[j].split("(",1)[1].replace("(","").replace(")","").replace(" ","").split(","))
        df1.loc[count,"Part Number"]=df["Part Number"][i]
        df1.loc[count,"Link"]=df["Link"][i]
        count=count+1

In [897]:
df1

,Sl.No,Model_Years,Years,Make,Model,Part Number,Link
0,0,[17-11],NaN,Chrysler,200,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...
1,1,[19-11],NaN,Chrysler,300,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...
2,2,[16-11],NaN,Chrysler,Town & Country,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...
3,3,[14-11],NaN,Dodge,Avenger,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...
4,4,[19-11],NaN,Dodge,Challenger,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...
...,...,...,...,...,...,...,...
786,786,[08-04],NaN,Dodge,Ram 3500,STD_FJ933,https://www.standardbrand.com/en/ecatalog?part...
787,787,[13-11],NaN,Ford,F-250 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...
788,788,[16-11],NaN,Ford,F-350 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...
789,789,[16-11],NaN,Ford,F-450 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...
790,790,[16-11],NaN,Ford,F-550 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...

In [898]:
df1=df1=df1.explode('Model_Years').reset_index()
df1

,index,Sl.No,Model_Years,Years,Make,Model,Part Number,Link
0,0,0,17-11,NaN,Chrysler,200,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...
1,1,1,19-11,NaN,Chrysler,300,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...
2,2,2,16-11,NaN,Chrysler,Town & Country,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...
3,3,3,14-11,NaN,Dodge,Avenger,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...
4,4,4,19-11,NaN,Dodge,Challenger,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...
...,...,...,...,...,...,...,...,...
818,786,786,08-04,NaN,Dodge,Ram 3500,STD_FJ933,https://www.standardbrand.com/en/ecatalog?part...
819,787,787,13-11,NaN,Ford,F-250 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...
820,788,788,16-11,NaN,Ford,F-350 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...
821,789,789,16-11,NaN,Ford,F-450 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...
822,790,790,16-11,NaN,Ford,F-550 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...

In [899]:
for i in range(len(df1)):
    if "-" in df1['Model_Years'][i]:
        #print(i)
        year=df1['Model_Years'].str.split('-')[i]
        startyear=year[1]
        endyear=year[0]
        df1.loc[i,'Start_Year']=startyear
        df1.loc[i,'End_Year']=endyear
    if "-" not in df1['Model_Years'][i]:
        #print (i)
        df1.loc[i,'Start_Year']=df1['Model_Years'][i]
        df1.loc[i,'End_Year']=df1['Model_Years'][i]

In [900]:
df1

,index,Sl.No,Model_Years,Years,Make,Model,Part Number,Link,Start_Year,End_Year
0,0,0,17-11,NaN,Chrysler,200,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,11,17
1,1,1,19-11,NaN,Chrysler,300,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,11,19
2,2,2,16-11,NaN,Chrysler,Town & Country,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,11,16
3,3,3,14-11,NaN,Dodge,Avenger,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,11,14
4,4,4,19-11,NaN,Dodge,Challenger,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,11,19
...,...,...,...,...,...,...,...,...,...,...
818,786,786,08-04,NaN,Dodge,Ram 3500,STD_FJ933,https://www.standardbrand.com/en/ecatalog?part...,04,08
819,787,787,13-11,NaN,Ford,F-250 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...,11,13
820,788,788,16-11,NaN,Ford,F-350 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...,11,16
821,789,789,16-11,NaN,Ford,F-450 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...,11,16
822,790,790,16-11,NaN,Ford,F-550 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...,11,16

In [901]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        823 non-null    int64
 1   Sl.No        823 non-null    object
 2   Model_Years  823 non-null    object
 3   Years        0 non-null      object
 4   Make         823 non-null    object
 5   Model        823 non-null    object
 6   Part Number  823 non-null    object
 7   Link         823 non-null    object
 8   Start_Year   823 non-null    object
 9   End_Year     823 non-null    object
dtypes: int64(1), object(9)
memory usage: 64.4+ KB

In [902]:
Nprefix="20"
Oprefix="19"
for i in range(len(df1)):

    if int(df1['Start_Year'][i]) <24:
        df1.loc[i,'Start_Year']=int(Nprefix+df1['Start_Year'][i])
    else:
        df1.loc[i,'Start_Year']=int(Oprefix+df1['Start_Year'][i])

In [903]:
Nprefix="20"
Oprefix="19"
for i in range(len(df1)):

    if int(df1['End_Year'][i]) <24:
        df1.loc[i,'End_Year']=int(Nprefix+df1['End_Year'][i])
    else:
        df1.loc[i,'End_Year']=int(Oprefix+df1['End_Year'][i])

In [904]:
for i in range (len(df1)):    
    df1.at[i,"Years"]=list(range(df1["Start_Year"][i],(df1["End_Year"][i]+1)))
    
df1=df1.explode('Years')

In [906]:
df1

,index,Sl.No,Model_Years,Years,Make,Model,Part Number,Link,Start_Year,End_Year
0,0,0,17-11,2011,Chrysler,200,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,2011,2017
0,0,0,17-11,2012,Chrysler,200,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,2011,2017
0,0,0,17-11,2013,Chrysler,200,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,2011,2017
0,0,0,17-11,2014,Chrysler,200,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,2011,2017
0,0,0,17-11,2015,Chrysler,200,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,2011,2017
...,...,...,...,...,...,...,...,...,...,...
822,790,790,16-11,2012,Ford,F-550 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...,2011,2016
822,790,790,16-11,2013,Ford,F-550 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...,2011,2016
822,790,790,16-11,2014,Ford,F-550 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...,2011,2016
822,790,790,16-11,2015,Ford,F-550 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...,2011,2016
822,790,790,16-11,2016,Ford,F-550 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...,2011,2016

In [907]:
df1["Application"]=df1["Years"].astype(str)+" "+df1["Make"]+" "+df1["Model"]
df1

,index,Sl.No,Model_Years,Years,Make,Model,Part Number,Link,Start_Year,End_Year,Application
0,0,0,17-11,2011,Chrysler,200,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,2011,2017,2011 Chrysler 200
0,0,0,17-11,2012,Chrysler,200,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,2011,2017,2012 Chrysler 200
0,0,0,17-11,2013,Chrysler,200,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,2011,2017,2013 Chrysler 200
0,0,0,17-11,2014,Chrysler,200,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,2011,2017,2014 Chrysler 200
0,0,0,17-11,2015,Chrysler,200,STD_FJ1147,https://www.standardbrand.com/en/ecatalog?part...,2011,2017,2015 Chrysler 200
...,...,...,...,...,...,...,...,...,...,...,...
822,790,790,16-11,2012,Ford,F-550 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...,2011,2016,2012 Ford F-550 Super Duty
822,790,790,16-11,2013,Ford,F-550 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...,2011,2016,2013 Ford F-550 Super Duty
822,790,790,16-11,2014,Ford,F-550 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...,2011,2016,2014 Ford F-550 Super Duty
822,790,790,16-11,2015,Ford,F-550 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...,2011,2016,2015 Ford F-550 Super Duty
822,790,790,16-11,2016,Ford,F-550 Super Duty,STD_FJ1222,https://www.standardbrand.com/en/ecatalog?part...,2011,2016,2016 Ford F-550 Super Duty

In [908]:
cols=["Part Number","Make","Model","Years","Application","Link"]
df1=df1[cols]

In [909]:
count=0
for i in range(len(df)):
    Alist=[]
    d=df['Spec'][i].replace(":\n",":").split("\n")
    for k in range(len(d)):
        if len(d[k])>2:
            Alist.append(d[k])
    df2.loc[count,"Part Number"]=df["Part Number"][i]
    df2.loc[count,"Link"]=df["Link"][i]
    df2.at[count,"Attributes"]=Alist
    count=count+1

In [918]:
dfAtt=df2[['Part Number','Attributes',"Link"]]
dfAtt=dfAtt.explode('Attributes')
dfAtt=dfAtt.explode('Attributes')
dfAtt[['Attributes', 'Value']] = dfAtt['Attributes'].str.split(':',1, expand=True)
dfffff=dfAtt.pivot(index='Part Number',columns='Attributes')['Value']
dfffff

Attributes,Color/Finish,Connector Gender,Contents,Engine ID Code,Engine Vin Code,Fuel Injection Type,Fuel Injector Type,Functions,Hardware included,Injectors Covered per Kit,Material,New or Reman,Notes,O-Rings Included,O.E.M. Replacement,System Type,Terminal Gender,Terminal Quantity,Terminal Type,Warranty
Part Number,,,,,,,,,,,,,,,,,,,,
STD_FJ100,Gray,NaN,NaN,NaN,NaN,NaN,MFI,NaN,NaN,NaN,NaN,New,Includes O-ring,NaN,NaN,Gas,Male,2,Blade,"3 years/36,000 mile"
STD_FJ1000,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,NaN,NaN,NaN,New,NaN,NaN,NaN,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ1029,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,No,NaN,NaN,New,NaN,Yes,NaN,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ1061,Black,NaN,NaN,NaN,NaN,MFI,MFI,NaN,NaN,NaN,NaN,New,NaN,Yes,Yes,Other,Male,2,Blade,"3 years/36,000 mile"
STD_FJ1089,"Black, Blue",NaN,NaN,NaN,NaN,NaN,MFI,NaN,NaN,NaN,NaN,New,NaN,No,NaN,Gas,NaN,NaN,NaN,"3 years/36,000 mile"
STD_FJ1116,"Black, Red, Silver",NaN,NaN,NaN,NaN,NaN,MFI,NaN,No,NaN,NaN,New,NaN,No,NaN,Gas,NaN,NaN,NaN,"3 years/36,000 mile"
STD_FJ1138,Black,NaN,NaN,NaN,NaN,NaN,GDI Injector,NaN,NaN,NaN,NaN,New,Includes O-ring,Yes,Yes,Direct,Male,2,Blade,"3 years/36,000 mile"
STD_FJ1147,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,No,NaN,NaN,New,NaN,Yes,Yes,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ1217,Black,NaN,NaN,NaN,NaN,NaN,GDI Injector,NaN,Yes,NaN,NaN,New,Includes O-ring,Yes,Yes,Direct,Male,2,Blade,"3 years/36,000 mile"
STD_FJ1222,Black,NaN,NaN,NaN,NaN,Diesel,Direct Injection,NaN,Yes,NaN,NaN,Remanufactured,NaN,Yes,Yes,Direct,Male,2,Blade,"3 years/36,000 mile"
STD_FJ1226,Black,NaN,NaN,NaN,8,Diesel,Direct Injection,NaN,NaN,NaN,NaN,Remanufactured,NaN,Yes,Yes,Direct,Male,2,Blade,"3 years/36,000 mile"
STD_FJ1267,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,No,NaN,NaN,New,NaN,Yes,NaN,Gas,Male,2,Blade,"3 years/36,000 mile"
STD_FJ173,Black,NaN,NaN,NaN,NaN,NaN,Direct Injection,NaN,NaN,NaN,NaN,New,NaN,NaN,NaN,Direct,NaN,NaN,NaN,"3 years/36,000 mile"
STD_FJ241,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,NaN,NaN,NaN,New,NaN,Yes,NaN,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ258,Black,NaN,NaN,NaN,NaN,NaN,Direct Injection,NaN,NaN,NaN,NaN,New,NaN,NaN,NaN,Direct,NaN,NaN,NaN,"3 years/36,000 mile"
STD_FJ315,Black,NaN,NaN,NaN,NaN,MFI,MFI,NaN,NaN,NaN,NaN,New,NaN,NaN,NaN,Gas,Male,2,Blade,"3 years/36,000 mile"
STD_FJ319,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,No,NaN,NaN,New,Includes O-ring,Yes,NaN,Top Feed,Male,2,Pin,"3 years/36,000 mile"
STD_FJ454,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,NaN,NaN,NaN,New,Includes O-ring,Yes,NaN,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ460,Black,NaN,NaN,NaN,NaN,MFI,MFI,NaN,No,NaN,NaN,New,NaN,Yes,NaN,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ463,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,NaN,NaN,NaN,New,Includes O-ring,Yes,NaN,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ474,Black,NaN,NaN,NaN,NaN,MFI,MFI,NaN,No,NaN,NaN,New,NaN,Yes,Yes,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ475,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,NaN,NaN,NaN,New,Includes O-ring,Yes,NaN,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ482,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,No,NaN,NaN,New,NaN,Yes,Yes,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ485,NaN,NaN,NaN,NaN,NaN,MFI,Fuel,NaN,Yes,NaN,NaN,New,NaN,Yes,NaN,Other,NaN,2,NaN,"3 years/36,000 mile"
STD_FJ489,Black,NaN,NaN,LLY,2,Diesel,Direct Injection,NaN,NaN,NaN,NaN,Remanufactured,NaN,NaN,Yes,Direct,Male,2,Blade,"3 years/36,000 mile"
STD_FJ503,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,NaN,NaN,NaN,New,Includes O-ring,NaN,NaN,Other,Male,12,Pin,"3 years/36,000 mile"
STD_FJ504,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,NaN,NaN,NaN,New,Includes O-ring,NaN,NaN,Other,Male,16,Pin,"3 years/36,000 mile"
STD_FJ585,Brown,NaN,NaN,NaN,NaN,NaN,MFI,NaN,NaN,NaN,NaN,New,Includes O-ring,NaN,NaN,Gas,Male,2,Blade,"3 years/36,000 mile"
STD_FJ612,Black,NaN,NaN,NaN,NaN,MFI,MFI,NaN,NaN,NaN,NaN,New,NaN,Yes,Yes,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ68,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,No,NaN,NaN,New,NaN,Yes,NaN,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ682,Gray,NaN,NaN,NaN,NaN,NaN,MFI,NaN,No,NaN,NaN,New,NaN,Yes,NaN,Gas,Male,2,Blade,"3 years/36,000 mile"
STD_FJ712,Gray,NaN,NaN,NaN,NaN,NaN,MFI,NaN,No,NaN,NaN,New,NaN,Yes,NaN,Gas,Male,2,Blade,"3 years/36,000 mile"
STD_FJ713,Red,NaN,NaN,NaN,NaN,NaN,MFI,NaN,No,NaN,NaN,New,NaN,Yes,NaN,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ732,Black,NaN,NaN,NaN,NaN,MFI,MFI,NaN,No,NaN,NaN,New,NaN,Yes,Yes,Other,Male,2,Blade,"3 years/36,000 mile"
STD_FJ738,Brown,NaN,NaN,NaN,NaN,Diesel,Direct Injection,NaN,NaN,NaN,NaN,Remanufactured,NaN,Yes,Yes,Direct,Male,2,Blade,"3 years/36,000 mile"
STD_FJ817,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,No,NaN,NaN,New,NaN,Yes,NaN,Gas,Male,2,Blade,"3 years/36,000 mile"
STD_FJ818,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,No,NaN,NaN,New,NaN,Yes,NaN,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ867,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,No,NaN,NaN,New,NaN,Yes,NaN,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ869,Black,NaN,NaN,NaN,NaN,MFI,MFI,NaN,No,NaN,NaN,New,NaN,Yes,NaN,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ887,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,No,NaN,NaN,New,NaN,Yes,NaN,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_FJ927,Metal,NaN,NaN,NaN,NaN,Diesel,Direct Injection,NaN,NaN,NaN,NaN,Remanufactured,NaN,Yes,Yes,Direct,Male,4,Pin,"3 years/36,000 mile"
STD_FJ928,Metal,NaN,NaN,NaN,NaN,Diesel,Direct Injection,NaN,NaN,NaN,NaN,Remanufactured,NaN,Yes,Yes,Direct,Male,4,Pin,"3 years/36,000 mile"
STD_FJ933,Metal,NaN,NaN,NaN,NaN,NaN,Direct Injection,NaN,NaN,NaN,NaN,Remanufactured,w/ 5 Hole Injector Nozzle,NaN,NaN,Direct,Male,2,Stud,"3 years/36,000 mile"
STD_FJ960,Black,NaN,NaN,NaN,NaN,Diesel,Direct Injection,NaN,NaN,NaN,NaN,Remanufactured,NaN,Yes,Yes,Direct,Male,2,Blade,"3 years/36,000 mile"
STD_FJ977,Black,NaN,NaN,NaN,NaN,MFI,MFI,NaN,No,NaN,NaN,New,NaN,Yes,Yes,Gas,Male,2,Blade,"3 years/36,000 mile"
STD_FJ994,Black,NaN,NaN,NaN,NaN,NaN,GDI Injector,NaN,NaN,NaN,NaN,New,Includes O-ring,Yes,Yes,Direct,Male,2,Blade,"3 years/36,000 mile"
STD_FJ998,Black,NaN,NaN,NaN,NaN,NaN,MFI,NaN,NaN,NaN,NaN,New,NaN,NaN,NaN,Top Feed,Male,2,Blade,"3 years/36,000 mile"
STD_HPI2,NaN,No Connector,Includes Caution Sheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"3 years/36,000 mile"
STD_IFS3,NaN,NaN,"1 Connector Tube, 1 O-Ring",NaN,NaN,NaN,NaN,Diesel Fuel Injector Connector Tube,NaN,1,Steel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"3 years/36,000 mile"
STD_TJ7,Brass,NaN,NaN,NaN,NaN,NaN,TBI,NaN,NaN,NaN,NaN,Remanufactured,NaN,NaN,NaN,Other,Male,2,Pin,"3 years/36,000 mile"

In [911]:
cols=['Part Number','Attributes',"Value","Link"]
dfAtt=dfAtt[cols]

In [912]:
summary_df = pd.pivot_table(dfAtt, values='Value', index='Attributes',aggfunc='count').reset_index()
summary_df =summary_df.sort_values(by='Value',ascending=False)
summary_df=summary_df.rename(columns ={'Value':'No Products contains this Attribute'})
summary_df

                   Attributes  No Products contains this Attribute
19                   Warranty                                   50
6          Fuel Injector Type                                   48
15                System Type                                   48
11               New or Reman                                   48
0                Color/Finish                                   47
17          Terminal Quantity                                   44
16            Terminal Gender                                   43
18              Terminal Type                                   43
13           O-Rings Included                                   36
8           Hardware included                                   22
14         O.E.M. Replacement                                   17
5         Fuel Injection Type                                   16
12                      Notes                                   12
4             Engine Vin Code                                    2
2                    Contents                                    2
7                   Functions                                    1
9   Injectors Covered per Kit                                    1
1            Connector Gender                                    1
3              Engine ID Code                                    1
10                   Material                                    1

In [920]:
with pd.ExcelWriter(OFolder+'\\'+f'ProductDetails_'+"Fuel Injector"+'.xlsx') as writer:  # doctest: +SKIP
    #df.to_excel(writer,index=False, sheet_name='Raw')
    df1.to_excel(writer,index=False, sheet_name='Coverage')
    dfffff.to_excel(writer,index=True, sheet_name='Attribute Values')
    summary_df.to_excel(writer,index=False, sheet_name='Attribute_Summary')

# 99. Archived Codes