# 1. Library calling

In [1]:
#pip install selenium
#pip install webdriver_manager
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib.parse import unquote
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
import pandas as pd
import datetime 

import warnings

# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

# 2. Defining the Product Information and Location

In [2]:
SummaryFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects'
summaryFile='Scraping_List.txt'
st=pd.read_csv(SummaryFolder+'\\'+summaryFile)
print(st)
#Define Product to extract
search_text = st['Product Name'][9]
print(search_text)
Source="Summit"
OFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Outputs'
IFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Inputs'

                                  Product Name
0                                Ignition Coil
1                      Windshield Washer Pumps
2                        coupler trailer locks
3          Adjustable Trailer Hitch Ball Mount
4                               Vacuum Cleaner
5                                   Spark Plug
6              bluetooth Enabled Trailer locks
7                          Power Steering Hose
8   Power Steering Pressure Line Hose Assembly
9                       Washer Fluid Reservoir
10          Hitch Ball Mount with Weight Scale
11                               LED Headlamps
12                             LED flashlights
13                   Fiberglass Tonneau Covers
14                    Aluminium Tonneau Covers
15                     Hardfold Tonneau Covers
16                            Spark Plug Wires
17                 washer fluid reservoir tank
18                   Non Automotive Gas Struts
Washer Fluid Reservoir

# 3. Setting Webdriver and Website Specific Information

In [3]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.get('https://www.summitracing.com/')

### Please update capatche.

In [6]:
driver.maximize_window()

In [4]:
# Find the search bar by its ID
try:
    search_bar = driver.find_element(By.ID, 'KeywordSearchBox')
except:
    search_bar=driver.find_element(By.ID, "twotabsearchtextbox")

# Enter the search text

search_bar.send_keys(search_text)

# Submit the form to perform the search
search_bar.submit()
search_bar.send_keys(Keys.ENTER)

In [5]:
driver.find_element(By.CLASS_NAME,'results-display-options').click()
driver.find_element(By.XPATH, "//label[@class='custom-radio']/input[@value='100']").click()

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [5]:
Cols=["Links","Name"]
df = pd.DataFrame(columns=Cols)

In [35]:
driver.find_element(By.CSS_SELECTOR,'[class="next-page"]').click()

In [6]:
count=0
for i in range(3):
        elements = driver.find_elements(By.CSS_SELECTOR, 'div.columns.medium-17.large-18.show-for-medium h2 a')

        # Extract href and title from each element
        for element in elements:
            href = element.get_attribute('href')
            title = element.text.strip()
            df.loc[count,'Sl.No']=count+1
            df.loc[count,'Links']=href
            df.loc[count,'Name']=title
            count=count+1        
        driver.find_element(By.TAG_NAME,'body').send_keys(Keys.END)
        sleep(1)
        next_button = driver.find_element(By.CSS_SELECTOR,'[class="next-page"]')
        next_button.click()
        i=i+1
        print("No of pages =", i)

No of pages = 1
No of pages = 2
No of pages = 3

In [7]:
df

,Links,Name,Sl.No
0,https://www.summitracing.com/parts/rnb-603-131,Dorman Windshield Washer Fluid Reservoirs 603-131,1.0
1,https://www.summitracing.com/parts/rnb-603-072,Dorman Windshield Washer Fluid Reservoirs 603-072,2.0
2,https://www.summitracing.com/parts/rnb-603-162,Dorman Windshield Washer Fluid Reservoirs 603-162,3.0
3,https://www.summitracing.com/parts/rnb-603-018,Dorman Windshield Washer Fluid Reservoirs 603-018,4.0
4,https://www.summitracing.com/parts/gmk-4012-24...,Goodmark Windshield Washer Fluid Reservoirs GM...,5.0
...,...,...,...
295,https://www.summitracing.com/parts/bdy-au1288104,Body Parts Windshield Washer Reservoirs AU1288104,296.0
296,https://www.summitracing.com/parts/bdy-lx1288117,Body Parts Windshield Washer Reservoirs LX1288117,297.0
297,https://www.summitracing.com/parts/ado-23362222,ACDelco GM Genuine Parts Windshield Washer Res...,298.0
298,https://www.summitracing.com/parts/ado-84763238,ACDelco GM Genuine Parts Windshield Washer Res...,299.0
299,https://www.summitracing.com/parts/ado-19256391,ACDelco GM Genuine Parts Windshield Washer Res...,300.0

# 5. Post Processing Data and Exporting

In [8]:
df=df.drop_duplicates(subset=["Links"])
df

,Links,Name,Sl.No
0,https://www.summitracing.com/parts/rnb-603-131,Dorman Windshield Washer Fluid Reservoirs 603-131,1.0
1,https://www.summitracing.com/parts/rnb-603-072,Dorman Windshield Washer Fluid Reservoirs 603-072,2.0
2,https://www.summitracing.com/parts/rnb-603-162,Dorman Windshield Washer Fluid Reservoirs 603-162,3.0
3,https://www.summitracing.com/parts/rnb-603-018,Dorman Windshield Washer Fluid Reservoirs 603-018,4.0
4,https://www.summitracing.com/parts/gmk-4012-24...,Goodmark Windshield Washer Fluid Reservoirs GM...,5.0
...,...,...,...
295,https://www.summitracing.com/parts/bdy-au1288104,Body Parts Windshield Washer Reservoirs AU1288104,296.0
296,https://www.summitracing.com/parts/bdy-lx1288117,Body Parts Windshield Washer Reservoirs LX1288117,297.0
297,https://www.summitracing.com/parts/ado-23362222,ACDelco GM Genuine Parts Windshield Washer Res...,298.0
298,https://www.summitracing.com/parts/ado-84763238,ACDelco GM Genuine Parts Windshield Washer Res...,299.0
299,https://www.summitracing.com/parts/ado-19256391,ACDelco GM Genuine Parts Windshield Washer Res...,300.0

In [9]:

df.to_excel(IFolder+'\\'+f'{Source}ProductLinks_'+search_text+'.xlsx', index=False)

# 99. Archived Codes