In [1]:
import pandas as pd
import datetime
import warnings
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

In [51]:
df1=pd.read_excel(input ("Please paste the File path").replace('"',""),sheet_name="Coverage")
df1

,Part Number,Make,Product_Name,Models,Source_Link,Start_Year,End_Year
0,RC-GMX030,Buick,NGK RC-GMX030 SPARK PLUG WIRE SET,Commercial Chassis,https://web.tecalliance.net/opticat/qa/parts/B...,1991,1993
1,RC-GMX030,Buick,NGK RC-GMX030 SPARK PLUG WIRE SET,Roadmaster,https://web.tecalliance.net/opticat/qa/parts/B...,1991,1993
2,RC-GMX030,Cadillac,NGK RC-GMX030 SPARK PLUG WIRE SET,Brougham,https://web.tecalliance.net/opticat/qa/parts/B...,1990,1992
3,RC-GMX030,Cadillac,NGK RC-GMX030 SPARK PLUG WIRE SET,Commercial Chassis,https://web.tecalliance.net/opticat/qa/parts/B...,1992,1993
4,RC-GMX030,Cadillac,NGK RC-GMX030 SPARK PLUG WIRE SET,Fleetwood,https://web.tecalliance.net/opticat/qa/parts/B...,1993,1993
...,...,...,...,...,...,...,...
940,RC-CRX036,Dodge,NGK RC-CRX036 SPARK PLUG WIRE SET,Ram 3500,https://web.tecalliance.net/opticat/qa/parts/B...,1994,1999
941,RC-CRX036,Dodge,NGK RC-CRX036 SPARK PLUG WIRE SET,Ramcharger,https://web.tecalliance.net/opticat/qa/parts/B...,1992,1993
942,RC-CRX036,Dodge,NGK RC-CRX036 SPARK PLUG WIRE SET,W150,https://web.tecalliance.net/opticat/qa/parts/B...,1992,1993
943,RC-CRX036,Dodge,NGK RC-CRX036 SPARK PLUG WIRE SET,W250,https://web.tecalliance.net/opticat/qa/parts/B...,1992,1993
944,RC-CRX036,Dodge,NGK RC-CRX036 SPARK PLUG WIRE SET,W350,https://web.tecalliance.net/opticat/qa/parts/B...,1993,1993

In [167]:
df1['Name_Lower'] = df1['Name'].str.lower()
df1["Name_Lower"][0]

'apexstone soft close toy box hinges soft close toy chest hinges slow closing hinges for toy safety hinge soft close hinge, set of 2'

In [168]:
df1['EL']=df1['Name_Lower'].str.replace('inches', ' in ',).str.replace('inch', ' in ',).str.replace('"', " in ").str.split().str.join(" ")
df1["Extended_Length"]=df1["EL"].str.split(" in ",expand=True)[0].apply(lambda x: x.split(' ')[-1]).str.strip()
del df1['EL']
df1[["Name","Extended_Length"]]

                                                  Name Extended_Length
0    Apexstone Soft Close Toy Box Hinges Soft Close...               2
1    2 Pack Extended 10 inch Gas Prop Force 100N/22...              10
2    Douper 200N Gas Struts Heavy Duty Soft Close L...               2
3    C1608054 20" Gas Prop Spring Strut 20 inch 100...              20
4    c16-18233 10 Inch 40Lb/180N Gas Strut Shocks S...              10
..                                                 ...             ...
543  2Pcs 17.78 Inch Rear Back Window glass Struts ...           17.78
544  OTUAYAUTO 14 inch Gas Strut - 107N/24Lbs Unive...              14
545  ARANA 36 inch 200Lb Gas Struts Spring Shocks S...              36
546  Suiwotin 2PCS 100N/22.5lb Gas Strut Lift Suppo...            10.6
547  2Pcs 11.33 Inch Front Hood Struts Lift Support...           11.33

[548 rows x 2 columns]

In [169]:
df1['F']=df1['Name_Lower'].str.replace('lbs', 'lb',).str.replace('pound', 'lb',).str.replace('"', "in").str.replace('/', " / ").str.replace("lb"," lb").str.split().str.join(" ")
df1["Force"]=df1["F"].str.split(" lb ",expand=True)[0].apply(lambda x: x.split(' ')[-1]).str.strip()
del df1['F']
df1[["Name","Force","Extended_Length"]]

                                                  Name Force Extended_Length
0    Apexstone Soft Close Toy Box Hinges Soft Close...     2               2
1    2 Pack Extended 10 inch Gas Prop Force 100N/22...    22              10
2    Douper 200N Gas Struts Heavy Duty Soft Close L...     2               2
3    C1608054 20" Gas Prop Spring Strut 20 inch 100...   100              20
4    c16-18233 10 Inch 40Lb/180N Gas Strut Shocks S...    40              10
..                                                 ...   ...             ...
543  2Pcs 17.78 Inch Rear Back Window glass Struts ...   rod           17.78
544  OTUAYAUTO 14 inch Gas Strut - 107N/24Lbs Unive...    24              14
545  ARANA 36 inch 200Lb Gas Struts Spring Shocks S...   200              36
546  Suiwotin 2PCS 100N/22.5lb Gas Strut Lift Suppo...  22.5            10.6
547  2Pcs 11.33 Inch Front Hood Struts Lift Support...   rod           11.33

[548 rows x 3 columns]

In [170]:
df1['Extended_Length']=pd.to_numeric(df1['Extended_Length'], errors='coerce')
df1['Force']=pd.to_numeric(df1['Force'], errors='coerce')

In [174]:
df1=df1[df1['Force']<=301.0]
df1=df1[df1['Extended_Length']>=7.0 ]
df1=df1[df1['Extended_Length']<=201.0]

In [175]:
with pd.ExcelWriter(OFolder+'\\'+f'{Source}ProductDetails_Tuned_'+search_text+'.xlsx') as writer:  # doctest: +SKIP
    df1.to_excel(writer,index=False, sheet_name='Raw')