In [1]:
import os
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
import numpy as np

## Baseline Creation

In [2]:
BaselineFolder=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\06_SPD_Tasks\Catalog_Team_Requests\Comparison\Caliper ACES"

In [3]:
Baselinefile_list = []

for root, dirs, files in os.walk(BaselineFolder):
    for f in files:
        if (".xlsx") in f and ("CARDONE") in f:
            Baselinefile_list.append(os.path.join(root, f))

Baselinefile_list

['C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\06_SPD_Tasks\\Catalog_Team_Requests\\Comparison\\Caliper ACES\\ACES_UPDATE_CPCX_CARDONE Reman_xml_converted.xlsx']

In [ ]:
# Update the BaseKeyColumns and BaseValidColumns as needed
BaseKeyColumns=['Make','Model','Year','Position']
BaseValidColumns=BaseKeyColumns+['Product','PartNumber']
BaseValidColumns

['Make', 'Model', 'Year', 'Position', 'Product', 'PartNumber']

In [5]:
df_baseline = pd.DataFrame(columns=["Sl.No"])
df_baseline

for i in Baselinefile_list:
    df = pd.read_excel(i)
    df_baseline=pd.concat([df_baseline,df],ignore_index=True)

df_baseline=df_baseline[BaseValidColumns].drop_duplicates()
df_baseline['Source']="CARDONE"
df_baseline['Year']=df_baseline['Year'].astype(str).str[:4]
df_baseline['Model']=df_baseline['Model'].astype(str)
df_baseline

,Make,Model,Year,Position,Product,PartNumber,Source
0,Chevrolet,Chevette,1978,Front Right,Disc Brake Caliper,18-4002,CARDONE
1,Chevrolet,Chevette,1979,Front Right,Disc Brake Caliper,18-4002,CARDONE
2,Pontiac,Acadian,1978,Front Right,Disc Brake Caliper,18-4002,CARDONE
3,Pontiac,Acadian,1979,Front Right,Disc Brake Caliper,18-4002,CARDONE
4,Chevrolet,Chevette,1978,Front Left,Disc Brake Caliper,18-4003,CARDONE
...,...,...,...,...,...,...,...
155818,Toyota,Camry,2020,Rear Left,Disc Brake Caliper,19-B7515,CARDONE
155827,Toyota,Camry,2021,Rear Left,Disc Brake Caliper,19-B7515,CARDONE
155836,Toyota,Camry,2022,Rear Left,Disc Brake Caliper,19-B7515,CARDONE
155846,Toyota,Camry,2023,Rear Left,Disc Brake Caliper,19-B7515,CARDONE
155856,Toyota,Camry,2024,Rear Left,Disc Brake Caliper,19-B7515,CARDONE

## Target Creation

In [6]:
TargetFolder=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\06_SPD_Tasks\Catalog_Team_Requests\Comparison\Caliper ACES"

In [7]:
Targetfile_list = []

for root, dirs, files in os.walk(TargetFolder):
    for f in files:
        if (".xlsx") in f and ("linkages") in f:
            Targetfile_list.append(os.path.join(root, f))

Targetfile_list

['C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\06_SPD_Tasks\\Catalog_Team_Requests\\Comparison\\Caliper ACES\\linkages-aces-export_329_8393 - LightDuty.xlsx',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\06_SPD_Tasks\\Catalog_Team_Requests\\Comparison\\Caliper ACES\\linkages-aces-export_329_8394 - MediumHeavyTruck.xlsx']

In [ ]:
# Update the TargetKeyColumns and TargetValidColumns as needed
TargetKeyColumns=['Make','Model','Year','Position']
TargetValidColumns=TargetKeyColumns+['ProductGroup','ArticleNumber']
TargetValidColumns

['Make', 'Model', 'Year', 'Position', 'ProductGroup', 'ArticleNumber']

In [9]:
df_target = pd.DataFrame(columns=["Sl.No"])
df_target
for i in Targetfile_list:
    df = pd.read_excel(i)
    df_target=pd.concat([df_target,df],ignore_index=True)

df_target=df_target[TargetValidColumns].drop_duplicates()
df_target['Source']="JNP"
df_target['Year']=df_target['Year'].astype(str).str[:4]
df_target['Model']=df_target['Model'].astype(str)
df_target

,Make,Model,Year,Position,ProductGroup,ArticleNumber,Source
0,Suzuki,Aerio,2002,Front Right,Disc Brake Caliper,CAL11706,JNP
1,Suzuki,Aerio,2002,Front Left,Disc Brake Caliper,CAL11705,JNP
2,Suzuki,Aerio,2002,Front Left,Disc Brake Caliper,CAL11705B1,JNP
3,Suzuki,Aerio,2002,Front Right,Disc Brake Caliper,CAL11706B1,JNP
4,Suzuki,Aerio,2003,Front Right,Disc Brake Caliper,CAL11706B1,JNP
...,...,...,...,...,...,...,...
200309,Ford,F-53 Motorhome Chassis,2010,Front Right,Disc Brake Caliper,CAL11007,JNP
200310,Ford,F-53 Motorhome Chassis,2010,Front Left,Disc Brake Caliper,CAL11007,JNP
200311,Ford,F-53 Motorhome Chassis,2010,Rear Left,Disc Brake Caliper,CAL11007,JNP
200312,Ford,E-450 Super Duty,2025,Rear Right,Disc Brake Caliper,CAL12047B1,JNP
200313,Ford,E-450 Super Duty,2025,Rear Left,Disc Brake Caliper,CAL12048B1,JNP

In [10]:
df_baseline['Available_in_JNP']=(df_target.groupby(TargetKeyColumns)['ArticleNumber']
                                 .apply(list)
                                 .reindex(df_baseline.set_index(BaseKeyColumns).index)
                                 .apply(lambda x: x if isinstance(x, list) else "Not Available in JNP")
                                 .values
                                 )
df_baseline

,Make,Model,Year,Position,Product,PartNumber,Source,Available_in_JNP
0,Chevrolet,Chevette,1978,Front Right,Disc Brake Caliper,18-4002,CARDONE,[CAL4129]
1,Chevrolet,Chevette,1979,Front Right,Disc Brake Caliper,18-4002,CARDONE,[CAL4129]
2,Pontiac,Acadian,1978,Front Right,Disc Brake Caliper,18-4002,CARDONE,"[CAL4123, CAL4129]"
3,Pontiac,Acadian,1979,Front Right,Disc Brake Caliper,18-4002,CARDONE,"[CAL4123, CAL4129]"
4,Chevrolet,Chevette,1978,Front Left,Disc Brake Caliper,18-4003,CARDONE,[CAL4130]
...,...,...,...,...,...,...,...,...
155818,Toyota,Camry,2020,Rear Left,Disc Brake Caliper,19-B7515,CARDONE,"[CAL13450B1, CAL14144692]"
155827,Toyota,Camry,2021,Rear Left,Disc Brake Caliper,19-B7515,CARDONE,"[CAL13450B1, CAL14144692]"
155836,Toyota,Camry,2022,Rear Left,Disc Brake Caliper,19-B7515,CARDONE,"[CAL13450B1, CAL14144692]"
155846,Toyota,Camry,2023,Rear Left,Disc Brake Caliper,19-B7515,CARDONE,"[CAL13450B1, CAL14144692]"
155856,Toyota,Camry,2024,Rear Left,Disc Brake Caliper,19-B7515,CARDONE,"[CAL13450B1, CAL14144692]"

In [12]:
df_target['Available_in_CARDONE']=(df_baseline.groupby(BaseKeyColumns)['PartNumber']
                                 .apply(list)
                                 .reindex(df_target.set_index(TargetValidColumns).index)
                                 .apply(lambda x: x if isinstance(x, list) else "Not Available in CARDONE")
                                 .values
                                 )
df_target

,Make,Model,Year,Position,ProductGroup,ArticleNumber,Source,Available_in_CARDONE
0,Suzuki,Aerio,2002,Front Right,Disc Brake Caliper,CAL11706,JNP,"[19-2863, 19-B2863]"
1,Suzuki,Aerio,2002,Front Left,Disc Brake Caliper,CAL11705,JNP,"[19-2862, 19-B2862]"
2,Suzuki,Aerio,2002,Front Left,Disc Brake Caliper,CAL11705B1,JNP,"[19-2862, 19-B2862]"
3,Suzuki,Aerio,2002,Front Right,Disc Brake Caliper,CAL11706B1,JNP,"[19-2863, 19-B2863]"
4,Suzuki,Aerio,2003,Front Right,Disc Brake Caliper,CAL11706B1,JNP,"[19-2863, 19-B2863]"
...,...,...,...,...,...,...,...,...
200309,Ford,F-53 Motorhome Chassis,2010,Front Right,Disc Brake Caliper,CAL11007,JNP,"[18-8046, 18-8047, 18-8058, 18-8058S, 18-B8046..."
200310,Ford,F-53 Motorhome Chassis,2010,Front Left,Disc Brake Caliper,CAL11007,JNP,"[18-8046, 18-8047, 18-8058, 18-8058S, 18-B8046..."
200311,Ford,F-53 Motorhome Chassis,2010,Rear Left,Disc Brake Caliper,CAL11007,JNP,"[18-8046, 18-8047, 18-8056, 18-B8046, 18-B8047]"
200312,Ford,E-450 Super Duty,2025,Rear Right,Disc Brake Caliper,CAL12047B1,JNP,Not Available in CARDONE
200313,Ford,E-450 Super Duty,2025,Rear Left,Disc Brake Caliper,CAL12048B1,JNP,Not Available in CARDONE

In [13]:
OFolder=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\06_SPD_Tasks\Catalog_Team_Requests\Comparison"

In [14]:
with pd.ExcelWriter(OFolder+'\\'+f'CALIPER_CARDONE_JNP_Comparison_1.xlsx') as writer:  # doctest: +SKIP
    df_target.to_excel(writer,index=False, sheet_name='JNP_CALIPER_List')
    df_baseline.to_excel(writer,index=False, sheet_name='CARDONE_CALIPER_List')