In [1]:
import os
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
import re
import openpyxl
import numpy as np

In [2]:
file_path=rf"C:\Users\vikram.vadhirajan\Downloads\NGK-Lawn and Garden1.xlsx"

In [3]:
workbook=openpyxl.load_workbook(file_path)
sheetname=workbook.sheetnames
print(sheetname)

['Table 3', 'Table 4', 'Table 5', 'Table 6', 'Table 7', 'Table 8', 'Table 9', 'Table 10', 'Table 11', 'Table 12', 'Table 13', 'Table 14', 'Table 15', 'Table 16', 'Table 17', 'Table 18', 'Table 19', 'Table 20', 'Table 21', 'Table 22', 'Table 23', 'Table 24', 'Table 25', 'Table 26', 'Table 27', 'Table 28', 'Table 29', 'Table 30', 'Table 31', 'Table 32', 'Table 33', 'Table 34', 'Table 35', 'Table 36', 'Table 37', 'Table 38', 'Table 39', 'Table 40', 'Table 41', 'Table 42', 'Table 43', 'Table 44', 'Table 45', 'Table 46', 'Table 47', 'Table 48', 'Table 49', 'Table 50', 'Table 51', 'Table 52', 'Table 53', 'Table 54', 'Table 55', 'Table 56', 'Table 57', 'Table 58', 'Table 59', 'Table 60', 'Table 61', 'Table 62', 'Table 63', 'Table 64', 'Table 65', 'Table 66', 'Table 67', 'Table 68', 'Table 69', 'Table 70', 'Table 71', 'Table 72', 'Table 73', 'Table 74', 'Table 75', 'Table 76', 'Table 77', 'Table 78', 'Table 79', 'Table 80', 'Table 81', 'Table 82', 'Table 83', 'Table 84', 'Table 85', 'Table 86', 'Table 87', 'Table 88', 'Table 89', 'Table 90', 'Table 91', 'Table 92', 'Table 93', 'Table 94', 'Table 95', 'Table 96', 'Table 97', 'Table 98', 'Table 99', 'Table 100', 'Table 101', 'Table 102', 'Table 103', 'Table 104', 'Table 105', 'Table 106', 'Table 107', 'Table 108', 'Table 109', 'Table 110', 'Table 111', 'Table 112', 'Table 113', 'Table 114', 'Table 115', 'Table 116', 'Table 117', 'Table 118', 'Table 119', 'Table 120', 'Table 121', 'Table 122', 'Table 123', 'Table 124', 'Table 125', 'Table 126', 'Table 127', 'Table 128', 'Table 129', 'Table 130', 'Table 131', 'Table 132', 'Table 133', 'Table 134', 'Table 135', 'Table 136', 'Table 137', 'Table 138', 'Table 139', 'Table 140', 'Table 141']

In [4]:
cols=['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP']
df_s = pd.DataFrame(columns=cols)
df_s

Empty DataFrame
Columns: [MAKE & MODEL, ENGINE, REGULAR PLUG, STK#, GAP]
Index: []

In [5]:
for s in sheetname:
    sno=int(s.split(" ")[1])
    if sno%2==1:
        # print("The sheet is odd numbered:", sno)
        #print(s)
        df1=pd.read_excel(file_path,sheet_name=s, skiprows=1, usecols='A:E')
        df2=pd.read_excel(file_path,sheet_name=s, skiprows=1,usecols="G:K")
        df1["Sheet Number"] = sno
        df2["Sheet Number"] = sno
        df2.rename(columns={'MAKE & MODEL.1':"MAKE & MODEL", 'ENGINE.1':"ENGINE", 'REGULAR PLUG.1':"REGULAR PLUG", 'STK#.1':"STK#", 'GAP.1':"GAP"}, inplace=True)
        df_s=pd.concat([df_s,df1,df2])#.dropna(axis=0, how='all', inplace=True)
        print(sno, df_s.columns)
    else:
        # print("The sheet is even numbered:", sno)
        #print(s)    
        df3=pd.read_excel(file_path,sheet_name=s,usecols='A:E')
        df4=pd.read_excel(file_path,sheet_name=s,usecols="G:K")
        df3["Sheet Number"] = sno
        df4["Sheet Number"] = sno
        df4.rename(columns={'MAKE & MODEL.1':"MAKE & MODEL", 'ENGINE.1':"ENGINE", 'REGULAR PLUG.1':"REGULAR PLUG", 'STK#.1':"STK#", 'GAP.1':"GAP"}, inplace=True)   
        df_s=pd.concat([df_s,df3,df4])
        print(sno, df_s.columns)

3 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
4 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
5 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
6 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
7 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
8 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
9 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
10 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
11 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
12 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
13 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
14 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
15 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
16 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
17 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
18 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
19 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
20 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
21 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
22 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
23 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
24 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
25 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
26 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
27 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
28 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
29 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
30 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
31 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
32 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
33 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
34 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
35 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
36 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
37 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
38 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
39 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
40 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
41 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
42 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
43 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
44 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
45 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
46 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
47 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
48 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
49 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
50 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
51 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
52 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
53 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
54 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
55 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
56 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
57 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
58 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
59 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
60 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
61 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
62 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
63 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
64 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
65 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
66 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
67 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
68 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
69 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
70 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
71 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
72 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
73 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
74 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
75 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
76 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
77 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
78 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
79 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
80 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
81 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
82 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
83 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
84 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
85 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
86 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
87 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
88 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
89 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
90 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
91 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
92 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
93 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
94 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
95 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
96 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
97 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
98 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
99 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
100 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
101 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
102 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
103 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
104 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
105 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
106 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
107 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
108 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
109 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
110 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
111 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
112 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
113 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
114 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
115 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
116 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
117 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
118 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
119 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
120 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
121 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
122 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
123 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
124 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
125 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
126 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
127 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
128 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
129 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
130 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
131 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
132 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
133 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
134 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
135 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
136 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
137 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
138 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
139 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
140 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')
141 Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')

In [6]:
df_s.columns

Index(['MAKE & MODEL', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP',
       'Sheet Number'],
      dtype='object')

In [7]:
df_s

      MAKE & MODEL ENGINE REGULAR PLUG    STK#    GAP  Sheet Number
0            AGWAY    NaN          NaN     NaN    NaN           3.0
1              754    NaN          B6S  3510.0  .025"           3.0
2    PL4, PL5, PL6    NaN       BM7A ^  6521.0  .025"           3.0
3   ALLIS CHALMERS    NaN          NaN     NaN    NaN           3.0
4               65    NaN     BM6A SLD  6021.0  .025"           3.0
..             ...    ...          ...     ...    ...           ...
25             NaN    NaN          NaN     NaN    NaN         141.0
26             NaN    NaN          NaN     NaN    NaN         141.0
27             NaN    NaN          NaN     NaN    NaN         141.0
28             NaN    NaN          NaN     NaN    NaN         141.0
29             NaN    NaN          NaN     NaN    NaN         141.0

[20630 rows x 6 columns]

In [8]:
df_s.dropna(axis=0, how='all', inplace=True)
df_s.reset_index(drop=True, inplace=True)

In [9]:
df_s["Make"]=np.where(
    (df_s["ENGINE"].isna()) & 
    (df_s["REGULAR PLUG"].isna()) & 
    (df_s["STK#"].isna()) & 
    (df_s["GAP"].isna()), 
    df_s["MAKE & MODEL"], 
    np.nan
)

In [10]:
df_s["Model"]=np.where( 
    df_s["Make"]==df_s["MAKE & MODEL"],
    np.nan,
    df_s["MAKE & MODEL"])

In [13]:
df_cleaned=df_s[["Sheet Number",'Make','Model', 'ENGINE', 'REGULAR PLUG', 'STK#', 'GAP']]
df_cleaned['Make'] = df_cleaned['Make'].ffill()
# df_cleaned['Model'] = df_cleaned['Model'].ffill()
df_cleaned["Remove"]=np.where(
    (df_s["ENGINE"].isna()) & 
    (df_s["REGULAR PLUG"].isna()) & 
    (df_s["STK#"].isna()) & 
    (df_s["GAP"].isna()) &
    (df_s["Model"].isna()), 
    0,
    1
)

In [14]:
df_cleaned = df_cleaned[df_cleaned['Remove'].apply(str).str.contains("1", regex=False, na=False, case=False)]
df_cleaned

,Sheet Number,Make,Model,ENGINE,REGULAR PLUG,STK#,GAP,Remove
1,3.0,AGWAY,754,NaN,B6S,3510.0,".025""",1
2,3.0,AGWAY,"PL4, PL5, PL6",NaN,BM7A ^,6521.0,".025""",1
4,3.0,ALLIS CHALMERS,65,NaN,BM6A SLD,6021.0,".025""",1
5,3.0,ALLIS CHALMERS,"75, 75A",NaN,BM6A SLD,6021.0,".025""",1
6,3.0,ALLIS CHALMERS,95,NaN,BM6A SLD,6021.0,".025""",1
...,...,...,...,...,...,...,...,...
20595,141.0,ZONGSHEN,SN360E-4,360cc,BPR6ES ^,7131.0,".036""",1
20596,141.0,ZONGSHEN,SN390E-4,390cc,BPR6ES ^,7131.0,".036""",1
20597,141.0,ZONGSHEN,SN420,420cc,BPR6ES ^,7131.0,".036""",1
20598,141.0,ZONGSHEN,SN420-4,420cc,BPR6ES ^,7131.0,".036""",1
20599,141.0,ZONGSHEN,SN420E-4,420cc,BPR6ES ^,7131.0,".036""",1