In [58]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [59]:
papath=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files\Rest\HOP20250222_PIES72Flat\HOP20250222_ProductAttribute.csv"

pallpath=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files\Rest\HOP20250222_PIES72Flat\HOP20250222_PIESData72.csv"

In [60]:
df_pa=pd.read_csv(papath,delimiter="|")

df_pall=pd.read_csv(pallpath,delimiter="|")

In [61]:
df_pa

,BrandAAIAID,PartNumber,AttributeID,AttributeData
0,FDCG,03925,WARNING CA Proposition 65,Yes
1,FDCG,03925,WARNING CA Proposition 65 Message,WARNING: This product can expose you to chemic...
2,FDCG,03926,WARNING CA Proposition 65,Yes
3,FDCG,03926,WARNING CA Proposition 65 Message,WARNING: This product can expose you to chemic...
4,FDCG,04026,WARNING CA Proposition 65,Yes
...,...,...,...,...
4347,FDCG,T9460BR,Position,NaN
4348,FDCG,T9460BR,WARNING CA Proposition 65,No
4349,FDCG,T94B,Type,Tail Light
4350,FDCG,T94B,WARNING CA Proposition 65,Yes
4351,FDCG,T94B,WARNING CA Proposition 65 Message,WARNING: This product can expose you to chemic...

In [62]:
df_pall

,BrandAAIAID,BrandLabel,PartNumber,EXPI_PTS,ACESApplications,QuantityPerApplication,QuantityPerApplicationUOM,MinimumOrderQuantity,MinimumOrderQuantityUOM,PartTerminologyID,...,CAD_JobberPrice,CAD_ListPrice,CAD_UnilateralPrice,CAD_RetailPrice,CAD_RetailMapPrice,CAD_WholesaleMAPPrice,CAD_WDPrice,CAD_JobberCorePrice,ModifyDate,partterminologyname
0,FDCG,Hopkins Towing Solution,03925,NaN,N,1.0,EA,12.0,EA,18276,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Level
1,FDCG,Hopkins Towing Solution,03926,NaN,N,1.0,EA,6.0,EA,18276,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Level
2,FDCG,Hopkins Towing Solution,04026,NaN,N,1.0,EA,4.0,EA,18276,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Level
3,FDCG,Hopkins Towing Solution,04115,NaN,N,1.0,EA,6.0,EA,18276,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Level
4,FDCG,Hopkins Towing Solution,05515,NaN,N,1.0,EA,4.0,EA,18276,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Level
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1151,FDCG,Hopkins Towing Solution,T85BR,NaN,N,NaN,NaN,NaN,NaN,16541,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Trailer Light
1152,FDCG,Hopkins Towing Solution,T9216BA,NaN,N,NaN,NaN,NaN,NaN,12983,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Parking Light Lens
1153,FDCG,Hopkins Towing Solution,T9216BR,NaN,N,NaN,NaN,NaN,NaN,12983,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Parking Light Lens
1154,FDCG,Hopkins Towing Solution,T9460BR,NaN,N,NaN,NaN,NaN,NaN,12983,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Parking Light Lens
1155,FDCG,Hopkins Towing Solution,T94B,NaN,N,NaN,NaN,NaN,NaN,16541,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Trailer Light

In [63]:
df_merged=df_pa.merge(df_pall,how='left',left_on="PartNumber",right_on="PartNumber")

In [64]:
df_merged

,BrandAAIAID_x,PartNumber,AttributeID,AttributeData,BrandAAIAID_y,BrandLabel,EXPI_PTS,ACESApplications,QuantityPerApplication,QuantityPerApplicationUOM,...,CAD_JobberPrice,CAD_ListPrice,CAD_UnilateralPrice,CAD_RetailPrice,CAD_RetailMapPrice,CAD_WholesaleMAPPrice,CAD_WDPrice,CAD_JobberCorePrice,ModifyDate,partterminologyname
0,FDCG,03925,WARNING CA Proposition 65,Yes,FDCG,Hopkins Towing Solution,NaN,N,1.0,EA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Level
1,FDCG,03925,WARNING CA Proposition 65 Message,WARNING: This product can expose you to chemic...,FDCG,Hopkins Towing Solution,NaN,N,1.0,EA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Level
2,FDCG,03926,WARNING CA Proposition 65,Yes,FDCG,Hopkins Towing Solution,NaN,N,1.0,EA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Level
3,FDCG,03926,WARNING CA Proposition 65 Message,WARNING: This product can expose you to chemic...,FDCG,Hopkins Towing Solution,NaN,N,1.0,EA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Level
4,FDCG,04026,WARNING CA Proposition 65,Yes,FDCG,Hopkins Towing Solution,NaN,N,1.0,EA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Level
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4347,FDCG,T9460BR,Position,NaN,FDCG,Hopkins Towing Solution,NaN,N,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Parking Light Lens
4348,FDCG,T9460BR,WARNING CA Proposition 65,No,FDCG,Hopkins Towing Solution,NaN,N,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Parking Light Lens
4349,FDCG,T94B,Type,Tail Light,FDCG,Hopkins Towing Solution,NaN,N,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Trailer Light
4350,FDCG,T94B,WARNING CA Proposition 65,Yes,FDCG,Hopkins Towing Solution,NaN,N,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Trailer Light
4351,FDCG,T94B,WARNING CA Proposition 65 Message,WARNING: This product can expose you to chemic...,FDCG,Hopkins Towing Solution,NaN,N,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Trailer Light

In [65]:
collist=['DESC_SHO', 'AttributeID' ]

In [66]:
df_final=df_merged[collist]
df_final.drop_duplicates().reset_index(drop=True)

                DESC_SHO                        AttributeID
0               RV Level          WARNING CA Proposition 65
1               RV Level  WARNING CA Proposition 65 Message
2    Trailer Wire Tester          WARNING CA Proposition 65
3    Trailer Wire Tester  WARNING CA Proposition 65 Message
4           TrlrWireCnct                    Connector Style
..                   ...                                ...
118      Auxiliary Light  WARNING CA Proposition 65 Message
119            Light Bar          WARNING CA Proposition 65
120            Light Bar  WARNING CA Proposition 65 Message
121   LightingControlMod          WARNING CA Proposition 65
122   LightingControlMod  WARNING CA Proposition 65 Message

[123 rows x 2 columns]

In [67]:
OFolder=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files\Rest"

In [69]:
with pd.ExcelWriter(OFolder+'\\'+f'Hopkins_Parts.xlsx') as writer:  # doctest: +SKIP
    df_pa.to_excel(writer,index=False, sheet_name='Attributes')
    df_pall.to_excel(writer,index=False, sheet_name='Part_Details')
    df_merged.to_excel(writer,index=False, sheet_name='Merged')