In [1]:
import os
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
import re
import openpyxl
import numpy as np
np.set_printoptions(legacy="1.13")

In [2]:
folder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files'
OFolder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files'

In [3]:
file_list=[]
for (root, dirs, file) in os.walk(folder):
    for f in file:
        if ('Attribute_List.xlsx') in f:

                    file_list.append(f)
file_list

['BPI_Attribute_List.xlsx',
 'Champ_Attribute_List.xlsx',
 'FRAM_Attribute_List.xlsx',
 'Hopkins_Attribute_List.xlsx',
 'Horizon_Global_Attribute_List.xlsx',
 'Luberfiner_Attribute_List.xlsx',
 'Lumileds_Attribute_List.xlsx',
 'PartCat_Attribute_List.xlsx',
 'PDM_Attribute_List.xlsx']

In [4]:
file_link=[]

for i in range(len(file_list)):
     for r,d,f in os.walk(folder):
          for files in f:
               if files == file_list[i]:
                    file_link.append(os.path.join(r,files))

In [5]:
len(file_link)

9

In [6]:
file_link[1]

'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\Documents - Product Support India Romania\\Catalog\\Score card\\Standard\\Import files\\Champ_Attribute_List.xlsx'

In [7]:
cols=['Brand']
df_s = pd.DataFrame(columns=cols)

In [8]:
for i in range(len(file_link)):
    file=file_link[i]
    print(file)
    workbook=openpyxl.load_workbook(file)
    sheetname=workbook.sheetnames
    print(sheetname)
    for s in sheetname:
        if (("FBG_Attributes" not in s)):
            print(s)
            df=pd.read_excel(file_link[i],sheet_name=s, keep_default_na=False, na_values=[''])
            df['Source']=file_link[i].split('\\')[-1].split('.')[0]  
            df_s=pd.concat([df_s,df])

C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files\BPI_Attribute_List.xlsx
['Chunk_1', 'Chunk_2', 'Chunk_3', 'FBG_Attributes']
Chunk_1
Chunk_2
Chunk_3
C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files\Champ_Attribute_List.xlsx
['Chunk_1', 'FBG_Attributes']
Chunk_1
C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files\FRAM_Attribute_List.xlsx
['Chunk_1', 'FBG_Attributes']
Chunk_1
C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files\Hopkins_Attribute_List.xlsx
['Chunk_1', 'FBG_Attributes']
Chunk_1
C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files\Horizon_Global_Attribute_List.xlsx
['Chunk_1', 'FBG_Attributes']
Chunk_1
C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files\Luberfiner_Attribute_List.xlsx
['Chunk_1', 'FBG_Attributes']
Chunk_1
C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files\Lumileds_Attribute_List.xlsx
['Chunk_1', 'FBG_Attributes']
Chunk_1
C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files\PartCat_Attribute_List.xlsx
['Chunk_1', 'Chunk_2', 'FBG_Attributes']
Chunk_1
Chunk_2
C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files\PDM_Attribute_List.xlsx
['Chunk_1', 'Chunk_2', 'FBG_Attributes']
Chunk_1
Chunk_2

In [9]:
df_s['PAName']=df_s['PAName'].str.strip()

In [11]:
df_AC=pd.read_excel(fr"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Autocare\20250731_Autocare_PCAdb.xlsx")
df_AC['Attribute_Type']="Autocare_Attribute"

In [12]:
df_AC

,CategoryID,CategoryName,PartTerminologyID,PartTerminologyName,PAID,PAName,Attribute_Type
0,1,Accessories,1020,Car Cover,14,Length,Autocare_Attribute
1,1,Accessories,1020,Car Cover,24,Width,Autocare_Attribute
2,1,Accessories,1020,Car Cover,10,Material,Autocare_Attribute
3,1,Accessories,1020,Car Cover,17,Color,Autocare_Attribute
4,1,Accessories,1020,Car Cover,513,Vented,Autocare_Attribute
...,...,...,...,...,...,...,...
140523,46,"Oil, Fluids and Chemicals",68086,Intercooler Fluid,3145,Universal Or Specific Fit,Autocare_Attribute
140524,46,"Oil, Fluids and Chemicals",68086,Intercooler Fluid,3390,Grade Type,Autocare_Attribute
140525,46,"Oil, Fluids and Chemicals",70868,Wheel Tape,14,Length,Autocare_Attribute
140526,46,"Oil, Fluids and Chemicals",70868,Wheel Tape,24,Width,Autocare_Attribute
140527,46,"Oil, Fluids and Chemicals",70868,Wheel Tape,10787,Pre-Cut Valve Tube Hole,Autocare_Attribute

In [13]:
df_s.Brand.unique()

array(['BPI', 'Champ', 'FRAM', 'Hopkins', 'Bargman', 'BULLDOG',
       'DRAW-TITE', 'FULTON', 'Hopkins_Towing_Solutions', 'REESE',
       'REESE_TOWPOWER', 'ROLA', 'TEKONSHA', 'Wesbar', 'Luberfiner',
       'Lumileds', 'Centric', 'IBI', 'StopTech', 'TRICO', 'BBDW_ASC',
       'BBFX_Balkamp', 'BBRQ_Autolite', 'BBZN_Strong Arm', 'BCQS_Carter',
       'CFHH_Duralast', 'CNHS_Magneti Marelli', 'CNRD_CARDONE New',
       'CPCX_CARDONE Reman', 'FNTH_Mighty Lift',
       'FXLT_Carquest Premium Water Pumps',
       'FXNK_Carquest Premium Fuel Pumps', 'FXPS_CARDONE Ultra',
       'GQWK_Import Direct Fuel Pumps', 'GQWN_Import Direct Water Pumps',
       'HNTB_Driveworks Water Pumps', 'HTTT_TruGrade',
       'HWMS_AVM Industries', 'HYJT_Carter Water Pumps',
       'HYTZ_Carter Premium Water Pumps', 'HYVJ_Airtex Fuel Pumps',
       'T00718_Mex Mighty Lift'], dtype=object)

In [14]:
df_PNS=df_s[['PartNumber','PartTerminologyName','Brand']].drop_duplicates(ignore_index=True)

In [15]:
df_merged=df_PNS.merge(df_AC,how='left')
df_merged

,PartNumber,PartTerminologyName,Brand,CategoryID,CategoryName,PartTerminologyID,PAID,PAName,Attribute_Type
0,A99000,Wheel Hub Washer,BPI,5.0,Driveline and Axles,22374.0,19.0,Thickness,Autocare_Attribute
1,A99000,Wheel Hub Washer,BPI,5.0,Driveline and Axles,22374.0,25.0,Outside Diameter,Autocare_Attribute
2,A99000,Wheel Hub Washer,BPI,5.0,Driveline and Axles,22374.0,18.0,Inside Diameter,Autocare_Attribute
3,A99000,Wheel Hub Washer,BPI,5.0,Driveline and Axles,22374.0,10.0,Material,Autocare_Attribute
4,A99000,Wheel Hub Washer,BPI,5.0,Driveline and Axles,22374.0,200.0,Finish,Autocare_Attribute
...,...,...,...,...,...,...,...,...,...
7403714,PG5022,Liftgate Lift Support,T00718_Mex Mighty Lift,2.0,Body,15599.0,43.0,Connector Gender,Autocare_Attribute
7403715,PG5022,Liftgate Lift Support,T00718_Mex Mighty Lift,2.0,Body,15599.0,26.0,Type,Autocare_Attribute
7403716,PG5022,Liftgate Lift Support,T00718_Mex Mighty Lift,2.0,Body,15599.0,10039.0,Inner Shaft Material,Autocare_Attribute
7403717,PG5022,Liftgate Lift Support,T00718_Mex Mighty Lift,2.0,Body,15599.0,488.0,Wiring Harness Included,Autocare_Attribute
7403718,PG5022,Liftgate Lift Support,T00718_Mex Mighty Lift,2.0,Body,15599.0,30.0,Mounting Hardware Included,Autocare_Attribute

In [16]:
df_merged

,PartNumber,PartTerminologyName,Brand,CategoryID,CategoryName,PartTerminologyID,PAID,PAName,Attribute_Type
0,A99000,Wheel Hub Washer,BPI,5.0,Driveline and Axles,22374.0,19.0,Thickness,Autocare_Attribute
1,A99000,Wheel Hub Washer,BPI,5.0,Driveline and Axles,22374.0,25.0,Outside Diameter,Autocare_Attribute
2,A99000,Wheel Hub Washer,BPI,5.0,Driveline and Axles,22374.0,18.0,Inside Diameter,Autocare_Attribute
3,A99000,Wheel Hub Washer,BPI,5.0,Driveline and Axles,22374.0,10.0,Material,Autocare_Attribute
4,A99000,Wheel Hub Washer,BPI,5.0,Driveline and Axles,22374.0,200.0,Finish,Autocare_Attribute
...,...,...,...,...,...,...,...,...,...
7403714,PG5022,Liftgate Lift Support,T00718_Mex Mighty Lift,2.0,Body,15599.0,43.0,Connector Gender,Autocare_Attribute
7403715,PG5022,Liftgate Lift Support,T00718_Mex Mighty Lift,2.0,Body,15599.0,26.0,Type,Autocare_Attribute
7403716,PG5022,Liftgate Lift Support,T00718_Mex Mighty Lift,2.0,Body,15599.0,10039.0,Inner Shaft Material,Autocare_Attribute
7403717,PG5022,Liftgate Lift Support,T00718_Mex Mighty Lift,2.0,Body,15599.0,488.0,Wiring Harness Included,Autocare_Attribute
7403718,PG5022,Liftgate Lift Support,T00718_Mex Mighty Lift,2.0,Body,15599.0,30.0,Mounting Hardware Included,Autocare_Attribute

In [17]:
df_s["Key"]=df_s['PartNumber'].astype(str)+df_s['PartTerminologyName'].astype(str)+df_s['PAName'].astype(str)

In [18]:
df_merged["Key"]=df_merged['PartNumber'].astype(str)+df_merged['PartTerminologyName'].astype(str)+df_merged['PAName'].astype(str)

In [19]:
df_s.columns

Index(['Brand', 'PartTerminologyName', 'PartNumber', 'PAName', 'Value',
       'Source', 'Key'],
      dtype='object')

In [20]:
df_AC

,CategoryID,CategoryName,PartTerminologyID,PartTerminologyName,PAID,PAName,Attribute_Type
0,1,Accessories,1020,Car Cover,14,Length,Autocare_Attribute
1,1,Accessories,1020,Car Cover,24,Width,Autocare_Attribute
2,1,Accessories,1020,Car Cover,10,Material,Autocare_Attribute
3,1,Accessories,1020,Car Cover,17,Color,Autocare_Attribute
4,1,Accessories,1020,Car Cover,513,Vented,Autocare_Attribute
...,...,...,...,...,...,...,...
140523,46,"Oil, Fluids and Chemicals",68086,Intercooler Fluid,3145,Universal Or Specific Fit,Autocare_Attribute
140524,46,"Oil, Fluids and Chemicals",68086,Intercooler Fluid,3390,Grade Type,Autocare_Attribute
140525,46,"Oil, Fluids and Chemicals",70868,Wheel Tape,14,Length,Autocare_Attribute
140526,46,"Oil, Fluids and Chemicals",70868,Wheel Tape,24,Width,Autocare_Attribute
140527,46,"Oil, Fluids and Chemicals",70868,Wheel Tape,10787,Pre-Cut Valve Tube Hole,Autocare_Attribute

In [21]:
df_Final=df_merged.merge(df_s,how="outer")

In [22]:
df_Final

,PartNumber,PartTerminologyName,Brand,CategoryID,CategoryName,PartTerminologyID,PAID,PAName,Attribute_Type,Key,Value,Source
0,1,Brake Master Cylinder Repair Kit,BPI,3.0,Brake,1840.0,853.0,Cup Material,Autocare_Attribute,1Brake Master Cylinder Repair KitCup Material,NaN,NaN
1,1,Brake Master Cylinder Repair Kit,BPI,3.0,Brake,1840.0,4942.0,Cup Outside Diameter,Autocare_Attribute,1Brake Master Cylinder Repair KitCup Outside D...,NaN,NaN
2,1,Brake Master Cylinder Repair Kit,BPI,3.0,Brake,1840.0,4098.0,Cylinder Bore Diameter,Autocare_Attribute,1Brake Master Cylinder Repair KitCylinder Bore...,NaN,BPI_Attribute_List
3,1,Brake Master Cylinder Repair Kit,BPI,3.0,Brake,1840.0,6102.0,Piston Composition,Autocare_Attribute,1Brake Master Cylinder Repair KitPiston Compos...,NaN,NaN
4,1,Brake Master Cylinder Repair Kit,BPI,3.0,Brake,1840.0,4939.0,Piston End 1 Diameter,Autocare_Attribute,1Brake Master Cylinder Repair KitPiston End 1 ...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
11552113,Z33073,Fuel Pump Tank Seal,GQWK_Import Direct Fuel Pumps,12.0,Air and Fuel Delivery,6262.0,4802.0,Rim Shape,Autocare_Attribute,Z33073Fuel Pump Tank SealRim Shape,NaN,NaN
11552114,Z33073,Fuel Pump Tank Seal,GQWK_Import Direct Fuel Pumps,12.0,Air and Fuel Delivery,6262.0,485.0,Seal Type,Autocare_Attribute,Z33073Fuel Pump Tank SealSeal Type,Gasket,PDM_Attribute_List
11552115,Z33073,Fuel Pump Tank Seal,GQWK_Import Direct Fuel Pumps,12.0,Air and Fuel Delivery,6262.0,486.0,Sealing Surface Type,Autocare_Attribute,Z33073Fuel Pump Tank SealSealing Surface Type,Flange,PDM_Attribute_List
11552116,Z33073,Fuel Pump Tank Seal,GQWK_Import Direct Fuel Pumps,12.0,Air and Fuel Delivery,6262.0,19.0,Thickness,Autocare_Attribute,Z33073Fuel Pump Tank SealThickness,4.0,PDM_Attribute_List
11552117,Z33073,Fuel Pump Tank Seal,GQWK_Import Direct Fuel Pumps,12.0,Air and Fuel Delivery,6262.0,24.0,Width,Autocare_Attribute,Z33073Fuel Pump Tank SealWidth,NaN,NaN

In [23]:
df_Final['AC_AttributeCount']=np.where(df_Final["Attribute_Type"].notna(), 1 , 0)
df_Final['Attribute_Value']=np.where((df_Final["Attribute_Type"].notna())  & (df_Final["Value"].notna()), 1 , 0)
# df_Final=df_Final.dropna(subset='Autocare')
df_Final['Attribute_Type']=np.where((df_Final["Attribute_Type"].notna())  , df_Final["Attribute_Type"] , 'FBG_Attribute')

In [24]:
df_Final

,PartNumber,PartTerminologyName,Brand,CategoryID,CategoryName,PartTerminologyID,PAID,PAName,Attribute_Type,Key,Value,Source,AC_AttributeCount,Attribute_Value
0,1,Brake Master Cylinder Repair Kit,BPI,3.0,Brake,1840.0,853.0,Cup Material,Autocare_Attribute,1Brake Master Cylinder Repair KitCup Material,NaN,NaN,1,0
1,1,Brake Master Cylinder Repair Kit,BPI,3.0,Brake,1840.0,4942.0,Cup Outside Diameter,Autocare_Attribute,1Brake Master Cylinder Repair KitCup Outside D...,NaN,NaN,1,0
2,1,Brake Master Cylinder Repair Kit,BPI,3.0,Brake,1840.0,4098.0,Cylinder Bore Diameter,Autocare_Attribute,1Brake Master Cylinder Repair KitCylinder Bore...,NaN,BPI_Attribute_List,1,0
3,1,Brake Master Cylinder Repair Kit,BPI,3.0,Brake,1840.0,6102.0,Piston Composition,Autocare_Attribute,1Brake Master Cylinder Repair KitPiston Compos...,NaN,NaN,1,0
4,1,Brake Master Cylinder Repair Kit,BPI,3.0,Brake,1840.0,4939.0,Piston End 1 Diameter,Autocare_Attribute,1Brake Master Cylinder Repair KitPiston End 1 ...,NaN,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11552113,Z33073,Fuel Pump Tank Seal,GQWK_Import Direct Fuel Pumps,12.0,Air and Fuel Delivery,6262.0,4802.0,Rim Shape,Autocare_Attribute,Z33073Fuel Pump Tank SealRim Shape,NaN,NaN,1,0
11552114,Z33073,Fuel Pump Tank Seal,GQWK_Import Direct Fuel Pumps,12.0,Air and Fuel Delivery,6262.0,485.0,Seal Type,Autocare_Attribute,Z33073Fuel Pump Tank SealSeal Type,Gasket,PDM_Attribute_List,1,1
11552115,Z33073,Fuel Pump Tank Seal,GQWK_Import Direct Fuel Pumps,12.0,Air and Fuel Delivery,6262.0,486.0,Sealing Surface Type,Autocare_Attribute,Z33073Fuel Pump Tank SealSealing Surface Type,Flange,PDM_Attribute_List,1,1
11552116,Z33073,Fuel Pump Tank Seal,GQWK_Import Direct Fuel Pumps,12.0,Air and Fuel Delivery,6262.0,19.0,Thickness,Autocare_Attribute,Z33073Fuel Pump Tank SealThickness,4.0,PDM_Attribute_List,1,1
11552117,Z33073,Fuel Pump Tank Seal,GQWK_Import Direct Fuel Pumps,12.0,Air and Fuel Delivery,6262.0,24.0,Width,Autocare_Attribute,Z33073Fuel Pump Tank SealWidth,NaN,NaN,1,0

In [25]:
df_BM=pd.read_excel(fr"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\FBG_Data\Active_Part_List_BrandMap.xlsx",sheet_name="BrandMap")
df_BM

,BrandName,Brand,Product Group,Source,Status,Parent-Child- Customer Brand
0,Bargman,Bargman,Towing,Hitch Pro,Active,Child
1,BBDW_ASC,ASC,Repair,PDM,Active,Parent
2,BBFX_Balkamp,Balkamp,Repair,PDM,Active,Customer (NAPA)
3,BBRQ_Autolite,Autolite,Repair,PDM,Active,Parent
4,BBZN_Strong Arm,Strong Arm,Repair,PDM,Active,Child
...,...,...,...,...,...,...
63,T02813_Cardone NAPA Canada,NaN,NaN,NaN,Inactive,NaN
64,T083_MEX Autolite,NaN,NaN,NaN,Inactive,NaN
65,Tekonsha,Tekonsha,Towing,Hitch Pro,Active,Child
66,TRICO,TRICO,Wipers,PartCat,Active,Parent
67,Wesbar,Wesbar,Towing,Hitch Pro,Active,Child

In [26]:
df_BM.columns

Index(['BrandName', 'Brand', 'Product Group', 'Source', 'Status',
       'Parent-Child- Customer Brand'],
      dtype='object')

In [27]:
df_mapped=df_Final.merge(df_BM,how="outer",left_on=["Brand"], right_on=["BrandName"],suffixes=('_match', '_filter'))
df_mapped

,PartNumber,PartTerminologyName,Brand_match,CategoryID,CategoryName,PartTerminologyID,PAID,PAName,Attribute_Type,Key,Value,Source_match,AC_AttributeCount,Attribute_Value,BrandName,Brand_filter,Product Group,Source_filter,Status,Parent-Child- Customer Brand
0,EWP1220,Engine Water Pump,BBDW_ASC,4.0,Belts and Cooling,2208.0,351.0,Casting Number,Autocare_Attribute,EWP1220Engine Water PumpCasting Number,NaN,NaN,1.0,0.0,BBDW_ASC,ASC,Repair,PDM,Active,Parent
1,EWP1220,Engine Water Pump,BBDW_ASC,4.0,Belts and Cooling,2208.0,354.0,Fan Clutch Included,Autocare_Attribute,EWP1220Engine Water PumpFan Clutch Included,NaN,NaN,1.0,0.0,BBDW_ASC,ASC,Repair,PDM,Active,Parent
2,EWP1220,Engine Water Pump,BBDW_ASC,4.0,Belts and Cooling,2208.0,3390.0,Grade Type,Autocare_Attribute,EWP1220Engine Water PumpGrade Type,NaN,NaN,1.0,0.0,BBDW_ASC,ASC,Repair,PDM,Active,Parent
3,EWP1220,Engine Water Pump,BBDW_ASC,4.0,Belts and Cooling,2208.0,357.0,Housing Material,Autocare_Attribute,EWP1220Engine Water PumpHousing Material,NaN,NaN,1.0,0.0,BBDW_ASC,ASC,Repair,PDM,Active,Parent
4,EWP1220,Engine Water Pump,BBDW_ASC,4.0,Belts and Cooling,2208.0,360.0,Hub Height,Autocare_Attribute,EWP1220Engine Water PumpHub Height,NaN,NaN,1.0,0.0,BBDW_ASC,ASC,Repair,PDM,Active,Parent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11552143,8261605,Agriculture Light,Wesbar,NaN,NaN,NaN,NaN,Lens Width,FBG_Attribute,8261605Agriculture LightLens Width,5.5,Horizon_Global_Attribute_List,0.0,0.0,Wesbar,Wesbar,Towing,Hitch Pro,Active,Child
11552144,8261605,Agriculture Light,Wesbar,NaN,NaN,NaN,NaN,Prop 65,FBG_Attribute,8261605Agriculture LightProp 65,Yes,Horizon_Global_Attribute_List,0.0,0.0,Wesbar,Wesbar,Towing,Hitch Pro,Active,Child
11552145,8261605,Agriculture Light,Wesbar,NaN,NaN,NaN,NaN,Prop 65 Chemical,FBG_Attribute,8261605Agriculture LightProp 65 Chemical,DEHP,Horizon_Global_Attribute_List,0.0,0.0,Wesbar,Wesbar,Towing,Hitch Pro,Active,Child
11552146,8261605,Agriculture Light,Wesbar,NaN,NaN,NaN,NaN,Prop 65 Warning,FBG_Attribute,8261605Agriculture LightProp 65 Warning,WARNING: Cancer and Reproductive Harm – www.p6...,Horizon_Global_Attribute_List,0.0,0.0,Wesbar,Wesbar,Towing,Hitch Pro,Active,Child
11552147,8261605,Agriculture Light,Wesbar,NaN,NaN,NaN,NaN,NaN,FBG_Attribute,8261605Agriculture Lightnan,NaN,NaN,0.0,0.0,Wesbar,Wesbar,Towing,Hitch Pro,Active,Child

In [28]:
df_mapped.columns

Index(['PartNumber', 'PartTerminologyName', 'Brand_match', 'CategoryID',
       'CategoryName', 'PartTerminologyID', 'PAID', 'PAName', 'Attribute_Type',
       'Key', 'Value', 'Source_match', 'AC_AttributeCount', 'Attribute_Value',
       'BrandName', 'Brand_filter', 'Product Group', 'Source_filter', 'Status',
       'Parent-Child- Customer Brand'],
      dtype='object')

In [29]:
df_final_List=df_mapped[['Product Group','Source_filter','BrandName','Brand_filter', 'PartNumber', 'PartTerminologyName', 'Status', 'PAName', 'Attribute_Type', 'Value', 'AC_AttributeCount', 'Attribute_Value','Key','Parent-Child- Customer Brand']]

In [30]:
df_final_List.rename(columns={'Brand_filter': 'Brand','Source_filter':'Source'}, inplace=True)

In [31]:
df_final_List.columns

Index(['Product Group', 'Source', 'BrandName', 'Brand', 'PartNumber',
       'PartTerminologyName', 'Status', 'PAName', 'Attribute_Type', 'Value',
       'AC_AttributeCount', 'Attribute_Value', 'Key',
       'Parent-Child- Customer Brand'],
      dtype='object')

In [32]:
df_final_List=df_final_List.drop_duplicates()
df_final_List = df_final_List[df_final_List['PartTerminologyName'].notna()]
df_final_List = df_final_List[df_final_List['Product Group'].notna()]
df_final_List

,Product Group,Source,BrandName,Brand,PartNumber,PartTerminologyName,Status,PAName,Attribute_Type,Value,AC_AttributeCount,Attribute_Value,Key,Parent-Child- Customer Brand
0,Repair,PDM,BBDW_ASC,ASC,EWP1220,Engine Water Pump,Active,Casting Number,Autocare_Attribute,NaN,1.0,0.0,EWP1220Engine Water PumpCasting Number,Parent
1,Repair,PDM,BBDW_ASC,ASC,EWP1220,Engine Water Pump,Active,Fan Clutch Included,Autocare_Attribute,NaN,1.0,0.0,EWP1220Engine Water PumpFan Clutch Included,Parent
2,Repair,PDM,BBDW_ASC,ASC,EWP1220,Engine Water Pump,Active,Grade Type,Autocare_Attribute,NaN,1.0,0.0,EWP1220Engine Water PumpGrade Type,Parent
3,Repair,PDM,BBDW_ASC,ASC,EWP1220,Engine Water Pump,Active,Housing Material,Autocare_Attribute,NaN,1.0,0.0,EWP1220Engine Water PumpHousing Material,Parent
4,Repair,PDM,BBDW_ASC,ASC,EWP1220,Engine Water Pump,Active,Hub Height,Autocare_Attribute,NaN,1.0,0.0,EWP1220Engine Water PumpHub Height,Parent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11552143,Towing,Hitch Pro,Wesbar,Wesbar,8261605,Agriculture Light,Active,Lens Width,FBG_Attribute,5.5,0.0,0.0,8261605Agriculture LightLens Width,Child
11552144,Towing,Hitch Pro,Wesbar,Wesbar,8261605,Agriculture Light,Active,Prop 65,FBG_Attribute,Yes,0.0,0.0,8261605Agriculture LightProp 65,Child
11552145,Towing,Hitch Pro,Wesbar,Wesbar,8261605,Agriculture Light,Active,Prop 65 Chemical,FBG_Attribute,DEHP,0.0,0.0,8261605Agriculture LightProp 65 Chemical,Child
11552146,Towing,Hitch Pro,Wesbar,Wesbar,8261605,Agriculture Light,Active,Prop 65 Warning,FBG_Attribute,WARNING: Cancer and Reproductive Harm – www.p6...,0.0,0.0,8261605Agriculture LightProp 65 Warning,Child
11552147,Towing,Hitch Pro,Wesbar,Wesbar,8261605,Agriculture Light,Active,NaN,FBG_Attribute,NaN,0.0,0.0,8261605Agriculture Lightnan,Child

In [33]:
df_final_List['Product Group'].unique()

array(['Repair', 'Brakes', 'Towing', 'Steering/ Electronics', 'Filter',
       'Lighting', 'Wipers'], dtype=object)

In [67]:
# chunk_size=1000000
# # Create a list of DataFrames by splitting the original DataFrame
# df_chunks = [df_mapped.iloc[i:i + chunk_size] for i in range(0, len(df_mapped), chunk_size)]

# with pd.ExcelWriter(r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\FBG_Data\FBG_SKU_Attributes.xlsx") as writer:  # doctest: +SKIP
#     for i, chunk in enumerate(df_chunks):
#         sheet_name = f"Chunk_{i+1}"  # Naming each sheet dynamically
#         chunk.to_excel(writer, sheet_name=sheet_name, index=False)

In [34]:
df_final_List.to_csv(r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\FBG_Data\FBG_SKU_Attributes.csv",index=False)

In [36]:
cols=['Brand']
df_a = pd.DataFrame(columns=cols)

In [34]:
file_link[1].split('\\')[-1].split('.')[0]

'Champ_Attribute_List'

In [ ]:
chunk_size=1000000
# Create a list of DataFrames by splitting the original DataFrame
df_chunks = [df_Match.iloc[i:i + chunk_size] for i in range(0, len(df_Match), chunk_size)]


with pd.ExcelWriter(OFolder+'\\'+'Horizon_Global_Attribute_List.xlsx') as writer:  # doctest: +SKIP
    for i, chunk in enumerate(df_chunks):
        sheet_name = f"Chunk_{i+1}"  # Naming each sheet dynamically
        chunk.to_excel(writer, sheet_name=sheet_name, index=False)

In [37]:
for i in range(len(file_link)):
    file=file_link[i]
    workbook=openpyxl.load_workbook(file)
    sheetname=workbook.sheetnames
    print(sheetname)
    for s in sheetname:
        if (("FBG_Attributes" in s)):
            print(s)
            df=pd.read_excel(file_link[i],sheet_name=s)
            df['Source']=file_link[i].split('\\')[-1].split('.')[0]  
            df_a=pd.concat([df_a,df])

['Chunk_1', 'Chunk_2', 'Chunk_3', 'FBG_Attributes']
FBG_Attributes
['Chunk_1', 'FBG_Attributes']
FBG_Attributes
['Chunk_1', 'FBG_Attributes']
FBG_Attributes
['Chunk_1', 'FBG_Attributes']
FBG_Attributes
['Chunk_1', 'FBG_Attributes']
FBG_Attributes
['Chunk_1', 'FBG_Attributes']
FBG_Attributes
['Chunk_1', 'FBG_Attributes']
FBG_Attributes
['Chunk_1', 'Chunk_2', 'FBG_Attributes']
FBG_Attributes
['Chunk_1', 'Chunk_2', 'FBG_Attributes']
FBG_Attributes

In [38]:
df_a

,Brand,PartTerminologyName,PAName,Source
0,BPI,Wheel Hub Washer,Finish,BPI_Attribute_List
1,BPI,Wheel Hub Washer,Inside Diameter,BPI_Attribute_List
2,BPI,Wheel Hub Washer,Outside Diameter,BPI_Attribute_List
3,BPI,Wheel Hub Washer,Thickness,BPI_Attribute_List
4,BPI,Parking Brake Disc Brake Pad Set,Inner Pad Height,BPI_Attribute_List
...,...,...,...,...
8465,T00718_Mex Mighty Lift,Multi-Purpose Lift Support Stud,Outer Cylinder Color,PDM_Attribute_List
8466,T00718_Mex Mighty Lift,Multi-Purpose Lift Support Stud,Universal Or Specific Fit,PDM_Attribute_List
8467,T00718_Mex Mighty Lift,Multi-Purpose Lift Support Bracket,Bracket Color,PDM_Attribute_List
8468,T00718_Mex Mighty Lift,Multi-Purpose Lift Support Bracket,Mounting Hole Quantity,PDM_Attribute_List
8469,T00718_Mex Mighty Lift,Multi-Purpose Lift Support Bracket,Universal Or Specific Fit,PDM_Attribute_List

In [39]:
df_a.to_csv(r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\FBG_Data\FBG_Attributes.csv",index=False)