In [1]:
import os
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

In [2]:
folder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\OReilly\Input\Attribute_Audits'
OFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\OReilly'

In [3]:
file_list=[]
for (root, dirs, file) in os.walk(folder):
    for f in file:
        if ('.xlsx') in f:
                    file_list.append(f)
file_list

['ASC Industries Inc_Agricultural & Equipment Water Pumps [N5026].xlsx',
 'ASC Industries Inc_Drive Belt Idler Assembly [6614].xlsx',
 'ASC Industries Inc_Engine Timing Belt Kit With Water Pump [7140].xlsx',
 'ASC Industries Inc_HD Truck Water Pump Backing Plate [N5468].xlsx',
 'ASC Industries Inc_HD Truck Water Pump Idler [N5469].xlsx',
 'ASC Industries Inc_HD Truck Water Pumps [N5124].xlsx',
 'ASC Industries Inc_Hybrid or EV Coolant Pump [8531].xlsx',
 'ASC Industries Inc_Water Pump Adapter [1399].xlsx',
 'ASC Industries Inc_Water Pump [1398].xlsx',
 'Brake Parts Inc LLC_Brake Drum [1269].xlsx',
 'Brake Parts Inc LLC_Brake Pads [3351].xlsx',
 'Brake Parts Inc LLC_Brake Rotor And Hub Assembly [3841].xlsx',
 'Brake Parts Inc LLC_Brake Rotor [1310].xlsx',
 'Brake Parts Inc LLC_HD Truck Brake Pads [N5119].xlsx',
 'Cardone Industries Inc_ABS Control Module [1294].xlsx',
 'Cardone Industries Inc_ABS Hydraulic Unit [1224].xlsx',
 'Cardone Industries Inc_ABS Pump And Motor [1226].xlsx',
 'Cardone Industries Inc_Accelerator Pedal Module [5550].xlsx',
 'Cardone Industries Inc_Accelerator Pedal Position Sensor [2183].xlsx',
 'Cardone Industries Inc_Agriculture or HD - Brakes & Accessories [N2496].xlsx',
 'Cardone Industries Inc_Air Pump [2127].xlsx',
 'Cardone Industries Inc_Air Suspension Compressor Drier [7068].xlsx',
 'Cardone Industries Inc_Air Suspension Compressor [6089].xlsx',
 'Cardone Industries Inc_Air Suspension Spring [6635].xlsx',
 'Cardone Industries Inc_Body Control Module [1596].xlsx',
 'Cardone Industries Inc_Brake Caliper Bracket [1260].xlsx',
 'Cardone Industries Inc_Brake Caliper [3345].xlsx',
 'Cardone Industries Inc_Brake Drum [1269].xlsx',
 'Cardone Industries Inc_Brake Master Cylinder Reservoir Kit [3868].xlsx',
 'Cardone Industries Inc_Brake Master Cylinder [1292].xlsx',
 'Cardone Industries Inc_Brake Proportioning Valve [1306].xlsx',
 'Cardone Industries Inc_Camshaft Position Sensor [2806].xlsx',
 'Cardone Industries Inc_Camshaft Synchronizer Alignment Kit [4161].xlsx',
 'Cardone Industries Inc_Climate Control Module [5056].xlsx',
 'Cardone Industries Inc_Clutch Master Cylinder [1339].xlsx',
 'Cardone Industries Inc_Complete Axle Assembly [7089].xlsx',
 'Cardone Industries Inc_Cooling Fan Controller or Module [1388].xlsx',
 'Cardone Industries Inc_Crankshaft Position or Angle Sensor [2807].xlsx',
 'Cardone Industries Inc_CV Half Shaft [1424].xlsx',
 'Cardone Industries Inc_Diesel Exhaust Fluid (DEF) Heater [7680].xlsx',
 'Cardone Industries Inc_Diesel Exhaust Fluid (DEF) Pump [7668].xlsx',
 'Cardone Industries Inc_Diesel Fuel Injector Driver Module [6486].xlsx',
 'Cardone Industries Inc_Diesel Fuel Injector Install Kit [2462].xlsx',
 'Cardone Industries Inc_Diesel Fuel Injector Pump [2464].xlsx',
 'Cardone Industries Inc_Diesel Fuel Injectors [N5136].xlsx',
 'Cardone Industries Inc_Diesel Particulate Filter Gasket [7705].xlsx',
 'Cardone Industries Inc_Diesel Particulate Filter [7090].xlsx',
 'Cardone Industries Inc_Distributor [2780].xlsx',
 'Cardone Industries Inc_Distributors [N0605].xlsx',
 'Cardone Industries Inc_Domestic Light or Medium Duty Turbochargers [N2652].xlsx',
 'Cardone Industries Inc_Drive Motor Inverter [7531].xlsx',
 'Cardone Industries Inc_Drive Shaft or Prop Shaft [1430].xlsx',
 'Cardone Industries Inc_EGR Cooler Gasket Kit [7366].xlsx',
 'Cardone Industries Inc_EGR Cooler [7011].xlsx',
 'Cardone Industries Inc_Electronic Brake Assembly [7455].xlsx',
 'Cardone Industries Inc_Electronic Brake Pedal Simulator [7454].xlsx',
 'Cardone Industries Inc_Engine or Powertrain Control Module [1599].xlsx',
 'Cardone Industries Inc_Exhaust Pipe Adapter [4095].xlsx',
 'Cardone Industries Inc_Four Wheel Drive Actuator [3942].xlsx',
 'Cardone Industries Inc_Fuel Injection Pump Installation Kit [6589].xlsx',
 'Cardone Industries Inc_Fuel Injector Control Module [6693].xlsx',
 'Cardone Industries Inc_Fuel Injector [2521].xlsx',
 'Cardone Industries Inc_Fuel Pump Driver Module [6617].xlsx',
 'Cardone Industries Inc_Fuel Pump Resistor [2533].xlsx',
 'Cardone Industries Inc_Glow Plug Controller [2794].xlsx',
 'Cardone Industries Inc_HD Truck Brake Boosters And Parts [N5463].xlsx',
 'Cardone Industries Inc_HD Truck Brake Calipers [N5462].xlsx',
 'Cardone Industries Inc_Headlight Actuator or Motor [1161].xlsx',
 'Cardone Industries Inc_Headlight Washer Nozzle [4523].xlsx',
 'Cardone Industries Inc_Hybrid or EV Battery Pack Disconnect [8442].xlsx',
 'Cardone Industries Inc_Instrument Cluster [5997].xlsx',
 'Cardone Industries Inc_Integrated Control Module [7096].xlsx',
 'Cardone Industries Inc_Liftgate or Tailgate Actuator [7092].xlsx',
 'Cardone Industries Inc_Lighting Control Module [3945].xlsx',
 'Cardone Industries Inc_Mass Air Flow Sensor or Meter [2204].xlsx',
 'Cardone Industries Inc_NOx (Nitrogen Oxide) Sensor [7625].xlsx',
 'Cardone Industries Inc_Oil Pump Shaft [2339].xlsx',
 'Cardone Industries Inc_Oil Rail Repair Kit [7176].xlsx',
 'Cardone Industries Inc_Parking Brake Actuator [7488].xlsx',
 'Cardone Industries Inc_Pitman Arm [2865].xlsx',
 'Cardone Industries Inc_Power Brake Booster [1305].xlsx',
 'Cardone Industries Inc_Power Cylinder [2866].xlsx',
 'Cardone Industries Inc_Power Steering Assist Motor [4157].xlsx',
 'Cardone Industries Inc_Power Steering Control Valve [2832].xlsx',
 'Cardone Industries Inc_Power Steering Fluid Reservoir [2868].xlsx',
 'Cardone Industries Inc_Power Steering Pump Pulley [2870].xlsx',
 'Cardone Industries Inc_Power Steering Pump [2869].xlsx',
 'Cardone Industries Inc_Power Supply Module [6457].xlsx',
 'Cardone Industries Inc_Power Window Motor Gear Kit [1199].xlsx',
 'Cardone Industries Inc_Rack & Pinion Complete Unit [2873].xlsx',
 'Cardone Industries Inc_Rack & Pinion Mount Bushings [2875].xlsx',
 'Cardone Industries Inc_Rack & Pinion Short Unit [2882].xlsx',
 'Cardone Industries Inc_Rack And Pinion Hydraulic Transfer Tubing Assembly [7353].xlsx',
 'Cardone Industries Inc_Relay Control Module [1675].xlsx',
 'Cardone Industries Inc_Shackle [2924].xlsx',
 'Cardone Industries Inc_Shock or Strut Conversion Kit [6345].xlsx',
 'Cardone Industries Inc_Shock or Strut [3415].xlsx',
 'Cardone Industries Inc_Steering Column [1216].xlsx',
 'Cardone Industries Inc_Steering Filter [2839].xlsx',
 'Cardone Industries Inc_Steering Gear Box [2840].xlsx',
 'Cardone Industries Inc_Steering Shaft [5130].xlsx',
 'Cardone Industries Inc_Supercharger [2373].xlsx',
 'Cardone Industries Inc_Suspension Ride Height Sensor [7337].xlsx',
 'Cardone Industries Inc_Suspension Self-Leveling Module [2948].xlsx',
 'Cardone Industries Inc_Suspension Solenoid [6360].xlsx',
 'Cardone Industries Inc_Tailgate Window Motor [1206].xlsx',
 'Cardone Industries Inc_Throttle Body [2603].xlsx',
 'Cardone Industries Inc_Tie Rod Bushing [2918].xlsx',
 'Cardone Industries Inc_Transfer Case Control Module [6702].xlsx',
 'Cardone Industries Inc_Transfer Case Shift Motor [3192].xlsx',
 'Cardone Industries Inc_Transmission Control Module [4165].xlsx',
 'Cardone Industries Inc_Trunk Lid Pull Down Motor [1207].xlsx',
 'Cardone Industries Inc_Turbocharger & Accessories [N5473].xlsx',
 'Cardone Industries Inc_Turbocharger Actuator [7663].xlsx',
 'Cardone Industries Inc_Turbocharger Cartridge or Wheel Service Parts [8718].xlsx',
 'Cardone Industries Inc_Turbocharger Coolant Line [7666].xlsx',
 'Cardone Industries Inc_Turbocharger Gasket [2310].xlsx',
 'Cardone Industries Inc_Turbocharger Mounting Kit [4953].xlsx',
 'Cardone Industries Inc_Turbocharger Oil Line [2393].xlsx',
 'Cardone Industries Inc_Turbocharger Position Solenoid [7241].xlsx',
 'Cardone Industries Inc_Turbocharger Service Kit [8843].xlsx',
 'Cardone Industries Inc_Turbocharger [2392].xlsx',
 'Cardone Industries Inc_Unclassified [99990].xlsx',
 'Cardone Industries Inc_Vacuum Pump Pulley [6765].xlsx',
 'Cardone Industries Inc_Vacuum Pump [2220].xlsx',
 'Cardone Industries Inc_Water Pump [1398].xlsx',
 'Cardone Industries Inc_Window Motor [1200].xlsx',
 'Cardone Industries Inc_Window Regulator And Motor Assembly [7141].xlsx',
 'Cardone Industries Inc_Window Regulator [1221].xlsx',
 'Cardone Industries Inc_Windshield Washer Pump [3297].xlsx',
 'Cardone Industries Inc_Windshield Wiper Motor Crank Arm Kit [7719].xlsx',
 'Cardone Industries Inc_Wiper Linkage or Transmission [3301].xlsx',
 'Cardone Industries Inc_Wiper Motor Pulse Board Module [3556].xlsx',
 'Cardone Industries Inc_Wiper Motor [3292].xlsx',
 'Carter Fuel Systems LLC_Agriculture or HD - Fuel & Oil Pumps [N2508].xlsx',
 'Carter Fuel Systems LLC_Direct Injection High Pressure Fuel Pump [9017].xlsx',
 'Carter Fuel Systems LLC_Fuel Line Fittings [N1476].xlsx',
 'Carter Fuel Systems LLC_Fuel Pump - Performance [2535P].xlsx',
 'Carter Fuel Systems LLC_Fuel Pump Pulsator [2530].xlsx',
 'Carter Fuel Systems LLC_Fuel Pump Pushrod [2532].xlsx',
 'Carter Fuel Systems LLC_Fuel Pump Reservoir [3951].xlsx',
 'Carter Fuel Systems LLC_Fuel Pump Spacer [2534].xlsx',
 'Carter Fuel Systems LLC_Fuel Pump Strainer [2518].xlsx',
 'Carter Fuel Systems LLC_Fuel Pump Tank Seal [2537].xlsx',
 'Carter Fuel Systems LLC_Fuel Pump Wiring Harness [3952].xlsx',
 'Carter Fuel Systems LLC_Fuel Pump [2535].xlsx',
 'Carter Fuel Systems LLC_Fuel Pumps - Electric - Universal [N0515].xlsx',
 'Carter Fuel Systems LLC_Fuel Pumps - Mechanical - Universal [N0516].xlsx',
 'Carter Fuel Systems LLC_Fuel Sending Unit or Assembly [1997].xlsx',
 'Carter Fuel Systems LLC_Fuel Tank or Sending Unit Lock Ring [4978].xlsx',
 'Carter Fuel Systems LLC_Gauge - Sending Units & Transducers [N0824].xlsx',
 'Carter Fuel Systems LLC_Marine - Fuel Pumps [N2261].xlsx',
 'Carter Fuel Systems LLC_Unclassified [99990].xlsx',
 'Champion Laboratories Inc_Engine Oil Filter [2269].xlsx',
 'Fram Group Operations LLC_Glow Plug [2793].xlsx',
 'Fram Group Operations LLC_Glow Plugs - Heavy Duty Trucks or Bus or Vans [N2530].xlsx',
 'Fram Group Operations LLC_Marine Spark Plugs - Inboard [N2252].xlsx',
 'Fram Group Operations LLC_Marine Spark Plugs - Jet Boat [N2254].xlsx',
 'Fram Group Operations LLC_Marine Spark Plugs - Outboard [N2253].xlsx',
 'Fram Group Operations LLC_Marine Spark Plugs - Personal Watercraft [N2251].xlsx',
 'Fram Group Operations LLC_OE Spark Plug Specification [7137].xlsx',
 'Fram Group Operations LLC_Small Engine - Spark Plugs [N0246].xlsx',
 'Fram Group Operations LLC_Spark Plug [3435].xlsx',
 'Fram Group Operations LLC_Spark Plugs - ATV or Moped or Motorcycle [N2244].xlsx',
 'Fram Group Operations LLC_Spark Plugs - Chain Saw or Snow Blower [N2250].xlsx',
 'Fram Group Operations LLC_Spark Plugs - Construction or Farm Equipment [N2246].xlsx',
 'Fram Group Operations LLC_Spark Plugs - Generator or Pumps [N2247].xlsx',
 'Fram Group Operations LLC_Spark Plugs - Heavy Duty Trucks or Bus or Vans [N2248].xlsx',
 'Fram Group Operations LLC_Spark Plugs - Industrial or Power Equipment Engines [N2255].xlsx',
 'Fram Group Operations LLC_Spark Plugs - Lawn & Garden [N2249].xlsx',
 'Fram Group Operations LLC_Spark Plugs - Racing [N0608].xlsx',
 'Fram Group Operations LLC_Spark Plugs - Snow Mobile [N2245].xlsx',
 'Hopkins Manufacturing Corporation_12 Volt Heaters And Fans [N0647].xlsx',
 'Hopkins Manufacturing Corporation_2 or 3 or 4 or 5 Way Flat Connectors, Wiring & Accessories [N1542].xlsx',
 'Hopkins Manufacturing Corporation_6 or 7 Way Connectors, Wiring & Accessories [N2480].xlsx',
 'Hopkins Manufacturing Corporation_Agriculture or HD - Cargo Control or Towing Products [N2507].xlsx',
 'Hopkins Manufacturing Corporation_Air Fresheners - Odor Eliminators [N0379].xlsx',
 'Hopkins Manufacturing Corporation_Air Fresheners - Other Scents [N1137].xlsx',
 'Hopkins Manufacturing Corporation_Air Fresheners - Vent Clips [N0375].xlsx',
 'Hopkins Manufacturing Corporation_Air Fresheners [N2725].xlsx',
 'Hopkins Manufacturing Corporation_Attachment Brackets [N1553].xlsx',
 'Hopkins Manufacturing Corporation_Auxiliary Lighting [N0394].xlsx',
 'Hopkins Manufacturing Corporation_Back-Up Lamp [N2154].xlsx',
 'Hopkins Manufacturing Corporation_Backup Alarms [N1847].xlsx',
 'Hopkins Manufacturing Corporation_Backup Cameras [N2277].xlsx',
 'Hopkins Manufacturing Corporation_Battery Booster Cables [N0359].xlsx',
 'Hopkins Manufacturing Corporation_Bench - Gray [N0131].xlsx',
 'Hopkins Manufacturing Corporation_Bench - Other Colors [N0133].xlsx',
 'Hopkins Manufacturing Corporation_Bench - Tan [N0130].xlsx',
 'Hopkins Manufacturing Corporation_Blow Guns [N2002].xlsx',
 'Hopkins Manufacturing Corporation_Breakaway Kit [N1548].xlsx',
 'Hopkins Manufacturing Corporation_Brushes [N4215].xlsx',
 'Hopkins Manufacturing Corporation_Brushes, Dusters & Mini Vacuum [N0455].xlsx',
 'Hopkins Manufacturing Corporation_Bucket - Black [N0134].xlsx',
 'Hopkins Manufacturing Corporation_Bucket - Gray [N0125].xlsx',
 'Hopkins Manufacturing Corporation_Bucket - Other Colors [N0127].xlsx',
 'Hopkins Manufacturing Corporation_Bucket - Tan [N0121].xlsx',
 'Hopkins Manufacturing Corporation_Buffing And Polishing Foam Smooth Pad [N4237].xlsx',
 'Hopkins Manufacturing Corporation_Cab Organizers [N0002].xlsx',
 'Hopkins Manufacturing Corporation_Cable Ties And Mounts [N4757].xlsx',
 'Hopkins Manufacturing Corporation_Car Wash - Buckets, Hoses & Nozzles [N0465].xlsx',
 'Hopkins Manufacturing Corporation_Car Wash - Sponges, Towels & Mitts [N0461].xlsx',
 'Hopkins Manufacturing Corporation_Car Wash [N0456].xlsx',
 'Hopkins Manufacturing Corporation_Cargo Net (Universal) [N0147].xlsx',
 'Hopkins Manufacturing Corporation_Carpet & Upholstery Cleaners [N0466].xlsx',
 'Hopkins Manufacturing Corporation_Chain Wrenches [N1000].xlsx',
 'Hopkins Manufacturing Corporation_Chamois [N0457].xlsx',
 'Hopkins Manufacturing Corporation_Clearance or Marker Lights - Amber [N0392].xlsx',
 'Hopkins Manufacturing Corporation_Clearance or Marker Lights - Red [N0391].xlsx',
 'Hopkins Manufacturing Corporation_Comfort [N0329].xlsx',
 'Hopkins Manufacturing Corporation_Consoles [N0319].xlsx',
 'Hopkins Manufacturing Corporation_De-Icers [N0005].xlsx',
 'Hopkins Manufacturing Corporation_Decals - Car Branded [N0300].xlsx',
 'Hopkins Manufacturing Corporation_Detailing Cloths [N4217].xlsx',
 'Hopkins Manufacturing Corporation_Displays [N9998].xlsx',
 'Hopkins Manufacturing Corporation_Dome Light Lens - Universal [N2198].xlsx',
 'Hopkins Manufacturing Corporation_Drip & Drain Pans [N0026].xlsx',
 'Hopkins Manufacturing Corporation_Driving Lights - Universal [N0393].xlsx',
 'Hopkins Manufacturing Corporation_Driving or Fog Light Wiring - Universal [N2436].xlsx',
 'Hopkins Manufacturing Corporation_Electric Brake Control Connector [5765].xlsx',
 'Hopkins Manufacturing Corporation_Electrical Ties & Clamps [N0226].xlsx',
 'Hopkins Manufacturing Corporation_Exterior Accessories [N0550].xlsx',
 'Hopkins Manufacturing Corporation_Fog Lights - Universal [N0845].xlsx',
 'Hopkins Manufacturing Corporation_Fuel Can - Spouts & Accessories [N0012].xlsx',
 'Hopkins Manufacturing Corporation_Fuel Filters [N5355].xlsx',
 'Hopkins Manufacturing Corporation_Fuel Funnels [N2462].xlsx',
 'Hopkins Manufacturing Corporation_Funnels [N0027].xlsx',
 'Hopkins Manufacturing Corporation_General Purpose Cleaner [N0440].xlsx',
 'Hopkins Manufacturing Corporation_Glass Cleaners [N0464].xlsx',
 'Hopkins Manufacturing Corporation_Glass Cleaning Towels & Wipes [N2401].xlsx',
 'Hopkins Manufacturing Corporation_Hand & Foot Warmers [N2326].xlsx',
 'Hopkins Manufacturing Corporation_Headlights - Halogen [N2337].xlsx',
 'Hopkins Manufacturing Corporation_Hitch Covers - Specialty [N1205].xlsx',
 'Hopkins Manufacturing Corporation_Hitch Covers [N5531].xlsx',
 'Hopkins Manufacturing Corporation_Interior Accessories [N0561].xlsx',
 'Hopkins Manufacturing Corporation_Interior Light [N0387].xlsx',
 'Hopkins Manufacturing Corporation_Key Chains [N5323].xlsx',
 'Hopkins Manufacturing Corporation_Leather Cleaners & Conditioners [N0463].xlsx',
 'Hopkins Manufacturing Corporation_LED Clearance or Marker Lights - Amber [N2646].xlsx',
 'Hopkins Manufacturing Corporation_LED Clearance or Marker Lights - Red [N2645].xlsx',
 'Hopkins Manufacturing Corporation_Levels [N0779].xlsx',
 'Hopkins Manufacturing Corporation_License Plate Frame (Universal) [N5533].xlsx',
 'Hopkins Manufacturing Corporation_License Plate Frame - Plastic [N0305].xlsx',
 'Hopkins Manufacturing Corporation_License Plate Lights [N0390].xlsx',
 'Hopkins Manufacturing Corporation_Light Bar - Universal [N2045].xlsx',
 'Hopkins Manufacturing Corporation_Lighting Mounting Brackets, Grommets & Plugs [N2194].xlsx',
 'Hopkins Manufacturing Corporation_Liquid Transfer Pumps & Accessories [N2327].xlsx',
 'Hopkins Manufacturing Corporation_Litter or Trash Bag [N0321].xlsx',
 'Hopkins Manufacturing Corporation_Loading Ramps [N2275].xlsx',
 'Hopkins Manufacturing Corporation_Logo Items - Novelties [N0506].xlsx',
 'Hopkins Manufacturing Corporation_Microfiber Bonnets [N4267].xlsx',
 'Hopkins Manufacturing Corporation_Mud Flap [1037].xlsx',
 'Hopkins Manufacturing Corporation_Nitrile Gloves [N2212].xlsx',
 'Hopkins Manufacturing Corporation_Oil Absorbent [N0431].xlsx',
 'Hopkins Manufacturing Corporation_Oil Change - Spouts & Accessories [N1931].xlsx',
 'Hopkins Manufacturing Corporation_Oil Filter Wrench (Universal) [N0066].xlsx',
 'Hopkins Manufacturing Corporation_Organizers [N0737].xlsx',
 'Hopkins Manufacturing Corporation_Parking Aid Camera [7974].xlsx',
 'Hopkins Manufacturing Corporation_Patch or Plug or Repair Kit [N0179].xlsx',
 'Hopkins Manufacturing Corporation_Pigtails & Sockets - 1 Wire [N1585].xlsx',
 'Hopkins Manufacturing Corporation_Polishing Cloths [N4223].xlsx',
 'Hopkins Manufacturing Corporation_Polishing Tools [N4281].xlsx',
 'Hopkins Manufacturing Corporation_Protectants, Interior Cleaners & Wipes [N0460].xlsx',
 'Hopkins Manufacturing Corporation_Ramp [N0771].xlsx',
 'Hopkins Manufacturing Corporation_Reflector - Universal [N1970].xlsx',
 'Hopkins Manufacturing Corporation_Replacement Relays [N0381].xlsx',
 'Hopkins Manufacturing Corporation_Seat Belts & Accessories [N0332].xlsx',
 'Hopkins Manufacturing Corporation_Seat Covers - Universal [N5325].xlsx',
 'Hopkins Manufacturing Corporation_Shop Supplies [N2305].xlsx',
 'Hopkins Manufacturing Corporation_Shop Supplies [N5333].xlsx',
 'Hopkins Manufacturing Corporation_Shop Towels [N0034].xlsx',
 'Hopkins Manufacturing Corporation_Shop Vacuums & Accessories [N0035].xlsx',
 'Hopkins Manufacturing Corporation_Small Engine Fuel Filters [N5251].xlsx',
 'Hopkins Manufacturing Corporation_Snow Brushes & Ice Scrapers [N0031].xlsx',
 'Hopkins Manufacturing Corporation_Snow Shovels [N0805].xlsx',
 'Hopkins Manufacturing Corporation_Splash or Mud Guard - Universal [N0174].xlsx',
 'Hopkins Manufacturing Corporation_Split Bench [N0111].xlsx',
 'Hopkins Manufacturing Corporation_Spotlights [N2391].xlsx',
 'Hopkins Manufacturing Corporation_Squeegees [N4510].xlsx',
 'Hopkins Manufacturing Corporation_Steering Wheel Covers - Slip On [N0135].xlsx',
 'Hopkins Manufacturing Corporation_Steering Wheel Covers [N5327].xlsx',
 'Hopkins Manufacturing Corporation_Sunglasses & Holders [N0346].xlsx',
 'Hopkins Manufacturing Corporation_Tail Light Converter [4139].xlsx',
 'Hopkins Manufacturing Corporation_Tail Light Converters - Universal [N1545].xlsx',
 'Hopkins Manufacturing Corporation_Tail Light Converters [N0158].xlsx',
 'Hopkins Manufacturing Corporation_Tail Lights (Universal) [N0389].xlsx',
 'Hopkins Manufacturing Corporation_Tape [N4424].xlsx',
 'Hopkins Manufacturing Corporation_Terry Cloth Bonnets [N4270].xlsx',
 'Hopkins Manufacturing Corporation_Tire Valve Caps & Extensions [N0183].xlsx',
 'Hopkins Manufacturing Corporation_Towing Light Kits [N5435].xlsx',
 'Hopkins Manufacturing Corporation_Traction Boards [N2324].xlsx',
 'Hopkins Manufacturing Corporation_Traffic Safety [N2220].xlsx',
 'Hopkins Manufacturing Corporation_Trailer Alignment & Leveling [N2318].xlsx',
 'Hopkins Manufacturing Corporation_Trailer Brake Controller (Universal) [N2123].xlsx',

In [4]:
file_link=[]

for i in range(len(file_list)):
     for r,d,f in os.walk(folder):
          for files in f:
               if files == file_list[i]:
                    file_link.append(os.path.join(r,files))

In [5]:
len(file_link)

583

In [6]:
file_link[0]

'C:\\Users\\Vikram.Vadhirajan\\OneDrive - Trico\\Documents - Product Support India Romania\\Catalog\\Score card\\OReilly\\Input\\Attribute_Audits\\ASC Industries Inc_Agricultural & Equipment Water Pumps [N5026].xlsx'

In [7]:
att_cols=["Part Type ID","Part Type Name","Attribute Description","Required"]
df_Attributes = pd.DataFrame(columns=att_cols)
for i in range(len(file_link)):
    dfa=pd.read_excel(file_link[i],sheet_name="Attributes")
    counts=0
    for j in range(len(dfa)):
        #dfa.loc[counts, "Source"]=file_link[i]
        dfa.loc[counts, "Brand"]=file_link[i].split("Attribute_Audits\\")[1].split("_")[0]
        dfa.loc[counts, "Product_Type"]=file_link[i].split("Attribute_Audits\\")[1].split("_")[1].replace(".xlsx","")
        counts=counts+1
    df_Attributes=df_Attributes.append(dfa)

In [8]:
df_Attributes['Required']=df_Attributes['Required'].fillna('Not Mandatory')

In [9]:
df_Attributes

,Part Type ID,Part Type Name,Attribute Description,Required,Brand,Product_Type
0,N5026,Agricultural & Equipment Water Pumps,Pulley Included,Mandatory,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026]
1,N5026,Agricultural & Equipment Water Pumps,New Or Remanufactured,Mandatory,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026]
2,N5026,Agricultural & Equipment Water Pumps,Back Housing Included,Not Mandatory,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026]
3,N5026,Agricultural & Equipment Water Pumps,Bolts Included,Not Mandatory,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026]
4,N5026,Agricultural & Equipment Water Pumps,Number Of Mounting Holes,Not Mandatory,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026]
...,...,...,...,...,...,...
9,3292,Wiper Motor,Wiring Harness Length (in),Not Mandatory,Trico Products Corp,Wiper Motor [3292]
0,3304,Wiper Refill,Length (in),Mandatory,Trico Products Corp,Wiper Refill [3304]
1,3304,Wiper Refill,Length (mm),Mandatory,Trico Products Corp,Wiper Refill [3304]
2,3304,Wiper Refill,Element Material,Not Mandatory,Trico Products Corp,Wiper Refill [3304]
3,3304,Wiper Refill,Superstructure Material,Not Mandatory,Trico Products Corp,Wiper Refill [3304]

In [10]:
df_Attributes['Key']=df_Attributes.Brand+df_Attributes.Product_Type+df_Attributes['Attribute Description']

In [11]:
df_Attributes

,Part Type ID,Part Type Name,Attribute Description,Required,Brand,Product_Type,Key
0,N5026,Agricultural & Equipment Water Pumps,Pulley Included,Mandatory,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],ASC Industries IncAgricultural & Equipment Wat...
1,N5026,Agricultural & Equipment Water Pumps,New Or Remanufactured,Mandatory,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],ASC Industries IncAgricultural & Equipment Wat...
2,N5026,Agricultural & Equipment Water Pumps,Back Housing Included,Not Mandatory,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],ASC Industries IncAgricultural & Equipment Wat...
3,N5026,Agricultural & Equipment Water Pumps,Bolts Included,Not Mandatory,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],ASC Industries IncAgricultural & Equipment Wat...
4,N5026,Agricultural & Equipment Water Pumps,Number Of Mounting Holes,Not Mandatory,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],ASC Industries IncAgricultural & Equipment Wat...
...,...,...,...,...,...,...,...
9,3292,Wiper Motor,Wiring Harness Length (in),Not Mandatory,Trico Products Corp,Wiper Motor [3292],Trico Products CorpWiper Motor [3292]Wiring Ha...
0,3304,Wiper Refill,Length (in),Mandatory,Trico Products Corp,Wiper Refill [3304],Trico Products CorpWiper Refill [3304]Length (in)
1,3304,Wiper Refill,Length (mm),Mandatory,Trico Products Corp,Wiper Refill [3304],Trico Products CorpWiper Refill [3304]Length (mm)
2,3304,Wiper Refill,Element Material,Not Mandatory,Trico Products Corp,Wiper Refill [3304],Trico Products CorpWiper Refill [3304]Element ...
3,3304,Wiper Refill,Superstructure Material,Not Mandatory,Trico Products Corp,Wiper Refill [3304],Trico Products CorpWiper Refill [3304]Superstr...

In [12]:
len(file_link)

583

In [13]:
con_cols=["Line","PLCD","Mfg Code","EPC Part Number","Item Number","Short Description","Brand","Product_Type"]
df_Att_values = pd.DataFrame(columns=con_cols)
for i in range(len(file_link)):
    df=pd.read_excel(file_link[i],sheet_name="Attribute Audit",skiprows=1)
    count=0
    if len(df)!=0:
        for j in range(len(df)):
            df.loc[count, "Brand"]=file_link[i].split("Attribute_Audits\\")[1].split("_")[0]
            df.loc[count, "Product_Type"]=file_link[i].split("Attribute_Audits\\")[1].split("_")[1].replace(".xlsx","")
            count=count+1
        df=df.melt(id_vars=con_cols, var_name='Attributes', value_name='Values')
        df_Att_values=df_Att_values.append(df)
    else:
        pass
df_Att_values

,Line,PLCD,Mfg Code,EPC Part Number,Item Number,Short Description,Brand,Product_Type,Attributes,Values
0,IDC,NaN,IDC,CP6230,CP6230,Water Pump,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],Pulley Included,Yes
1,IDC,NaN,IDC,CP6230,CP6230,Water Pump,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],New Or Remanufactured,New
2,IDC,NaN,IDC,CP6230,CP6230,Water Pump,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],Back Housing Included,No
3,IDC,NaN,IDC,CP6230,CP6230,Water Pump,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],Bolts Included,Yes
4,IDC,NaN,IDC,CP6230,CP6230,Water Pump,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],Number Of Mounting Holes,4
...,...,...,...,...,...,...,...,...,...,...
43,TRI,NaN,TRI,43220,43-220,Wiper Refill,Trico Products Corp,Wiper Refill [3304],Superstructure Material,Steel
44,TRI,NaN,TRI,45200,45-200,Wiper Refill,Trico Products Corp,Wiper Refill [3304],Superstructure Material,Steel
45,TRI,9.0,TRI,47600,47-600,Wiper Refill,Trico Products Corp,Wiper Refill [3304],Superstructure Material,Stainless Steel
46,TRI,NaN,TRI,47700,47-700,Wiper Refill,Trico Products Corp,Wiper Refill [3304],Superstructure Material,Stainless Steel
47,TRI,NaN,TRI,47800,47-800,Wiper Refill,Trico Products Corp,Wiper Refill [3304],Superstructure Material,Stainless Steel

In [14]:
df_Att_values.nunique()

Line                    37
PLCD                    32
Mfg Code                30
EPC Part Number      43206
Item Number          43351
Short Description      974
Brand                   10
Product_Type           533
Attributes            2098
Values                9854
dtype: int64

In [15]:
df_Att_values['Key']=df_Att_values.Brand+df_Att_values.Product_Type+df_Att_values.Attributes

In [16]:
df_Att_values

,Line,PLCD,Mfg Code,EPC Part Number,Item Number,Short Description,Brand,Product_Type,Attributes,Values,Key
0,IDC,NaN,IDC,CP6230,CP6230,Water Pump,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],Pulley Included,Yes,ASC Industries IncAgricultural & Equipment Wat...
1,IDC,NaN,IDC,CP6230,CP6230,Water Pump,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],New Or Remanufactured,New,ASC Industries IncAgricultural & Equipment Wat...
2,IDC,NaN,IDC,CP6230,CP6230,Water Pump,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],Back Housing Included,No,ASC Industries IncAgricultural & Equipment Wat...
3,IDC,NaN,IDC,CP6230,CP6230,Water Pump,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],Bolts Included,Yes,ASC Industries IncAgricultural & Equipment Wat...
4,IDC,NaN,IDC,CP6230,CP6230,Water Pump,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],Number Of Mounting Holes,4,ASC Industries IncAgricultural & Equipment Wat...
...,...,...,...,...,...,...,...,...,...,...,...
43,TRI,NaN,TRI,43220,43-220,Wiper Refill,Trico Products Corp,Wiper Refill [3304],Superstructure Material,Steel,Trico Products CorpWiper Refill [3304]Superstr...
44,TRI,NaN,TRI,45200,45-200,Wiper Refill,Trico Products Corp,Wiper Refill [3304],Superstructure Material,Steel,Trico Products CorpWiper Refill [3304]Superstr...
45,TRI,9.0,TRI,47600,47-600,Wiper Refill,Trico Products Corp,Wiper Refill [3304],Superstructure Material,Stainless Steel,Trico Products CorpWiper Refill [3304]Superstr...
46,TRI,NaN,TRI,47700,47-700,Wiper Refill,Trico Products Corp,Wiper Refill [3304],Superstructure Material,Stainless Steel,Trico Products CorpWiper Refill [3304]Superstr...
47,TRI,NaN,TRI,47800,47-800,Wiper Refill,Trico Products Corp,Wiper Refill [3304],Superstructure Material,Stainless Steel,Trico Products CorpWiper Refill [3304]Superstr...

In [17]:
df_final=pd.merge(df_Att_values,df_Attributes, on='Key', how='left')

In [18]:
df_final

,Line,PLCD,Mfg Code,EPC Part Number,Item Number,Short Description,Brand_x,Product_Type_x,Attributes,Values,Key,Part Type ID,Part Type Name,Attribute Description,Required,Brand_y,Product_Type_y
0,IDC,NaN,IDC,CP6230,CP6230,Water Pump,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],Pulley Included,Yes,ASC Industries IncAgricultural & Equipment Wat...,N5026,Agricultural & Equipment Water Pumps,Pulley Included,Mandatory,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026]
1,IDC,NaN,IDC,CP6230,CP6230,Water Pump,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],New Or Remanufactured,New,ASC Industries IncAgricultural & Equipment Wat...,N5026,Agricultural & Equipment Water Pumps,New Or Remanufactured,Mandatory,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026]
2,IDC,NaN,IDC,CP6230,CP6230,Water Pump,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],Back Housing Included,No,ASC Industries IncAgricultural & Equipment Wat...,N5026,Agricultural & Equipment Water Pumps,Back Housing Included,Not Mandatory,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026]
3,IDC,NaN,IDC,CP6230,CP6230,Water Pump,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],Bolts Included,Yes,ASC Industries IncAgricultural & Equipment Wat...,N5026,Agricultural & Equipment Water Pumps,Bolts Included,Not Mandatory,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026]
4,IDC,NaN,IDC,CP6230,CP6230,Water Pump,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026],Number Of Mounting Holes,4,ASC Industries IncAgricultural & Equipment Wat...,N5026,Agricultural & Equipment Water Pumps,Number Of Mounting Holes,Not Mandatory,ASC Industries Inc,Agricultural & Equipment Water Pumps [N5026]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734112,TRI,NaN,TRI,43220,43-220,Wiper Refill,Trico Products Corp,Wiper Refill [3304],Superstructure Material,Steel,Trico Products CorpWiper Refill [3304]Superstr...,3304,Wiper Refill,Superstructure Material,Not Mandatory,Trico Products Corp,Wiper Refill [3304]
734113,TRI,NaN,TRI,45200,45-200,Wiper Refill,Trico Products Corp,Wiper Refill [3304],Superstructure Material,Steel,Trico Products CorpWiper Refill [3304]Superstr...,3304,Wiper Refill,Superstructure Material,Not Mandatory,Trico Products Corp,Wiper Refill [3304]
734114,TRI,9.0,TRI,47600,47-600,Wiper Refill,Trico Products Corp,Wiper Refill [3304],Superstructure Material,Stainless Steel,Trico Products CorpWiper Refill [3304]Superstr...,3304,Wiper Refill,Superstructure Material,Not Mandatory,Trico Products Corp,Wiper Refill [3304]
734115,TRI,NaN,TRI,47700,47-700,Wiper Refill,Trico Products Corp,Wiper Refill [3304],Superstructure Material,Stainless Steel,Trico Products CorpWiper Refill [3304]Superstr...,3304,Wiper Refill,Superstructure Material,Not Mandatory,Trico Products Corp,Wiper Refill [3304]
734116,TRI,NaN,TRI,47800,47-800,Wiper Refill,Trico Products Corp,Wiper Refill [3304],Superstructure Material,Stainless Steel,Trico Products CorpWiper Refill [3304]Superstr...,3304,Wiper Refill,Superstructure Material,Not Mandatory,Trico Products Corp,Wiper Refill [3304]

In [19]:
df_final.columns

Index(['Line', 'PLCD', 'Mfg Code', 'EPC Part Number', 'Item Number',
       'Short Description', 'Brand_x', 'Product_Type_x', 'Attributes',
       'Values', 'Key', 'Part Type ID', 'Part Type Name',
       'Attribute Description', 'Required', 'Brand_y', 'Product_Type_y'],
      dtype='object')

In [20]:
df_List=df_final[['Brand_x','Product_Type_x','EPC Part Number', 'Item Number','Short Description', 'Attributes', 'Values','Part Type Name', 'Required']]

In [21]:
df_List.shape

(734117, 9)

In [131]:
df_List=df_List[df_List["Required"]=="Mandatory"]

In [21]:
df_List.shape

(734117, 9)

In [22]:
with pd.ExcelWriter(OFolder+'\\'+'OReilly_Mandatory_Baseline.xlsx') as writer:  # doctest: +SKIP
    df_List.to_excel(writer,index=False, sheet_name='Raw')