In [16]:
import os
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
import re
import openpyxl
import numpy as np

In [17]:
folder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\NAPA\Mandatory\WIP'
OFolder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\28_NAPA_Scorecard'

In [18]:
file_list=[]
for (root, dirs, file) in os.walk(folder):
    for f in file:
        if  ("NAPA_SKU_Attributes" in f) and ("Baseline" not in f): #('.xlsx') and
            file_list.append(f)
file_list

['NAPA_SKU_Attributes_Autolite.xlsx',
 'NAPA_SKU_Attributes_BPI.xlsx',
 'NAPA_SKU_Attributes_TRICO.xlsx',
 '20250702_NAPA_SKU_Attributes_BPI-Hydraulics.xlsx']

In [19]:
file_link=[]

for i in range(len(file_list)):
     for r,d,f in os.walk(folder):
          for files in f:
               if files == file_list[i]:
                    file_link.append(os.path.join(r,files))

In [20]:
len(file_link)

4

In [21]:
file_link[0].split("_")[-1].replace(".xlsx","")

'Autolite'

In [22]:
file_link[2].split("_")[-1].replace(".xlsx","")

'TRICO'

In [23]:
#cols=["Filename","part Type",'Product ID','*\xa0<Name>', 'Working Column','Supplier Classification Reference', 'Manufacturer', 'ASG Vendor Name','<Parent ID>', '<Object Type Name>','variable','value']
cols=["Part Type","PartNumber"]
df_s = pd.DataFrame(columns=cols)
df_s

Empty DataFrame
Columns: [Part Type, PartNumber]
Index: []

In [24]:
IDs=["FBG_Brand","Part Type","PartNumber","Parent article number","Product Group","Article Status Description"]

In [25]:
for i in range(3,4):
    workbook=openpyxl.load_workbook(file_link[i])
    sheetname=workbook.sheetnames
    print(sheetname)
    for s in sheetname:
        if (("STEPLOV" not in s)):
            print(s)
            df=pd.read_excel(file_link[i],sheet_name=s)
            df["FBG_Brand"]=file_link[i].split("_")[-1].replace(".xlsx","")
            df=pd.melt(df,id_vars=IDs).reset_index(drop=True)            
            df_s=pd.concat([df_s,df])

['Brake Hose', 'Brake Master Cylinder', 'Brake Cylinder Repair   Servic', 'Clutch Master Cylinder Repair ', 'Brake Master Cylinder Reservoi', 'Brake Master Cylinder Cap', 'Gasket', 'Brake Proportioning Valve', 'Brake Wheel Cylinder', 'Brake Wheel Cylinder Boot Kit', 'Brake Wheel Cylinder Cup', 'Parking Brake Cable', 'STEPLOV']
Brake Hose
Brake Master Cylinder
Brake Cylinder Repair   Servic
Clutch Master Cylinder Repair
Brake Master Cylinder Reservoi
Brake Master Cylinder Cap
Gasket
Brake Proportioning Valve
Brake Wheel Cylinder
Brake Wheel Cylinder Boot Kit
Brake Wheel Cylinder Cup
Parking Brake Cable

In [27]:
df_s.loc[df_s['FBG_Brand'].str.lower() == "BPI-Hydraulics".lower(), 'FBG_Brand'] = "BPI"
df_s

,Part Type,PartNumber,FBG_Brand,Parent article number,Product Group,Article Status Description,variable,value
0,Brake Hose,100402,BPI,381076,Brake Hydraulic Hose,Inactive,Overall Length,698.5
1,Brake Hose,10304,BPI,10304,Brake Hydraulic Hose,Available,Overall Length,388.62
2,Brake Hose,10595,BPI,10595,Brake Hydraulic Hose,Available,Overall Length,294.64
3,Brake Hose,11146,BPI,11146,Brake Hydraulic Hose,Available,Overall Length,454.66
4,Brake Hose,11147,BPI,11147,Brake Hydraulic Hose,Available,Overall Length,391.16
...,...,...,...,...,...,...,...,...
39199,Parking Brake Cable,97656,BPI,97656,Parking Brake Cable,Available,SDS Required,No (135233618)
39200,Parking Brake Cable,97657,BPI,97657,Parking Brake Cable,Available,SDS Required,No (135233618)
39201,Parking Brake Cable,97658,BPI,97658,Parking Brake Cable,Available,SDS Required,No (135233618)
39202,Parking Brake Cable,BC500A,BPI,BC500A,Parking Brake Cable Shortener,Available,SDS Required,No (135233618)
39203,-----,-----,BPI,-----,-----,-----,SDS Required,-----

In [28]:
df_s = df_s[df_s['value'].notna()]

In [29]:
df_s

,Part Type,PartNumber,FBG_Brand,Parent article number,Product Group,Article Status Description,variable,value
0,Brake Hose,100402,BPI,381076,Brake Hydraulic Hose,Inactive,Overall Length,698.5
1,Brake Hose,10304,BPI,10304,Brake Hydraulic Hose,Available,Overall Length,388.62
2,Brake Hose,10595,BPI,10595,Brake Hydraulic Hose,Available,Overall Length,294.64
3,Brake Hose,11146,BPI,11146,Brake Hydraulic Hose,Available,Overall Length,454.66
4,Brake Hose,11147,BPI,11147,Brake Hydraulic Hose,Available,Overall Length,391.16
...,...,...,...,...,...,...,...,...
39199,Parking Brake Cable,97656,BPI,97656,Parking Brake Cable,Available,SDS Required,No (135233618)
39200,Parking Brake Cable,97657,BPI,97657,Parking Brake Cable,Available,SDS Required,No (135233618)
39201,Parking Brake Cable,97658,BPI,97658,Parking Brake Cable,Available,SDS Required,No (135233618)
39202,Parking Brake Cable,BC500A,BPI,BC500A,Parking Brake Cable Shortener,Available,SDS Required,No (135233618)
39203,-----,-----,BPI,-----,-----,-----,SDS Required,-----

In [30]:
df_s=df_s[['FBG_Brand','Part Type', 'PartNumber', 'variable', 'value']].drop_duplicates().reset_index(drop=True)

In [31]:
df_s

,FBG_Brand,Part Type,PartNumber,variable,value
0,BPI,Brake Hose,100402,Overall Length,698.5
1,BPI,Brake Hose,10304,Overall Length,388.62
2,BPI,Brake Hose,10595,Overall Length,294.64
3,BPI,Brake Hose,11146,Overall Length,454.66
4,BPI,Brake Hose,11147,Overall Length,391.16
...,...,...,...,...,...
103811,BPI,Parking Brake Cable,97655,SDS Required,No (135233618)
103812,BPI,Parking Brake Cable,97656,SDS Required,No (135233618)
103813,BPI,Parking Brake Cable,97657,SDS Required,No (135233618)
103814,BPI,Parking Brake Cable,97658,SDS Required,No (135233618)
103815,BPI,Parking Brake Cable,BC500A,SDS Required,No (135233618)