In [1]:
import os
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
import re
import openpyxl
import numpy as np

In [2]:
folder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\NAPA\Mandatory\Input\Smartsheets\Unblocked'
OFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\NAPA\Mandatory\WIP'

In [3]:
file_list=[]
for (root, dirs, file) in os.walk(folder):
    for f in file:
        if ('.xlsm') in f:
                    file_list.append(f)
file_list

['BMCR.xlsm',
 'BRHA.xlsm',
 'BS.xlsm',
 'BSAL.xlsm',
 'BSARS.xlsm',
 'BSASA.xlsm',
 'BSHK.xlsm',
 'BSS.xlsm',
 'BWC.xlsm',
 'CB.xlsm',
 'CBK.xlsm',
 'CP.xlsm',
 'CSBK.xlsm',
 'DBBK.xlsm',
 'DBC.xlsm',
 'DBHK.xlsm',
 'Excel--2025-12-16--00-34-2025-12-16_00.34.30.xlsm',
 'Excel--2025-12-16--00-34-2025-12-16_00.34.52.xlsm',
 'Excel--2025-12-16--00-35-2025-12-16_00.35.38.xlsm',
 'Excel--2025-12-16--00-36-2025-12-16_00.36.04.xlsm',
 'Excel--2025-12-16--00-36-2025-12-16_00.36.27.xlsm',
 'Excel--2025-12-16--00-37-2025-12-16_00.37.18.xlsm',
 'Excel--2025-12-17--08-19-2025-12-17_08.19.26.xlsm',
 'Excel--2025-12-17--08-19-2025-12-17_08.19.40.xlsm',
 'Excel--2025-12-17--08-19-2025-12-17_08.19.59.xlsm',
 'Excel--2025-12-17--08-20-2025-12-17_08.20.16.xlsm',
 'Excel--2025-12-17--08-21-2025-12-17_08.21.46.xlsm',
 'Excel--2025-12-17--08-22-2025-12-17_08.22.34.xlsm',
 'Excel--2025-12-17--08-22-2025-12-17_08.22.50.xlsm',
 'Excel--2025-12-17--08-23-2025-12-17_08.23.05.xlsm',
 'Excel--2025-12-17--08-23-2025-12-17_08.23.21.xlsm',
 'Excel--2025-12-17--08-23-2025-12-17_08.23.38.xlsm',
 'Excel--2025-12-17--08-23-2025-12-17_08.23.51.xlsm',
 'Excel--2025-12-17--08-24-2025-12-17_08.24.38.xlsm',
 'Excel--2025-12-17--08-24-2025-12-17_08.24.52.xlsm',
 'Excel--2025-12-17--08-25-2025-12-17_08.25.08.xlsm',
 'Excel--2025-12-17--08-25-2025-12-17_08.25.26.xlsm',
 'Excel--2025-12-17--08-25-2025-12-17_08.25.43.xlsm',
 'Excel--2025-12-17--08-25-2025-12-17_08.25.59.xlsm',
 'Excel--2025-12-17--08-26-2025-12-17_08.26.12.xlsm',
 'Excel--2025-12-17--08-26-2025-12-17_08.26.31.xlsm',
 'Excel--2025-12-17--08-26-2025-12-17_08.26.52.xlsm',
 'Excel--2025-12-17--08-27-2025-12-17_08.27.08.xlsm',
 'Excel--2025-12-17--08-48-2025-12-17_08.48.45.xlsm',
 'Excel--2025-12-17--08-49-2025-12-17_08.49.01.xlsm',
 'Excel--2025-12-17--08-49-2025-12-17_08.49.12.xlsm',
 'Excel--2025-12-17--08-49-2025-12-17_08.49.26.xlsm',
 'Excel--2025-12-17--08-49-2025-12-17_08.49.37.xlsm',
 'Excel--2025-12-17--08-49-2025-12-17_08.49.56.xlsm',
 'Excel--2025-12-17--08-50-2025-12-17_08.50.11.xlsm',
 'Excel--2025-12-17--08-50-2025-12-17_08.50.28.xlsm',
 'Excel--2025-12-17--08-50-2025-12-17_08.50.40.xlsm',
 'Excel--2025-12-17--08-50-2025-12-17_08.50.56.xlsm',
 'Excel--2025-12-17--08-51-2025-12-17_08.51.13.xlsm',
 'Excel--2025-12-17--08-51-2025-12-17_08.51.28.xlsm',
 'Excel--2025-12-17--08-51-2025-12-17_08.51.42.xlsm',
 'Excel--2025-12-17--08-51-2025-12-17_08.51.59.xlsm',
 'Excel--2025-12-17--08-52-2025-12-17_08.52.11.xlsm',
 'Excel--2025-12-17--08-52-2025-12-17_08.52.28.xlsm',
 'Excel--2025-12-17--08-56-2025-12-17_08.56.51.xlsm',
 'Excel--2025-12-17--08-57-2025-12-17_08.57.06.xlsm',
 'Excel--2025-12-17--08-57-2025-12-17_08.57.22.xlsm',
 'Excel--2025-12-17--08-57-2025-12-17_08.57.38.xlsm',
 'Excel--2025-12-17--08-57-2025-12-17_08.57.54.xlsm',
 'Excel--2025-12-17--08-58-2025-12-17_08.58.16.xlsm',
 'Excel--2025-12-17--08-58-2025-12-17_08.58.32.xlsm',
 'Excel--2025-12-17--08-58-2025-12-17_08.58.50.xlsm',
 'Excel--2025-12-17--08-59-2025-12-17_08.59.49.xlsm',
 'Excel--2025-12-17--09-00-2025-12-17_09.00.07.xlsm',
 'Excel--2025-12-17--09-00-2025-12-17_09.00.33.xlsm',
 'Sensor.xlsm']

In [4]:
file_link=[]

for i in range(len(file_list)):
     for r,d,f in os.walk(folder):
          for files in f:
               if files == file_list[i]:
                    file_link.append(os.path.join(r,files))

In [5]:
len(file_link)

71

In [6]:
file_link[1]

'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\Documents - Product Support India Romania\\Catalog\\Score card\\NAPA\\Mandatory\\Input\\Smartsheets\\Unblocked\\BRHA.xlsm'

In [19]:
cols=["Filename","part Type",'Product ID','*\xa0<Name>', 'Working Column','Supplier Classification Reference', 'Manufacturer', 'ASG Vendor Name','<Parent ID>', '<Object Type Name>','Attribute','value']
df_s = pd.DataFrame(columns=cols)
df_s

Empty DataFrame
Columns: [Filename, part Type, Product ID, * <Name>, Working Column, Supplier Classification Reference, Manufacturer, ASG Vendor Name, <Parent ID>, <Object Type Name>, Attribute, value]
Index: []

In [7]:
repl='''C:\\Users\\Vikram.Vadhirajan\\OneDrive - Trico\\Documents - Product Support India Romania\\Catalog\\Score card\\NAPA\\Mandatory\\Input\\'''
IDS=["Filename","part Type",'Product ID','*\xa0<Name>', 'Working Column','Supplier Classification Reference', 'Manufacturer', 'ASG Vendor Name','<Parent ID>', '<Object Type Name>']

In [ ]:
#trial to delete




for i in range(len(file_link)):
    workbook=openpyxl.load_workbook(file_link[i])
    sheetname=workbook.sheetnames
    print(sheetname)
    for s in sheetname:
        if (("STEP" not in s) and ("Cover" not in s)):
            print(s)
            df=pd.read_excel(file_link[i],sheet_name=s, skiprows=9)
            df["Filename"]=file_link[i]
            df=df[['Filename','<Parent ID>']].drop_duplicates()
            df_s=pd.concat([df_s,df])

['Cover', 'STEPChanges', 'Brake Master Cylinder Reservoi', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Master Cylinder Reservoi
['Cover', 'STEPChanges', 'Brake Rotor and Hub Assembly', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Rotor and Hub Assembly
['Cover', 'STEPChanges', 'STEPLogging', 'Bleeder Screw', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Bleeder Screw
['Cover', 'STEPChanges', 'STEPLogging', 'Brake Shoe Adjuster Lever', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Adjuster Lever
['Cover', 'STEPChanges', 'STEPLogging', 'Brake Shoe Adjuster Repair   S', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Adjuster Repair   S
['Cover', 'STEPChanges', 'Brake Shoe Adjuster Screw Assy', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Adjuster Screw Assy
['Cover', 'STEPChanges', 'Brake Shoe Hardware Kit', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Hardware Kit
['Cover', 'STEPChanges', 'Brake Shoe Spring', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Spring
['Cover', 'STEPChanges', 'Brake Wheel Cylinder', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Wheel Cylinder
['Cover', 'STEPChanges', 'Caliper Bolt', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Caliper Bolt
['Cover', 'STEPChanges', 'Caliper Bolt Kit', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Caliper Bolt Kit
['Cover', 'STEPChanges', 'Caliper Piston', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Caliper Piston
['Cover', 'STEPChanges', 'Caliper Seal and Boot Kit', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Caliper Seal and Boot Kit
['Cover', 'STEPChanges', 'Disc Brake Bushing Kit', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Disc Brake Bushing Kit
['Cover', 'STEPChanges', 'Disc Brake Clip', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Disc Brake Clip
['Cover', 'STEPChanges', 'Disc Brake Hardware Kit', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Disc Brake Hardware Kit
['Cover', 'STEPChanges', 'Brake Shoe Hold-Down Kit', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Hold-Down Kit
['Cover', 'Caliper Bolt Sleeve', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Caliper Bolt Sleeve
['Cover', 'Brake Rotor Shim', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Rotor Shim
['Cover', 'Disc Brake Boot Kit', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Disc Brake Boot Kit
['Cover', 'Caliper Spring', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Caliper Spring
['Cover', 'Brake Cylinder Repair   Servic', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Cylinder Repair   Servic
['Cover', 'Brake Shoe Hold-Down Nails', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Hold-Down Nails
['Cover', 'Brake Shoe Adjuster Cable', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Adjuster Cable
['Cover', 'Brake Drum', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Drum
['Cover', 'Sealing Washer', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Sealing Washer
['Cover', 'Brake Caliper', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Caliper
['Cover', 'Brake Backing Plate Assembly', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Backing Plate Assembly
['Cover', 'Brake Shoe Clip', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Clip
['Cover', 'Caliper Damper Kit', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Caliper Damper Kit
['Cover', 'Caliper Pin Retainer', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Caliper Pin Retainer
['Cover', 'Brake Check Valve', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Check Valve
['Cover', 'Brake Pad Wear Indicator', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Pad Wear Indicator
['Cover', 'Switch', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Switch
['Cover', 'Brake Rotor Hub', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Rotor Hub
['Cover', 'Parking Brake Spring', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Parking Brake Spring
['Cover', 'Brake Shoe Stud', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Stud
['Cover', 'Brake Master Cylinder Cap', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Master Cylinder Cap
['Cover', 'STEPChanges', 'Brake Shoe Adjuster Cable Guid', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Adjuster Cable Guid
['Cover', 'Brake Shoe Hold-Down Cup', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Hold-Down Cup
['Cover', 'Caliper Guide Pin', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Caliper Guide Pin
['Cover', 'Drum Brake Bolt', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Drum Brake Bolt
['Cover', 'Parking Brake Hardware Kit', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Parking Brake Hardware Kit
['Cover', 'Wheel Cylinder to Brake Shoe L', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Wheel Cylinder to Brake Shoe L
['Cover', 'Brake Actuating Lever', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Actuating Lever
['Cover', 'Brake Shoe Adjuster Kit', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Adjuster Kit
['Cover', 'Brake Wheel Cylinder Cup', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Wheel Cylinder Cup
['Cover', 'Disc Brake Screw', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Disc Brake Screw
['Cover', 'Bleeder Screw Cap', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Bleeder Screw Cap
['Cover', 'Brake Washer', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Washer
['Cover', 'Brake Wheel Cylinder Retainer ', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Wheel Cylinder Retainer
['Cover', 'Parking Brake Lever Pivot Pin', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Parking Brake Lever Pivot Pin
['Cover', 'Trailer Brake Magnet', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Trailer Brake Magnet
['Cover', 'Wiring Harness', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Wiring Harness
['Cover', 'Brake Wheel Cylinder Boot Kit', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Wheel Cylinder Boot Kit
['Cover', 'Brake Lock System', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Lock System
['Cover', 'Brake Shoe Anchor Pin', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Anchor Pin
['Cover', 'Cabinet', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Cabinet
['Cover', 'Caliper Seal Kit', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Caliper Seal Kit
['Cover', 'Trailer Brake Controller', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Trailer Brake Controller
['Cover', 'Brake Align Gauge', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Align Gauge
['Cover', 'Brake Hose Lock', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Hose Lock
['Cover', 'Brake Proportioning Valve', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Proportioning Valve
['Cover', 'Brake Shoe Anchor Support Brac', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Anchor Support Brac
['Cover', 'Clutch Master Cylinder Repair ', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Clutch Master Cylinder Repair
['Cover', 'Brake Shoe Anchor Spring Lock', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Anchor Spring Lock
['Cover', 'Brake Shoe Spring Kit', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Spring Kit
['Cover', 'Brake Shoe Spring Kit', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Spring Kit
['Cover', 'Brake Shoe Adjuster Screw Kit', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Shoe Adjuster Screw Kit
['Cover', 'Cabinet Base', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Cabinet Base
['Cover', 'STEPChanges', 'Sensor', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Sensor

In [ ]:
df_s

,Filename,part Type,Product ID,* <Name>,Working Column,Supplier Classification Reference,Manufacturer,ASG Vendor Name,<Parent ID>,<Object Type Name>,variable,value
0,C:\Users\vikram.vadhirajan\OneDrive - Trico\Do...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brake Master Cylinder Reservoir (PRODPCC_136_1...,NaN,NaN,NaN
0,C:\Users\vikram.vadhirajan\OneDrive - Trico\Do...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brake Rotor and Hub Assembly (PRODPCC_136_1376...,NaN,NaN,NaN
0,C:\Users\vikram.vadhirajan\OneDrive - Trico\Do...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bleeder Screw (PRODPCC_136_1362_5),NaN,NaN,NaN
0,C:\Users\vikram.vadhirajan\OneDrive - Trico\Do...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brake Shoe Adjuster Lever (PRODPCC_136_1367_80),NaN,NaN,NaN
0,C:\Users\vikram.vadhirajan\OneDrive - Trico\Do...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brake Shoe Adjuster Repair / Service Kit (PROD...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
0,C:\Users\vikram.vadhirajan\OneDrive - Trico\Do...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brake Shoe Spring Kit (PRODPCC_136_1367_260),NaN,NaN,NaN
0,C:\Users\vikram.vadhirajan\OneDrive - Trico\Do...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brake Shoe Spring Kit (PRODPCC_136_1367_260),NaN,NaN,NaN
0,C:\Users\vikram.vadhirajan\OneDrive - Trico\Do...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brake Shoe Adjuster Screw Kit (PRODPCC_136_136...,NaN,NaN,NaN
0,C:\Users\vikram.vadhirajan\OneDrive - Trico\Do...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cabinet Base (PRODPCC_899_8997_20),NaN,NaN,NaN
0,C:\Users\vikram.vadhirajan\OneDrive - Trico\Do...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sensor (PRODPCC_512_5126_8),NaN,NaN,NaN

In [22]:
repl='''C:\\Users\\Vikram.Vadhirajan\\OneDrive - Trico\\Documents - Product Support India Romania\\Catalog\\Score card\\NAPA\\Mandatory\\Input\\'''
IDS=["part Type",'Product ID','*\xa0<Name>', 'Working Column', 'Manufacturer', '<Parent ID>', '<Object Type Name>']

In [23]:
filelink=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Excel--2026-01-13--05-40-2026-01-13_05.47.50.xlsm'    
workbook=openpyxl.load_workbook(filelink)
sheetname=workbook.sheetnames
print(sheetname)
for s in sheetname:
    if (("STEP" not in s) and ("Cover" not in s)):
        print(s)
        df=pd.read_excel(filelink,sheet_name=s, skiprows=9)
        # df["Filename"]=filelink.replace(repl,"")
        df["part Type"]=df['<Parent ID>'].mode()[0].split('''(''')[0]
        df=pd.melt(df,id_vars=IDS,var_name='Attribute').reset_index(drop=True)
        df_s=pd.concat([df_s,df])

['Cover', 'Bleeder Screw', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings', 'Bleeder Screw Cap', 'Bleeder Screw Repair   Service', 'Brake Backing Plate Assembly', 'Brake Kit', 'Brake Caliper', 'Brake Wheel Cylinder Boot Kit', 'Brake Master Cylinder', 'Brake Cylinder Repair   Servic', 'Brake Proportioning Valve', 'Brake Master Cylinder Reservoi', 'Brake Wheel Cylinder', 'Brake Wheel Cylinder Cup', 'Brake Wheel Cylinder Retainer ', 'Disc Brake Backing Plate', 'Caliper Bolt', 'Disc Brake Boot Kit', 'Disc Brake Bushing Kit', 'Caliper Bolt Sleeve', 'Caliper Bracket', 'Caliper Damper Kit', 'Caliper Pin Retainer', 'Caliper Piston', 'Disc Brake Check Valve', 'Disc Brake Clip', 'Caliper Guide Pin', 'Disc Brake Hardware Kit', 'Disc Brake Screw', 'Caliper Seal and Boot Kit', 'Caliper Seal Kit', 'Brake Rotor Shim', 'Caliper Spring', 'Brake Pad Wear Indicator', 'Caliper Bolt Kit', 'Drum Brake Bolt', 'Brake Actuating Lever', 'Brake Shoe Adjuster Cable Guid', 'Brake Shoe Adjuster Cable', 'Brake Backing Plate Hole Cover', 'Brake Shoe Adjuster Kit', 'Brake Shoe Adjuster Lever', 'Brake Shoe Adjuster Repair   S', 'Brake Shoe Adjuster Screw Assy', 'Brake Shoe Anchor Pin', 'Brake Shoe Anchor Spring Lock', 'Brake Shoe Anchor Support Brac', 'Brake Shoe Hold-Down Cup', 'Brake Shoe Hold-Down Kit', 'Brake Shoe Hold-Down Nails', 'Brake Shoe Clip', 'Brake Shoe Hardware Kit', 'Brake Lock System', 'Brake Shoe Adjuster Screw Kit', 'Brake Shoe Spring', 'Brake Shoe Spring Kit', 'Brake Shoe Stud', 'Brake Washer', 'Wheel Cylinder to Brake Shoe L', 'Trailer Brake Clip', 'Trailer Brake Installation Kit', 'Trailer Brake Magnet', 'Trailer Brake Magnet Retainer', 'Trailer Brake Pulse Preventer', 'Trailer Brake Replacement Cabl', 'Brake Pads', 'Brake Shoe Kit', 'Brake Shoes', 'Brake Hose Banjo Bolt', 'Brake Hose', 'Brake Hose Lock', 'Brake Tubing', 'Brake Tubing Kit', 'Parking Brake Cable', 'Parking Brake Cable Connector', 'Parking Brake Cable Kit', 'Parking Brake Hardware Kit', 'Parking Brake Lever Pivot Pin', 'Parking Brake Spring', 'Brake Booster', 'Brake Check Valve', 'Brake Drum', 'Brake Rotor', 'Brake Rotor and Pad Kit', 'Brake Rotor Hub', 'Brake Rotor and Hub Assembly']
Bleeder Screw
Bleeder Screw Cap
Bleeder Screw Repair   Service
Brake Backing Plate Assembly
Brake Kit
Brake Caliper
Brake Wheel Cylinder Boot Kit
Brake Master Cylinder
Brake Cylinder Repair   Servic
Brake Proportioning Valve
Brake Master Cylinder Reservoi
Brake Wheel Cylinder
Brake Wheel Cylinder Cup
Brake Wheel Cylinder Retainer
Disc Brake Backing Plate
Caliper Bolt
Disc Brake Boot Kit
Disc Brake Bushing Kit
Caliper Bolt Sleeve
Caliper Bracket
Caliper Damper Kit
Caliper Pin Retainer
Caliper Piston
Disc Brake Check Valve
Disc Brake Clip
Caliper Guide Pin
Disc Brake Hardware Kit
Disc Brake Screw
Caliper Seal and Boot Kit
Caliper Seal Kit
Brake Rotor Shim
Caliper Spring
Brake Pad Wear Indicator
Caliper Bolt Kit
Drum Brake Bolt
Brake Actuating Lever
Brake Shoe Adjuster Cable Guid
Brake Shoe Adjuster Cable
Brake Shoe Adjuster Kit
Brake Shoe Adjuster Lever
Brake Shoe Adjuster Repair   S
Brake Shoe Adjuster Screw Assy
Brake Shoe Anchor Pin
Brake Shoe Anchor Spring Lock
Brake Shoe Anchor Support Brac
Brake Shoe Hold-Down Cup
Brake Shoe Hold-Down Kit
Brake Shoe Hold-Down Nails
Brake Shoe Clip
Brake Shoe Hardware Kit
Brake Lock System
Brake Shoe Adjuster Screw Kit
Brake Shoe Spring
Brake Shoe Spring Kit
Brake Shoe Stud
Brake Washer
Wheel Cylinder to Brake Shoe L
Trailer Brake Clip
Trailer Brake Installation Kit
Trailer Brake Magnet
Trailer Brake Magnet Retainer
Trailer Brake Pulse Preventer
Trailer Brake Replacement Cabl
Brake Pads
Brake Shoe Kit
Brake Shoes
Brake Hose Banjo Bolt
Brake Hose
Brake Hose Lock
Brake Tubing
Brake Tubing Kit
Parking Brake Cable
Parking Brake Cable Connector
Parking Brake Cable Kit
Parking Brake Hardware Kit
Parking Brake Lever Pivot Pin
Parking Brake Spring
Brake Booster
Brake Check Valve
Brake Drum
Brake Rotor
Brake Rotor and Pad Kit
Brake Rotor Hub
Brake Rotor and Hub Assembly

In [30]:
df_s

,Filename,part Type,Product ID,* <Name>,Working Column,Supplier Classification Reference,Manufacturer,ASG Vendor Name,<Parent ID>,<Object Type Name>,Attribute,value
0,NaN,Bleeder Screw,PRODPCC_136_1362_5•buy_4475171,22069,NaN,NaN,NaN,NaN,Bleeder Screw (PRODPCC_136_1362_5),GPC Buy Item,Head Diameter,NaN
1,NaN,Bleeder Screw,PRODPCC_136_1362_5•buy_4482660,25214,NaN,NaN,NaN,NaN,Bleeder Screw (PRODPCC_136_1362_5),GPC Buy Item,Head Diameter,NaN
2,NaN,Bleeder Screw,PRODPCC_136_1362_5•buy_5278642,11596,NaN,NaN,NaN,NaN,Bleeder Screw (PRODPCC_136_1362_5),GPC Buy Item,Head Diameter,NaN
3,NaN,Bleeder Screw,PRODPCC_136_1362_5•buy_5284250,22068,NaN,NaN,NaN,NaN,Bleeder Screw (PRODPCC_136_1362_5),GPC Buy Item,Head Diameter,NaN
4,NaN,Bleeder Screw,PRODPCC_136_1362_5•buy_5292759,20089,NaN,NaN,NaN,NaN,Bleeder Screw (PRODPCC_136_1362_5),GPC Buy Item,Head Diameter,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
12551,NaN,Brake Rotor and Hub Assembly,PRODPCC_136_1376_16•buy_5341943,86603,NaN,NaN,Brake Parts Inc. Products,NaN,Brake Rotor and Hub Assembly (PRODPCC_136_1376...,GPC Buy Item,UNSPSC Code,25171715
12552,NaN,Brake Rotor and Hub Assembly,PRODPCC_136_1376_16•buy_5341971,86530,NaN,NaN,Brake Parts Inc. Products,NaN,Brake Rotor and Hub Assembly (PRODPCC_136_1376...,GPC Buy Item,UNSPSC Code,25171715
12553,NaN,Brake Rotor and Hub Assembly,PRODPCC_136_1376_16•buy_5342957,RA86465,NaN,NaN,Brake Parts Inc. Products,NaN,Brake Rotor and Hub Assembly (PRODPCC_136_1376...,GPC Buy Item,UNSPSC Code,25171715
12554,NaN,Brake Rotor and Hub Assembly,PRODPCC_136_1376_16•buy_5343844,4886444,NaN,NaN,Brake Parts Inc. Products,NaN,Brake Rotor and Hub Assembly (PRODPCC_136_1376...,GPC Buy Item,UNSPSC Code,25171715
12555,NaN,Brake Rotor and Hub Assembly,PRODPCC_136_1376_16•buy_6302400,RA881778,NaN,NaN,Brake Parts Inc. Products,NaN,Brake Rotor and Hub Assembly (PRODPCC_136_1376...,GPC Buy Item,UNSPSC Code,25171715

In [32]:
df_parttype=df_s[["part Type", '*\xa0<Name>','Attribute', 'value']].drop_duplicates()
df_parttype=df_parttype[df_parttype['Attribute']=="Brand"]
df_parttype

                          part Type  * <Name> Attribute               value
416                  Bleeder Screw      22069     Brand  NAPA Ultra Premium
417                  Bleeder Screw      25214     Brand  NAPA Ultra Premium
418                  Bleeder Screw      11596     Brand  NAPA Ultra Premium
419                  Bleeder Screw      22068     Brand  NAPA Ultra Premium
420                  Bleeder Screw      20089     Brand  NAPA Ultra Premium
...                             ...       ...       ...                 ...
5835  Brake Rotor and Hub Assembly      86603     Brand  NAPA Ultra Premium
5836  Brake Rotor and Hub Assembly      86530     Brand  NAPA Ultra Premium
5837  Brake Rotor and Hub Assembly    RA86465     Brand  NAPA Ultra Premium
5838  Brake Rotor and Hub Assembly    4886444     Brand                NAPA
5839  Brake Rotor and Hub Assembly   RA881778     Brand  NAPA Ultra Premium

[21551 rows x 4 columns]

In [ ]:
for i in range(1,len(file_link)):
    workbook=openpyxl.load_workbook(file_link[i])
    sheetname=workbook.sheetnames
    print(sheetname)
    for s in sheetname:
        if (("STEP" not in s) and ("Cover" not in s)):
            print(s)
            df=pd.read_excel(file_link[i],sheet_name=s, skiprows=9)
            df["Filename"]=file_link[i].replace(repl,"")
            df["part Type"]=df["part Type"]=df['<Parent ID>'].mode()[0].split('''(''')[0]
            df=pd.melt(df,id_vars=IDS).reset_index(drop=True)
            df_s=pd.concat([df_s,df])

['Cover', 'STEPChanges', 'Brake Rotor and Hub Assembly', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings']
Brake Rotor and Hub Assembly

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['Supplier Classification Reference', 'ASG Vendor Name']"

In [10]:
df_s.shape

(1381410, 12)

In [11]:
df_s

,Filename,part Type,Product ID,* <Name>,Working Column,Supplier Classification Reference,Manufacturer,ASG Vendor Name,<Parent ID>,<Object Type Name>,variable,value
0,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,103,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.679 IN
1,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,104,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.679 IN
2,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,3924,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.75 IN
3,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,4092,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.5 IN
4,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,458,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.374 IN
...,...,...,...,...,...,...,...,...,...,...,...,...
34,RevisedFromNAPA\NAPA TRICO Updated Mandatory S...,Promotional Item,PRODPCC_899_8996_5•buy_147411528,3CASEREBATE,NaN,supplier_3765Products,NaN,NaN,Promotional Item (PRODPCC_899_8996_5),GPC Buy Item,SDS Required,No (135233618)
35,RevisedFromNAPA\NAPA TRICO Updated Mandatory S...,Promotional Item,PRODPCC_899_8996_5•buy_138961471,SAFECOMBO,NaN,supplier_3765Products,NaN,NaN,Promotional Item (PRODPCC_899_8996_5),GPC Buy Item,SDS Required,No (135233618)
36,RevisedFromNAPA\NAPA TRICO Updated Mandatory S...,Promotional Item,STIBO_SMARTSHEET_TEMPLATE_PRODUCT,SAMPLE123,NaN,supplier_211539362Products,NAPA,NaN,PRODPCC_899_8999_30,GPC Buy Item,Weight,5.75 lbs
37,RevisedFromNAPA\NAPA TRICO Updated Mandatory S...,Promotional Item,PRODPCC_899_8996_5•buy_147411528,3CASEREBATE,NaN,supplier_3765Products,NaN,NaN,Promotional Item (PRODPCC_899_8996_5),GPC Buy Item,Weight,NaN
38,RevisedFromNAPA\NAPA TRICO Updated Mandatory S...,Promotional Item,PRODPCC_899_8996_5•buy_138961471,SAFECOMBO,NaN,supplier_3765Products,NaN,NaN,Promotional Item (PRODPCC_899_8996_5),GPC Buy Item,Weight,NaN

In [12]:
df_s=df_s[df_s['*\xa0<Name>']!="SAMPLE123"]

In [13]:
df_s['Brand']=df_s['Filename']
repllist={'Autolite - Smart Sheet 11.1.24.xlsm': "Autolite",'NAPA BPI Smartsheet Export 2024-10-22.xlsm': "BPI",'NAPA TRICO Smartsheet Export 2024-10-22.xlsm': "TRICO"}

df_s['Brand'] = df_s['Brand'].replace(repllist, regex=True)

In [42]:
df_s['Key']=df_s.Brand+df_s['part Type']+df_s['variable']

In [43]:
df_s=df_s.reset_index(drop=True)

In [44]:
df_untouched=df_s

In [45]:
df_untouched.shape

(744461, 14)

In [46]:
df_s=df_untouched[df_untouched['Key']!="BPIBrake HosePosition ☰      "]

In [47]:
df_s=df_s[~df_s.Key.str.contains(".1")]

In [48]:
df_s

,Filename,part Type,Product ID,* <Name>,Working Column,Supplier Classification Reference,Manufacturer,ASG Vendor Name,<Parent ID>,<Object Type Name>,variable,value,Brand,Key
0,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,103,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.679 IN,Autolite,AutoliteSpark PlugSpark Plug Reach
1,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,104,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.679 IN,Autolite,AutoliteSpark PlugSpark Plug Reach
2,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,3924,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.75 IN,Autolite,AutoliteSpark PlugSpark Plug Reach
3,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,4092,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.5 IN,Autolite,AutoliteSpark PlugSpark Plug Reach
4,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,458,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.374 IN,Autolite,AutoliteSpark PlugSpark Plug Reach
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744456,NAPA TRICO Smartsheet Export 2024-10-22.xlsm,Promotional Item,PRODPCC_899_8996_5•buy_138961471,SAFECOMBO,NaN,supplier_3765Products,NaN,NaN,Promotional Item (PRODPCC_899_8996_5),GPC Buy Item,VMRS Code,NaN,TRICO,TRICOPromotional ItemVMRS Code
744457,NAPA TRICO Smartsheet Export 2024-10-22.xlsm,Promotional Item,PRODPCC_899_8996_5•buy_147411528,3CASEREBATE,NaN,supplier_3765Products,NaN,NaN,Promotional Item (PRODPCC_899_8996_5),GPC Buy Item,SDS Required,No (135233618),TRICO,TRICOPromotional ItemSDS Required
744458,NAPA TRICO Smartsheet Export 2024-10-22.xlsm,Promotional Item,PRODPCC_899_8996_5•buy_138961471,SAFECOMBO,NaN,supplier_3765Products,NaN,NaN,Promotional Item (PRODPCC_899_8996_5),GPC Buy Item,SDS Required,No (135233618),TRICO,TRICOPromotional ItemSDS Required
744459,NAPA TRICO Smartsheet Export 2024-10-22.xlsm,Promotional Item,PRODPCC_899_8996_5•buy_147411528,3CASEREBATE,NaN,supplier_3765Products,NaN,NaN,Promotional Item (PRODPCC_899_8996_5),GPC Buy Item,Weight,NaN,TRICO,TRICOPromotional ItemWeight
744460,NAPA TRICO Smartsheet Export 2024-10-22.xlsm,Promotional Item,PRODPCC_899_8996_5•buy_138961471,SAFECOMBO,NaN,supplier_3765Products,NaN,NaN,Promotional Item (PRODPCC_899_8996_5),GPC Buy Item,Weight,NaN,TRICO,TRICOPromotional ItemWeight

In [49]:
df_s=df_s.reset_index(drop=True)

In [50]:
for i in range (len(df_s)):
    s=df_s['Key'][i]
    clean = re.sub(r'[^a-zA-Z0-9]', '', s)
    df_s.loc[i,'Key']=clean

In [51]:
df_s['Filename'][1]

'Autolite - Smart Sheet 11.1.24.xlsm'

In [52]:
df_s.head()

,Filename,part Type,Product ID,* <Name>,Working Column,Supplier Classification Reference,Manufacturer,ASG Vendor Name,<Parent ID>,<Object Type Name>,variable,value,Brand,Key
0,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,103,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.679 IN,Autolite,AutoliteSparkPlugSparkPlugReach
1,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,104,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.679 IN,Autolite,AutoliteSparkPlugSparkPlugReach
2,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,3924,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.75 IN,Autolite,AutoliteSparkPlugSparkPlugReach
3,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,4092,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.5 IN,Autolite,AutoliteSparkPlugSparkPlugReach
4,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,458,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.374 IN,Autolite,AutoliteSparkPlugSparkPlugReach

In [53]:
df_s.shape

(708044, 14)

In [54]:
df_attribute=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\NAPA\Mandatory\Reference\Mandatory_Attributes.xlsx",skiprows=2)

In [55]:
for i in range (len(df_attribute)):
    s=df_attribute['Key'][i]
    clean = re.sub(r'[^a-zA-Z0-9]', '', s)
    df_attribute.loc[i,'Key']=clean

In [56]:
df_attribute['Key'].value_counts()

Key
BPIBrakeCaliperWeight                   1
BPIHoseWeight                           1
BPIBleederScrewWeight                   1
BPIBleederScrewCapWeight                1
BPIBleederScrewRepairServiceWeight      1
                                       ..
BPICaliperBoltWeight                    1
BPIBrakeWheelCylinderRetainerWeight     1
BPIBrakeWheelCylinderCupWeight          1
BPIBrakeWheelCylinderWeight             1
BPIBrakeMasterCylinderReservoiWeight    1
Name: count, Length: 2873, dtype: int64

In [57]:
df_final=pd.merge(df_s,df_attribute[['Key','Required']], on='Key', how='left')
df_final.head()

,Filename,part Type,Product ID,* <Name>,Working Column,Supplier Classification Reference,Manufacturer,ASG Vendor Name,<Parent ID>,<Object Type Name>,variable,value,Brand,Key,Required
0,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,103,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.679 IN,Autolite,AutoliteSparkPlugSparkPlugReach,1.0
1,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,104,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.679 IN,Autolite,AutoliteSparkPlugSparkPlugReach,1.0
2,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,3924,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.75 IN,Autolite,AutoliteSparkPlugSparkPlugReach,1.0
3,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,4092,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.5 IN,Autolite,AutoliteSparkPlugSparkPlugReach,1.0
4,Autolite - Smart Sheet 11.1.24.xlsm,Spark Plug,NaN,458,NaN,NaN,NaN,NaN,Spark Plug (PRODPCC_512_5121_250),GPC Buy Item,Spark Plug Reach,0.374 IN,Autolite,AutoliteSparkPlugSparkPlugReach,1.0

In [58]:
df_final.shape

(708044, 15)

In [59]:
df_final['Key'].value_counts()

Key
BPIBrakeHoseEnd2Diameter                4090
BPIBrakeHoseMaterial                    4090
BPIBrakeHoseManufacturerPartNumber      4090
BPIBrakeHoseHoseInnerDiameter           4090
BPIBrakeHoseHoseEndFittingType2         4090
                                        ...
BPICaliperGuidePinOutsideDiameter          1
BPICaliperGuidePinInsideDiameter           1
TRICOWindshieldWasherPumpSDSRequired       1
TRICOWindshieldWasherPumpVMRSCode          1
TRICOWindshieldWasherPumpPackaging         1
Name: count, Length: 2846, dtype: int64

In [60]:
df_final.columns

Index(['Filename', 'part Type', 'Product ID', '* <Name>', 'Working Column',
       'Supplier Classification Reference', 'Manufacturer', 'ASG Vendor Name',
       '<Parent ID>', '<Object Type Name>', 'variable', 'value', 'Brand',
       'Key', 'Required'],
      dtype='object')

In [61]:
df_List=df_final[[ 'part Type', 'Product ID', '*\xa0<Name>',  '<Parent ID>', 'variable', 'value', 'Brand','Required']]

In [62]:
df_List=df_List.rename(columns={'part Type': "Part Type", '*\xa0<Name>': "SKU",  'variable': "Attribute", 'value':"Value"})

In [63]:
df_List[['Brand','Part Type', 'SKU','Product ID',  '<Parent ID>',  'Required','Attribute', 'Value']]

,Brand,Part Type,SKU,Product ID,<Parent ID>,Required,Attribute,Value
0,Autolite,Spark Plug,103,NaN,Spark Plug (PRODPCC_512_5121_250),1.0,Spark Plug Reach,0.679 IN
1,Autolite,Spark Plug,104,NaN,Spark Plug (PRODPCC_512_5121_250),1.0,Spark Plug Reach,0.679 IN
2,Autolite,Spark Plug,3924,NaN,Spark Plug (PRODPCC_512_5121_250),1.0,Spark Plug Reach,0.75 IN
3,Autolite,Spark Plug,4092,NaN,Spark Plug (PRODPCC_512_5121_250),1.0,Spark Plug Reach,0.5 IN
4,Autolite,Spark Plug,458,NaN,Spark Plug (PRODPCC_512_5121_250),1.0,Spark Plug Reach,0.374 IN
...,...,...,...,...,...,...,...,...
708039,TRICO,Promotional Item,SAFECOMBO,PRODPCC_899_8996_5•buy_138961471,Promotional Item (PRODPCC_899_8996_5),1.0,VMRS Code,NaN
708040,TRICO,Promotional Item,3CASEREBATE,PRODPCC_899_8996_5•buy_147411528,Promotional Item (PRODPCC_899_8996_5),1.0,SDS Required,No (135233618)
708041,TRICO,Promotional Item,SAFECOMBO,PRODPCC_899_8996_5•buy_138961471,Promotional Item (PRODPCC_899_8996_5),1.0,SDS Required,No (135233618)
708042,TRICO,Promotional Item,3CASEREBATE,PRODPCC_899_8996_5•buy_147411528,Promotional Item (PRODPCC_899_8996_5),0.0,Weight,NaN
708043,TRICO,Promotional Item,SAFECOMBO,PRODPCC_899_8996_5•buy_138961471,Promotional Item (PRODPCC_899_8996_5),0.0,Weight,NaN

In [ ]:
# for i in range(len(df_List)):
#     s=df_List["Values"][i]
#     if s is np.nan:
#         df_List.loc[i,'Values']=0
#     else:
#         df_List.loc[i,'Values']=1

In [318]:
#df_List=df_List.dropna()

In [ ]:
#df_List=df_List[df_List["Required"]=="Mandatory"]

In [64]:
df_List.shape

(708044, 8)

In [65]:
df_List=df_List[['Brand','Part Type', 'SKU','Product ID',  '<Parent ID>',  'Required','Attribute', 'Value']]

In [66]:
with pd.ExcelWriter(OFolder+'\\'+'NAPA_Mandatory_Baseline_updated.xlsx') as writer:  # doctest: +SKIP
    df_List.to_excel(writer,index=False, sheet_name='Raw')