In [4]:
import os
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
import re
import openpyxl
import numpy as np

In [5]:
folder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files\PDM\excel Files'
OFolder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files'

In [6]:
file_list=[]
for (root, dirs, file) in os.walk(folder):
    for f in file:
        if ('.xlsx') in f:

                    file_list.append(f)
file_list

['EXCEL_SEGMENTS_FULL_BBDW_ASC_20250206_121416.xlsx',
 'EXCEL_SEGMENTS_FULL_BBFX_Balkamp_20250206_122139.xlsx',
 'EXCEL_SEGMENTS_FULL_BBRH_Motorcraft_20250206_123343.xlsx',
 'EXCEL_SEGMENTS_FULL_BBRQ_Autolite_20250206_121627.xlsx',
 'EXCEL_SEGMENTS_FULL_BBZN_Strong Arm_20250206_123643.xlsx',
 'EXCEL_SEGMENTS_FULL_BCQS_Carter_20250206_123158.xlsx',
 'EXCEL_SEGMENTS_FULL_BCVC_ACDelco_20250206_121147.xlsx',
 'EXCEL_SEGMENTS_FULL_BCVC_ACDelco_20250206_121227.xlsx',
 'EXCEL_SEGMENTS_FULL_BCVC_ACDelco_20250206_121239.xlsx',
 'EXCEL_SEGMENTS_FULL_CFHH_Duralast_20250206_122312.xlsx',
 'EXCEL_SEGMENTS_FULL_CFHH_Duralast_20250206_133239.xlsx',
 'EXCEL_SEGMENTS_FULL_CNHS_Magneti Marelli_20250206_133336.xlsx',
 'EXCEL_SEGMENTS_FULL_CNRD_CARDONE New_20250206_134027.xlsx',
 'EXCEL_SEGMENTS_FULL_CPCX_CARDONE Reman_20250206_130618.xlsx',
 'EXCEL_SEGMENTS_FULL_FLJL_Champ filters_20250206_133244.xlsx',
 'EXCEL_SEGMENTS_FULL_FNTH_Mighty Lift_20250206_123435.xlsx',
 'EXCEL_SEGMENTS_FULL_FXLT_Carquest Premium Water Pumps_20250206_122953.xlsx',
 'EXCEL_SEGMENTS_FULL_FXNK_Carquest Premium Fuel Pumps_20250206_122946.xlsx',
 'EXCEL_SEGMENTS_FULL_FXPS_CARDONE Ultra_20250206_122810.xlsx',
 'EXCEL_SEGMENTS_FULL_GFDR_NAPA Fuel Pumps_20250206_123514.xlsx',
 'EXCEL_SEGMENTS_FULL_GQWK_Import Direct Fuel Pumps_20250206_123238.xlsx',
 'EXCEL_SEGMENTS_FULL_GQWM_Import Direct Timing Kits and Water Pumps_20250206_123245.xlsx',
 'EXCEL_SEGMENTS_FULL_GQWN_Import Direct Water Pumps_20250206_123310.xlsx',
 'EXCEL_SEGMENTS_FULL_GQXB_MasterPro Fuel Pumps_20250206_123249.xlsx',
 'EXCEL_SEGMENTS_FULL_HFVZ_Autolite Iridium XP_20250206_121746.xlsx',
 'EXCEL_SEGMENTS_FULL_HNTB_Driveworks Water Pumps_20250206_123142.xlsx',
 'EXCEL_SEGMENTS_FULL_HTTT_TruGrade_20250206_123803.xlsx',
 'EXCEL_SEGMENTS_FULL_HWMS_AVM Industries_20250206_122117.xlsx',
 'EXCEL_SEGMENTS_FULL_HXLR_Autolite Ignition - Archived_20250206_121709.xlsx',
 'EXCEL_SEGMENTS_FULL_HXLS_Autolite Copper_20250206_121408.xlsx',
 'EXCEL_SEGMENTS_FULL_HXLT_Autolite Double Platinum_20250206_121425.xlsx',
 'EXCEL_SEGMENTS_FULL_HXLV_Autolite Glow Plugs_20250206_121446.xlsx',
 'EXCEL_SEGMENTS_FULL_HXLW_Autolite Platinum_20250206_121831.xlsx',
 'EXCEL_SEGMENTS_FULL_HXLX_Autolite Racing_20250206_121915.xlsx',
 'EXCEL_SEGMENTS_FULL_HXLY_Autolite Xtreme Sport_20250206_121939.xlsx',
 'EXCEL_SEGMENTS_FULL_HXLZ_Autolite Xtreme Start_20250206_122000.xlsx',
 'EXCEL_SEGMENTS_FULL_HXMB_Autolite Iridium Ultra_20250206_132943.xlsx',
 'EXCEL_SEGMENTS_FULL_HXTZ_Michelin Engine Parts_20250206_123327.xlsx',
 'EXCEL_SEGMENTS_FULL_HYJT_Carter Water Pumps_20250206_123132.xlsx',
 'EXCEL_SEGMENTS_FULL_HYTZ_Carter Premium Water Pumps_20250206_123028.xlsx',
 'EXCEL_SEGMENTS_FULL_HYVJ_Airtex Fuel Pumps_20250206_121429.xlsx',
 'EXCEL_SEGMENTS_FULL_OE05_MOTOR OE_20250206_124034.xlsx',
 'EXCEL_SEGMENTS_FULL_T00718_Mex Mighty Lift_20250206_123332.xlsx',
 'EXCEL_SEGMENTS_FULL_T02616_Base Spark Plugs_20250206_122130.xlsx',
 'EXCEL_SEGMENTS_FULL_T02624_Cardone OReilly_20250206_131628.xlsx',
 'EXCEL_SEGMENTS_FULL_T02667_Cardone Advance_20250206_125331.xlsx',
 'EXCEL_SEGMENTS_FULL_T02668_Cardone AutoZone_20250206_140141.xlsx',
 'EXCEL_SEGMENTS_FULL_T02669_Cardone GM_AC Delco_20250206_123018.xlsx',
 'EXCEL_SEGMENTS_FULL_T02670_Cardone Goodyear_20250206_122418.xlsx',
 'EXCEL_SEGMENTS_FULL_T02723_Cardone Carquest_20250206_122245.xlsx',
 'EXCEL_SEGMENTS_FULL_T02812_Cardone NAPA US_20250206_125426.xlsx',
 'EXCEL_SEGMENTS_FULL_T02813_Cardone NAPA Canada_20250206_125547.xlsx',
 'EXCEL_SEGMENTS_FULL_T02960_Autolite Othermotive_20250206_121810.xlsx',
 'EXCEL_SEGMENTS_FULL_T083_MEX Autolite_20250206_133446.xlsx']

In [7]:
file_link=[]

for i in range(len(file_list)):
     for r,d,f in os.walk(folder):
          for files in f:
               if files == file_list[i]:
                    file_link.append(os.path.join(r,files))

In [8]:
len(file_link)

54

In [9]:
file_link[1]

'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\Documents - Product Support India Romania\\Catalog\\Score card\\Standard\\Import files\\PDM\\excel Files\\EXCEL_SEGMENTS_FULL_BBFX_Balkamp_20250206_122139.xlsx'

In [22]:
cols=['Brand','PartType', 'Attribute', 'AttributeUom','AttributeUomDescription','AttributeUomLabel']
df_s = pd.DataFrame(columns=cols)

In [23]:
file_link[1].split("FULL_")[1].split("_20")[0]

'BBFX_Balkamp'

In [ ]:
for i in range(len(file_link)):
    # workbook=openpyxl.load_workbook(file_link[i])
    BrandName= file_link[i].split("FULL_")[1].split("_20")[0]
    print(i,BrandName)
    df_item=pd.read_excel(file_link[i],sheet_name="Items")
    df_Attr=pd.read_excel(file_link[i],sheet_name="PartAttributes")
    df_item=df_item.astype(str)
    df_Attr=df_Attr.astype(str)
    df=df_Attr.merge(df_item,how="inner")
    ListColumns=['Brand','PartType', 'Attribute', 'AttributeUom','AttributeUomDescription','AttributeUomLabel']
    df=df[ListColumns]
    df=df.drop_duplicates().reset_index(drop=True)
    df['BrandName']=BrandName
    df_s=pd.concat([df_s,df])

0 BBDW_ASC
1 BBFX_Balkamp
2 BBRH_Motorcraft
3 BBRQ_Autolite
4 BBZN_Strong Arm
5 BCQS_Carter
6 BCVC_ACDelco
7 BCVC_ACDelco
8 BCVC_ACDelco
9 CFHH_Duralast
10 CFHH_Duralast
11 CNHS_Magneti Marelli
12 CNRD_CARDONE New
13 CPCX_CARDONE Reman
14 FLJL_Champ filters
15 FNTH_Mighty Lift
16 FXLT_Carquest Premium Water Pumps
17 FXNK_Carquest Premium Fuel Pumps
18 FXPS_CARDONE Ultra
19 GFDR_NAPA Fuel Pumps
20 GQWK_Import Direct Fuel Pumps
21 GQWM_Import Direct Timing Kits and Water Pumps
22 GQWN_Import Direct Water Pumps
23 GQXB_MasterPro Fuel Pumps
24 HFVZ_Autolite Iridium XP
25 HNTB_Driveworks Water Pumps
26 HTTT_TruGrade
27 HWMS_AVM Industries
28 HXLR_Autolite Ignition - Archived
29 HXLS_Autolite Copper
30 HXLT_Autolite Double Platinum
31 HXLV_Autolite Glow Plugs
32 HXLW_Autolite Platinum
33 HXLX_Autolite Racing
34 HXLY_Autolite Xtreme Sport
35 HXLZ_Autolite Xtreme Start
36 HXMB_Autolite Iridium Ultra
37 HXTZ_Michelin Engine Parts
38 HYJT_Carter Water Pumps
39 HYTZ_Carter Premium Water Pumps
40 HYVJ_Airtex Fuel Pumps
41 OE05_MOTOR OE
42 T00718_Mex Mighty Lift
43 T02616_Base Spark Plugs
44 T02624_Cardone OReilly
45 T02667_Cardone Advance
46 T02668_Cardone AutoZone
47 T02669_Cardone GM_AC Delco
48 T02670_Cardone Goodyear
49 T02723_Cardone Carquest
50 T02812_Cardone NAPA US
51 T02813_Cardone NAPA Canada
52 T02960_Autolite Othermotive
53 T083_MEX Autolite

In [24]:
for i in range(len(file_link)):
    # workbook=openpyxl.load_workbook(file_link[i])
    BrandName= file_link[i].split("FULL_")[1].split("_20")[0]
    print(i,BrandName)
    df_item=pd.read_excel(file_link[i],sheet_name="Items")
    df_Attr=pd.read_excel(file_link[i],sheet_name="PartAttributes")
    df_item=df_item.astype(str)[['PartNumber','PartType']]
    df_Attr=df_Attr.astype(str)
    df=df_Attr.merge(df_item,how="inner")
    # ListColumns=['Brand','PartType', 'Attribute', 'AttributeUom','AttributeUomDescription','AttributeUomLabel']
    # df=df[ListColumns]
    df=df.drop_duplicates().reset_index(drop=True)
    df['BrandName']=BrandName
    df_s=pd.concat([df_s,df])

0 BBDW_ASC
1 BBFX_Balkamp
2 BBRH_Motorcraft
3 BBRQ_Autolite
4 BBZN_Strong Arm
5 BCQS_Carter
6 BCVC_ACDelco
7 BCVC_ACDelco
8 BCVC_ACDelco
9 CFHH_Duralast
10 CFHH_Duralast
11 CNHS_Magneti Marelli
12 CNRD_CARDONE New
13 CPCX_CARDONE Reman
14 FLJL_Champ filters
15 FNTH_Mighty Lift
16 FXLT_Carquest Premium Water Pumps
17 FXNK_Carquest Premium Fuel Pumps
18 FXPS_CARDONE Ultra
19 GFDR_NAPA Fuel Pumps
20 GQWK_Import Direct Fuel Pumps
21 GQWM_Import Direct Timing Kits and Water Pumps
22 GQWN_Import Direct Water Pumps
23 GQXB_MasterPro Fuel Pumps
24 HFVZ_Autolite Iridium XP
25 HNTB_Driveworks Water Pumps
26 HTTT_TruGrade
27 HWMS_AVM Industries
28 HXLR_Autolite Ignition - Archived
29 HXLS_Autolite Copper
30 HXLT_Autolite Double Platinum
31 HXLV_Autolite Glow Plugs
32 HXLW_Autolite Platinum
33 HXLX_Autolite Racing
34 HXLY_Autolite Xtreme Sport
35 HXLZ_Autolite Xtreme Start
36 HXMB_Autolite Iridium Ultra
37 HXTZ_Michelin Engine Parts
38 HYJT_Carter Water Pumps
39 HYTZ_Carter Premium Water Pumps
40 HYVJ_Airtex Fuel Pumps
41 OE05_MOTOR OE
42 T00718_Mex Mighty Lift
43 T02616_Base Spark Plugs
44 T02624_Cardone OReilly
45 T02667_Cardone Advance
46 T02668_Cardone AutoZone
47 T02669_Cardone GM_AC Delco
48 T02670_Cardone Goodyear
49 T02723_Cardone Carquest
50 T02812_Cardone NAPA US
51 T02813_Cardone NAPA Canada
52 T02960_Autolite Othermotive
53 T083_MEX Autolite

In [25]:
df_s=df_s[[ 'BrandName', 'PartType', 'Attribute',  'AttributeUomLabel', 'PartNumber',
       'AttributeValue']]

In [26]:
df_s

,BrandName,PartType,Attribute,AttributeUomLabel,PartNumber,AttributeValue
0,BBDW_ASC,Engine Water Pump,Fan Clutch Included,nan,WP-1000,No
1,BBDW_ASC,Engine Water Pump,Housing Material,nan,WP-1000,Cast Iron
2,BBDW_ASC,Engine Water Pump,Hub Height,MM,WP-1000,113.03
3,BBDW_ASC,Engine Water Pump,Hub Hole Quantity,nan,WP-1000,4
4,BBDW_ASC,Engine Water Pump,Hub Hole Thread Size,nan,WP-1000,M6X1.00
...,...,...,...,...,...,...
6901,T083_MEX Autolite,Windshield Wiper Blade,SMALL ENGINE,nan,UR-8,N
6902,T083_MEX Autolite,Windshield Wiper Blade,SNOWMOBILE,nan,UR-8,N
6903,T083_MEX Autolite,Windshield Wiper Blade,TRANSMISSION SPECIFIC,nan,UR-8,N
6904,T083_MEX Autolite,Windshield Wiper Blade,Design,nan,UR-8,For heavy rains
6905,T083_MEX Autolite,Windshield Wiper Blade,Frame Type,nan,UR-8,Beam

In [33]:
df_s=df_s.reset_index(drop=True)
df_s.rename(columns={"PartType": "Part Terminology Name",
"Attribute": "Part Attribute Name",
"AttributeUom": "UOM Codes",
"AttributeUomDescription": "UOM Description",
"AttributeUomLabel": "UOMLabel"
}, inplace=True);

In [34]:
df_s['UOMLabel']=df_s['UOMLabel'].str.lower()

In [35]:
df_s

,Brand,Part Terminology Name,Part Attribute Name,UOM Codes,UOM Description,UOMLabel,PartNumber,AttributeValue,BrandName
0,BBDW,Engine Water Pump,Fan Clutch Included,nan,nan,nan,WP-1000,No,BBDW_ASC
1,BBDW,Engine Water Pump,Housing Material,nan,nan,nan,WP-1000,Cast Iron,BBDW_ASC
2,BBDW,Engine Water Pump,Hub Height,MM,Millimeter,mm,WP-1000,113.03,BBDW_ASC
3,BBDW,Engine Water Pump,Hub Hole Quantity,nan,nan,nan,WP-1000,4,BBDW_ASC
4,BBDW,Engine Water Pump,Hub Hole Thread Size,nan,nan,nan,WP-1000,M6X1.00,BBDW_ASC
...,...,...,...,...,...,...,...,...,...
52154,BBRQ,Spark Plug,Resistor Type,nan,nan,nan,XS5723DP,Yes,BBRQ_Autolite
52155,BBRQ,Spark Plug,Seat Type,nan,nan,nan,XS5723DP,Flat,BBRQ_Autolite
52156,BBRQ,Spark Plug,Skirt,nan,nan,nan,XS5723DP,Yes,BBRQ_Autolite
52157,BBRQ,Spark Plug,Thread Diameter,MM,Millimeter,mm,XS5723DP,10,BBRQ_Autolite
52158,BBRQ,Spark Plug,Washer Included,nan,nan,nan,XS5723DP,Yes,BBRQ_Autolite

In [23]:
with pd.ExcelWriter(OFolder+'\\'+'FBG_Attribute_List.xlsx') as writer:  # doctest: +SKIP
    df_s.to_excel(writer,index=False, sheet_name='FBG_PDM_Data')