In [1]:
import pandas as pd
import datetime
import warnings
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

In [2]:
file=input ("Please paste the File path").replace('"',"")

In [3]:
df=pd.read_excel(file)
df.head()

,Source,SourceName,Name,Product,Current Price,List Price,Rating,No of Ratings,Short_Details,Details,...,Brand,Manufacturer,FirstAvailableDate,ReviewSummary,Sentiment,Material,ASIN,Links,Part Number,UPC Code
0,Amazon,AmazonProductDetails_Washer Fluid Reservoir.xlsx,ACDelco GM Original Equipment 25979368 Windshi...,Washer Fluid Reservoir,NaN,31.80,4.8,41.0,Exterior Finish Painted\nBrand ACDelco\nItem W...,About this item\nPumps fluid from washer fluid...,...,ACDelco,ACDelco,"December 24, 2013",NaN,NaN,NaN,B00HI02OKO,https://www.amazon.com/dp/B00HI02OKO,25979368,NaN
1,Amazon,AmazonProductDetails_Washer Fluid Reservoir.xlsx,JEPFHYKE Windshield Washer Fluid Reservoir Tan...,Washer Fluid Reservoir,60.41,60.41,0.0,0.0,NaN,Fitment:Please check Amazon Fitment Filter and...,...,JEPFHYKE,JEPFHYKE,"May 8, 2023",NaN,[],NaN,B0C4L5M43C,https://www.amazon.com/dp/B0C4L5M43C,HLHA86007-2218690072_2218690208_2,NaN
2,Amazon,AmazonProductDetails_Washer Fluid Reservoir.xlsx,DTREEL Compatible with Convertible Windshield ...,Washer Fluid Reservoir,98.26,98.26,0.0,0.0,NaN,Fitment:Please check Amazon Fitment Filter and...,...,DTREEL,DTREEL,"October 11, 2023",NaN,[],NaN,B0CKVD4HXW,https://www.amazon.com/dp/B0CKVD4HXW,RCWA80189-HT22063426,NaN
3,Amazon,AmazonProductDetails_Washer Fluid Reservoir.xlsx,Dorman 603-187 Front Washer Fluid Reservoir fo...,Washer Fluid Reservoir,108.00,119.99,3.2,5.0,Brand Dorman\nFit Type Vehicle Specific\nItem ...,About this item\nDirect replacement - this win...,...,Dorman,DormanProducts,"October 29, 2014",NaN,[],NaN,B00OZVOJDO,https://www.amazon.com/dp/B00OZVOJDO,603-187,NaN
4,Amazon,AmazonProductDetails_Washer Fluid Reservoir.xlsx,Dorman - 603-025 - WINDSHIELD WASHER FLUID RES...,Washer Fluid Reservoir,NaN,14.60,4.0,1.0,NaN,NaN,...,Dorman,NaN,"September 25, 2013",NaN,[],NaN,B0BF4QPLZ5,https://www.amazon.com/dp/B0BF4QPLZ5,603-025,NaN

In [4]:
df['Name_Clean']=df['Name'].str.lower().str.replace("compatible with","").str.replace('w/',"with ")
for i in range(len(df)):


    if 'cap'in df['Name_Clean'][i] and 'with' in df['Name_Clean'][i]:
            df.loc[i,'Product']="Washer Fluid Reservoir With Cap"
    elif 'grommet'in df['Name_Clean'][i] and 'with' in df['Name_Clean'][i]:
        df.loc[i,'Product']="Washer Fluid Reservoir With Grommet"
    elif 'hose'in df['Name_Clean'][i] and 'with' in df['Name_Clean'][i]:
        df.loc[i,'Product']="Washer Fluid Reservoir With Hose"
    elif 'cap 'in df['Name_Clean'][i] and 'with' not in df['Name_Clean'][i]:
        df.loc[i,'Product']="Cap"
    elif 'grommet' in df['Name_Clean'][i]:
        df.loc[i,"Product"]='Grommet'
    elif 'hose'in df['Name_Clean'][i] and 'with' not in df['Name_Clean'][i]:
        df.loc[i,'Product']="Hose"
    elif 'pump'in df['Name_Clean'][i] and ('tank' not in df['Name_Clean'][i] or 'reservoir' not in df['Name_Clean'][i]) :
        df.loc[i,'Product']="Washer Pump"
    elif "washer " in df['Name_Clean'][i] and "reservoir" in df['Name_Clean'][i]:
        df.loc[i,'Product']="Washer Fluid Reservoir"
    else:
        df.loc[i,'Product']="Other Product"


del df['Name_Clean']

In [6]:
df['Product'].value_counts()

Washer Fluid Reservoir              1596
Washer Pump                          395
Other Product                        252
Cap                                  211
Washer Fluid Reservoir With Cap      182
Hose                                  15
Grommet                               10
Washer Fluid Reservoir With Hose       4
Name: Product, dtype: int64

In [7]:
df.head()

,Source,SourceName,Name,Product,Current Price,List Price,Rating,No of Ratings,Short_Details,Details,...,Brand,Manufacturer,FirstAvailableDate,ReviewSummary,Sentiment,Material,ASIN,Links,Part Number,UPC Code
0,Amazon,AmazonProductDetails_Washer Fluid Reservoir.xlsx,ACDelco GM Original Equipment 25979368 Windshi...,Washer Pump,NaN,31.80,4.8,41.0,Exterior Finish Painted\nBrand ACDelco\nItem W...,About this item\nPumps fluid from washer fluid...,...,ACDelco,ACDelco,"December 24, 2013",NaN,NaN,NaN,B00HI02OKO,https://www.amazon.com/dp/B00HI02OKO,25979368,NaN
1,Amazon,AmazonProductDetails_Washer Fluid Reservoir.xlsx,JEPFHYKE Windshield Washer Fluid Reservoir Tan...,Washer Fluid Reservoir,60.41,60.41,0.0,0.0,NaN,Fitment:Please check Amazon Fitment Filter and...,...,JEPFHYKE,JEPFHYKE,"May 8, 2023",NaN,[],NaN,B0C4L5M43C,https://www.amazon.com/dp/B0C4L5M43C,HLHA86007-2218690072_2218690208_2,NaN
2,Amazon,AmazonProductDetails_Washer Fluid Reservoir.xlsx,DTREEL Compatible with Convertible Windshield ...,Washer Fluid Reservoir,98.26,98.26,0.0,0.0,NaN,Fitment:Please check Amazon Fitment Filter and...,...,DTREEL,DTREEL,"October 11, 2023",NaN,[],NaN,B0CKVD4HXW,https://www.amazon.com/dp/B0CKVD4HXW,RCWA80189-HT22063426,NaN
3,Amazon,AmazonProductDetails_Washer Fluid Reservoir.xlsx,Dorman 603-187 Front Washer Fluid Reservoir fo...,Washer Fluid Reservoir,108.00,119.99,3.2,5.0,Brand Dorman\nFit Type Vehicle Specific\nItem ...,About this item\nDirect replacement - this win...,...,Dorman,DormanProducts,"October 29, 2014",NaN,[],NaN,B00OZVOJDO,https://www.amazon.com/dp/B00OZVOJDO,603-187,NaN
4,Amazon,AmazonProductDetails_Washer Fluid Reservoir.xlsx,Dorman - 603-025 - WINDSHIELD WASHER FLUID RES...,Washer Fluid Reservoir,NaN,14.60,4.0,1.0,NaN,NaN,...,Dorman,NaN,"September 25, 2013",NaN,[],NaN,B0BF4QPLZ5,https://www.amazon.com/dp/B0BF4QPLZ5,603-025,NaN

In [8]:
with pd.ExcelWriter(file) as writer:  # doctest: +SKIP
    df.to_excel(writer,index=False, sheet_name='Raw')