In [1]:
import pandas as pd

In [2]:
NAPA=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\02_Warranty_Analysis\Warrantly Analysis\Customer Data\NAPA\NAPA Warranty Report Jan23 - Feb24.xlsx"
excel_file = pd.ExcelFile(NAPA)
all_data = []
for sheet_name in excel_file.sheet_names:
    sheet_data = excel_file.parse(sheet_name)
    sheet_data['Sheet Name'] = sheet_name
    all_data.append(sheet_data)
df_NAPA = pd.concat(all_data, ignore_index=True)
df_NAPA

,Month,Field Line Abbr | Desc Prod Group,Product Group Code | Desc Prod Group,[Field Line | Parsed SKU],Product Desc,Defective Sales Qty,Regular Sales Qty,Defect Rate,Defective Cost Amt,Regular Sale Cost Amt,Defect Rate Cost Amt,Sheet Name
0,2023-01-01,NB | NAPA BRAKE ROTORS,502 | LIGHT TRUCK/SUV,NB | 48880279,BRAKE ROTOR,300.0,11934.0,0.025138,8571.00,340954.38,0.025138,Jan 2023
1,2023-01-01,NB | NAPA BRAKE ROTORS,502 | LIGHT TRUCK/SUV,NB | 48880508,BRAKE ROTOR,224.0,8035.0,0.027878,6399.68,229559.95,0.027878,Jan 2023
2,2023-01-01,NB | NAPA BRAKE ROTORS,504 | MD-OTHER,NB | 48880875,BRAKE ROTOR,219.0,3392.0,0.064564,16247.61,251652.48,0.064564,Jan 2023
3,2023-01-01,NB | NAPA BRAKE ROTORS,502 | LIGHT TRUCK/SUV,NB | 48880636,BRAKE ROTOR,217.0,4156.0,0.052214,6199.69,118736.92,0.052214,Jan 2023
4,2023-01-01,WIP | NAPA WINDSHIELD PRODUCTS,11 | EXACTFIT BEAM,WIP | 6022PP,22IN EXACTFIT-BEAM,203.0,26635.0,0.007622,1114.47,146226.15,0.007622,Jan 2023
...,...,...,...,...,...,...,...,...,...,...,...,...
494808,2024-08-01,ADN | ADAPTIVE ONE CALIPERS,30 | BRACKETED CALPR,ADN | 11327XA,BRAKE CALIPER,1.0,0.0,-,20.52,0.00,-,Jan24-July24
494809,2024-09-01,ADN | ADAPTIVE ONE CALIPERS,30 | BRACKETED CALPR,ADN | 11327XA,BRAKE CALIPER,1.0,0.0,-,20.52,0.00,-,Jan24-July24
494810,2024-10-01,ADN | ADAPTIVE ONE CALIPERS,30 | BRACKETED CALPR,ADN | 11327XA,BRAKE CALIPER,1.0,0.0,-,20.52,0.00,-,Jan24-July24
494811,2024-11-01,ADN | ADAPTIVE ONE CALIPERS,30 | BRACKETED CALPR,ADN | 11327XA,BRAKE CALIPER,1.0,0.0,-,20.52,0.00,-,Jan24-July24
494812,2024-12-01,ADN | ADAPTIVE ONE CALIPERS,30 | BRACKETED CALPR,ADN | 11327XA,BRAKE CALIPER,1.0,0.0,-,20.52,0.00,-,Jan24-July24

In [3]:
OR=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\02_Warranty_Analysis\Warrantly Analysis\Customer Data\O'Reilly\O'Reilly Warranty Report Jan23 - Feb24.xlsx"
excel_file = pd.ExcelFile(OR)
all_data = []
for sheet_name in excel_file.sheet_names:
    sheet_data = excel_file.parse(sheet_name)
    sheet_data['Sheet Name'] = sheet_name
    all_data.append(sheet_data)
df_OR = pd.concat(all_data, ignore_index=True)
df_OR

,Month,Line,Plcd,Subc,Item,Mfg,Description,Sales @ Cost,Warranty @ Cost,Net Warranty Percent,Net Units,Warranty Returns Units,Net Warranty Unit Percent,Product Manager,Category,Subcategory,Segment,Vendor Line Description,Sheet Name
0,2025-02-01,MTC,0.0,0,CP1028,WP-458,77-64 FORD/MERCURY,187.32,15.61,0.0833,11,1,0.0909,JARROD MEYER,COOLING,WATER PUMPS,MECHANICAL WATER PUMPS,WATER PUMPS (EWASTE),Feb-2025
1,2025-02-01,IDC,8.0,0,CP6682,WP-2398,19-10 TOYOTA/LEXUS,392.80,0.00,0.0000,2,0,0.0000,JARROD MEYER,COOLING,WATER PUMPS,ELECTRIC WATER PUMPS,IMP WATER PUMPS (EWASTE),Feb-2025
2,2025-02-01,IDC,0.0,0,CP9470,WP-9363,20-03 HON/ACU/SAT,0.00,0.00,NaN,0,0,NaN,JARROD MEYER,COOLING,WATER PUMPS,MECHANICAL WATER PUMPS,IMPORT WATER PUMPS,Feb-2025
3,2025-02-01,IDC,0.0,0,CP9406,WP-9187,18-00 TOYOTA/SCION,74.60,14.92,0.2000,4,1,0.2500,JARROD MEYER,COOLING,WATER PUMPS,MECHANICAL WATER PUMPS,IMPORT WATER PUMPS,Feb-2025
4,2025-02-01,IDC,0.0,0,CP9365,WP-9204,"04-98 ACURA,HONDA",0.00,0.00,NaN,0,0,NaN,JARROD MEYER,COOLING,WATER PUMPS,MECHANICAL WATER PUMPS,IMPORT WATER PUMPS,Feb-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
933088,2023-01-01,IDF,0.0,0,A30457,A30457,11-06 TOYOTA,27271.75,13345.75,0.4894,120,115,0.9583,DAVID RAY,FUEL SYSTEM,FUEL PUMPS,ELECTRICAL FUEL PUMP COMPLETE ASSEMBLIES,ELECTRICAL FUEL PUMPS,Jan 2023
933089,2023-01-01,PFP,0.0,0,A30025,A30025,03-99 CHEV SILVERADO,104742.70,17796.30,0.1699,2008,411,0.2047,DAVID RAY,FUEL SYSTEM,FUEL PUMPS,ELECTRICAL FUEL PUMP COMPLETE ASSEMBLIES,ELECTRICAL FUEL PUMPS,Jan 2023
933090,2023-01-01,PFP,1.0,0,HP16403,HP16403,17-10 GM SUV,47899.35,18804.93,0.3926,246,159,0.6463,DAVID RAY,FUEL SYSTEM,FUEL PUMPS,ELECTRICAL FUEL PUMP COMPLETE ASSEMBLIES,MECHANICAL FUEL PUMPS,Jan 2023
933091,2023-01-01,MTC,0.0,0,CP6009,WP-1106,19-07 GM TRUCK,246457.38,36971.56,0.1500,3547,626,0.1765,JARROD MEYER,COOLING,WATER PUMPS,MECHANICAL WATER PUMPS,WATER PUMPS (EWASTE),Jan 2023
933092,2023-01-01,MTC,0.0,0,CP5104,WP-9409,06-99 GM TRUCKS,342329.34,61440.56,0.1795,6821,1492,0.2187,JARROD MEYER,COOLING,WATER PUMPS,MECHANICAL WATER PUMPS,WATER PUMPS (EWASTE),Jan 2023

In [4]:
PA=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\02_Warranty_Analysis\Warrantly Analysis\Customer Data\Parts Authority\Parts Authority Warranty 23 and 24.xlsx"
excel_file = pd.ExcelFile(PA)
all_data = []
for sheet_name in excel_file.sheet_names:
    sheet_data = excel_file.parse(sheet_name)
    sheet_data['Sheet Name'] = sheet_name
    all_data.append(sheet_data)
df_PA = pd.concat(all_data, ignore_index=True)
df_PA

,"Gen2,Scenario","Gen2,Product","Gen3,Product",Reported Gross Sales,Net Trade Units,SA Net-Net,Sales Warranties,Net Trade Sales,Reported Gross Units,Warranty Units,SA Net-Net.1,Time - Default,SA Net-Net.2,"Gen2,Product - Default","Gen2,Product.1","Gen3,Product.1","Gen4,Product","Gen5,Product",Sheet Name
0,Actual 2023,Caliper Product Summary,1411 CALIPER FRICTION READY,291.64,10.0,266.30,-25.34,266.30,11.0,-1.0,266.30,Mar,266.30,Caliper Product Summary,Caliper Product Summary,1411 CALIPER FRICTION READY,PG1411 CALIPER FRICTION READY,141.65516,Parts Authority Warranty 23
1,Actual 2023,Caliper Product Summary,1418 AIR DISC BRAKE,110.92,13.0,104.28,-6.64,104.28,14.0,-1.0,104.28,Apr,104.28,Caliper Product Summary,Caliper Product Summary,1418 AIR DISC BRAKE,PG1418 AIR DISC BRAKE,117.44034,Parts Authority Warranty 23
2,Actual 2023,Caliper Product Summary,1418 AIR DISC BRAKE,NaN,-1.0,-8.35,-8.35,-8.35,NaN,-1.0,-8.35,Mar,-8.35,Caliper Product Summary,Caliper Product Summary,1418 AIR DISC BRAKE,PG1418 AIR DISC BRAKE,117.44011,Parts Authority Warranty 23
3,Actual 2023,Caliper Product Summary,1418 AIR DISC BRAKE,73.84,13.0,68.09,-5.75,68.09,14.0,-1.0,68.09,Mar,68.09,Caliper Product Summary,Caliper Product Summary,1418 AIR DISC BRAKE,PG1418 AIR DISC BRAKE,117.66025,Parts Authority Warranty 23
4,Actual 2023,Caliper Product Summary,1418 AIR DISC BRAKE,NaN,-1.0,-8.02,-8.02,-8.02,NaN,-1.0,-8.02,Mar,-8.02,Caliper Product Summary,Caliper Product Summary,1418 AIR DISC BRAKE,PG1418 AIR DISC BRAKE,117.6504,Parts Authority Warranty 23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296199,Actual 2024,Hydraulic Product Summary,1145 CLUTCH CONCENTRIC SLAVE,37.31,1.0,37.31,NaN,37.31,1.0,NaN,37.31,Sep,37.31,Hydraulic Product Summary,Hydraulic Product Summary,1145 CLUTCH CONCENTRIC SLAVE,PG1145 CLUTCH CONCENTRIC SLAVE,303.61005,2024
296200,Actual 2024,Hydraulic Product Summary,1142 CLUTCH CABLES,10.80,1.0,10.80,NaN,10.80,1.0,NaN,10.80,Aug,10.80,Hydraulic Product Summary,Hydraulic Product Summary,1142 CLUTCH CABLES,PG1142 CLUTCH CABLES,156.48007,2024
296201,Actual 2024,Hydraulic Product Summary,1142 CLUTCH CABLES,3.91,1.0,3.91,NaN,3.91,1.0,NaN,3.91,Aug,3.91,Hydraulic Product Summary,Hydraulic Product Summary,1142 CLUTCH CABLES,PG1142 CLUTCH CABLES,156.33103,2024
296202,Actual 2024,Hydraulic Product Summary,1142 CLUTCH CABLES,0.00,NaN,0.00,NaN,0.00,NaN,NaN,0.00,Oct,0.00,Hydraulic Product Summary,Hydraulic Product Summary,1142 CLUTCH CABLES,PG1142 CLUTCH CABLES,156.42009,2024
296203,Actual 2024,Hydraulic Product Summary,1142 CLUTCH CABLES,15.51,1.0,15.51,NaN,15.51,1.0,NaN,15.51,Sep,15.51,Hydraulic Product Summary,Hydraulic Product Summary,1142 CLUTCH CABLES,PG1142 CLUTCH CABLES,156.42009,2024

In [11]:
df_PA['Month']=pd.to_datetime(df_PA['Time - Default']+"-"+df_PA['Gen2,Scenario'].str[-4:])

C:\Users\vikram.vadhirajan\AppData\Local\Temp\ipykernel_29492\3220340437.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_PA['Month']=pd.to_datetime(df_PA['Time - Default']+"-"+df_PA['Gen2,Scenario'].str[-4:])

In [12]:
df_PA

,"Gen2,Scenario","Gen2,Product","Gen3,Product",Reported Gross Sales,Net Trade Units,SA Net-Net,Sales Warranties,Net Trade Sales,Reported Gross Units,Warranty Units,SA Net-Net.1,Time - Default,SA Net-Net.2,"Gen2,Product - Default","Gen2,Product.1","Gen3,Product.1","Gen4,Product","Gen5,Product",Sheet Name,Month
0,Actual 2023,Caliper Product Summary,1411 CALIPER FRICTION READY,291.64,10.0,266.30,-25.34,266.30,11.0,-1.0,266.30,Mar,266.30,Caliper Product Summary,Caliper Product Summary,1411 CALIPER FRICTION READY,PG1411 CALIPER FRICTION READY,141.65516,Parts Authority Warranty 23,2023-03-01
1,Actual 2023,Caliper Product Summary,1418 AIR DISC BRAKE,110.92,13.0,104.28,-6.64,104.28,14.0,-1.0,104.28,Apr,104.28,Caliper Product Summary,Caliper Product Summary,1418 AIR DISC BRAKE,PG1418 AIR DISC BRAKE,117.44034,Parts Authority Warranty 23,2023-04-01
2,Actual 2023,Caliper Product Summary,1418 AIR DISC BRAKE,NaN,-1.0,-8.35,-8.35,-8.35,NaN,-1.0,-8.35,Mar,-8.35,Caliper Product Summary,Caliper Product Summary,1418 AIR DISC BRAKE,PG1418 AIR DISC BRAKE,117.44011,Parts Authority Warranty 23,2023-03-01
3,Actual 2023,Caliper Product Summary,1418 AIR DISC BRAKE,73.84,13.0,68.09,-5.75,68.09,14.0,-1.0,68.09,Mar,68.09,Caliper Product Summary,Caliper Product Summary,1418 AIR DISC BRAKE,PG1418 AIR DISC BRAKE,117.66025,Parts Authority Warranty 23,2023-03-01
4,Actual 2023,Caliper Product Summary,1418 AIR DISC BRAKE,NaN,-1.0,-8.02,-8.02,-8.02,NaN,-1.0,-8.02,Mar,-8.02,Caliper Product Summary,Caliper Product Summary,1418 AIR DISC BRAKE,PG1418 AIR DISC BRAKE,117.6504,Parts Authority Warranty 23,2023-03-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296199,Actual 2024,Hydraulic Product Summary,1145 CLUTCH CONCENTRIC SLAVE,37.31,1.0,37.31,NaN,37.31,1.0,NaN,37.31,Sep,37.31,Hydraulic Product Summary,Hydraulic Product Summary,1145 CLUTCH CONCENTRIC SLAVE,PG1145 CLUTCH CONCENTRIC SLAVE,303.61005,2024,2024-09-01
296200,Actual 2024,Hydraulic Product Summary,1142 CLUTCH CABLES,10.80,1.0,10.80,NaN,10.80,1.0,NaN,10.80,Aug,10.80,Hydraulic Product Summary,Hydraulic Product Summary,1142 CLUTCH CABLES,PG1142 CLUTCH CABLES,156.48007,2024,2024-08-01
296201,Actual 2024,Hydraulic Product Summary,1142 CLUTCH CABLES,3.91,1.0,3.91,NaN,3.91,1.0,NaN,3.91,Aug,3.91,Hydraulic Product Summary,Hydraulic Product Summary,1142 CLUTCH CABLES,PG1142 CLUTCH CABLES,156.33103,2024,2024-08-01
296202,Actual 2024,Hydraulic Product Summary,1142 CLUTCH CABLES,0.00,NaN,0.00,NaN,0.00,NaN,NaN,0.00,Oct,0.00,Hydraulic Product Summary,Hydraulic Product Summary,1142 CLUTCH CABLES,PG1142 CLUTCH CABLES,156.42009,2024,2024-10-01
296203,Actual 2024,Hydraulic Product Summary,1142 CLUTCH CABLES,15.51,1.0,15.51,NaN,15.51,1.0,NaN,15.51,Sep,15.51,Hydraulic Product Summary,Hydraulic Product Summary,1142 CLUTCH CABLES,PG1142 CLUTCH CABLES,156.42009,2024,2024-09-01

In [14]:
LSB=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\02_Warranty_Analysis\Warrantly Analysis\Customer Data\LeSchwab_Brakes.xlsx"
excel_file = pd.ExcelFile(LSB)
all_data = []
for sheet_name in excel_file.sheet_names:
    sheet_data = excel_file.parse(sheet_name)
    sheet_data['Sheet Name'] = sheet_name
    all_data.append(sheet_data)
df_LSB = pd.concat(all_data, ignore_index=True)
df_LSB

,BATCH #,CLAIM #,PROD #,SIZE/LINE,ADJ. CODE,MILEAGE ON,MILEAGE OFF,Run Mileage,ADJ CODE DESCRIPTION,CREDIT DUE $,Warranty Type,Date,Part/Problem,Mileage Code,Sheet Name
0,47534,260254,RC10959CS,RC10959CS,YL,0,0,0.0,LEAKS,81.61,Normal,2024-01-01,RC10959CSLEAKS,1.0,2024
1,47533,994,RC12163C,RC12163C,YK,0,0,0.0,"NEW DEFECT,NO STORE DETAILS",96.17,New,2024-01-01,"RC12163CNEW DEFECT,NO STORE DETAILS",1.0,2024
2,47533,994,RC12164C,RC12164C,YKF,0,0,0.0,"FROZEN, NEW DEFECT",96.17,New,2024-01-01,"RC12164CFROZEN, NEW DEFECT",1.0,2024
3,47533,26672,RC12963C,RC12963C,YKT,0,0,0.0,"STRIPPED THREADS, NEW DEFECT",84.85,New,2024-01-01,"RC12963CSTRIPPED THREADS, NEW DEFECT",1.0,2024
4,47533,26673,RC11896C,RC11896C,YKT,0,0,0.0,"STRIPPED THREADS, NEW DEFECT",81.96,New,2024-01-01,"RC11896CSTRIPPED THREADS, NEW DEFECT",1.0,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26625,47484,8041197,RC12180C,RC12180C,YK,0,0,0.0,"NEW DEFECT,NO STORE DETAILS",72.38,New,NaT,NaN,NaN,2023
26626,47484,8041200,RC12779C,RC12779C,YKT,0,0,0.0,"STRIPPED THREADS, NEW DEFECT",101.55,New,NaT,NaN,NaN,2023
26627,47484,8041214,RC11839C,RC11839C,YKT,0,0,0.0,"STRIPPED THREADS, NEW DEFECT",77.49,New,NaT,NaN,NaN,2023
26628,47484,8041216,RC12620C,RC12620C,YK,0,0,0.0,"NEW DEFECT,NO STORE DETAILS",83.08,New,NaT,NaN,NaN,2023
26629,47484,8041221,RC12026C,RC12026C,YK,0,0,0.0,"NEW DEFECT,NO STORE DETAILS",105.41,New,NaT,NaN,NaN,2023

In [10]:
AZ=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\02_Warranty_Analysis\Warrantly Analysis\Customer Data\Autozone\Updated AZO Warranty Report Jan23 - Feb24.xlsx"
excel_file = pd.ExcelFile(AZ)
all_data = []
for sheet_name in excel_file.sheet_names:
    sheet_data = excel_file.parse(sheet_name)
    sheet_data['Sheet Name'] = sheet_name
    all_data.append(sheet_data)
df_AZ = pd.concat(all_data, ignore_index=True)
df_AZ

,Month,MajorMinor,Part,Item,Description,Vendor,Warranty Return Retail,Gross Retail,Net Retail,Warranty Return Units,Gross Units,Net Units,Sheet Name,Unnamed: 0
0,2023-01-01,0595-TG STRAINER,5111000,563498.0,FUEL STRAINER,"CARTER FUEL SYSTEMS, LLC",-160.99,1519.99,1305.06,10.0,64.0,53.0,AZ 2023,NaN
1,2023-01-01,0595-TG STRAINER,5111001,563495.0,FUEL STRAINER,"CARTER FUEL SYSTEMS, LLC",-95.13,624.89,522.27,2.0,82.0,80.0,AZ 2023,NaN
2,2023-01-01,0595-TG STRAINER,5111002,563493.0,FUEL STRAINER,"CARTER FUEL SYSTEMS, LLC",-8.90,359.79,350.89,0.0,2.0,2.0,AZ 2023,NaN
3,2023-01-01,0595-TG STRAINER,5111003,563492.0,FUEL STRAINER,"CARTER FUEL SYSTEMS, LLC",0.00,47.98,47.98,1.0,14.0,13.0,AZ 2023,NaN
4,2023-01-01,0595-TG STRAINER,5111004,563491.0,FUEL STRAINER,"CARTER FUEL SYSTEMS, LLC",-19.99,276.86,256.87,10.0,95.0,82.0,AZ 2023,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242418,2025-03-01,0957-AUTOLITE IRIDIUM PLG,XS4164,1112056.0,AUTOLITE XS4164 XTREME S,FRAM GROUP (AUTOLITE),0.00,19.98,19.98,0.0,2.0,2.0,Sales Detail (2),NaN
242419,2025-03-01,0999-MISC SPARK PLUGS,XS4164DP,255785.0,AUTOLITE MOTORCYCLE PLUG,FRAM GROUP (AUTOLITE),0.00,24.76,12.38,0.0,4.0,2.0,Sales Detail (2),NaN
242420,2025-03-01,0999-MISC SPARK PLUGS,XS4302,723270.0,POWER TIP MOTORCYCLE,FRAM GROUP (AUTOLITE),0.00,22.76,22.76,0.0,4.0,4.0,Sales Detail (2),NaN
242421,2025-03-01,0999-MISC SPARK PLUGS,XS65,723395.0,PLATINUM FINE WIRE,FRAM GROUP (AUTOLITE),0.00,12.38,12.38,0.0,2.0,2.0,Sales Detail (2),NaN
242422,2025-03-01,0999-MISC SPARK PLUGS,XS65DP,255787.0,AUTOLITE MOTORCYCLE PLUG,FRAM GROUP (AUTOLITE),0.00,56.61,56.61,0.0,9.0,9.0,Sales Detail (2),NaN

In [11]:
df_AZ.columns

Index(['Month', 'MajorMinor', 'Part', 'Item', 'Description', 'Vendor',
       'Warranty Return Retail', 'Gross Retail', 'Net Retail',
       'Warranty Return Units', 'Gross Units', 'Net Units', 'Sheet Name',
       'Unnamed: 0'],
      dtype='object')

In [12]:
df_PA.columns

Index(['Gen2,Scenario', 'Gen2,Product', 'Gen3,Product', 'Reported Gross Sales',
       'Net Trade Units', 'SA Net-Net', 'Sales Warranties', 'Net Trade Sales',
       'Reported Gross Units', 'Warranty Units', 'SA Net-Net.1',
       'Time - Default', 'SA Net-Net.2', 'Gen2,Product - Default',
       'Gen2,Product.1', 'Gen3,Product.1', 'Gen4,Product', 'Gen5,Product',
       'Sheet Name'],
      dtype='object')

In [15]:
df_LSB.columns

Index(['BATCH #', 'CLAIM #', 'PROD #', 'SIZE/LINE', 'ADJ. CODE',
       'MILEAGE ON  ', 'MILEAGE OFF', 'Run Mileage', 'ADJ CODE DESCRIPTION',
       'CREDIT DUE $', 'Warranty Type', 'Date', 'Part/Problem', 'Mileage Code',
       'Sheet Name'],
      dtype='object')

In [14]:
df_NAPA.columns

Index(['Month', 'Field Line Abbr | Desc Prod Group',
       'Product Group Code | Desc Prod Group', '[Field Line | Parsed SKU]',
       'Product Desc', 'Defective Sales Qty', 'Regular Sales Qty',
       'Defect Rate', 'Defective Cost Amt', 'Regular Sale Cost Amt',
       'Defect Rate Cost Amt', 'Sheet Name'],
      dtype='object')

In [15]:
df_OR.columns

Index(['Month', 'Line', 'Plcd', 'Subc', 'Item', 'Mfg', 'Description',
       'Sales @ Cost', 'Warranty @ Cost', 'Net Warranty Percent', 'Net Units',
       'Warranty Returns Units', 'Net Warranty Unit Percent',
       'Product Manager', 'Category', 'Subcategory', 'Segment',
       'Vendor Line Description', 'Sheet Name'],
      dtype='object')