In [59]:
import pandas as pd

In [60]:
df_aa=pd.read_excel(f"D:\99_Downloads\Keyfile_TMP.xlsx",sheet_name="Sheet1",usecols="A:D")
df_bb=pd.read_excel(f"D:\99_Downloads\Keyfile_TMP.xlsx", sheet_name="Sheet2",usecols="A:D")

In [61]:
df_bb.head()

   Key  Length  Width  Height
0  BB1     NaN    NaN     NaN
1  BB2   10.24   8.86    7.87
2  BB3     NaN    NaN     NaN
3  BB4   14.57   8.66    7.99
4  BB5    8.86   4.33    4.33

In [62]:
df_aa["Match"]=None
df_aa

     Key  Length  Width  Height Match
0    AA1   12.40   7.09    5.71  None
1    AA2   13.19   8.27    8.07  None
2    AA3    9.25   7.28    6.69  None
3    AA4   10.63   6.38    5.35  None
4    AA5    8.66   4.13    3.94  None
5    AA6    7.32   4.09    3.93  None
6    AA7    9.53   5.31    4.65  None
7    AA8   12.60   4.33    3.78  None
8    AA9   10.24   8.86    7.87  None
9   AA10   10.24   8.86    7.87  None
10  AA11    8.23   7.28    7.09  None
11  AA12   13.39   8.86    7.87  None
12  AA13   14.57   8.66    7.99  None
13  AA14   14.57   8.66    5.91  None
14  AA15   17.52   8.66    7.68  None
15  AA16   22.24  10.83    7.87  None
16  AA17   18.50  10.00    7.68  None
17  AA18    8.66   6.30    5.12  None
18  AA19    9.49   7.09    5.12  None
19  AA20   12.60   8.66    5.12  None
20  AA21    8.40   7.30    6.13  None
21  AA22   12.60   7.40    6.13  None
22  AA23   14.30   5.80    3.70  None
23  AA24   10.50   7.50    7.63  None
24  AA25   19.60   7.87    6.10  None
25  AA26   10.24   7.01    5.59  None
26  AA27    6.89   4.33    4.09  None

In [63]:
for i in range (len(df_aa)):
    best_key = None
    best_score = float("inf")

    for j in range(len(df_bb)):
        if (
            df_bb.loc[j, "Length"] <= df_aa.loc[i, "Length"] and
            df_bb.loc[j, "Width"]  <= df_aa.loc[i, "Width"] and
            df_bb.loc[j, "Height"] <= df_aa.loc[i, "Height"]
        ):

            score = (
                (df_aa.loc[i, "Length"] - df_bb.loc[j, "Length"]) +
                (df_aa.loc[i, "Width"]  - df_bb.loc[j, "Width"]) +
                (df_aa.loc[i, "Height"] - df_bb.loc[j, "Height"])
            )

            if score < best_score:
                best_score = score
                best_key = df_bb.loc[j, "Key"]

    df_aa.at[i, "Match"] = best_key

In [64]:
df_aa

     Key  Length  Width  Height Match
0    AA1   12.40   7.09    5.71  BB20
1    AA2   13.19   8.27    8.07  BB11
2    AA3    9.25   7.28    6.69   BB5
3    AA4   10.63   6.38    5.35   BB6
4    AA5    8.66   4.13    3.94  None
5    AA6    7.32   4.09    3.93  None
6    AA7    9.53   5.31    4.65   BB5
7    AA8   12.60   4.33    3.78  None
8    AA9   10.24   8.86    7.87   BB2
9   AA10   10.24   8.86    7.87   BB2
10  AA11    8.23   7.28    7.09  None
11  AA12   13.39   8.86    7.87   BB2
12  AA13   14.57   8.66    7.99   BB4
13  AA14   14.57   8.66    5.91  BB11
14  AA15   17.52   8.66    7.68  BB16
15  AA16   22.24  10.83    7.87  BB30
16  AA17   18.50  10.00    7.68  BB31
17  AA18    8.66   6.30    5.12  None
18  AA19    9.49   7.09    5.12   BB5
19  AA20   12.60   8.66    5.12  BB20
20  AA21    8.40   7.30    6.13  None
21  AA22   12.60   7.40    6.13   BB7
22  AA23   14.30   5.80    3.70  None
23  AA24   10.50   7.50    7.63   BB6
24  AA25   19.60   7.87    6.10  BB11
25  AA26   10.24   7.01    5.59   BB6
26  AA27    6.89   4.33    4.09  None