In [23]:
import pandas as pd

In [24]:
df=pd.read_excel(r"C:\Users\vikram.vadhirajan\Downloads\RMK PATASHAALA - KASH ROBOTICS FINAL LIST.xlsx" , sheet_name='Master Student List', skiprows=3)

In [25]:
df.head()

,S.No,Student Name,Age,School,Class / Sec,Mobile No,Email,Fee Status,Address
0,1,KAVYA SINGH,10,RMK PATASHAALA,IV-A,6380165141,rakeshchandu1985@gmail.com,Paid,"369,Teachers colony,kavaraipettai.601206"
1,2,THAVAN .B,10,RMK PATASHAALA,IV-A,9840285312,Dharmasconstruction@gmail.com,Paid,"No:2/169,chinna vazhuthalambedu,Gummidipoondi."
2,3,PARDHU SAI .V,9,RMK PATASHAALA,IV-A,9963884859,Jalandhar.reddy33@gmail.com,Paid,"No:12,Shakthi nagar,4th crossstreet,Ponneri."
3,4,SANAYA .N,10,RMK PATASHAALA,IV-A,9994844359,nerendarseervi@gmail.com,Paid,"293,P.H.Road,PADIRVEDU 601202"
4,5,RITHVIK SHEERVI,10,RMK PATASHAALA,IV-A,8807578406,Kailashchoudary5@gmail.com,Paid,"89/50,M.H ROAD,MADARAPAKKAM 601201"

In [26]:
df["Class / Sec"]=df["Class / Sec"].str.replace(" ", "")

In [27]:
df["Class / Sec"]=df["Class / Sec"].str.replace("-", "")

In [28]:
df["Class / Sec"]=df["Class / Sec"].astype(str).str[:-1]

In [29]:
df

,S.No,Student Name,Age,School,Class / Sec,Mobile No,Email,Fee Status,Address
0,1,KAVYA SINGH,10,RMK PATASHAALA,IV,6380165141,rakeshchandu1985@gmail.com,Paid,"369,Teachers colony,kavaraipettai.601206"
1,2,THAVAN .B,10,RMK PATASHAALA,IV,9840285312,Dharmasconstruction@gmail.com,Paid,"No:2/169,chinna vazhuthalambedu,Gummidipoondi."
2,3,PARDHU SAI .V,9,RMK PATASHAALA,IV,9963884859,Jalandhar.reddy33@gmail.com,Paid,"No:12,Shakthi nagar,4th crossstreet,Ponneri."
3,4,SANAYA .N,10,RMK PATASHAALA,IV,9994844359,nerendarseervi@gmail.com,Paid,"293,P.H.Road,PADIRVEDU 601202"
4,5,RITHVIK SHEERVI,10,RMK PATASHAALA,IV,8807578406,Kailashchoudary5@gmail.com,Paid,"89/50,M.H ROAD,MADARAPAKKAM 601201"
...,...,...,...,...,...,...,...,...,...
359,360,DARSHIT B,14YRS,RMK PATASHAALA,IX,9444724082,darshitispro@gmail.com,Paid,"2/169,chinna vazhuthalambedu, Gummidipundi - 6..."
360,361,KRISHANTH P M,13YRS,RMK PATASHAALA,IX,9840486491,manoparthi23782@gmail.com,Paid,"NO: 138A, BAJANA KOIL STREET, Palavakkam UTHUK..."
361,362,DHANYASRI B,13YRS,RMK PATASHAALA,IX,9487794341,balawest999@gmail,Paid,"1084/A, prithivi nagar, Gummudipoodi , ph : 60..."
362,363,DIVYA KUMARI,13YRS,RMK PATASHAALA,IX,9142174569,kumaridivya2828@gmail.com,Paid,"NO:232, RS ROAD, SRIKRISHNA COMPLEX, KAVARAIPE..."
363,364,PRANAV P K,13YRS,RMK PATASHAALA,IX,9080476569,poonguzharselvi@gmail.com,Paid,"D No 295/21 2nd floor, Samarapuri, Kavaraipett..."

In [22]:
df["Class / Sec"].value_counts()

Class / Sec
VII     88
V       68
VI      59
VIII    56
IV      50
IX      42
Name: count, dtype: int64

In [ ]:
roman_dict = {
    "I": 1,
    "II": 2,
    "III": 3,
    "IV": 4,
    "V": 5,
    "VI": 6,
    "VII": 7,
    "VIII": 8,
    "IX": 9,
    "X": 10,
    "XI":11,
    "XII":12,
}

In [38]:
df["Grade"] = df["Class / Sec"].map(roman_dict)

In [39]:
df

,S.No,Student Name,Age,School,Class / Sec,Mobile No,Email,Fee Status,Address,Grade
0,1,KAVYA SINGH,10,RMK PATASHAALA,IV,6380165141,rakeshchandu1985@gmail.com,Paid,"369,Teachers colony,kavaraipettai.601206",4
1,2,THAVAN .B,10,RMK PATASHAALA,IV,9840285312,Dharmasconstruction@gmail.com,Paid,"No:2/169,chinna vazhuthalambedu,Gummidipoondi.",4
2,3,PARDHU SAI .V,9,RMK PATASHAALA,IV,9963884859,Jalandhar.reddy33@gmail.com,Paid,"No:12,Shakthi nagar,4th crossstreet,Ponneri.",4
3,4,SANAYA .N,10,RMK PATASHAALA,IV,9994844359,nerendarseervi@gmail.com,Paid,"293,P.H.Road,PADIRVEDU 601202",4
4,5,RITHVIK SHEERVI,10,RMK PATASHAALA,IV,8807578406,Kailashchoudary5@gmail.com,Paid,"89/50,M.H ROAD,MADARAPAKKAM 601201",4
...,...,...,...,...,...,...,...,...,...,...
359,360,DARSHIT B,14YRS,RMK PATASHAALA,IX,9444724082,darshitispro@gmail.com,Paid,"2/169,chinna vazhuthalambedu, Gummidipundi - 6...",9
360,361,KRISHANTH P M,13YRS,RMK PATASHAALA,IX,9840486491,manoparthi23782@gmail.com,Paid,"NO: 138A, BAJANA KOIL STREET, Palavakkam UTHUK...",9
361,362,DHANYASRI B,13YRS,RMK PATASHAALA,IX,9487794341,balawest999@gmail,Paid,"1084/A, prithivi nagar, Gummudipoodi , ph : 60...",9
362,363,DIVYA KUMARI,13YRS,RMK PATASHAALA,IX,9142174569,kumaridivya2828@gmail.com,Paid,"NO:232, RS ROAD, SRIKRISHNA COMPLEX, KAVARAIPE...",9
363,364,PRANAV P K,13YRS,RMK PATASHAALA,IX,9080476569,poonguzharselvi@gmail.com,Paid,"D No 295/21 2nd floor, Samarapuri, Kavaraipett...",9

In [40]:
df.to_excel(r"C:\Users\vikram.vadhirajan\Downloads\Robotics_Cleaned.xlsx", index=False)